define(
//begin v1.x content
{
	"eraAbbr": [
		"BE"
	],
	"field-era": "эра",
	"field-year": "год",
	"field-year-relative+-1": "в прошлом году",
	"field-year-relative+0": "в этом году",
	"field-year-relative+1": "в следующем году",
	"field-year-short": "г.",
	"field-year-narrow": "г.",
	"field-quarter": "квартал",
	"field-quarter-relative+-1": "в прошлом квартале",
	"field-quarter-relative+0": "в текущем квартале",
	"field-quarter-relative+1": "в следующем квартале",
	"field-quarter-short": "кв.",
	"field-quarter-short-relative+-1": "последний кв.",
	"field-quarter-short-relative+0": "текущий кв.",
	"field-quarter-short-relative+1": "следующий кв.",
	"field-quarter-narrow": "кв.",
	"field-quarter-narrow-relative+-1": "посл. кв.",
	"field-quarter-narrow-relative+0": "тек. кв.",
	"field-quarter-narrow-relative+1": "след. кв.",
	"field-month": "месяц",
	"field-month-relative+-1": "в прошлом месяце",
	"field-month-relative+0": "в этом месяце",
	"field-month-relative+1": "в следующем месяце",
	"field-month-short": "мес.",
	"field-month-narrow": "мес.",
	"field-week": "неделя",
	"field-week-relative+-1": "на прошлой неделе",
	"field-week-relative+0": "на этой неделе",
	"field-week-relative+1": "на следующей неделе",
	"field-week-short": "нед.",
	"field-week-narrow": "нед.",
	"field-day": "день",
	"field-day-relative+-2": "позавчера",
	"field-day-relative+-1": "вчера",
	"field-day-relative+0": "сегодня",
	"field-day-relative+1": "завтра",
	"field-day-relative+2": "послезавтра",
	"field-day-short": "дн.",
	"field-day-narrow": "дн.",
	"field-weekday": "день недели",
	"field-sun-relative+-1": "в прошлое воскресенье",
	"field-sun-relative+0": "в это воскресенье",
	"field-sun-relative+1": "в следующее воскресенье",
	"field-sun-short-relative+-1": "в прош. вс.",
	"field-sun-short-relative+0": "в это вс.",
	"field-sun-short-relative+1": "в след. вс.",
	"field-sun-narrow-relative+-1": "в прош. вс.",
	"field-sun-narrow-relative+0": "в это вс.",
	"field-sun-narrow-relative+1": "в след. вс.",
	"field-mon-relative+-1": "в прошлый понедельник",
	"field-mon-relative+0": "в этот понедельник",
	"field-mon-relative+1": "в следующий понедельник",
	"field-mon-short-relative+-1": "в прош. пн.",
	"field-mon-short-relative+0": "в этот пн.",
	"field-mon-short-relative+1": "в след. пн.",
	"field-mon-narrow-relative+-1": "в прош. пн.",
	"field-mon-narrow-relative+0": "в этот пн.",
	"field-mon-narrow-relative+1": "в след. пн.",
	"field-tue-relative+-1": "в прошлый вторник",
	"field-tue-relative+0": "в этот вторник",
	"field-tue-relative+1": "в следующий вторник",
	"field-tue-short-relative+-1": "в прош. вт.",
	"field-tue-short-relative+0": "в этот вт.",
	"field-tue-short-relative+1": "в след. вт.",
	"field-tue-narrow-relative+-1": "в прош. вт.",
	"field-tue-narrow-relative+0": "в этот вт.",
	"field-tue-narrow-relative+1": "в след. вт.",
	"field-wed-relative+-1": "в прошлую среду",
	"field-wed-relative+0": "в эту среду",
	"field-wed-relative+1": "в следующую среду",
	"field-wed-short-relative+-1": "в прош. ср.",
	"field-wed-short-relative+0": "в эту ср.",
	"field-wed-short-relative+1": "в след. ср.",
	"field-wed-narrow-relative+-1": "в прош. ср.",
	"field-wed-narrow-relative+0": "в эту ср.",
	"field-wed-narrow-relative+1": "в след. ср.",
	"field-thu-relative+-1": "в прошлый четверг",
	"field-thu-relative+0": "в этот четверг",
	"field-thu-relative+1": "в следующий четверг",
	"field-thu-short-relative+-1": "в прош. чт.",
	"field-thu-short-relative+0": "в этот чт.",
	"field-thu-short-relative+1": "в след. чт.",
	"field-thu-narrow-relative+-1": "в прош. чт.",
	"field-thu-narrow-relative+0": "в этот чт.",
	"field-thu-narrow-relative+1": "в след. чт.",
	"field-fri-relative+-1": "в прошлую пятницу",
	"field-fri-relative+0": "в эту пятницу",
	"field-fri-relative+1": "в следующую пятницу",
	"field-fri-short-relative+-1": "в прош. пт.",
	"field-fri-short-relative+0": "в эту пт.",
	"field-fri-short-relative+1": "в след. пт.",
	"field-fri-narrow-relative+-1": "в прош. пт.",
	"field-fri-narrow-relative+0": "в эту пт.",
	"field-fri-narrow-relative+1": "в след. пт.",
	"field-sat-relative+-1": "в прошлую субботу",
	"field-sat-relative+0": "в эту субботу",
	"field-sat-relative+1": "в следующую субботу",
	"field-sat-short-relative+-1": "в прош. сб.",
	"field-sat-short-relative+0": "в эту сб.",
	"field-sat-short-relative+1": "в след. сб.",
	"field-sat-narrow-relative+-1": "в прош. сб.",
	"field-sat-narrow-relative+0": "в эту сб.",
	"field-sat-narrow-relative+1": "в след. сб.",
	"field-dayperiod": "ДП/ПП",
	"field-hour": "час",
	"field-hour-relative+0": "в этом часе",
	"field-hour-short": "ч.",
	"field-hour-narrow": "ч",
	"field-minute": "минута",
	"field-minute-relative+0": "в эту минуту",
	"field-minute-short": "мин.",
	"field-minute-narrow": "мин",
	"field-second": "секунда",
	"field-second-relative+0": "сейчас",
	"field-second-short": "сек.",
	"field-second-narrow": "с",
	"field-zone": "часовой пояс",
	"days-format-abbr": [
		"вс",
		"пн",
		"вт",
		"ср",
		"чт",
		"пт",
		"сб"
	],
	"days-format-narrow": [
		"вс",
		"пн",
		"вт",
		"ср",
		"чт",
		"пт",
		"сб"
	],
	"days-format-short": [
		"вс",
		"пн",
		"вт",
		"ср",
		"чт",
		"пт",
		"сб"
	],
	"days-format-wide": [
		"воскресенье",
		"понедельник",
		"вторник",
		"среда",
		"четверг",
		"пятница",
		"суббота"
	],
	"days-standAlone-abbr": [
		"вс",
		"пн",
		"вт",
		"ср",
		"чт",
		"пт",
		"сб"
	],
	"days-standAlone-narrow": [
		"В",
		"П",
		"В",
		"С",
		"Ч",
		"П",
		"С"
	],
	"days-standAlone-short": [
		"вс",
		"пн",
		"вт",
		"ср",
		"чт",
		"пт",
		"сб"
	],
	"days-standAlone-wide": [
		"воскресенье",
		"понедельник",
		"вторник",
		"среда",
		"четверг",
		"пятница",
		"суббота"
	],
	"quarters-format-abbr": [
		"1-й кв.",
		"2-й кв.",
		"3-й кв.",
		"4-й кв."
	],
	"quarters-format-wide": [
		"1-й квартал",
		"2-й квартал",
		"3-й квартал",
		"4-й квартал"
	],
	"quarters-standAlone-abbr": [
		"1-й кв.",
		"2-й кв.",
		"3-й кв.",
		"4-й кв."
	],
	"quarters-standAlone-wide": [
		"1-й квартал",
		"2-й квартал",
		"3-й квартал",
		"4-й квартал"
	],
	"dayPeriods-format-abbr-am": "ДП",
	"dayPeriods-format-abbr-pm": "ПП",
	"dayPeriods-format-narrow-am": "ДП",
	"dayPeriods-format-narrow-pm": "ПП",
	"dayPeriods-format-wide-am": "ДП",
	"dayPeriods-format-wide-pm": "ПП",
	"dayPeriods-standAlone-abbr-am": "ДП",
	"dayPeriods-standAlone-abbr-pm": "ПП",
	"dayPeriods-standAlone-narrow-am": "ДП",
	"dayPeriods-standAlone-narrow-pm": "ПП",
	"dayPeriods-standAlone-wide-am": "ДП",
	"dayPeriods-standAlone-wide-pm": "ПП",
	"dateFormat-full": "EEEE, d MMMM y 'г'. G",
	"dateFormat-long": "d MMMM y 'г'. G",
	"dateFormat-medium": "d MMM y 'г'. G",
	"dateFormat-short": "dd.MM.y G",
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "LLL y G",
	"dateFormatItem-GyMMMd": "d MMM y 'г'. G",
	"dateFormatItem-GyMMMEd": "E, d MMM y 'г'. G",
	"dateFormatItem-H": "H",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-Md": "dd.MM",
	"dateFormatItem-MEd": "E, dd.MM",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MMMEd": "ccc, d MMM",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-yyyyM": "MM.y G",
	"dateFormatItem-yyyyMd": "dd.MM.y G",
	"dateFormatItem-yyyyMEd": "E, dd.MM.y G",
	"dateFormatItem-yyyyMMM": "LLL y G",
	"dateFormatItem-yyyyMMMd": "d MMM y 'г'. G",
	"dateFormatItem-yyyyMMMEd": "E, d MMM y 'г'. G",
	"dateFormatItem-yyyyMMMM": "LLLL y G",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-yyyyQQQQ": "QQQQ y 'г'. G",
	"timeFormat-full": "H:mm:ss zzzz",
	"timeFormat-long": "H:mm:ss z",
	"timeFormat-medium": "H:mm:ss",
	"timeFormat-short": "H:mm",
	"dateTimeFormat-full": "{1}, {0}",
	"dateTimeFormat-long": "{1}, {0}",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateTimeFormat-short": "{1}, {0}",
	"months-format-abbr": [
		"янв.",
		"февр.",
		"мар.",
		"апр.",
		"мая",
		"июн.",
		"июл.",
		"авг.",
		"сент.",
		"окт.",
		"нояб.",
		"дек."
	],
	"months-format-narrow": [
		"Я",
		"Ф",
		"М",
		"А",
		"М",
		"И",
		"И",
		"А",
		"С",
		"О",
		"Н",
		"Д"
	],
	"months-format-wide": [
		"января",
		"февраля",
		"марта",
		"апреля",
		"мая",
		"июня",
		"июля",
		"августа",
		"сентября",
		"октября",
		"ноября",
		"декабря"
	],
	"months-standAlone-abbr": [
		"янв.",
		"февр.",
		"март",
		"апр.",
		"май",
		"июнь",
		"июль",
		"авг.",
		"сент.",
		"окт.",
		"нояб.",
		"дек."
	],
	"months-standAlone-narrow": [
		"Я",
		"Ф",
		"М",
		"А",
		"М",
		"И",
		"И",
		"А",
		"С",
		"О",
		"Н",
		"Д"
	],
	"months-standAlone-wide": [
		"январь",
		"февраль",
		"март",
		"апрель",
		"май",
		"июнь",
		"июль",
		"август",
		"сентябрь",
		"октябрь",
		"ноябрь",
		"декабрь"
	]
}
//end v1.x content
);