define(
//begin v1.x content
{
	"months-format-abbr": [
		"Тот",
		"Бабэ",
		"Хатур",
		"Кихак",
		"Тубэ",
		"Амшир",
		"Барамхат",
		"Бармуда",
		"Башнас",
		"Бауна",
		"Абиб",
		"Мисра",
		"Наси"
	],
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12",
		"13"
	],
	"months-format-wide": [
		"Тот",
		"Бабэ",
		"Хатур",
		"Кихак",
		"Тубэ",
		"Амшир",
		"Барамхат",
		"Бармуда",
		"Башнас",
		"Бауна",
		"Абиб",
		"Мисра",
		"Наси"
	],
	"months-standAlone-abbr": [
		"Тот",
		"Бабэ",
		"Хатур",
		"Кихак",
		"Тубэ",
		"Амшир",
		"Барамхат",
		"Бармуда",
		"Башнас",
		"Бауна",
		"Абиб",
		"Мисра",
		"Наси"
	],
	"months-standAlone-wide": [
		"Тот",
		"Бабэ",
		"Хатур",
		"Кихак",
		"Тубэ",
		"Амшир",
		"Барамхат",
		"Бармуда",
		"Башнас",
		"Бауна",
		"Абиб",
		"Мисра",
		"Наси"
	],
	"field-era": "эра",
	"field-year": "год",
	"field-year-relative+-1": "в прошлом году",
	"field-year-relative+0": "в этом году",
	"field-year-relative+1": "в следующем году",
	"field-year-short": "г.",
	"field-year-narrow": "г.",
	"field-quarter": "квартал",
	"field-quarter-relative+-1": "в прошлом квартале",
	"field-quarter-relative+0": "в текущем квартале",
	"field-quarter-relative+1": "в следующем квартале",
	"field-quarter-short": "кв.",
	"field-quarter-short-relative+-1": "последний кв.",
	"field-quarter-short-relative+0": "текущий кв.",
	"field-quarter-short-relative+1": "следующий кв.",
	"field-quarter-narrow": "кв.",
	"field-quarter-narrow-relative+-1": "посл. кв.",
	"field-quarter-narrow-relative+0": "тек. кв.",
	"field-quarter-narrow-relative+1": "след. кв.",
	"field-month": "месяц",
	"field-month-relative+-1": "в прошлом месяце",
	"field-month-relative+0": "в этом месяце",
	"field-month-relative+1": "в следующем месяце",
	"field-month-short": "мес.",
	"field-month-narrow": "мес.",
	"field-week": "неделя",
	"field-week-relative+-1": "на прошлой неделе",
	"field-week-relative+0": "на этой неделе",
	"field-week-relative+1": "на следующей неделе",
	"field-week-short": "нед.",
	"field-week-narrow": "нед.",
	"field-day": "день",
	"field-day-relative+-2": "позавчера",
	"field-day-relative+-1": "вчера",
	"field-day-relative+0": "сегодня",
	"field-day-relative+1": "завтра",
	"field-day-relative+2": "послезавтра",
	"field-day-short": "дн.",
	"field-day-narrow": "дн.",
	"field-weekday": "день недели",
	"field-sun-relative+-1": "в прошлое воскресенье",
	"field-sun-relative+0": "в это воскресенье",
	"field-sun-relative+1": "в следующее воскресенье",
	"field-sun-short-relative+-1": "в прош. вс.",
	"field-sun-short-relative+0": "в это вс.",
	"field-sun-short-relative+1": "в след. вс.",
	"field-sun-narrow-relative+-1": "в прош. вс.",
	"field-sun-narrow-relative+0": "в это вс.",
	"field-sun-narrow-relative+1": "в след. вс.",
	"field-mon-relative+-1": "в прошлый понедельник",
	"field-mon-relative+0": "в этот понедельник",
	"field-mon-relative+1": "в следующий понедельник",
	"field-mon-short-relative+-1": "в прош. пн.",
	"field-mon-short-relative+0": "в этот пн.",
	"field-mon-short-relative+1": "в след. пн.",
	"field-mon-narrow-relative+-1": "в прош. пн.",
	"field-mon-narrow-relative+0": "в этот пн.",
	"field-mon-narrow-relative+1": "в след. пн.",
	"field-tue-relative+-1": "в прошлый вторник",
	"field-tue-relative+0": "в этот вторник",
	"field-tue-relative+1": "в следующий вторник",
	"field-tue-short-relative+-1": "в прош. вт.",
	"field-tue-short-relative+0": "в этот вт.",
	"field-tue-short-relative+1": "в след. вт.",
	"field-tue-narrow-relative+-1": "в прош. вт.",
	"field-tue-narrow-relative+0": "в этот вт.",
	"field-tue-narrow-relative+1": "в след. вт.",
	"field-wed-relative+-1": "в прошлую среду",
	"field-wed-relative+0": "в эту среду",
	"field-wed-relative+1": "в следующую среду",
	"field-wed-short-relative+-1": "в прош. ср.",
	"field-wed-short-relative+0": "в эту ср.",
	"field-wed-short-relative+1": "в след. ср.",
	"field-wed-narrow-relative+-1": "в прош. ср.",
	"field-wed-narrow-relative+0": "в эту ср.",
	"field-wed-narrow-relative+1": "в след. ср.",
	"field-thu-relative+-1": "в прошлый четверг",
	"field-thu-relative+0": "в этот четверг",
	"field-thu-relative+1": "в следующий четверг",
	"field-thu-short-relative+-1": "в прош. чт.",
	"field-thu-short-relative+0": "в этот чт.",
	"field-thu-short-relative+1": "в след. чт.",
	"field-thu-narrow-relative+-1": "в прош. чт.",
	"field-thu-narrow-relative+0": "в этот чт.",
	"field-thu-narrow-relative+1": "в след. чт.",
	"field-fri-relative+-1": "в прошлую пятницу",
	"field-fri-relative+0": "в эту пятницу",
	"field-fri-relative+1": "в следующую пятницу",
	"field-fri-short-relative+-1": "в прош. пт.",
	"field-fri-short-relative+0": "в эту пт.",
	"field-fri-short-relative+1": "в след. пт.",
	"field-fri-narrow-relative+-1": "в прош. пт.",
	"field-fri-narrow-relative+0": "в эту пт.",
	"field-fri-narrow-relative+1": "в след. пт.",
	"field-sat-relative+-1": "в прошлую субботу",
	"field-sat-relative+0": "в эту субботу",
	"field-sat-relative+1": "в следующую субботу",
	"field-sat-short-relative+-1": "в прош. сб.",
	"field-sat-short-relative+0": "в эту сб.",
	"field-sat-short-relative+1": "в след. сб.",
	"field-sat-narrow-relative+-1": "в прош. сб.",
	"field-sat-narrow-relative+0": "в эту сб.",
	"field-sat-narrow-relative+1": "в след. сб.",
	"field-dayperiod": "ДП/ПП",
	"field-hour": "час",
	"field-hour-relative+0": "в этом часе",
	"field-hour-short": "ч.",
	"field-hour-narrow": "ч",
	"field-minute": "минута",
	"field-minute-relative+0": "в эту минуту",
	"field-minute-short": "мин.",
	"field-minute-narrow": "мин",
	"field-second": "секунда",
	"field-second-relative+0": "сейчас",
	"field-second-short": "сек.",
	"field-second-narrow": "с",
	"field-zone": "часовой пояс"
}
//end v1.x content
);