define(
//begin v1.x content
{
	"months-format-abbr": [
		"1월",
		"2월",
		"3월",
		"4월",
		"5월",
		"6월",
		"7월",
		"8월",
		"9월",
		"10월",
		"11월",
		"12월"
	],
	"months-format-wide": [
		"1월",
		"2월",
		"3월",
		"4월",
		"5월",
		"6월",
		"7월",
		"8월",
		"9월",
		"10월",
		"11월",
		"12월"
	],
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"dateFormat-full": "U년 MMM d일 EEEE",
	"dateFormat-long": "U년 MMM d일",
	"dateFormat-medium": "y. M. d.",
	"dateFormat-short": "y. M. d.",
	"dateFormatItem-d": "d일",
	"dateFormatItem-Ed": "d일 (E)",
	"dateFormatItem-EEEEd": "d일 EEEE",
	"dateFormatItem-Gy": "U년",
	"dateFormatItem-GyMMM": "U년 MMM",
	"dateFormatItem-GyMMMd": "U년 MMM d일",
	"dateFormatItem-GyMMMEd": "U년 MMM d일 (E)",
	"dateFormatItem-GyMMMEEEEd": "U년 MMM d일 EEEE",
	"dateFormatItem-h": "a h시",
	"dateFormatItem-H": "H시",
	"dateFormatItem-hm": "a h:mm",
	"dateFormatItem-hms": "a h:mm:ss",
	"dateFormatItem-Hms": "H시 m분 s초",
	"dateFormatItem-M": "MMM",
	"dateFormatItem-Md": "M. d.",
	"dateFormatItem-MEd": "M. d. (E)",
	"dateFormatItem-MEEEEd": "M. d. EEEE",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "MMM d일",
	"dateFormatItem-MMMEd": "MMM d일 (E)",
	"dateFormatItem-MMMEEEEd": "MMM d일 EEEE",
	"dateFormatItem-MMMMd": "MMMM d일",
	"dateFormatItem-y": "U년",
	"dateFormatItem-yMd": "U. M. d.",
	"dateFormatItem-yyyy": "U년",
	"dateFormatItem-yyyyM": "U. M.",
	"dateFormatItem-yyyyMd": "U. M. d.",
	"dateFormatItem-yyyyMEd": "U. M. d. (E)",
	"dateFormatItem-yyyyMEEEEd": "U. M. d. EEEE",
	"dateFormatItem-yyyyMMM": "U년 MMM",
	"dateFormatItem-yyyyMMMd": "U년 MMM d일",
	"dateFormatItem-yyyyMMMEd": "U년 MMM d일 (E)",
	"dateFormatItem-yyyyMMMEEEEd": "U년 MMM d일 EEEE",
	"dateFormatItem-yyyyMMMM": "U년 MMMM",
	"dateFormatItem-yyyyQQQ": "U년 QQQ",
	"dateFormatItem-yyyyQQQQ": "U년 QQQQ",
	"field-era": "연호",
	"field-year": "년",
	"field-year-relative+-1": "작년",
	"field-year-relative+0": "올해",
	"field-year-relative+1": "내년",
	"field-year-short": "년",
	"field-year-narrow": "년",
	"field-quarter": "분기",
	"field-quarter-relative+-1": "지난 분기",
	"field-quarter-relative+0": "이번 분기",
	"field-quarter-relative+1": "다음 분기",
	"field-quarter-short": "분기",
	"field-quarter-narrow": "분기",
	"field-month": "월",
	"field-month-relative+-1": "지난달",
	"field-month-relative+0": "이번 달",
	"field-month-relative+1": "다음 달",
	"field-month-short": "월",
	"field-month-narrow": "월",
	"field-week": "주",
	"field-week-relative+-1": "지난주",
	"field-week-relative+0": "이번 주",
	"field-week-relative+1": "다음 주",
	"field-week-short": "주",
	"field-week-narrow": "주",
	"field-day": "일",
	"field-day-relative+-2": "그저께",
	"field-day-relative+-1": "어제",
	"field-day-relative+0": "오늘",
	"field-day-relative+1": "내일",
	"field-day-relative+2": "모레",
	"field-day-short": "일",
	"field-day-narrow": "일",
	"field-weekday": "요일",
	"field-sun-relative+-1": "지난 일요일",
	"field-sun-relative+0": "이번 일요일",
	"field-sun-relative+1": "다음 일요일",
	"field-sun-short-relative+-1": "지난 일요일",
	"field-sun-short-relative+0": "이번 일요일",
	"field-sun-short-relative+1": "다음 일요일",
	"field-sun-narrow-relative+-1": "지난 일요일",
	"field-sun-narrow-relative+0": "이번 일요일",
	"field-sun-narrow-relative+1": "다음 일요일",
	"field-mon-relative+-1": "지난 월요일",
	"field-mon-relative+0": "이번 월요일",
	"field-mon-relative+1": "다음 월요일",
	"field-mon-short-relative+-1": "지난 월요일",
	"field-mon-short-relative+0": "이번 월요일",
	"field-mon-short-relative+1": "다음 월요일",
	"field-mon-narrow-relative+-1": "지난 월요일",
	"field-mon-narrow-relative+0": "이번 월요일",
	"field-mon-narrow-relative+1": "다음 월요일",
	"field-tue-relative+-1": "지난 화요일",
	"field-tue-relative+0": "이번 화요일",
	"field-tue-relative+1": "다음 화요일",
	"field-tue-short-relative+-1": "지난 화요일",
	"field-tue-short-relative+0": "이번 화요일",
	"field-tue-short-relative+1": "다음 화요일",
	"field-tue-narrow-relative+-1": "지난 화요일",
	"field-tue-narrow-relative+0": "이번 화요일",
	"field-tue-narrow-relative+1": "다음 화요일",
	"field-wed-relative+-1": "지난 수요일",
	"field-wed-relative+0": "이번 수요일",
	"field-wed-relative+1": "다음 수요일",
	"field-wed-short-relative+-1": "지난 수요일",
	"field-wed-short-relative+0": "이번 수요일",
	"field-wed-short-relative+1": "다음 수요일",
	"field-wed-narrow-relative+-1": "지난 수요일",
	"field-wed-narrow-relative+0": "이번 수요일",
	"field-wed-narrow-relative+1": "다음 수요일",
	"field-thu-relative+-1": "지난 목요일",
	"field-thu-relative+0": "이번 목요일",
	"field-thu-relative+1": "다음 목요일",
	"field-thu-short-relative+-1": "지난 목요일",
	"field-thu-short-relative+0": "이번 목요일",
	"field-thu-short-relative+1": "다음 목요일",
	"field-thu-narrow-relative+-1": "지난 목요일",
	"field-thu-narrow-relative+0": "이번 목요일",
	"field-thu-narrow-relative+1": "다음 목요일",
	"field-fri-relative+-1": "지난 금요일",
	"field-fri-relative+0": "이번 금요일",
	"field-fri-relative+1": "다음 금요일",
	"field-fri-short-relative+-1": "지난 금요일",
	"field-fri-short-relative+0": "이번 금요일",
	"field-fri-short-relative+1": "다음 금요일",
	"field-fri-narrow-relative+-1": "지난 금요일",
	"field-fri-narrow-relative+0": "이번 금요일",
	"field-fri-narrow-relative+1": "다음 금요일",
	"field-sat-relative+-1": "지난 토요일",
	"field-sat-relative+0": "이번 토요일",
	"field-sat-relative+1": "다음 토요일",
	"field-sat-short-relative+-1": "지난 토요일",
	"field-sat-short-relative+0": "이번 토요일",
	"field-sat-short-relative+1": "다음 토요일",
	"field-sat-narrow-relative+-1": "지난 토요일",
	"field-sat-narrow-relative+0": "이번 토요일",
	"field-sat-narrow-relative+1": "다음 토요일",
	"field-dayperiod": "오전/오후",
	"field-hour": "시",
	"field-hour-relative+0": "현재 시간",
	"field-hour-short": "시",
	"field-hour-narrow": "시",
	"field-minute": "분",
	"field-minute-relative+0": "현재 분",
	"field-minute-short": "분",
	"field-minute-narrow": "분",
	"field-second": "초",
	"field-second-relative+0": "지금",
	"field-second-short": "초",
	"field-second-narrow": "초",
	"field-zone": "시간대"
}
//end v1.x content
);