define(
//begin v1.x content
{
	"dateFormat-full": "G y년 M월 d일 EEEE",
	"dateFormat-long": "G y년 M월 d일",
	"dateFormat-medium": "G y. M. d.",
	"dateFormat-short": "G y. M. d.",
	"dateTimeFormat-full": "{1} {0}",
	"dateTimeFormat-long": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "d일",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "d일 (E)",
	"dateFormatItem-EEEEd": "d일 EEEE",
	"dateFormatItem-Gy": "G y년",
	"dateFormatItem-GyMMM": "G y년 MMM월",
	"dateFormatItem-GyMMMd": "G y년 MMM월 d일",
	"dateFormatItem-GyMMMEd": "G y년 MMM월 d일 (E)",
	"dateFormatItem-GyMMMEEEEd": "G y년 MMM월 d일 EEEE",
	"dateFormatItem-h": "a h시",
	"dateFormatItem-H": "H시",
	"dateFormatItem-HHmmss": "HH:mm:ss",
	"dateFormatItem-hm": "a h:mm",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-hms": "a h:mm:ss",
	"dateFormatItem-Hms": "H시 m분 s초",
	"dateFormatItem-M": "M월",
	"dateFormatItem-Md": "M. d.",
	"dateFormatItem-MEd": "M. d. (E)",
	"dateFormatItem-MEEEEd": "M. d. EEEE",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "MMM월 d일",
	"dateFormatItem-MMMEd": "MMM월 d일 (E)",
	"dateFormatItem-MMMEEEEd": "MMM월 d일 EEEE",
	"dateFormatItem-MMMMd": "MMMM월 d일",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "G y년",
	"dateFormatItem-yyyy": "G y년",
	"dateFormatItem-yyyyM": "G y. M.",
	"dateFormatItem-yyyyMd": "G y. M. d.",
	"dateFormatItem-yyyyMEd": "G y. M. d. (E)",
	"dateFormatItem-yyyyMEEEEd": "G y. M. d. EEEE",
	"dateFormatItem-yyyyMMM": "G y년 MMM월",
	"dateFormatItem-yyyyMMMd": "G y년 MMM월 d일",
	"dateFormatItem-yyyyMMMEd": "G y년 MMM월 d일 (E)",
	"dateFormatItem-yyyyMMMEEEEd": "G y년 MMM월 d일 EEEE",
	"dateFormatItem-yyyyMMMM": "G y년 MMMM월",
	"dateFormatItem-yyyyQQQ": "G y년 QQQ",
	"dateFormatItem-yyyyQQQQ": "G y년 QQQQ",
	"field-era": "연호",
	"field-year": "년",
	"field-year-relative+-1": "작년",
	"field-year-relative+0": "올해",
	"field-year-relative+1": "내년",
	"field-year-short": "년",
	"field-year-narrow": "년",
	"field-quarter": "분기",
	"field-quarter-relative+-1": "지난 분기",
	"field-quarter-relative+0": "이번 분기",
	"field-quarter-relative+1": "다음 분기",
	"field-quarter-short": "분기",
	"field-quarter-narrow": "분기",
	"field-month": "월",
	"field-month-relative+-1": "지난달",
	"field-month-relative+0": "이번 달",
	"field-month-relative+1": "다음 달",
	"field-month-short": "월",
	"field-month-narrow": "월",
	"field-week": "주",
	"field-week-relative+-1": "지난주",
	"field-week-relative+0": "이번 주",
	"field-week-relative+1": "다음 주",
	"field-week-short": "주",
	"field-week-narrow": "주",
	"field-day": "일",
	"field-day-relative+-2": "그저께",
	"field-day-relative+-1": "어제",
	"field-day-relative+0": "오늘",
	"field-day-relative+1": "내일",
	"field-day-relative+2": "모레",
	"field-day-short": "일",
	"field-day-narrow": "일",
	"field-weekday": "요일",
	"field-sun-relative+-1": "지난 일요일",
	"field-sun-relative+0": "이번 일요일",
	"field-sun-relative+1": "다음 일요일",
	"field-sun-short-relative+-1": "지난 일요일",
	"field-sun-short-relative+0": "이번 일요일",
	"field-sun-short-relative+1": "다음 일요일",
	"field-sun-narrow-relative+-1": "지난 일요일",
	"field-sun-narrow-relative+0": "이번 일요일",
	"field-sun-narrow-relative+1": "다음 일요일",
	"field-mon-relative+-1": "지난 월요일",
	"field-mon-relative+0": "이번 월요일",
	"field-mon-relative+1": "다음 월요일",
	"field-mon-short-relative+-1": "지난 월요일",
	"field-mon-short-relative+0": "이번 월요일",
	"field-mon-short-relative+1": "다음 월요일",
	"field-mon-narrow-relative+-1": "지난 월요일",
	"field-mon-narrow-relative+0": "이번 월요일",
	"field-mon-narrow-relative+1": "다음 월요일",
	"field-tue-relative+-1": "지난 화요일",
	"field-tue-relative+0": "이번 화요일",
	"field-tue-relative+1": "다음 화요일",
	"field-tue-short-relative+-1": "지난 화요일",
	"field-tue-short-relative+0": "이번 화요일",
	"field-tue-short-relative+1": "다음 화요일",
	"field-tue-narrow-relative+-1": "지난 화요일",
	"field-tue-narrow-relative+0": "이번 화요일",
	"field-tue-narrow-relative+1": "다음 화요일",
	"field-wed-relative+-1": "지난 수요일",
	"field-wed-relative+0": "이번 수요일",
	"field-wed-relative+1": "다음 수요일",
	"field-wed-short-relative+-1": "지난 수요일",
	"field-wed-short-relative+0": "이번 수요일",
	"field-wed-short-relative+1": "다음 수요일",
	"field-wed-narrow-relative+-1": "지난 수요일",
	"field-wed-narrow-relative+0": "이번 수요일",
	"field-wed-narrow-relative+1": "다음 수요일",
	"field-thu-relative+-1": "지난 목요일",
	"field-thu-relative+0": "이번 목요일",
	"field-thu-relative+1": "다음 목요일",
	"field-thu-short-relative+-1": "지난 목요일",
	"field-thu-short-relative+0": "이번 목요일",
	"field-thu-short-relative+1": "다음 목요일",
	"field-thu-narrow-relative+-1": "지난 목요일",
	"field-thu-narrow-relative+0": "이번 목요일",
	"field-thu-narrow-relative+1": "다음 목요일",
	"field-fri-relative+-1": "지난 금요일",
	"field-fri-relative+0": "이번 금요일",
	"field-fri-relative+1": "다음 금요일",
	"field-fri-short-relative+-1": "지난 금요일",
	"field-fri-short-relative+0": "이번 금요일",
	"field-fri-short-relative+1": "다음 금요일",
	"field-fri-narrow-relative+-1": "지난 금요일",
	"field-fri-narrow-relative+0": "이번 금요일",
	"field-fri-narrow-relative+1": "다음 금요일",
	"field-sat-relative+-1": "지난 토요일",
	"field-sat-relative+0": "이번 토요일",
	"field-sat-relative+1": "다음 토요일",
	"field-sat-short-relative+-1": "지난 토요일",
	"field-sat-short-relative+0": "이번 토요일",
	"field-sat-short-relative+1": "다음 토요일",
	"field-sat-narrow-relative+-1": "지난 토요일",
	"field-sat-narrow-relative+0": "이번 토요일",
	"field-sat-narrow-relative+1": "다음 토요일",
	"field-dayperiod": "오전/오후",
	"field-hour": "시",
	"field-hour-relative+0": "현재 시간",
	"field-hour-short": "시",
	"field-hour-narrow": "시",
	"field-minute": "분",
	"field-minute-relative+0": "현재 분",
	"field-minute-short": "분",
	"field-minute-narrow": "분",
	"field-second": "초",
	"field-second-relative+0": "지금",
	"field-second-short": "초",
	"field-second-narrow": "초",
	"field-zone": "시간대"
}
//end v1.x content
);