define(
//begin v1.x content
{
	"months-format-abbr": [
		"1월",
		"2월",
		"3월",
		"4월",
		"5월",
		"6월",
		"7월",
		"8월",
		"9월",
		"10월",
		"11월",
		"12월"
	],
	"months-format-narrow": [
		"1월",
		"2월",
		"3월",
		"4월",
		"5월",
		"6월",
		"7월",
		"8월",
		"9월",
		"10월",
		"11월",
		"12월"
	],
	"months-format-wide": [
		"1월",
		"2월",
		"3월",
		"4월",
		"5월",
		"6월",
		"7월",
		"8월",
		"9월",
		"10월",
		"11월",
		"12월"
	],
	"months-standAlone-abbr": [
		"1월",
		"2월",
		"3월",
		"4월",
		"5월",
		"6월",
		"7월",
		"8월",
		"9월",
		"10월",
		"11월",
		"12월"
	],
	"months-standAlone-narrow": [
		"1월",
		"2월",
		"3월",
		"4월",
		"5월",
		"6월",
		"7월",
		"8월",
		"9월",
		"10월",
		"11월",
		"12월"
	],
	"months-standAlone-wide": [
		"1월",
		"2월",
		"3월",
		"4월",
		"5월",
		"6월",
		"7월",
		"8월",
		"9월",
		"10월",
		"11월",
		"12월"
	],
	"days-format-abbr": [
		"일",
		"월",
		"화",
		"수",
		"목",
		"금",
		"토"
	],
	"days-format-narrow": [
		"일",
		"월",
		"화",
		"수",
		"목",
		"금",
		"토"
	],
	"days-format-short": [
		"일",
		"월",
		"화",
		"수",
		"목",
		"금",
		"토"
	],
	"days-format-wide": [
		"일요일",
		"월요일",
		"화요일",
		"수요일",
		"목요일",
		"금요일",
		"토요일"
	],
	"days-standAlone-abbr": [
		"일",
		"월",
		"화",
		"수",
		"목",
		"금",
		"토"
	],
	"days-standAlone-narrow": [
		"일",
		"월",
		"화",
		"수",
		"목",
		"금",
		"토"
	],
	"days-standAlone-short": [
		"일",
		"월",
		"화",
		"수",
		"목",
		"금",
		"토"
	],
	"days-standAlone-wide": [
		"일요일",
		"월요일",
		"화요일",
		"수요일",
		"목요일",
		"금요일",
		"토요일"
	],
	"quarters-format-abbr": [
		"1분기",
		"2분기",
		"3분기",
		"4분기"
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"제 1/4분기",
		"제 2/4분기",
		"제 3/4분기",
		"제 4/4분기"
	],
	"quarters-standAlone-abbr": [
		"1분기",
		"2분기",
		"3분기",
		"4분기"
	],
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-standAlone-wide": [
		"제 1/4분기",
		"제 2/4분기",
		"제 3/4분기",
		"제 4/4분기"
	],
	"dayPeriods-format-abbr-midnight": "자정",
	"dayPeriods-format-abbr-am": "AM",
	"dayPeriods-format-abbr-noon": "정오",
	"dayPeriods-format-abbr-pm": "PM",
	"dayPeriods-format-abbr-morning1": "새벽",
	"dayPeriods-format-abbr-morning2": "오전",
	"dayPeriods-format-abbr-afternoon1": "오후",
	"dayPeriods-format-abbr-evening1": "저녁",
	"dayPeriods-format-abbr-night1": "밤",
	"dayPeriods-format-narrow-midnight": "자정",
	"dayPeriods-format-narrow-am": "AM",
	"dayPeriods-format-narrow-noon": "정오",
	"dayPeriods-format-narrow-pm": "PM",
	"dayPeriods-format-narrow-morning1": "새벽",
	"dayPeriods-format-narrow-morning2": "오전",
	"dayPeriods-format-narrow-afternoon1": "오후",
	"dayPeriods-format-narrow-evening1": "저녁",
	"dayPeriods-format-narrow-night1": "밤",
	"dayPeriods-format-wide-midnight": "자정",
	"dayPeriods-format-wide-am": "오전",
	"dayPeriods-format-wide-noon": "정오",
	"dayPeriods-format-wide-pm": "오후",
	"dayPeriods-format-wide-morning1": "새벽",
	"dayPeriods-format-wide-morning2": "오전",
	"dayPeriods-format-wide-afternoon1": "오후",
	"dayPeriods-format-wide-evening1": "저녁",
	"dayPeriods-format-wide-night1": "밤",
	"dayPeriods-standAlone-abbr-midnight": "자정",
	"dayPeriods-standAlone-abbr-am": "AM",
	"dayPeriods-standAlone-abbr-noon": "정오",
	"dayPeriods-standAlone-abbr-pm": "PM",
	"dayPeriods-standAlone-abbr-morning1": "새벽",
	"dayPeriods-standAlone-abbr-morning2": "오전",
	"dayPeriods-standAlone-abbr-afternoon1": "오후",
	"dayPeriods-standAlone-abbr-evening1": "저녁",
	"dayPeriods-standAlone-abbr-night1": "밤",
	"dayPeriods-standAlone-narrow-midnight": "자정",
	"dayPeriods-standAlone-narrow-am": "AM",
	"dayPeriods-standAlone-narrow-noon": "정오",
	"dayPeriods-standAlone-narrow-pm": "PM",
	"dayPeriods-standAlone-narrow-morning1": "새벽",
	"dayPeriods-standAlone-narrow-morning2": "오전",
	"dayPeriods-standAlone-narrow-afternoon1": "오후",
	"dayPeriods-standAlone-narrow-evening1": "저녁",
	"dayPeriods-standAlone-narrow-night1": "밤",
	"dayPeriods-standAlone-wide-midnight": "자정",
	"dayPeriods-standAlone-wide-am": "오전",
	"dayPeriods-standAlone-wide-noon": "정오",
	"dayPeriods-standAlone-wide-pm": "오후",
	"dayPeriods-standAlone-wide-morning1": "새벽",
	"dayPeriods-standAlone-wide-morning2": "오전",
	"dayPeriods-standAlone-wide-afternoon1": "오후",
	"dayPeriods-standAlone-wide-evening1": "저녁",
	"dayPeriods-standAlone-wide-night1": "밤",
	"eraNames": [
		"기원전",
		"서기"
	],
	"eraAbbr": [
		"BC",
		"AD"
	],
	"dateFormat-full": "y년 M월 d일 EEEE",
	"dateFormat-long": "y년 M월 d일",
	"dateFormat-medium": "y. M. d.",
	"dateFormat-short": "yy. M. d.",
	"timeFormat-full": "a h시 m분 s초 zzzz",
	"timeFormat-long": "a h시 m분 s초 z",
	"timeFormat-medium": "a h:mm:ss",
	"timeFormat-short": "a h:mm",
	"dateTimeFormat-full": "{1} {0}",
	"dateTimeFormat-long": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "d일",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "d일 (E)",
	"dateFormatItem-EEEEd": "d일 EEEE",
	"dateFormatItem-Ehm": "(E) a h:mm",
	"dateFormatItem-EHm": "(E) HH:mm",
	"dateFormatItem-Ehms": "(E) a h:mm:ss",
	"dateFormatItem-EHms": "(E) HH:mm:ss",
	"dateFormatItem-Gy": "G y년",
	"dateFormatItem-GyMMM": "G y년 MMM",
	"dateFormatItem-GyMMMd": "G y년 MMM d일",
	"dateFormatItem-GyMMMEd": "G y년 MMM d일 (E)",
	"dateFormatItem-GyMMMEEEEd": "G y년 MMM d일 EEEE",
	"dateFormatItem-h": "a h시",
	"dateFormatItem-H": "H시",
	"dateFormatItem-HHmmss": "HH:mm:ss",
	"dateFormatItem-hm": "a h:mm",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-hms": "a h:mm:ss",
	"dateFormatItem-Hms": "H시 m분 s초",
	"dateFormatItem-hmsv": "a h:mm:ss v",
	"dateFormatItem-Hmsv": "H시 m분 s초 v",
	"dateFormatItem-hmv": "a h:mm v",
	"dateFormatItem-Hmv": "HH:mm v",
	"dateFormatItem-M": "M월",
	"dateFormatItem-Md": "M. d.",
	"dateFormatItem-MEd": "M. d. (E)",
	"dateFormatItem-MEEEEd": "M. d. EEEE",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "MMM d일",
	"dateFormatItem-MMMEd": "MMM d일 (E)",
	"dateFormatItem-MMMEEEEd": "MMM d일 EEEE",
	"dateFormatItem-MMMMd": "MMMM d일",
	"dateFormatItem-MMMMW": "MMM W번째 주",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y년",
	"dateFormatItem-yM": "y. M.",
	"dateFormatItem-yMd": "y. M. d.",
	"dateFormatItem-yMEd": "y. M. d. (E)",
	"dateFormatItem-yMEEEEd": "y. M. d. EEEE",
	"dateFormatItem-yMM": "y. M.",
	"dateFormatItem-yMMM": "y년 MMM",
	"dateFormatItem-yMMMd": "y년 MMM d일",
	"dateFormatItem-yMMMEd": "y년 MMM d일 (E)",
	"dateFormatItem-yMMMEEEEd": "y년 MMM d일 EEEE",
	"dateFormatItem-yMMMM": "y년 MMMM",
	"dateFormatItem-yQQQ": "y년 QQQ",
	"dateFormatItem-yQQQQ": "y년 QQQQ",
	"dateFormatItem-yw": "y년 w번째 주",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-era": "연호",
	"field-year": "년",
	"field-year-relative+-1": "작년",
	"field-year-relative+0": "올해",
	"field-year-relative+1": "내년",
	"field-year-short": "년",
	"field-year-narrow": "년",
	"field-quarter": "분기",
	"field-quarter-relative+-1": "지난 분기",
	"field-quarter-relative+0": "이번 분기",
	"field-quarter-relative+1": "다음 분기",
	"field-quarter-short": "분기",
	"field-quarter-narrow": "분기",
	"field-month": "월",
	"field-month-relative+-1": "지난달",
	"field-month-relative+0": "이번 달",
	"field-month-relative+1": "다음 달",
	"field-month-short": "월",
	"field-month-narrow": "월",
	"field-week": "주",
	"field-week-relative+-1": "지난주",
	"field-week-relative+0": "이번 주",
	"field-week-relative+1": "다음 주",
	"field-week-short": "주",
	"field-week-narrow": "주",
	"field-day": "일",
	"field-day-relative+-2": "그저께",
	"field-day-relative+-1": "어제",
	"field-day-relative+0": "오늘",
	"field-day-relative+1": "내일",
	"field-day-relative+2": "모레",
	"field-day-short": "일",
	"field-day-narrow": "일",
	"field-weekday": "요일",
	"field-sun-relative+-1": "지난 일요일",
	"field-sun-relative+0": "이번 일요일",
	"field-sun-relative+1": "다음 일요일",
	"field-sun-short-relative+-1": "지난 일요일",
	"field-sun-short-relative+0": "이번 일요일",
	"field-sun-short-relative+1": "다음 일요일",
	"field-sun-narrow-relative+-1": "지난 일요일",
	"field-sun-narrow-relative+0": "이번 일요일",
	"field-sun-narrow-relative+1": "다음 일요일",
	"field-mon-relative+-1": "지난 월요일",
	"field-mon-relative+0": "이번 월요일",
	"field-mon-relative+1": "다음 월요일",
	"field-mon-short-relative+-1": "지난 월요일",
	"field-mon-short-relative+0": "이번 월요일",
	"field-mon-short-relative+1": "다음 월요일",
	"field-mon-narrow-relative+-1": "지난 월요일",
	"field-mon-narrow-relative+0": "이번 월요일",
	"field-mon-narrow-relative+1": "다음 월요일",
	"field-tue-relative+-1": "지난 화요일",
	"field-tue-relative+0": "이번 화요일",
	"field-tue-relative+1": "다음 화요일",
	"field-tue-short-relative+-1": "지난 화요일",
	"field-tue-short-relative+0": "이번 화요일",
	"field-tue-short-relative+1": "다음 화요일",
	"field-tue-narrow-relative+-1": "지난 화요일",
	"field-tue-narrow-relative+0": "이번 화요일",
	"field-tue-narrow-relative+1": "다음 화요일",
	"field-wed-relative+-1": "지난 수요일",
	"field-wed-relative+0": "이번 수요일",
	"field-wed-relative+1": "다음 수요일",
	"field-wed-short-relative+-1": "지난 수요일",
	"field-wed-short-relative+0": "이번 수요일",
	"field-wed-short-relative+1": "다음 수요일",
	"field-wed-narrow-relative+-1": "지난 수요일",
	"field-wed-narrow-relative+0": "이번 수요일",
	"field-wed-narrow-relative+1": "다음 수요일",
	"field-thu-relative+-1": "지난 목요일",
	"field-thu-relative+0": "이번 목요일",
	"field-thu-relative+1": "다음 목요일",
	"field-thu-short-relative+-1": "지난 목요일",
	"field-thu-short-relative+0": "이번 목요일",
	"field-thu-short-relative+1": "다음 목요일",
	"field-thu-narrow-relative+-1": "지난 목요일",
	"field-thu-narrow-relative+0": "이번 목요일",
	"field-thu-narrow-relative+1": "다음 목요일",
	"field-fri-relative+-1": "지난 금요일",
	"field-fri-relative+0": "이번 금요일",
	"field-fri-relative+1": "다음 금요일",
	"field-fri-short-relative+-1": "지난 금요일",
	"field-fri-short-relative+0": "이번 금요일",
	"field-fri-short-relative+1": "다음 금요일",
	"field-fri-narrow-relative+-1": "지난 금요일",
	"field-fri-narrow-relative+0": "이번 금요일",
	"field-fri-narrow-relative+1": "다음 금요일",
	"field-sat-relative+-1": "지난 토요일",
	"field-sat-relative+0": "이번 토요일",
	"field-sat-relative+1": "다음 토요일",
	"field-sat-short-relative+-1": "지난 토요일",
	"field-sat-short-relative+0": "이번 토요일",
	"field-sat-short-relative+1": "다음 토요일",
	"field-sat-narrow-relative+-1": "지난 토요일",
	"field-sat-narrow-relative+0": "이번 토요일",
	"field-sat-narrow-relative+1": "다음 토요일",
	"field-dayperiod": "오전/오후",
	"field-hour": "시",
	"field-hour-relative+0": "현재 시간",
	"field-hour-short": "시",
	"field-hour-narrow": "시",
	"field-minute": "분",
	"field-minute-relative+0": "현재 분",
	"field-minute-short": "분",
	"field-minute-narrow": "분",
	"field-second": "초",
	"field-second-relative+0": "지금",
	"field-second-short": "초",
	"field-second-narrow": "초",
	"field-zone": "시간대",
	"eraNarrow": [
		"BC",
		"AD"
	]
}
//end v1.x content
);