define(
//begin v1.x content
{
	"months-format-abbr": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-format-wide": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-standAlone-abbr": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-standAlone-wide": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"dateFormat-full": "U MMMM d, EEEE",
	"dateFormat-long": "U MMMM d",
	"dateFormat-medium": "U MMM d",
	"dateFormat-short": "y-MM-dd",
	"dateTimeFormat-full": "{1} {0}",
	"dateTimeFormat-long": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "d",
	"dateFormatItem-Ed": "d, E",
	"dateFormatItem-Gy": "U",
	"dateFormatItem-GyMMM": "U MMM",
	"dateFormatItem-GyMMMd": "U MMM d",
	"dateFormatItem-GyMMMEd": "U MMM d, E",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "MM-dd",
	"dateFormatItem-MEd": "MM-dd, E",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "MMM d",
	"dateFormatItem-MMMEd": "MMM d, E",
	"dateFormatItem-y": "U",
	"dateFormatItem-yMd": "y-MM-dd",
	"dateFormatItem-yyyy": "U",
	"dateFormatItem-yyyyM": "y-MM",
	"dateFormatItem-yyyyMd": "y-MM-dd",
	"dateFormatItem-yyyyMEd": "y-MM-dd, E",
	"dateFormatItem-yyyyMMM": "U MMM",
	"dateFormatItem-yyyyMMMd": "U MMM d",
	"dateFormatItem-yyyyMMMEd": "U MMM d, E",
	"dateFormatItem-yyyyQQQ": "U QQQ",
	"dateFormatItem-yyyyQQQQ": "U QQQQ",
	"field-era": "era",
	"field-year": "metai",
	"field-year-relative+-1": "praėjusiais metais",
	"field-year-relative+0": "šiais metais",
	"field-year-relative+1": "kitais metais",
	"field-year-short": "m.",
	"field-year-narrow": "m.",
	"field-quarter": "ketvirtis",
	"field-quarter-relative+-1": "praėjęs ketvirtis",
	"field-quarter-relative+0": "šis ketvirtis",
	"field-quarter-relative+1": "kitas ketvirtis",
	"field-quarter-short": "ketv.",
	"field-quarter-narrow": "ketv.",
	"field-month": "mėnuo",
	"field-month-relative+-1": "praėjusį mėnesį",
	"field-month-relative+0": "šį mėnesį",
	"field-month-relative+1": "kitą mėnesį",
	"field-month-short": "mėn.",
	"field-month-narrow": "mėn.",
	"field-week": "savaitė",
	"field-week-relative+-1": "praėjusią savaitę",
	"field-week-relative+0": "šią savaitę",
	"field-week-relative+1": "kitą savaitę",
	"field-week-short": "sav.",
	"field-week-narrow": "sav.",
	"field-day": "diena",
	"field-day-relative+-2": "užvakar",
	"field-day-relative+-1": "vakar",
	"field-day-relative+0": "šiandien",
	"field-day-relative+1": "rytoj",
	"field-day-relative+2": "poryt",
	"field-day-short": "d.",
	"field-day-narrow": "d.",
	"field-weekday": "savaitės diena",
	"field-sun-relative+-1": "praėjusį sekmadienį",
	"field-sun-relative+0": "šį sekmadienį",
	"field-sun-relative+1": "kitą sekmadienį",
	"field-sun-short-relative+-1": "praėjusį sekm.",
	"field-sun-short-relative+0": "šį sekm.",
	"field-sun-short-relative+1": "kitą sekm.",
	"field-sun-narrow-relative+-1": "praėjusį sekm.",
	"field-sun-narrow-relative+0": "šį sekm.",
	"field-sun-narrow-relative+1": "kitą sekm.",
	"field-mon-relative+-1": "praėjusį pirmadienį",
	"field-mon-relative+0": "šį pirmadienį",
	"field-mon-relative+1": "kitą pirmadienį",
	"field-mon-short-relative+-1": "praėjusį pirm.",
	"field-mon-short-relative+0": "šį pirm.",
	"field-mon-short-relative+1": "kitą pirm.",
	"field-mon-narrow-relative+-1": "praėjusį pirm.",
	"field-mon-narrow-relative+0": "šį pirm.",
	"field-mon-narrow-relative+1": "kitą pirm.",
	"field-tue-relative+-1": "praėjusį antradienį",
	"field-tue-relative+0": "šį antradienį",
	"field-tue-relative+1": "kitą antradienį",
	"field-tue-short-relative+-1": "praėjusį antr.",
	"field-tue-short-relative+0": "šį antr.",
	"field-tue-short-relative+1": "kitą antr.",
	"field-tue-narrow-relative+-1": "praėjusį antr.",
	"field-tue-narrow-relative+0": "šį antr.",
	"field-tue-narrow-relative+1": "kitą antr.",
	"field-wed-relative+-1": "praėjusį trečiadienį",
	"field-wed-relative+0": "šį trečiadienį",
	"field-wed-relative+1": "kitą trečiadienį",
	"field-wed-short-relative+-1": "praėjusį treč.",
	"field-wed-short-relative+0": "šį treč.",
	"field-wed-short-relative+1": "kitą treč.",
	"field-wed-narrow-relative+-1": "praėjusį treč.",
	"field-wed-narrow-relative+0": "šį treč.",
	"field-wed-narrow-relative+1": "kitą treč.",
	"field-thu-relative+-1": "praėjusį ketvirtadienį",
	"field-thu-relative+0": "šį ketvirtadienį",
	"field-thu-relative+1": "kitą ketvirtadienį",
	"field-thu-short-relative+-1": "praėjusį ketv.",
	"field-thu-short-relative+0": "šį ketv.",
	"field-thu-short-relative+1": "kitą ketv.",
	"field-thu-narrow-relative+-1": "praėjusį ketv.",
	"field-thu-narrow-relative+0": "šį ketv.",
	"field-thu-narrow-relative+1": "kitą ketv.",
	"field-fri-relative+-1": "praėjusį penktadienį",
	"field-fri-relative+0": "šį penktadienį",
	"field-fri-relative+1": "kitą penktadienį",
	"field-fri-short-relative+-1": "praėjusį penkt.",
	"field-fri-short-relative+0": "šį penkt.",
	"field-fri-short-relative+1": "kitą penkt.",
	"field-fri-narrow-relative+-1": "praėjusį penkt.",
	"field-fri-narrow-relative+0": "šį penkt.",
	"field-fri-narrow-relative+1": "kitą penkt.",
	"field-sat-relative+-1": "praėjusį šeštadienį",
	"field-sat-relative+0": "šį šeštadienį",
	"field-sat-relative+1": "kitą šeštadienį",
	"field-sat-short-relative+-1": "praėjusį šešt.",
	"field-sat-short-relative+0": "šį šešt.",
	"field-sat-short-relative+1": "kitą šešt.",
	"field-sat-narrow-relative+-1": "praėjusį šešt.",
	"field-sat-narrow-relative+0": "šį šešt.",
	"field-sat-narrow-relative+1": "kitą šešt.",
	"field-dayperiod": "iki pietų / po pietų",
	"field-hour": "valanda",
	"field-hour-relative+0": "šią valandą",
	"field-hour-short": "val.",
	"field-hour-narrow": "h",
	"field-minute": "minutė",
	"field-minute-relative+0": "šią minutę",
	"field-minute-short": "min.",
	"field-minute-narrow": "min.",
	"field-second": "sekundė",
	"field-second-relative+0": "dabar",
	"field-second-short": "sek.",
	"field-second-narrow": "s",
	"field-zone": "laiko juosta"
}
//end v1.x content
);