define(
//begin v1.x content
{
	"months-format-abbr": [
		"saus.",
		"vas.",
		"kov.",
		"bal.",
		"geg.",
		"birž.",
		"liep.",
		"rugp.",
		"rugs.",
		"spal.",
		"lapkr.",
		"gruod."
	],
	"months-format-narrow": [
		"S",
		"V",
		"K",
		"B",
		"G",
		"B",
		"L",
		"R",
		"R",
		"S",
		"L",
		"G"
	],
	"months-format-wide": [
		"sausio",
		"vasario",
		"kovo",
		"balandžio",
		"gegužės",
		"birželio",
		"liepos",
		"rugpjūčio",
		"rugsėjo",
		"spalio",
		"lapkričio",
		"gruodžio"
	],
	"months-standAlone-abbr": [
		"saus.",
		"vas.",
		"kov.",
		"bal.",
		"geg.",
		"birž.",
		"liep.",
		"rugp.",
		"rugs.",
		"spal.",
		"lapkr.",
		"gruod."
	],
	"months-standAlone-narrow": [
		"S",
		"V",
		"K",
		"B",
		"G",
		"B",
		"L",
		"R",
		"R",
		"S",
		"L",
		"G"
	],
	"months-standAlone-wide": [
		"sausis",
		"vasaris",
		"kovas",
		"balandis",
		"gegužė",
		"birželis",
		"liepa",
		"rugpjūtis",
		"rugsėjis",
		"spalis",
		"lapkritis",
		"gruodis"
	],
	"days-format-abbr": [
		"sk",
		"pr",
		"an",
		"tr",
		"kt",
		"pn",
		"št"
	],
	"days-format-narrow": [
		"S",
		"P",
		"A",
		"T",
		"K",
		"P",
		"Š"
	],
	"days-format-short": [
		"Sk",
		"Pr",
		"An",
		"Tr",
		"Kt",
		"Pn",
		"Št"
	],
	"days-format-wide": [
		"sekmadienis",
		"pirmadienis",
		"antradienis",
		"trečiadienis",
		"ketvirtadienis",
		"penktadienis",
		"šeštadienis"
	],
	"days-standAlone-abbr": [
		"sk",
		"pr",
		"an",
		"tr",
		"kt",
		"pn",
		"št"
	],
	"days-standAlone-narrow": [
		"S",
		"P",
		"A",
		"T",
		"K",
		"P",
		"Š"
	],
	"days-standAlone-short": [
		"Sk",
		"Pr",
		"An",
		"Tr",
		"Kt",
		"Pn",
		"Št"
	],
	"days-standAlone-wide": [
		"sekmadienis",
		"pirmadienis",
		"antradienis",
		"trečiadienis",
		"ketvirtadienis",
		"penktadienis",
		"šeštadienis"
	],
	"quarters-format-abbr": [
		"I k.",
		"II k.",
		"III k.",
		"IV k."
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"I ketvirtis",
		"II ketvirtis",
		"III ketvirtis",
		"IV ketvirtis"
	],
	"quarters-standAlone-abbr": [
		"I ketv.",
		"II ketv.",
		"III ketv.",
		"IV ketv."
	],
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-standAlone-wide": [
		"I ketvirtis",
		"II ketvirtis",
		"III ketvirtis",
		"IV ketvirtis"
	],
	"dayPeriods-format-abbr-midnight": "vidurnaktis",
	"dayPeriods-format-abbr-am": "priešpiet",
	"dayPeriods-format-abbr-noon": "perpiet",
	"dayPeriods-format-abbr-pm": "popiet",
	"dayPeriods-format-abbr-morning1": "rytas",
	"dayPeriods-format-abbr-afternoon1": "popietė",
	"dayPeriods-format-abbr-evening1": "vakaras",
	"dayPeriods-format-abbr-night1": "naktis",
	"dayPeriods-format-narrow-midnight": "vidurnaktis",
	"dayPeriods-format-narrow-am": "pr. p.",
	"dayPeriods-format-narrow-noon": "perpiet",
	"dayPeriods-format-narrow-pm": "pop.",
	"dayPeriods-format-narrow-morning1": "rytas",
	"dayPeriods-format-narrow-afternoon1": "popietė",
	"dayPeriods-format-narrow-evening1": "vakaras",
	"dayPeriods-format-narrow-night1": "naktis",
	"dayPeriods-format-wide-midnight": "vidurnaktis",
	"dayPeriods-format-wide-am": "priešpiet",
	"dayPeriods-format-wide-noon": "perpiet",
	"dayPeriods-format-wide-pm": "popiet",
	"dayPeriods-format-wide-morning1": "rytas",
	"dayPeriods-format-wide-afternoon1": "popietė",
	"dayPeriods-format-wide-evening1": "vakaras",
	"dayPeriods-format-wide-night1": "naktis",
	"dayPeriods-standAlone-abbr-midnight": "vidurnaktis",
	"dayPeriods-standAlone-abbr-am": "priešpiet",
	"dayPeriods-standAlone-abbr-noon": "vidurdienis",
	"dayPeriods-standAlone-abbr-pm": "popiet",
	"dayPeriods-standAlone-abbr-morning1": "rytas",
	"dayPeriods-standAlone-abbr-afternoon1": "diena",
	"dayPeriods-standAlone-abbr-evening1": "vakaras",
	"dayPeriods-standAlone-abbr-night1": "naktis",
	"dayPeriods-standAlone-narrow-midnight": "vidurnaktis",
	"dayPeriods-standAlone-narrow-am": "pr. p.",
	"dayPeriods-standAlone-narrow-noon": "vidurdienis",
	"dayPeriods-standAlone-narrow-pm": "pop.",
	"dayPeriods-standAlone-narrow-morning1": "rytas",
	"dayPeriods-standAlone-narrow-afternoon1": "diena",
	"dayPeriods-standAlone-narrow-evening1": "vakaras",
	"dayPeriods-standAlone-narrow-night1": "naktis",
	"dayPeriods-standAlone-wide-midnight": "vidurnaktis",
	"dayPeriods-standAlone-wide-am": "priešpiet",
	"dayPeriods-standAlone-wide-noon": "vidurdienis",
	"dayPeriods-standAlone-wide-pm": "popiet",
	"dayPeriods-standAlone-wide-morning1": "rytas",
	"dayPeriods-standAlone-wide-afternoon1": "diena",
	"dayPeriods-standAlone-wide-evening1": "vakaras",
	"dayPeriods-standAlone-wide-night1": "naktis",
	"eraNames": [
		"prieš Kristų",
		"po Kristaus"
	],
	"eraAbbr": [
		"pr. Kr.",
		"po Kr."
	],
	"eraNarrow": [
		"pr. Kr.",
		"po Kr."
	],
	"dateFormat-full": "y 'm'. MMMM d 'd'., EEEE",
	"dateFormat-long": "y 'm'. MMMM d 'd'.",
	"dateFormat-medium": "y-MM-dd",
	"dateFormat-short": "y-MM-dd",
	"timeFormat-full": "HH:mm:ss zzzz",
	"timeFormat-long": "HH:mm:ss z",
	"timeFormat-medium": "HH:mm:ss",
	"timeFormat-short": "HH:mm",
	"dateTimeFormat-full": "{1} {0}",
	"dateTimeFormat-long": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "dd",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "d, E",
	"dateFormatItem-Ehm": "hh:mm a, E",
	"dateFormatItem-EHm": "HH:mm, E",
	"dateFormatItem-Ehms": "hh:mm:ss a, E",
	"dateFormatItem-EHms": "HH:mm:ss, E",
	"dateFormatItem-Gy": "y 'm'. G",
	"dateFormatItem-GyMMM": "y-MM G",
	"dateFormatItem-GyMMMd": "y-MM-dd G",
	"dateFormatItem-GyMMMEd": "y-MM-dd G, E",
	"dateFormatItem-GyMMMM": "y 'm'. G, LLLL",
	"dateFormatItem-GyMMMMd": "y 'm'. G MMMM d 'd'.",
	"dateFormatItem-GyMMMMEd": "y 'm'. G MMMM d 'd'., E",
	"dateFormatItem-h": "hh a",
	"dateFormatItem-H": "HH",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hmsv": "hh:mm:ss a; v",
	"dateFormatItem-Hmsv": "HH:mm:ss; v",
	"dateFormatItem-hmv": "hh:mm a; v",
	"dateFormatItem-Hmv": "HH:mm; v",
	"dateFormatItem-M": "MM",
	"dateFormatItem-Md": "MM-d",
	"dateFormatItem-MEd": "MM-dd, E",
	"dateFormatItem-MMdd": "MM-dd",
	"dateFormatItem-MMM": "MM",
	"dateFormatItem-MMMd": "MM-dd",
	"dateFormatItem-MMMEd": "MM-dd, E",
	"dateFormatItem-MMMM": "LLLL",
	"dateFormatItem-MMMMd": "MMMM d 'd'.",
	"dateFormatItem-MMMMEd": "MMMM d 'd'., E",
	"dateFormatItem-MMMMW": "MMM W 'sav'.",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y",
	"dateFormatItem-yM": "y-MM",
	"dateFormatItem-yMd": "y-MM-dd",
	"dateFormatItem-yMEd": "y-MM-dd, E",
	"dateFormatItem-yMMM": "y-MM",
	"dateFormatItem-yMMMd": "y-MM-dd",
	"dateFormatItem-yMMMEd": "y-MM-dd, E",
	"dateFormatItem-yMMMM": "y 'm'. LLLL",
	"dateFormatItem-yMMMMd": "y 'm'. MMMM d 'd'.",
	"dateFormatItem-yMMMMEd": "y 'm'. MMMM d 'd'., E",
	"dateFormatItem-yQQQ": "y QQQ",
	"dateFormatItem-yQQQQ": "y QQQQ",
	"dateFormatItem-yw": "y w 'sav'.",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-era": "era",
	"field-year": "metai",
	"field-year-relative+-1": "praėjusiais metais",
	"field-year-relative+0": "šiais metais",
	"field-year-relative+1": "kitais metais",
	"field-year-short": "m.",
	"field-year-narrow": "m.",
	"field-quarter": "ketvirtis",
	"field-quarter-relative+-1": "praėjęs ketvirtis",
	"field-quarter-relative+0": "šis ketvirtis",
	"field-quarter-relative+1": "kitas ketvirtis",
	"field-quarter-short": "ketv.",
	"field-quarter-narrow": "ketv.",
	"field-month": "mėnuo",
	"field-month-relative+-1": "praėjusį mėnesį",
	"field-month-relative+0": "šį mėnesį",
	"field-month-relative+1": "kitą mėnesį",
	"field-month-short": "mėn.",
	"field-month-narrow": "mėn.",
	"field-week": "savaitė",
	"field-week-relative+-1": "praėjusią savaitę",
	"field-week-relative+0": "šią savaitę",
	"field-week-relative+1": "kitą savaitę",
	"field-week-short": "sav.",
	"field-week-narrow": "sav.",
	"field-day": "diena",
	"field-day-relative+-2": "užvakar",
	"field-day-relative+-1": "vakar",
	"field-day-relative+0": "šiandien",
	"field-day-relative+1": "rytoj",
	"field-day-relative+2": "poryt",
	"field-day-short": "d.",
	"field-day-narrow": "d.",
	"field-weekday": "savaitės diena",
	"field-sun-relative+-1": "praėjusį sekmadienį",
	"field-sun-relative+0": "šį sekmadienį",
	"field-sun-relative+1": "kitą sekmadienį",
	"field-sun-short-relative+-1": "praėjusį sekm.",
	"field-sun-short-relative+0": "šį sekm.",
	"field-sun-short-relative+1": "kitą sekm.",
	"field-sun-narrow-relative+-1": "praėjusį sekm.",
	"field-sun-narrow-relative+0": "šį sekm.",
	"field-sun-narrow-relative+1": "kitą sekm.",
	"field-mon-relative+-1": "praėjusį pirmadienį",
	"field-mon-relative+0": "šį pirmadienį",
	"field-mon-relative+1": "kitą pirmadienį",
	"field-mon-short-relative+-1": "praėjusį pirm.",
	"field-mon-short-relative+0": "šį pirm.",
	"field-mon-short-relative+1": "kitą pirm.",
	"field-mon-narrow-relative+-1": "praėjusį pirm.",
	"field-mon-narrow-relative+0": "šį pirm.",
	"field-mon-narrow-relative+1": "kitą pirm.",
	"field-tue-relative+-1": "praėjusį antradienį",
	"field-tue-relative+0": "šį antradienį",
	"field-tue-relative+1": "kitą antradienį",
	"field-tue-short-relative+-1": "praėjusį antr.",
	"field-tue-short-relative+0": "šį antr.",
	"field-tue-short-relative+1": "kitą antr.",
	"field-tue-narrow-relative+-1": "praėjusį antr.",
	"field-tue-narrow-relative+0": "šį antr.",
	"field-tue-narrow-relative+1": "kitą antr.",
	"field-wed-relative+-1": "praėjusį trečiadienį",
	"field-wed-relative+0": "šį trečiadienį",
	"field-wed-relative+1": "kitą trečiadienį",
	"field-wed-short-relative+-1": "praėjusį treč.",
	"field-wed-short-relative+0": "šį treč.",
	"field-wed-short-relative+1": "kitą treč.",
	"field-wed-narrow-relative+-1": "praėjusį treč.",
	"field-wed-narrow-relative+0": "šį treč.",
	"field-wed-narrow-relative+1": "kitą treč.",
	"field-thu-relative+-1": "praėjusį ketvirtadienį",
	"field-thu-relative+0": "šį ketvirtadienį",
	"field-thu-relative+1": "kitą ketvirtadienį",
	"field-thu-short-relative+-1": "praėjusį ketv.",
	"field-thu-short-relative+0": "šį ketv.",
	"field-thu-short-relative+1": "kitą ketv.",
	"field-thu-narrow-relative+-1": "praėjusį ketv.",
	"field-thu-narrow-relative+0": "šį ketv.",
	"field-thu-narrow-relative+1": "kitą ketv.",
	"field-fri-relative+-1": "praėjusį penktadienį",
	"field-fri-relative+0": "šį penktadienį",
	"field-fri-relative+1": "kitą penktadienį",
	"field-fri-short-relative+-1": "praėjusį penkt.",
	"field-fri-short-relative+0": "šį penkt.",
	"field-fri-short-relative+1": "kitą penkt.",
	"field-fri-narrow-relative+-1": "praėjusį penkt.",
	"field-fri-narrow-relative+0": "šį penkt.",
	"field-fri-narrow-relative+1": "kitą penkt.",
	"field-sat-relative+-1": "praėjusį šeštadienį",
	"field-sat-relative+0": "šį šeštadienį",
	"field-sat-relative+1": "kitą šeštadienį",
	"field-sat-short-relative+-1": "praėjusį šešt.",
	"field-sat-short-relative+0": "šį šešt.",
	"field-sat-short-relative+1": "kitą šešt.",
	"field-sat-narrow-relative+-1": "praėjusį šešt.",
	"field-sat-narrow-relative+0": "šį šešt.",
	"field-sat-narrow-relative+1": "kitą šešt.",
	"field-dayperiod": "iki pietų / po pietų",
	"field-hour": "valanda",
	"field-hour-relative+0": "šią valandą",
	"field-hour-short": "val.",
	"field-hour-narrow": "h",
	"field-minute": "minutė",
	"field-minute-relative+0": "šią minutę",
	"field-minute-short": "min.",
	"field-minute-narrow": "min.",
	"field-second": "sekundė",
	"field-second-relative+0": "dabar",
	"field-second-short": "sek.",
	"field-second-narrow": "s",
	"field-zone": "laiko juosta"
}
//end v1.x content
);