define(
//begin v1.x content
{
	"months-format-abbr": [
		"sij",
		"velj",
		"ožu",
		"tra",
		"svi",
		"lip",
		"srp",
		"kol",
		"ruj",
		"lis",
		"stu",
		"pro"
	],
	"months-format-narrow": [
		"1.",
		"2.",
		"3.",
		"4.",
		"5.",
		"6.",
		"7.",
		"8.",
		"9.",
		"10.",
		"11.",
		"12."
	],
	"months-format-wide": [
		"siječnja",
		"veljače",
		"ožujka",
		"travnja",
		"svibnja",
		"lipnja",
		"srpnja",
		"kolovoza",
		"rujna",
		"listopada",
		"studenoga",
		"prosinca"
	],
	"months-standAlone-abbr": [
		"sij",
		"velj",
		"ožu",
		"tra",
		"svi",
		"lip",
		"srp",
		"kol",
		"ruj",
		"lis",
		"stu",
		"pro"
	],
	"months-standAlone-narrow": [
		"1.",
		"2.",
		"3.",
		"4.",
		"5.",
		"6.",
		"7.",
		"8.",
		"9.",
		"10.",
		"11.",
		"12."
	],
	"months-standAlone-wide": [
		"siječanj",
		"veljača",
		"ožujak",
		"travanj",
		"svibanj",
		"lipanj",
		"srpanj",
		"kolovoz",
		"rujan",
		"listopad",
		"studeni",
		"prosinac"
	],
	"days-format-abbr": [
		"ned",
		"pon",
		"uto",
		"sri",
		"čet",
		"pet",
		"sub"
	],
	"days-format-narrow": [
		"N",
		"P",
		"U",
		"S",
		"Č",
		"P",
		"S"
	],
	"days-format-short": [
		"ned",
		"pon",
		"uto",
		"sri",
		"čet",
		"pet",
		"sub"
	],
	"days-format-wide": [
		"nedjelja",
		"ponedjeljak",
		"utorak",
		"srijeda",
		"četvrtak",
		"petak",
		"subota"
	],
	"days-standAlone-abbr": [
		"ned",
		"pon",
		"uto",
		"sri",
		"čet",
		"pet",
		"sub"
	],
	"days-standAlone-narrow": [
		"n",
		"p",
		"u",
		"s",
		"č",
		"p",
		"s"
	],
	"days-standAlone-short": [
		"ned",
		"pon",
		"uto",
		"sri",
		"čet",
		"pet",
		"sub"
	],
	"days-standAlone-wide": [
		"nedjelja",
		"ponedjeljak",
		"utorak",
		"srijeda",
		"četvrtak",
		"petak",
		"subota"
	],
	"quarters-format-abbr": [
		"1kv",
		"2kv",
		"3kv",
		"4kv"
	],
	"quarters-format-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"quarters-format-wide": [
		"1. kvartal",
		"2. kvartal",
		"3. kvartal",
		"4. kvartal"
	],
	"quarters-standAlone-abbr": [
		"1. kv.",
		"2. kv.",
		"3. kv.",
		"4. kv."
	],
	"quarters-standAlone-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"quarters-standAlone-wide": [
		"1. kvartal",
		"2. kvartal",
		"3. kvartal",
		"4. kvartal"
	],
	"dayPeriods-format-abbr-midnight": "ponoć",
	"dayPeriods-format-abbr-am": "AM",
	"dayPeriods-format-abbr-noon": "podne",
	"dayPeriods-format-abbr-pm": "PM",
	"dayPeriods-format-abbr-morning1": "ujutro",
	"dayPeriods-format-abbr-afternoon1": "popodne",
	"dayPeriods-format-abbr-evening1": "navečer",
	"dayPeriods-format-abbr-night1": "noću",
	"dayPeriods-format-narrow-midnight": "ponoć",
	"dayPeriods-format-narrow-am": "AM",
	"dayPeriods-format-narrow-noon": "podne",
	"dayPeriods-format-narrow-pm": "PM",
	"dayPeriods-format-narrow-morning1": "ujutro",
	"dayPeriods-format-narrow-afternoon1": "popodne",
	"dayPeriods-format-narrow-evening1": "navečer",
	"dayPeriods-format-narrow-night1": "noću",
	"dayPeriods-format-wide-midnight": "ponoć",
	"dayPeriods-format-wide-am": "AM",
	"dayPeriods-format-wide-noon": "podne",
	"dayPeriods-format-wide-pm": "PM",
	"dayPeriods-format-wide-morning1": "ujutro",
	"dayPeriods-format-wide-afternoon1": "popodne",
	"dayPeriods-format-wide-evening1": "navečer",
	"dayPeriods-format-wide-night1": "noću",
	"dayPeriods-standAlone-abbr-midnight": "ponoć",
	"dayPeriods-standAlone-abbr-am": "AM",
	"dayPeriods-standAlone-abbr-noon": "podne",
	"dayPeriods-standAlone-abbr-pm": "PM",
	"dayPeriods-standAlone-abbr-morning1": "ujutro",
	"dayPeriods-standAlone-abbr-afternoon1": "popodne",
	"dayPeriods-standAlone-abbr-evening1": "navečer",
	"dayPeriods-standAlone-abbr-night1": "noću",
	"dayPeriods-standAlone-narrow-midnight": "ponoć",
	"dayPeriods-standAlone-narrow-am": "AM",
	"dayPeriods-standAlone-narrow-noon": "podne",
	"dayPeriods-standAlone-narrow-pm": "PM",
	"dayPeriods-standAlone-narrow-morning1": "ujutro",
	"dayPeriods-standAlone-narrow-afternoon1": "popodne",
	"dayPeriods-standAlone-narrow-evening1": "navečer",
	"dayPeriods-standAlone-narrow-night1": "noću",
	"dayPeriods-standAlone-wide-midnight": "ponoć",
	"dayPeriods-standAlone-wide-am": "AM",
	"dayPeriods-standAlone-wide-noon": "podne",
	"dayPeriods-standAlone-wide-pm": "PM",
	"dayPeriods-standAlone-wide-morning1": "ujutro",
	"dayPeriods-standAlone-wide-afternoon1": "popodne",
	"dayPeriods-standAlone-wide-evening1": "navečer",
	"dayPeriods-standAlone-wide-night1": "noću",
	"eraNames": [
		"prije Krista",
		"poslije Krista"
	],
	"eraAbbr": [
		"pr. Kr.",
		"po. Kr."
	],
	"eraNarrow": [
		"pr.n.e.",
		"AD"
	],
	"dateFormat-full": "EEEE, d. MMMM y.",
	"dateFormat-long": "d. MMMM y.",
	"dateFormat-medium": "d. MMM y.",
	"dateFormat-short": "dd. MM. y.",
	"timeFormat-full": "HH:mm:ss (zzzz)",
	"timeFormat-long": "HH:mm:ss z",
	"timeFormat-medium": "HH:mm:ss",
	"timeFormat-short": "HH:mm",
	"dateTimeFormat-full": "{1} 'u' {0}",
	"dateTimeFormat-long": "{1} 'u' {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "d.",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E, d.",
	"dateFormatItem-Ehm": "E h:mm a",
	"dateFormatItem-EHm": "E HH:mm",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-Gy": "y. G",
	"dateFormatItem-GyMMM": "LLL y. G",
	"dateFormatItem-GyMMMd": "d. MMM y. G",
	"dateFormatItem-GyMMMEd": "E, d. MMM y. G",
	"dateFormatItem-h": "h a",
	"dateFormatItem-H": "HH",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hmsv": "h:mm:ss a v",
	"dateFormatItem-Hmsv": "HH:mm:ss v",
	"dateFormatItem-hmv": "h:mm a v",
	"dateFormatItem-Hmv": "HH:mm v",
	"dateFormatItem-M": "L.",
	"dateFormatItem-Md": "dd. MM.",
	"dateFormatItem-MEd": "E, dd. MM.",
	"dateFormatItem-MMdd": "dd. MM.",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-MMMMEd": "E, d. MMMM",
	"dateFormatItem-MMMMW": "W. 'tjedan' 'u' MMM",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y.",
	"dateFormatItem-yM": "MM. y.",
	"dateFormatItem-yMd": "dd. MM. y.",
	"dateFormatItem-yMEd": "E, dd. MM. y.",
	"dateFormatItem-yMM": "MM. y.",
	"dateFormatItem-yMMM": "LLL y.",
	"dateFormatItem-yMMMd": "d. MMM y.",
	"dateFormatItem-yMMMEd": "E, d. MMM y.",
	"dateFormatItem-yMMMM": "LLLL y.",
	"dateFormatItem-yQQQ": "QQQ y.",
	"dateFormatItem-yQQQQ": "QQQQ y.",
	"dateFormatItem-yw": "w. 'tjedan' 'u' y.",
	"dateTimeFormats-appendItem-Timezone": "{0} ({1})",
	"field-era": "era",
	"field-year": "godina",
	"field-year-relative+-1": "prošle godine",
	"field-year-relative+0": "ove godine",
	"field-year-relative+1": "sljedeće godine",
	"field-year-short": "g.",
	"field-year-short-relative+-1": "prošle god.",
	"field-year-short-relative+0": "ove god.",
	"field-year-short-relative+1": "sljedeće god.",
	"field-year-narrow": "g.",
	"field-year-narrow-relative+-1": "prošle g.",
	"field-year-narrow-relative+0": "ove g.",
	"field-year-narrow-relative+1": "sljedeće g.",
	"field-quarter": "kvartal",
	"field-quarter-relative+-1": "prošli kvartal",
	"field-quarter-relative+0": "ovaj kvartal",
	"field-quarter-relative+1": "sljedeći kvartal",
	"field-quarter-short": "kv.",
	"field-quarter-short-relative+-1": "prošli kv.",
	"field-quarter-short-relative+0": "ovaj kv.",
	"field-quarter-short-relative+1": "sljedeći kv.",
	"field-quarter-narrow": "kv.",
	"field-quarter-narrow-relative+-1": "prošli kv.",
	"field-quarter-narrow-relative+0": "ovaj kv.",
	"field-quarter-narrow-relative+1": "sljedeći kv.",
	"field-month": "mjesec",
	"field-month-relative+-1": "prošli mjesec",
	"field-month-relative+0": "ovaj mjesec",
	"field-month-relative+1": "sljedeći mjesec",
	"field-month-short": "mj.",
	"field-month-short-relative+-1": "prošli mj.",
	"field-month-short-relative+0": "ovaj mj.",
	"field-month-short-relative+1": "sljedeći mj.",
	"field-month-narrow": "m.",
	"field-month-narrow-relative+-1": "prošli mj.",
	"field-month-narrow-relative+0": "ovaj mj.",
	"field-month-narrow-relative+1": "sljedeći mj.",
	"field-week": "tjedan",
	"field-week-relative+-1": "prošli tjedan",
	"field-week-relative+0": "ovaj tjedan",
	"field-week-relative+1": "sljedeći tjedan",
	"field-week-short": "tj.",
	"field-week-short-relative+-1": "prošli tj.",
	"field-week-short-relative+0": "ovaj tj.",
	"field-week-short-relative+1": "sljedeći tj.",
	"field-week-narrow": "tj.",
	"field-week-narrow-relative+-1": "prošli tj.",
	"field-week-narrow-relative+0": "ovaj tj.",
	"field-week-narrow-relative+1": "sljedeći tj.",
	"field-day": "dan",
	"field-day-relative+-2": "prekjučer",
	"field-day-relative+-1": "jučer",
	"field-day-relative+0": "danas",
	"field-day-relative+1": "sutra",
	"field-day-relative+2": "prekosutra",
	"field-day-short": "d.",
	"field-day-short-relative+-2": "prekjučer",
	"field-day-short-relative+-1": "jučer",
	"field-day-short-relative+0": "danas",
	"field-day-short-relative+1": "sutra",
	"field-day-short-relative+2": "prekosutra",
	"field-day-narrow": "d.",
	"field-day-narrow-relative+-2": "prekjučer",
	"field-day-narrow-relative+-1": "jučer",
	"field-day-narrow-relative+0": "danas",
	"field-day-narrow-relative+1": "sutra",
	"field-day-narrow-relative+2": "prekosutra",
	"field-weekday": "dan u tjednu",
	"field-sun-relative+-1": "prošla nedjelja",
	"field-sun-relative+0": "ova nedjelja",
	"field-sun-relative+1": "sljedeća nedjelja",
	"field-sun-short-relative+-1": "prošla ned.",
	"field-sun-short-relative+0": "ova ned.",
	"field-sun-short-relative+1": "sljedeća ned.",
	"field-sun-narrow-relative+-1": "prošla ned.",
	"field-sun-narrow-relative+0": "ova ned.",
	"field-sun-narrow-relative+1": "sljedeća ned.",
	"field-mon-relative+-1": "prošli ponedjeljak",
	"field-mon-relative+0": "ovaj ponedjeljak",
	"field-mon-relative+1": "sljedeći ponedjeljak",
	"field-mon-short-relative+-1": "prošli pon.",
	"field-mon-short-relative+0": "ovaj pon.",
	"field-mon-short-relative+1": "sljedeći pon.",
	"field-mon-narrow-relative+-1": "prošli pon.",
	"field-mon-narrow-relative+0": "ovaj pon.",
	"field-mon-narrow-relative+1": "sljedeći pon.",
	"field-tue-relative+-1": "prošli utorak",
	"field-tue-relative+0": "ovaj utorak",
	"field-tue-relative+1": "sljedeći utorak",
	"field-tue-short-relative+-1": "prošli uto.",
	"field-tue-short-relative+0": "ovaj uto.",
	"field-tue-short-relative+1": "sljedeći uto.",
	"field-tue-narrow-relative+-1": "prošli uto.",
	"field-tue-narrow-relative+0": "ovaj uto.",
	"field-tue-narrow-relative+1": "sljedeći uto.",
	"field-wed-relative+-1": "prošla srijeda",
	"field-wed-relative+0": "ova srijeda",
	"field-wed-relative+1": "sljedeća srijeda",
	"field-wed-short-relative+-1": "prošla sri.",
	"field-wed-short-relative+0": "ova sri.",
	"field-wed-short-relative+1": "sljedeća sri.",
	"field-wed-narrow-relative+-1": "prošla sri.",
	"field-wed-narrow-relative+0": "ova sri.",
	"field-wed-narrow-relative+1": "sljedeća sri.",
	"field-thu-relative+-1": "prošli četvrtak",
	"field-thu-relative+0": "ovaj četvrtak",
	"field-thu-relative+1": "sljedeći četvrtak",
	"field-thu-short-relative+-1": "prošli čet.",
	"field-thu-short-relative+0": "ovaj čet.",
	"field-thu-short-relative+1": "sljedeći čet.",
	"field-thu-narrow-relative+-1": "prošli čet.",
	"field-thu-narrow-relative+0": "ovaj čet.",
	"field-thu-narrow-relative+1": "sljedeći čet.",
	"field-fri-relative+-1": "prošli petak",
	"field-fri-relative+0": "ovaj petak",
	"field-fri-relative+1": "sljedeći petak",
	"field-fri-short-relative+-1": "prošli pet.",
	"field-fri-short-relative+0": "ovaj pet.",
	"field-fri-short-relative+1": "sljedeći pet.",
	"field-fri-narrow-relative+-1": "prošli pet.",
	"field-fri-narrow-relative+0": "ovaj pet.",
	"field-fri-narrow-relative+1": "sljedeći pet.",
	"field-sat-relative+-1": "prošla subota",
	"field-sat-relative+0": "ova subota",
	"field-sat-relative+1": "sljedeća subota",
	"field-sat-short-relative+-1": "prošla sub.",
	"field-sat-short-relative+0": "ova sub.",
	"field-sat-short-relative+1": "sljedeća sub.",
	"field-sat-narrow-relative+-1": "prošla sub.",
	"field-sat-narrow-relative+0": "ova sub.",
	"field-sat-narrow-relative+1": "sljedeća sub.",
	"field-dayperiod": "AM/PM",
	"field-hour": "sat",
	"field-hour-relative+0": "ovaj sat",
	"field-hour-short": "h",
	"field-hour-narrow": "h",
	"field-minute": "minuta",
	"field-minute-relative+0": "ova minuta",
	"field-minute-short": "min",
	"field-minute-narrow": "min",
	"field-second": "sekunda",
	"field-second-relative+0": "sad",
	"field-second-short": "s",
	"field-second-narrow": "s",
	"field-zone": "vremenska zona"
}
//end v1.x content
);