define(
//begin v1.x content
{
	"months-format-abbr": [
		"Meskerem",
		"Tekemt",
		"Hedar",
		"Tahsas",
		"Ter",
		"Yekatit",
		"Megabit",
		"Miazia",
		"Genbot",
		"Sene",
		"Hamle",
		"Nehasse",
		"Pagumen"
	],
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12",
		"13"
	],
	"months-standAlone-abbr": [
		"Meskerem",
		"Tekemt",
		"Hedar",
		"Tahsas",
		"Ter",
		"Yekatit",
		"Megabit",
		"Miazia",
		"Genbot",
		"Sene",
		"Hamle",
		"Nehasse",
		"Pagumen"
	],
	"months-standAlone-wide": [
		"Meskerem",
		"Tekemt",
		"Hedar",
		"Tahsas",
		"Ter",
		"Yekatit",
		"Megabit",
		"Miazia",
		"Genbot",
		"Sene",
		"Hamle",
		"Nehasse",
		"Pagumen"
	],
	"field-era": "era",
	"field-year": "ano",
	"field-year-relative+-1": "ano passado",
	"field-year-relative+0": "este ano",
	"field-year-relative+1": "próximo ano",
	"field-year-short": "ano",
	"field-year-narrow": "ano",
	"field-quarter": "trimestre",
	"field-quarter-relative+-1": "último trimestre",
	"field-quarter-relative+0": "este trimestre",
	"field-quarter-relative+1": "próximo trimestre",
	"field-quarter-short": "trim.",
	"field-quarter-narrow": "trim.",
	"field-month": "mês",
	"field-month-relative+-1": "mês passado",
	"field-month-relative+0": "este mês",
	"field-month-relative+1": "próximo mês",
	"field-month-short": "mês",
	"field-month-narrow": "mês",
	"field-week": "semana",
	"field-week-relative+-1": "semana passada",
	"field-week-relative+0": "esta semana",
	"field-week-relative+1": "próxima semana",
	"field-week-short": "sem.",
	"field-week-narrow": "sem.",
	"field-day": "dia",
	"field-day-relative+-2": "anteontem",
	"field-day-relative+-1": "ontem",
	"field-day-relative+0": "hoje",
	"field-day-relative+1": "amanhã",
	"field-day-relative+2": "depois de amanhã",
	"field-day-short": "dia",
	"field-day-narrow": "dia",
	"field-weekday": "dia da semana",
	"field-sun-relative+-1": "domingo passado",
	"field-sun-relative+0": "este domingo",
	"field-sun-relative+1": "próximo domingo",
	"field-sun-short-relative+-1": "dom. passado",
	"field-sun-short-relative+0": "este dom.",
	"field-sun-short-relative+1": "próximo dom.",
	"field-sun-narrow-relative+-1": "dom. passado",
	"field-sun-narrow-relative+0": "este dom.",
	"field-sun-narrow-relative+1": "próximo dom.",
	"field-mon-relative+-1": "segunda-feira passada",
	"field-mon-relative+0": "esta segunda-feira",
	"field-mon-relative+1": "próxima segunda-feira",
	"field-mon-short-relative+-1": "seg. passada",
	"field-mon-short-relative+0": "esta seg.",
	"field-mon-short-relative+1": "próxima seg.",
	"field-mon-narrow-relative+-1": "seg. passada",
	"field-mon-narrow-relative+0": "esta seg.",
	"field-mon-narrow-relative+1": "próxima seg.",
	"field-tue-relative+-1": "terça-feira passada",
	"field-tue-relative+0": "esta terça-feira",
	"field-tue-relative+1": "próxima terça-feira",
	"field-tue-short-relative+-1": "ter. passada",
	"field-tue-short-relative+0": "esta ter.",
	"field-tue-short-relative+1": "próxima ter.",
	"field-tue-narrow-relative+-1": "ter. passada",
	"field-tue-narrow-relative+0": "esta ter.",
	"field-tue-narrow-relative+1": "próxima ter.",
	"field-wed-relative+-1": "quarta-feira passada",
	"field-wed-relative+0": "esta quarta-feira",
	"field-wed-relative+1": "próxima quarta-feira",
	"field-wed-short-relative+-1": "qua. passada",
	"field-wed-short-relative+0": "esta qua.",
	"field-wed-short-relative+1": "próxima qua.",
	"field-wed-narrow-relative+-1": "qua. passada",
	"field-wed-narrow-relative+0": "esta qua.",
	"field-wed-narrow-relative+1": "próxima qua.",
	"field-thu-relative+-1": "quinta-feira passada",
	"field-thu-relative+0": "esta quinta-feira",
	"field-thu-relative+1": "próxima quinta-feira",
	"field-thu-short-relative+-1": "qui. passada",
	"field-thu-short-relative+0": "esta qui.",
	"field-thu-short-relative+1": "próx. qui",
	"field-thu-narrow-relative+-1": "qui. passada",
	"field-thu-narrow-relative+0": "esta qui.",
	"field-thu-narrow-relative+1": "próx. qui",
	"field-fri-relative+-1": "sexta-feira passada",
	"field-fri-relative+0": "esta sexta-feira",
	"field-fri-relative+1": "próxima sexta-feira",
	"field-fri-short-relative+-1": "sex. passada",
	"field-fri-short-relative+0": "esta sex.",
	"field-fri-short-relative+1": "próxima sex.",
	"field-fri-narrow-relative+-1": "sex. passada",
	"field-fri-narrow-relative+0": "esta sex.",
	"field-fri-narrow-relative+1": "próxima sex.",
	"field-sat-relative+-1": "sábado passado",
	"field-sat-relative+0": "este sábado",
	"field-sat-relative+1": "próximo sábado",
	"field-sat-short-relative+-1": "sáb. passado",
	"field-sat-short-relative+0": "este sáb.",
	"field-sat-short-relative+1": "próximo sáb.",
	"field-sat-narrow-relative+-1": "sáb. passado",
	"field-sat-narrow-relative+0": "este sáb.",
	"field-sat-narrow-relative+1": "próximo sáb.",
	"field-dayperiod": "AM/PM",
	"field-hour": "hora",
	"field-hour-relative+0": "esta hora",
	"field-hour-short": "h",
	"field-hour-narrow": "h",
	"field-minute": "minuto",
	"field-minute-relative+0": "este minuto",
	"field-minute-short": "min.",
	"field-minute-narrow": "m",
	"field-second": "segundo",
	"field-second-relative+0": "agora",
	"field-second-short": "seg.",
	"field-second-narrow": "s",
	"field-zone": "fuso horário"
}
//end v1.x content
);