define(
//begin v1.x content
{
	"months-format-abbr": [
		"jan",
		"fev",
		"mar",
		"abr",
		"mai",
		"jun",
		"jul",
		"ago",
		"set",
		"out",
		"nov",
		"dez"
	],
	"months-format-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"months-format-wide": [
		"janeiro",
		"fevereiro",
		"março",
		"abril",
		"maio",
		"junho",
		"julho",
		"agosto",
		"setembro",
		"outubro",
		"novembro",
		"dezembro"
	],
	"months-standAlone-abbr": [
		"jan",
		"fev",
		"mar",
		"abr",
		"mai",
		"jun",
		"jul",
		"ago",
		"set",
		"out",
		"nov",
		"dez"
	],
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"months-standAlone-wide": [
		"janeiro",
		"fevereiro",
		"março",
		"abril",
		"maio",
		"junho",
		"julho",
		"agosto",
		"setembro",
		"outubro",
		"novembro",
		"dezembro"
	],
	"days-format-abbr": [
		"dom",
		"seg",
		"ter",
		"qua",
		"qui",
		"sex",
		"sáb"
	],
	"days-format-narrow": [
		"D",
		"S",
		"T",
		"Q",
		"Q",
		"S",
		"S"
	],
	"days-format-short": [
		"dom",
		"seg",
		"ter",
		"qua",
		"qui",
		"sex",
		"sáb"
	],
	"days-format-wide": [
		"domingo",
		"segunda-feira",
		"terça-feira",
		"quarta-feira",
		"quinta-feira",
		"sexta-feira",
		"sábado"
	],
	"days-standAlone-abbr": [
		"dom",
		"seg",
		"ter",
		"qua",
		"qui",
		"sex",
		"sáb"
	],
	"days-standAlone-narrow": [
		"D",
		"S",
		"T",
		"Q",
		"Q",
		"S",
		"S"
	],
	"days-standAlone-short": [
		"dom",
		"seg",
		"ter",
		"qua",
		"qui",
		"sex",
		"sáb"
	],
	"days-standAlone-wide": [
		"domingo",
		"segunda-feira",
		"terça-feira",
		"quarta-feira",
		"quinta-feira",
		"sexta-feira",
		"sábado"
	],
	"quarters-format-abbr": [
		"T1",
		"T2",
		"T3",
		"T4"
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"1º trimestre",
		"2º trimestre",
		"3º trimestre",
		"4º trimestre"
	],
	"quarters-standAlone-abbr": [
		"T1",
		"T2",
		"T3",
		"T4"
	],
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-standAlone-wide": [
		"1º trimestre",
		"2º trimestre",
		"3º trimestre",
		"4º trimestre"
	],
	"dayPeriods-format-abbr-midnight": "meia-noite",
	"dayPeriods-format-abbr-am": "AM",
	"dayPeriods-format-abbr-noon": "meio-dia",
	"dayPeriods-format-abbr-pm": "PM",
	"dayPeriods-format-abbr-morning1": "da manhã",
	"dayPeriods-format-abbr-afternoon1": "da tarde",
	"dayPeriods-format-abbr-evening1": "da noite",
	"dayPeriods-format-abbr-night1": "da madrugada",
	"dayPeriods-format-narrow-midnight": "meia-noite",
	"dayPeriods-format-narrow-am": "AM",
	"dayPeriods-format-narrow-noon": "meio-dia",
	"dayPeriods-format-narrow-pm": "PM",
	"dayPeriods-format-narrow-morning1": "da manhã",
	"dayPeriods-format-narrow-afternoon1": "da tarde",
	"dayPeriods-format-narrow-evening1": "da noite",
	"dayPeriods-format-narrow-night1": "da madrugada",
	"dayPeriods-format-wide-midnight": "meia-noite",
	"dayPeriods-format-wide-am": "AM",
	"dayPeriods-format-wide-noon": "meio-dia",
	"dayPeriods-format-wide-pm": "PM",
	"dayPeriods-format-wide-morning1": "da manhã",
	"dayPeriods-format-wide-afternoon1": "da tarde",
	"dayPeriods-format-wide-evening1": "da noite",
	"dayPeriods-format-wide-night1": "da madrugada",
	"dayPeriods-standAlone-abbr-midnight": "meia-noite",
	"dayPeriods-standAlone-abbr-am": "AM",
	"dayPeriods-standAlone-abbr-noon": "meio-dia",
	"dayPeriods-standAlone-abbr-pm": "PM",
	"dayPeriods-standAlone-abbr-morning1": "manhã",
	"dayPeriods-standAlone-abbr-afternoon1": "tarde",
	"dayPeriods-standAlone-abbr-evening1": "noite",
	"dayPeriods-standAlone-abbr-night1": "madrugada",
	"dayPeriods-standAlone-narrow-midnight": "meia-noite",
	"dayPeriods-standAlone-narrow-am": "AM",
	"dayPeriods-standAlone-narrow-noon": "meio-dia",
	"dayPeriods-standAlone-narrow-pm": "PM",
	"dayPeriods-standAlone-narrow-morning1": "manhã",
	"dayPeriods-standAlone-narrow-afternoon1": "tarde",
	"dayPeriods-standAlone-narrow-evening1": "noite",
	"dayPeriods-standAlone-narrow-night1": "madrugada",
	"dayPeriods-standAlone-wide-midnight": "meia-noite",
	"dayPeriods-standAlone-wide-am": "AM",
	"dayPeriods-standAlone-wide-noon": "meio-dia",
	"dayPeriods-standAlone-wide-pm": "PM",
	"dayPeriods-standAlone-wide-morning1": "manhã",
	"dayPeriods-standAlone-wide-afternoon1": "tarde",
	"dayPeriods-standAlone-wide-evening1": "noite",
	"dayPeriods-standAlone-wide-night1": "madrugada",
	"eraNames": [
		"antes de Cristo",
		"depois de Cristo"
	],
	"eraAbbr": [
		"a.C.",
		"d.C."
	],
	"dateFormat-full": "EEEE, d 'de' MMMM 'de' y",
	"dateFormat-long": "d 'de' MMMM 'de' y",
	"dateFormat-medium": "d 'de' MMM 'de' y",
	"dateFormat-short": "dd/MM/y",
	"timeFormat-full": "HH:mm:ss zzzz",
	"timeFormat-long": "HH:mm:ss z",
	"timeFormat-medium": "HH:mm:ss",
	"timeFormat-short": "HH:mm",
	"dateTimeFormat-full": "{1} {0}",
	"dateTimeFormat-long": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "d",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-Ehm": "E, h:mm a",
	"dateFormatItem-EHm": "E, HH:mm",
	"dateFormatItem-Ehms": "E, h:mm:ss a",
	"dateFormatItem-EHms": "E, HH:mm:ss",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "MMM 'de' y G",
	"dateFormatItem-GyMMMd": "d 'de' MMM 'de' y G",
	"dateFormatItem-GyMMMEd": "E, d 'de' MMM 'de' y G",
	"dateFormatItem-h": "h a",
	"dateFormatItem-H": "HH",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hmsv": "h:mm:ss a v",
	"dateFormatItem-Hmsv": "HH:mm:ss v",
	"dateFormatItem-hmv": "h:mm a v",
	"dateFormatItem-Hmv": "HH:mm v",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-MEd": "E, dd/MM",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d 'de' MMM",
	"dateFormatItem-MMMEd": "E, d 'de' MMM",
	"dateFormatItem-MMMMd": "d 'de' MMMM",
	"dateFormatItem-MMMMEd": "E, d 'de' MMMM",
	"dateFormatItem-MMMMW": "W'ª' 'semana' 'de' MMMM",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y",
	"dateFormatItem-yM": "MM/y",
	"dateFormatItem-yMd": "dd/MM/y",
	"dateFormatItem-yMEd": "E, dd/MM/y",
	"dateFormatItem-yMM": "MM/y",
	"dateFormatItem-yMMM": "MMM 'de' y",
	"dateFormatItem-yMMMd": "d 'de' MMM 'de' y",
	"dateFormatItem-yMMMEd": "E, d 'de' MMM 'de' y",
	"dateFormatItem-yMMMM": "MMMM 'de' y",
	"dateFormatItem-yMMMMd": "d 'de' MMMM 'de' y",
	"dateFormatItem-yMMMMEd": "E, d 'de' MMMM 'de' y",
	"dateFormatItem-yQQQ": "QQQ 'de' y",
	"dateFormatItem-yQQQQ": "QQQQ 'de' y",
	"dateFormatItem-yw": "w'ª' 'semana' 'de' y",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-era": "era",
	"field-year": "ano",
	"field-year-relative+-1": "ano passado",
	"field-year-relative+0": "este ano",
	"field-year-relative+1": "próximo ano",
	"field-year-short": "ano",
	"field-year-narrow": "ano",
	"field-quarter": "trimestre",
	"field-quarter-relative+-1": "último trimestre",
	"field-quarter-relative+0": "este trimestre",
	"field-quarter-relative+1": "próximo trimestre",
	"field-quarter-short": "trim.",
	"field-quarter-narrow": "trim.",
	"field-month": "mês",
	"field-month-relative+-1": "mês passado",
	"field-month-relative+0": "este mês",
	"field-month-relative+1": "próximo mês",
	"field-month-short": "mês",
	"field-month-narrow": "mês",
	"field-week": "semana",
	"field-week-relative+-1": "semana passada",
	"field-week-relative+0": "esta semana",
	"field-week-relative+1": "próxima semana",
	"field-week-short": "sem.",
	"field-week-narrow": "sem.",
	"field-day": "dia",
	"field-day-relative+-2": "anteontem",
	"field-day-relative+-1": "ontem",
	"field-day-relative+0": "hoje",
	"field-day-relative+1": "amanhã",
	"field-day-relative+2": "depois de amanhã",
	"field-day-short": "dia",
	"field-day-narrow": "dia",
	"field-weekday": "dia da semana",
	"field-sun-relative+-1": "domingo passado",
	"field-sun-relative+0": "este domingo",
	"field-sun-relative+1": "próximo domingo",
	"field-sun-short-relative+-1": "dom. passado",
	"field-sun-short-relative+0": "este dom.",
	"field-sun-short-relative+1": "próximo dom.",
	"field-sun-narrow-relative+-1": "dom. passado",
	"field-sun-narrow-relative+0": "este dom.",
	"field-sun-narrow-relative+1": "próximo dom.",
	"field-mon-relative+-1": "segunda-feira passada",
	"field-mon-relative+0": "esta segunda-feira",
	"field-mon-relative+1": "próxima segunda-feira",
	"field-mon-short-relative+-1": "seg. passada",
	"field-mon-short-relative+0": "esta seg.",
	"field-mon-short-relative+1": "próxima seg.",
	"field-mon-narrow-relative+-1": "seg. passada",
	"field-mon-narrow-relative+0": "esta seg.",
	"field-mon-narrow-relative+1": "próxima seg.",
	"field-tue-relative+-1": "terça-feira passada",
	"field-tue-relative+0": "esta terça-feira",
	"field-tue-relative+1": "próxima terça-feira",
	"field-tue-short-relative+-1": "ter. passada",
	"field-tue-short-relative+0": "esta ter.",
	"field-tue-short-relative+1": "próxima ter.",
	"field-tue-narrow-relative+-1": "ter. passada",
	"field-tue-narrow-relative+0": "esta ter.",
	"field-tue-narrow-relative+1": "próxima ter.",
	"field-wed-relative+-1": "quarta-feira passada",
	"field-wed-relative+0": "esta quarta-feira",
	"field-wed-relative+1": "próxima quarta-feira",
	"field-wed-short-relative+-1": "qua. passada",
	"field-wed-short-relative+0": "esta qua.",
	"field-wed-short-relative+1": "próxima qua.",
	"field-wed-narrow-relative+-1": "qua. passada",
	"field-wed-narrow-relative+0": "esta qua.",
	"field-wed-narrow-relative+1": "próxima qua.",
	"field-thu-relative+-1": "quinta-feira passada",
	"field-thu-relative+0": "esta quinta-feira",
	"field-thu-relative+1": "próxima quinta-feira",
	"field-thu-short-relative+-1": "qui. passada",
	"field-thu-short-relative+0": "esta qui.",
	"field-thu-short-relative+1": "próx. qui",
	"field-thu-narrow-relative+-1": "qui. passada",
	"field-thu-narrow-relative+0": "esta qui.",
	"field-thu-narrow-relative+1": "próx. qui",
	"field-fri-relative+-1": "sexta-feira passada",
	"field-fri-relative+0": "esta sexta-feira",
	"field-fri-relative+1": "próxima sexta-feira",
	"field-fri-short-relative+-1": "sex. passada",
	"field-fri-short-relative+0": "esta sex.",
	"field-fri-short-relative+1": "próxima sex.",
	"field-fri-narrow-relative+-1": "sex. passada",
	"field-fri-narrow-relative+0": "esta sex.",
	"field-fri-narrow-relative+1": "próxima sex.",
	"field-sat-relative+-1": "sábado passado",
	"field-sat-relative+0": "este sábado",
	"field-sat-relative+1": "próximo sábado",
	"field-sat-short-relative+-1": "sáb. passado",
	"field-sat-short-relative+0": "este sáb.",
	"field-sat-short-relative+1": "próximo sáb.",
	"field-sat-narrow-relative+-1": "sáb. passado",
	"field-sat-narrow-relative+0": "este sáb.",
	"field-sat-narrow-relative+1": "próximo sáb.",
	"field-dayperiod": "AM/PM",
	"field-hour": "hora",
	"field-hour-relative+0": "esta hora",
	"field-hour-short": "h",
	"field-hour-narrow": "h",
	"field-minute": "minuto",
	"field-minute-relative+0": "este minuto",
	"field-minute-short": "min.",
	"field-minute-narrow": "m",
	"field-second": "segundo",
	"field-second-relative+0": "agora",
	"field-second-short": "seg.",
	"field-second-narrow": "s",
	"field-zone": "fuso horário",
	"eraNarrow": [
		"a.C.",
		"d.C."
	]
}
//end v1.x content
);