define(
//begin v1.x content
{
	"months-format-abbr": [
		"jan.",
		"feb.",
		"mars",
		"apr.",
		"maj",
		"juni",
		"juli",
		"aug.",
		"sep.",
		"okt.",
		"nov.",
		"dec."
	],
	"months-format-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"months-format-wide": [
		"januari",
		"februari",
		"mars",
		"april",
		"maj",
		"juni",
		"juli",
		"augusti",
		"september",
		"oktober",
		"november",
		"december"
	],
	"months-standAlone-abbr": [
		"jan.",
		"feb.",
		"mars",
		"apr.",
		"maj",
		"juni",
		"juli",
		"aug.",
		"sep.",
		"okt.",
		"nov.",
		"dec."
	],
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"months-standAlone-wide": [
		"januari",
		"februari",
		"mars",
		"april",
		"maj",
		"juni",
		"juli",
		"augusti",
		"september",
		"oktober",
		"november",
		"december"
	],
	"days-format-abbr": [
		"sön",
		"mån",
		"tis",
		"ons",
		"tors",
		"fre",
		"lör"
	],
	"days-format-narrow": [
		"S",
		"M",
		"T",
		"O",
		"T",
		"F",
		"L"
	],
	"days-format-short": [
		"sö",
		"må",
		"ti",
		"on",
		"to",
		"fr",
		"lö"
	],
	"days-format-wide": [
		"söndag",
		"måndag",
		"tisdag",
		"onsdag",
		"torsdag",
		"fredag",
		"lördag"
	],
	"days-standAlone-abbr": [
		"sön",
		"mån",
		"tis",
		"ons",
		"tors",
		"fre",
		"lör"
	],
	"days-standAlone-narrow": [
		"S",
		"M",
		"T",
		"O",
		"T",
		"F",
		"L"
	],
	"days-standAlone-short": [
		"sö",
		"må",
		"ti",
		"on",
		"to",
		"fr",
		"lö"
	],
	"days-standAlone-wide": [
		"söndag",
		"måndag",
		"tisdag",
		"onsdag",
		"torsdag",
		"fredag",
		"lördag"
	],
	"quarters-format-abbr": [
		"K1",
		"K2",
		"K3",
		"K4"
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"1:a kvartalet",
		"2:a kvartalet",
		"3:e kvartalet",
		"4:e kvartalet"
	],
	"quarters-standAlone-abbr": [
		"K1",
		"K2",
		"K3",
		"K4"
	],
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-standAlone-wide": [
		"1:a kvartalet",
		"2:a kvartalet",
		"3:e kvartalet",
		"4:e kvartalet"
	],
	"dayPeriods-format-abbr-midnight": "midnatt",
	"dayPeriods-format-abbr-am": "fm",
	"dayPeriods-format-abbr-pm": "em",
	"dayPeriods-format-abbr-morning1": "på morg.",
	"dayPeriods-format-abbr-morning2": "på förm.",
	"dayPeriods-format-abbr-afternoon1": "på efterm.",
	"dayPeriods-format-abbr-evening1": "på kvällen",
	"dayPeriods-format-abbr-night1": "på natten",
	"dayPeriods-format-narrow-midnight": "midn.",
	"dayPeriods-format-narrow-am": "fm",
	"dayPeriods-format-narrow-pm": "em",
	"dayPeriods-format-narrow-morning1": "på morg.",
	"dayPeriods-format-narrow-morning2": "på förm.",
	"dayPeriods-format-narrow-afternoon1": "på efterm.",
	"dayPeriods-format-narrow-evening1": "på kvällen",
	"dayPeriods-format-narrow-night1": "på natten",
	"dayPeriods-format-wide-midnight": "midnatt",
	"dayPeriods-format-wide-am": "fm",
	"dayPeriods-format-wide-pm": "em",
	"dayPeriods-format-wide-morning1": "på morgonen",
	"dayPeriods-format-wide-morning2": "på förmiddagen",
	"dayPeriods-format-wide-afternoon1": "på eftermiddagen",
	"dayPeriods-format-wide-evening1": "på kvällen",
	"dayPeriods-format-wide-night1": "på natten",
	"dayPeriods-standAlone-abbr-midnight": "midnatt",
	"dayPeriods-standAlone-abbr-am": "f.m.",
	"dayPeriods-standAlone-abbr-pm": "e.m.",
	"dayPeriods-standAlone-abbr-morning1": "morgon",
	"dayPeriods-standAlone-abbr-morning2": "förm.",
	"dayPeriods-standAlone-abbr-afternoon1": "efterm.",
	"dayPeriods-standAlone-abbr-evening1": "kväll",
	"dayPeriods-standAlone-abbr-night1": "natt",
	"dayPeriods-standAlone-narrow-midnight": "midn.",
	"dayPeriods-standAlone-narrow-am": "fm",
	"dayPeriods-standAlone-narrow-pm": "em",
	"dayPeriods-standAlone-narrow-morning1": "morg.",
	"dayPeriods-standAlone-narrow-morning2": "förm.",
	"dayPeriods-standAlone-narrow-afternoon1": "efterm.",
	"dayPeriods-standAlone-narrow-evening1": "kväll",
	"dayPeriods-standAlone-narrow-night1": "natt",
	"dayPeriods-standAlone-wide-midnight": "midnatt",
	"dayPeriods-standAlone-wide-am": "förmiddag",
	"dayPeriods-standAlone-wide-pm": "eftermiddag",
	"dayPeriods-standAlone-wide-morning1": "morgon",
	"dayPeriods-standAlone-wide-morning2": "förmiddag",
	"dayPeriods-standAlone-wide-afternoon1": "eftermiddag",
	"dayPeriods-standAlone-wide-evening1": "kväll",
	"dayPeriods-standAlone-wide-night1": "natt",
	"eraNames": [
		"före Kristus",
		"efter Kristus"
	],
	"eraAbbr": [
		"f.Kr.",
		"e.Kr."
	],
	"eraNarrow": [
		"f.Kr.",
		"fvt",
		"e.Kr.",
		"vt"
	],
	"dateFormat-full": "EEEE d MMMM y",
	"dateFormat-long": "d MMMM y",
	"dateFormat-medium": "d MMM y",
	"dateFormat-short": "y-MM-dd",
	"timeFormat-full": "'kl'. HH.mm.ss zzzz",
	"timeFormat-long": "HH.mm.ss z",
	"timeFormat-medium": "HH.mm.ss",
	"timeFormat-short": "HH.mm",
	"dateTimeFormat-full": "{1} {0}",
	"dateTimeFormat-long": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "d",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-Ehm": "E h:mm a",
	"dateFormatItem-EHm": "E HH:mm",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"dateFormatItem-GyMMMEd": "E d MMM y G",
	"dateFormatItem-h": "h a",
	"dateFormatItem-H": "HH",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hmsv": "h:mm:ss a v",
	"dateFormatItem-Hmsv": "HH:mm:ss v",
	"dateFormatItem-hmv": "h:mm a v",
	"dateFormatItem-Hmv": "HH:mm v",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-MMd": "d/M",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MMMEd": "E d MMM",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-MMMMEd": "E d MMMM",
	"dateFormatItem-MMMMW": "'vecka' W 'i' MMM",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y",
	"dateFormatItem-yM": "y-MM",
	"dateFormatItem-yMd": "y-MM-dd",
	"dateFormatItem-yMEd": "E, y-MM-dd",
	"dateFormatItem-yMM": "y-MM",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yMMMd": "d MMM y",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"dateFormatItem-yw": "'vecka' w, y",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-era": "era",
	"field-year": "år",
	"field-year-relative+-1": "i fjol",
	"field-year-relative+0": "i år",
	"field-year-relative+1": "nästa år",
	"field-year-short": "år",
	"field-year-short-relative+-1": "i fjol",
	"field-year-short-relative+0": "i år",
	"field-year-short-relative+1": "nästa år",
	"field-year-narrow": "år",
	"field-year-narrow-relative+-1": "i fjol",
	"field-year-narrow-relative+0": "i år",
	"field-year-narrow-relative+1": "nästa år",
	"field-quarter": "kvartal",
	"field-quarter-relative+-1": "förra kvartalet",
	"field-quarter-relative+0": "detta kvartal",
	"field-quarter-relative+1": "nästa kvartal",
	"field-quarter-short": "kv.",
	"field-quarter-short-relative+-1": "förra kv.",
	"field-quarter-short-relative+0": "detta kv.",
	"field-quarter-short-relative+1": "nästa kv.",
	"field-quarter-narrow": "kv.",
	"field-quarter-narrow-relative+-1": "förra kv.",
	"field-quarter-narrow-relative+0": "detta kv.",
	"field-quarter-narrow-relative+1": "nästa kv.",
	"field-month": "månad",
	"field-month-relative+-1": "förra månaden",
	"field-month-relative+0": "denna månad",
	"field-month-relative+1": "nästa månad",
	"field-month-short": "m",
	"field-month-short-relative+-1": "förra mån.",
	"field-month-short-relative+0": "denna mån.",
	"field-month-short-relative+1": "nästa mån.",
	"field-month-narrow": "mån",
	"field-month-narrow-relative+-1": "förra mån.",
	"field-month-narrow-relative+0": "denna mån.",
	"field-month-narrow-relative+1": "nästa mån.",
	"field-week": "vecka",
	"field-week-relative+-1": "förra veckan",
	"field-week-relative+0": "denna vecka",
	"field-week-relative+1": "nästa vecka",
	"field-week-short": "v",
	"field-week-short-relative+-1": "förra v.",
	"field-week-short-relative+0": "denna v.",
	"field-week-short-relative+1": "nästa v.",
	"field-week-narrow": "v",
	"field-week-narrow-relative+-1": "förra v.",
	"field-week-narrow-relative+0": "denna v.",
	"field-week-narrow-relative+1": "nästa v.",
	"field-day": "dag",
	"field-day-relative+-2": "i förrgår",
	"field-day-relative+-1": "i går",
	"field-day-relative+0": "i dag",
	"field-day-relative+1": "i morgon",
	"field-day-relative+2": "i övermorgon",
	"field-day-short": "dag",
	"field-day-short-relative+-2": "i förrgår",
	"field-day-short-relative+-1": "i går",
	"field-day-short-relative+0": "i dag",
	"field-day-short-relative+1": "i morgon",
	"field-day-short-relative+2": "i övermorgon",
	"field-day-narrow": "dag",
	"field-day-narrow-relative+-2": "i förrgår",
	"field-day-narrow-relative+-1": "i går",
	"field-day-narrow-relative+0": "i dag",
	"field-day-narrow-relative+1": "i morgon",
	"field-day-narrow-relative+2": "i övermorgon",
	"field-weekday": "veckodag",
	"field-sun-relative+-1": "söndag förra veckan",
	"field-sun-relative+0": "söndag denna vecka",
	"field-sun-relative+1": "söndag nästa vecka",
	"field-sun-short-relative+-1": "sön. förra veckan",
	"field-sun-short-relative+0": "sön. denna vecka",
	"field-sun-short-relative+1": "sön. nästa vecka",
	"field-sun-narrow-relative+-1": "förra sön.",
	"field-sun-narrow-relative+0": "denna sön.",
	"field-sun-narrow-relative+1": "nästa sön.",
	"field-mon-relative+-1": "måndag förra veckan",
	"field-mon-relative+0": "måndag denna vecka",
	"field-mon-relative+1": "måndag nästa vecka",
	"field-mon-short-relative+-1": "mån. förra veckan",
	"field-mon-short-relative+0": "mån. denna vecka",
	"field-mon-short-relative+1": "mån. nästa vecka",
	"field-mon-narrow-relative+-1": "förra mån.",
	"field-mon-narrow-relative+0": "denna mån.",
	"field-mon-narrow-relative+1": "nästa mån.",
	"field-tue-relative+-1": "tisdag förra veckan",
	"field-tue-relative+0": "tisdag denna vecka",
	"field-tue-relative+1": "tisdag nästa vecka",
	"field-tue-short-relative+-1": "tis. förra veckan",
	"field-tue-short-relative+0": "tis. denna vecka",
	"field-tue-short-relative+1": "tis. nästa vecka",
	"field-tue-narrow-relative+-1": "förra tis.",
	"field-tue-narrow-relative+0": "denna tis.",
	"field-tue-narrow-relative+1": "nästa tis.",
	"field-wed-relative+-1": "onsdag förra veckan",
	"field-wed-relative+0": "onsdag denna vecka",
	"field-wed-relative+1": "onsdag nästa vecka",
	"field-wed-short-relative+-1": "ons. förra veckan",
	"field-wed-short-relative+0": "ons. denna vecka",
	"field-wed-short-relative+1": "ons. nästa vecka",
	"field-wed-narrow-relative+-1": "förra ons.",
	"field-wed-narrow-relative+0": "denna ons.",
	"field-wed-narrow-relative+1": "nästa ons.",
	"field-thu-relative+-1": "torsdag förra veckan",
	"field-thu-relative+0": "torsdag denna vecka",
	"field-thu-relative+1": "torsdag nästa vecka",
	"field-thu-short-relative+-1": "tors. förra veckan",
	"field-thu-short-relative+0": "tors. denna vecka",
	"field-thu-short-relative+1": "tors. nästa vecka",
	"field-thu-narrow-relative+-1": "förra tors.",
	"field-thu-narrow-relative+0": "denna tors.",
	"field-thu-narrow-relative+1": "nästa tors.",
	"field-fri-relative+-1": "fredag förra veckan",
	"field-fri-relative+0": "fredag denna vecka",
	"field-fri-relative+1": "fredag nästa vecka",
	"field-fri-short-relative+-1": "fre. förra veckan",
	"field-fri-short-relative+0": "fre. denna vecka",
	"field-fri-short-relative+1": "fre. nästa vecka",
	"field-fri-narrow-relative+-1": "förra fre.",
	"field-fri-narrow-relative+0": "denna fre.",
	"field-fri-narrow-relative+1": "nästa fre.",
	"field-sat-relative+-1": "lördag förra veckan",
	"field-sat-relative+0": "lördag denna vecka",
	"field-sat-relative+1": "lördag nästa vecka",
	"field-sat-short-relative+-1": "lör. förra veckan",
	"field-sat-short-relative+0": "lör. denna vecka",
	"field-sat-short-relative+1": "lör. nästa vecka",
	"field-sat-narrow-relative+-1": "förra lör.",
	"field-sat-narrow-relative+0": "denna lör.",
	"field-sat-narrow-relative+1": "nästa lör.",
	"field-dayperiod": "fm/em",
	"field-hour": "timme",
	"field-hour-relative+0": "denna timme",
	"field-hour-short": "tim",
	"field-hour-short-relative+0": "denna timme",
	"field-hour-narrow": "h",
	"field-hour-narrow-relative+0": "denna timme",
	"field-minute": "minut",
	"field-minute-relative+0": "denna minut",
	"field-minute-short": "min",
	"field-minute-short-relative+0": "denna minut",
	"field-minute-narrow": "m",
	"field-minute-narrow-relative+0": "denna minut",
	"field-second": "sekund",
	"field-second-relative+0": "nu",
	"field-second-short": "sek",
	"field-second-short-relative+0": "nu",
	"field-second-narrow": "s",
	"field-second-narrow-relative+0": "nu",
	"field-zone": "tidszon"
}
//end v1.x content
);