define(
//begin v1.x content
{
	"months-format-abbr": [
		"tishrí",
		"heshván",
		"kislév",
		"tevét",
		"shevát",
		"adár I",
		"adár",
		"nisán",
		"ijjár",
		"siván",
		"tammúz",
		"ab",
		"elúl"
	],
	"months-format-abbr-leap": "adár II",
	"months-format-wide": [
		"tishrí",
		"heshván",
		"kislév",
		"tevét",
		"shevát",
		"adár I",
		"adár",
		"nisán",
		"ijjár",
		"siván",
		"tammúz",
		"ab",
		"elúl"
	],
	"months-format-wide-leap": "adár II",
	"months-standAlone-abbr": [
		"Tishrí",
		"Heshván",
		"Kislév",
		"Tevét",
		"Shevát",
		"Adár I",
		"Adár",
		"Nisán",
		"Ijjár",
		"Siván",
		"Tammúz",
		"Ab",
		"Elúl"
	],
	"months-standAlone-abbr-leap": "Adár II",
	"months-standAlone-wide": [
		"Tishrí",
		"Heshván",
		"Kislév",
		"Tevét",
		"Shevát",
		"Adár I",
		"Adár",
		"Nisán",
		"Ijjár",
		"Siván",
		"Tammúz",
		"Ab",
		"Elúl"
	],
	"months-standAlone-wide-leap": "Adár II",
	"eraAbbr": [
		"AM"
	],
	"field-era": "era",
	"field-year": "år",
	"field-year-relative+-1": "i fjol",
	"field-year-relative+0": "i år",
	"field-year-relative+1": "nästa år",
	"field-year-short": "år",
	"field-year-short-relative+-1": "i fjol",
	"field-year-short-relative+0": "i år",
	"field-year-short-relative+1": "nästa år",
	"field-year-narrow": "år",
	"field-year-narrow-relative+-1": "i fjol",
	"field-year-narrow-relative+0": "i år",
	"field-year-narrow-relative+1": "nästa år",
	"field-quarter": "kvartal",
	"field-quarter-relative+-1": "förra kvartalet",
	"field-quarter-relative+0": "detta kvartal",
	"field-quarter-relative+1": "nästa kvartal",
	"field-quarter-short": "kv.",
	"field-quarter-short-relative+-1": "förra kv.",
	"field-quarter-short-relative+0": "detta kv.",
	"field-quarter-short-relative+1": "nästa kv.",
	"field-quarter-narrow": "kv.",
	"field-quarter-narrow-relative+-1": "förra kv.",
	"field-quarter-narrow-relative+0": "detta kv.",
	"field-quarter-narrow-relative+1": "nästa kv.",
	"field-month": "månad",
	"field-month-relative+-1": "förra månaden",
	"field-month-relative+0": "denna månad",
	"field-month-relative+1": "nästa månad",
	"field-month-short": "m",
	"field-month-short-relative+-1": "förra mån.",
	"field-month-short-relative+0": "denna mån.",
	"field-month-short-relative+1": "nästa mån.",
	"field-month-narrow": "mån",
	"field-month-narrow-relative+-1": "förra mån.",
	"field-month-narrow-relative+0": "denna mån.",
	"field-month-narrow-relative+1": "nästa mån.",
	"field-week": "vecka",
	"field-week-relative+-1": "förra veckan",
	"field-week-relative+0": "denna vecka",
	"field-week-relative+1": "nästa vecka",
	"field-week-short": "v",
	"field-week-short-relative+-1": "förra v.",
	"field-week-short-relative+0": "denna v.",
	"field-week-short-relative+1": "nästa v.",
	"field-week-narrow": "v",
	"field-week-narrow-relative+-1": "förra v.",
	"field-week-narrow-relative+0": "denna v.",
	"field-week-narrow-relative+1": "nästa v.",
	"field-day": "dag",
	"field-day-relative+-2": "i förrgår",
	"field-day-relative+-1": "i går",
	"field-day-relative+0": "i dag",
	"field-day-relative+1": "i morgon",
	"field-day-relative+2": "i övermorgon",
	"field-day-short": "dag",
	"field-day-short-relative+-2": "i förrgår",
	"field-day-short-relative+-1": "i går",
	"field-day-short-relative+0": "i dag",
	"field-day-short-relative+1": "i morgon",
	"field-day-short-relative+2": "i övermorgon",
	"field-day-narrow": "dag",
	"field-day-narrow-relative+-2": "i förrgår",
	"field-day-narrow-relative+-1": "i går",
	"field-day-narrow-relative+0": "i dag",
	"field-day-narrow-relative+1": "i morgon",
	"field-day-narrow-relative+2": "i övermorgon",
	"field-weekday": "veckodag",
	"field-sun-relative+-1": "söndag förra veckan",
	"field-sun-relative+0": "söndag denna vecka",
	"field-sun-relative+1": "söndag nästa vecka",
	"field-sun-short-relative+-1": "sön. förra veckan",
	"field-sun-short-relative+0": "sön. denna vecka",
	"field-sun-short-relative+1": "sön. nästa vecka",
	"field-sun-narrow-relative+-1": "förra sön.",
	"field-sun-narrow-relative+0": "denna sön.",
	"field-sun-narrow-relative+1": "nästa sön.",
	"field-mon-relative+-1": "måndag förra veckan",
	"field-mon-relative+0": "måndag denna vecka",
	"field-mon-relative+1": "måndag nästa vecka",
	"field-mon-short-relative+-1": "mån. förra veckan",
	"field-mon-short-relative+0": "mån. denna vecka",
	"field-mon-short-relative+1": "mån. nästa vecka",
	"field-mon-narrow-relative+-1": "förra mån.",
	"field-mon-narrow-relative+0": "denna mån.",
	"field-mon-narrow-relative+1": "nästa mån.",
	"field-tue-relative+-1": "tisdag förra veckan",
	"field-tue-relative+0": "tisdag denna vecka",
	"field-tue-relative+1": "tisdag nästa vecka",
	"field-tue-short-relative+-1": "tis. förra veckan",
	"field-tue-short-relative+0": "tis. denna vecka",
	"field-tue-short-relative+1": "tis. nästa vecka",
	"field-tue-narrow-relative+-1": "förra tis.",
	"field-tue-narrow-relative+0": "denna tis.",
	"field-tue-narrow-relative+1": "nästa tis.",
	"field-wed-relative+-1": "onsdag förra veckan",
	"field-wed-relative+0": "onsdag denna vecka",
	"field-wed-relative+1": "onsdag nästa vecka",
	"field-wed-short-relative+-1": "ons. förra veckan",
	"field-wed-short-relative+0": "ons. denna vecka",
	"field-wed-short-relative+1": "ons. nästa vecka",
	"field-wed-narrow-relative+-1": "förra ons.",
	"field-wed-narrow-relative+0": "denna ons.",
	"field-wed-narrow-relative+1": "nästa ons.",
	"field-thu-relative+-1": "torsdag förra veckan",
	"field-thu-relative+0": "torsdag denna vecka",
	"field-thu-relative+1": "torsdag nästa vecka",
	"field-thu-short-relative+-1": "tors. förra veckan",
	"field-thu-short-relative+0": "tors. denna vecka",
	"field-thu-short-relative+1": "tors. nästa vecka",
	"field-thu-narrow-relative+-1": "förra tors.",
	"field-thu-narrow-relative+0": "denna tors.",
	"field-thu-narrow-relative+1": "nästa tors.",
	"field-fri-relative+-1": "fredag förra veckan",
	"field-fri-relative+0": "fredag denna vecka",
	"field-fri-relative+1": "fredag nästa vecka",
	"field-fri-short-relative+-1": "fre. förra veckan",
	"field-fri-short-relative+0": "fre. denna vecka",
	"field-fri-short-relative+1": "fre. nästa vecka",
	"field-fri-narrow-relative+-1": "förra fre.",
	"field-fri-narrow-relative+0": "denna fre.",
	"field-fri-narrow-relative+1": "nästa fre.",
	"field-sat-relative+-1": "lördag förra veckan",
	"field-sat-relative+0": "lördag denna vecka",
	"field-sat-relative+1": "lördag nästa vecka",
	"field-sat-short-relative+-1": "lör. förra veckan",
	"field-sat-short-relative+0": "lör. denna vecka",
	"field-sat-short-relative+1": "lör. nästa vecka",
	"field-sat-narrow-relative+-1": "förra lör.",
	"field-sat-narrow-relative+0": "denna lör.",
	"field-sat-narrow-relative+1": "nästa lör.",
	"field-dayperiod": "fm/em",
	"field-hour": "timme",
	"field-hour-relative+0": "denna timme",
	"field-hour-short": "tim",
	"field-hour-short-relative+0": "denna timme",
	"field-hour-narrow": "h",
	"field-hour-narrow-relative+0": "denna timme",
	"field-minute": "minut",
	"field-minute-relative+0": "denna minut",
	"field-minute-short": "min",
	"field-minute-short-relative+0": "denna minut",
	"field-minute-narrow": "m",
	"field-minute-narrow-relative+0": "denna minut",
	"field-second": "sekund",
	"field-second-relative+0": "nu",
	"field-second-short": "sek",
	"field-second-short-relative+0": "nu",
	"field-second-narrow": "s",
	"field-second-narrow-relative+0": "nu",
	"field-zone": "tidszon",
	"days-format-abbr": [
		"sön",
		"mån",
		"tis",
		"ons",
		"tors",
		"fre",
		"lör"
	],
	"days-format-narrow": [
		"S",
		"M",
		"T",
		"O",
		"T",
		"F",
		"L"
	],
	"days-format-short": [
		"sö",
		"må",
		"ti",
		"on",
		"to",
		"fr",
		"lö"
	],
	"days-format-wide": [
		"söndag",
		"måndag",
		"tisdag",
		"onsdag",
		"torsdag",
		"fredag",
		"lördag"
	],
	"days-standAlone-abbr": [
		"sön",
		"mån",
		"tis",
		"ons",
		"tors",
		"fre",
		"lör"
	],
	"days-standAlone-narrow": [
		"S",
		"M",
		"T",
		"O",
		"T",
		"F",
		"L"
	],
	"days-standAlone-short": [
		"sö",
		"må",
		"ti",
		"on",
		"to",
		"fr",
		"lö"
	],
	"days-standAlone-wide": [
		"söndag",
		"måndag",
		"tisdag",
		"onsdag",
		"torsdag",
		"fredag",
		"lördag"
	],
	"quarters-format-abbr": [
		"K1",
		"K2",
		"K3",
		"K4"
	],
	"quarters-format-wide": [
		"1:a kvartalet",
		"2:a kvartalet",
		"3:e kvartalet",
		"4:e kvartalet"
	],
	"quarters-standAlone-abbr": [
		"K1",
		"K2",
		"K3",
		"K4"
	],
	"quarters-standAlone-wide": [
		"1:a kvartalet",
		"2:a kvartalet",
		"3:e kvartalet",
		"4:e kvartalet"
	],
	"dayPeriods-format-abbr-am": "fm",
	"dayPeriods-format-abbr-pm": "em",
	"dayPeriods-format-narrow-am": "fm",
	"dayPeriods-format-narrow-pm": "em",
	"dayPeriods-format-wide-am": "fm",
	"dayPeriods-format-wide-pm": "em",
	"dayPeriods-standAlone-abbr-am": "f.m.",
	"dayPeriods-standAlone-abbr-pm": "e.m.",
	"dayPeriods-standAlone-narrow-am": "fm",
	"dayPeriods-standAlone-narrow-pm": "em",
	"dayPeriods-standAlone-wide-am": "förmiddag",
	"dayPeriods-standAlone-wide-pm": "eftermiddag",
	"dateFormat-full": "EEEE d MMMM y G",
	"dateFormat-long": "d MMMM y G",
	"dateFormat-medium": "d MMM y G",
	"dateFormat-short": "G y-MM-dd",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"dateFormatItem-GyMMMEd": "E d MMM y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MMMEd": "E d MMM",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-yyyyM": "y-MM G",
	"dateFormatItem-yyyyMd": "y-MM-dd G",
	"dateFormatItem-yyyyMEd": "E y-MM-dd G",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-yyyyMMMEd": "E d MMM y G",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"timeFormat-full": "'kl'. HH.mm.ss zzzz",
	"timeFormat-long": "HH.mm.ss z",
	"timeFormat-medium": "HH.mm.ss",
	"timeFormat-short": "HH.mm"
}
//end v1.x content
);