define(
//begin v1.x content
{
	"months-format-abbr": [
		"Ιαν",
		"Φεβ",
		"Μαρ",
		"Απρ",
		"Μαΐ",
		"Ιουν",
		"Ιουλ",
		"Αυγ",
		"Σεπ",
		"Οκτ",
		"Νοε",
		"Δεκ"
	],
	"months-format-narrow": [
		"Ι",
		"Φ",
		"Μ",
		"Α",
		"Μ",
		"Ι",
		"Ι",
		"Α",
		"Σ",
		"Ο",
		"Ν",
		"Δ"
	],
	"months-format-wide": [
		"Ιανουαρίου",
		"Φεβρουαρίου",
		"Μαρτίου",
		"Απριλίου",
		"Μαΐου",
		"Ιουνίου",
		"Ιουλίου",
		"Αυγούστου",
		"Σεπτεμβρίου",
		"Οκτωβρίου",
		"Νοεμβρίου",
		"Δεκεμβρίου"
	],
	"months-standAlone-abbr": [
		"Ιαν",
		"Φεβ",
		"Μάρ",
		"Απρ",
		"Μάι",
		"Ιούν",
		"Ιούλ",
		"Αύγ",
		"Σεπ",
		"Οκτ",
		"Νοέ",
		"Δεκ"
	],
	"months-standAlone-narrow": [
		"Ι",
		"Φ",
		"Μ",
		"Α",
		"Μ",
		"Ι",
		"Ι",
		"Α",
		"Σ",
		"Ο",
		"Ν",
		"Δ"
	],
	"months-standAlone-wide": [
		"Ιανουάριος",
		"Φεβρουάριος",
		"Μάρτιος",
		"Απρίλιος",
		"Μάιος",
		"Ιούνιος",
		"Ιούλιος",
		"Αύγουστος",
		"Σεπτέμβριος",
		"Οκτώβριος",
		"Νοέμβριος",
		"Δεκέμβριος"
	],
	"days-format-abbr": [
		"Κυρ",
		"Δευ",
		"Τρί",
		"Τετ",
		"Πέμ",
		"Παρ",
		"Σάβ"
	],
	"days-format-narrow": [
		"Κ",
		"Δ",
		"Τ",
		"Τ",
		"Π",
		"Π",
		"Σ"
	],
	"days-format-short": [
		"Κυ",
		"Δε",
		"Τρ",
		"Τε",
		"Πέ",
		"Πα",
		"Σά"
	],
	"days-format-wide": [
		"Κυριακή",
		"Δευτέρα",
		"Τρίτη",
		"Τετάρτη",
		"Πέμπτη",
		"Παρασκευή",
		"Σάββατο"
	],
	"days-standAlone-abbr": [
		"Κυρ",
		"Δευ",
		"Τρί",
		"Τετ",
		"Πέμ",
		"Παρ",
		"Σάβ"
	],
	"days-standAlone-narrow": [
		"Κ",
		"Δ",
		"Τ",
		"Τ",
		"Π",
		"Π",
		"Σ"
	],
	"days-standAlone-short": [
		"Κυ",
		"Δε",
		"Τρ",
		"Τε",
		"Πέ",
		"Πα",
		"Σά"
	],
	"days-standAlone-wide": [
		"Κυριακή",
		"Δευτέρα",
		"Τρίτη",
		"Τετάρτη",
		"Πέμπτη",
		"Παρασκευή",
		"Σάββατο"
	],
	"quarters-format-abbr": [
		"Τ1",
		"Τ2",
		"Τ3",
		"Τ4"
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"1ο τρίμηνο",
		"2ο τρίμηνο",
		"3ο τρίμηνο",
		"4ο τρίμηνο"
	],
	"quarters-standAlone-abbr": [
		"Τ1",
		"Τ2",
		"Τ3",
		"Τ4"
	],
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-standAlone-wide": [
		"1ο τρίμηνο",
		"2ο τρίμηνο",
		"3ο τρίμηνο",
		"4ο τρίμηνο"
	],
	"dayPeriods-format-abbr-am": "π.μ.",
	"dayPeriods-format-abbr-pm": "μ.μ.",
	"dayPeriods-format-abbr-morning1": "πρωί",
	"dayPeriods-format-abbr-afternoon1": "μεσημ.",
	"dayPeriods-format-abbr-evening1": "απόγ.",
	"dayPeriods-format-abbr-night1": "βράδυ",
	"dayPeriods-format-narrow-am": "πμ",
	"dayPeriods-format-narrow-pm": "μμ",
	"dayPeriods-format-narrow-morning1": "πρωί",
	"dayPeriods-format-narrow-afternoon1": "μεσημ.",
	"dayPeriods-format-narrow-evening1": "απόγ.",
	"dayPeriods-format-narrow-night1": "βράδυ",
	"dayPeriods-format-wide-am": "π.μ.",
	"dayPeriods-format-wide-pm": "μ.μ.",
	"dayPeriods-format-wide-morning1": "πρωί",
	"dayPeriods-format-wide-afternoon1": "μεσημέρι",
	"dayPeriods-format-wide-evening1": "απόγευμα",
	"dayPeriods-format-wide-night1": "βράδυ",
	"dayPeriods-standAlone-abbr-am": "π.μ.",
	"dayPeriods-standAlone-abbr-pm": "μ.μ.",
	"dayPeriods-standAlone-abbr-morning1": "πρωί",
	"dayPeriods-standAlone-abbr-afternoon1": "μεσημ.",
	"dayPeriods-standAlone-abbr-evening1": "απόγ.",
	"dayPeriods-standAlone-abbr-night1": "βράδυ",
	"dayPeriods-standAlone-narrow-am": "π.μ.",
	"dayPeriods-standAlone-narrow-pm": "μ.μ.",
	"dayPeriods-standAlone-narrow-morning1": "πρωί",
	"dayPeriods-standAlone-narrow-afternoon1": "μεσημ.",
	"dayPeriods-standAlone-narrow-evening1": "απόγ.",
	"dayPeriods-standAlone-narrow-night1": "βράδυ",
	"dayPeriods-standAlone-wide-am": "π.μ.",
	"dayPeriods-standAlone-wide-pm": "μ.μ.",
	"dayPeriods-standAlone-wide-morning1": "πρωί",
	"dayPeriods-standAlone-wide-afternoon1": "μεσημέρι",
	"dayPeriods-standAlone-wide-evening1": "απόγευμα",
	"dayPeriods-standAlone-wide-night1": "βράδυ",
	"eraNames": [
		"προ Χριστού",
		"μετά Χριστόν"
	],
	"eraAbbr": [
		"π.Χ.",
		"μ.Χ."
	],
	"dateFormat-full": "EEEE, d MMMM y",
	"dateFormat-long": "d MMMM y",
	"dateFormat-medium": "d MMM y",
	"dateFormat-short": "d/M/yy",
	"timeFormat-full": "h:mm:ss a zzzz",
	"timeFormat-long": "h:mm:ss a z",
	"timeFormat-medium": "h:mm:ss a",
	"timeFormat-short": "h:mm a",
	"dateTimeFormat-full": "{1} - {0}",
	"dateTimeFormat-long": "{1} - {0}",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-d": "d",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-Ehm": "E h:mm a",
	"dateFormatItem-EHm": "E HH:mm",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "LLL y G",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"dateFormatItem-GyMMMEd": "E, d MMM y G",
	"dateFormatItem-h": "h a",
	"dateFormatItem-H": "HH",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hmsv": "h:mm:ss a v",
	"dateFormatItem-Hmsv": "HH:mm:ss v",
	"dateFormatItem-hmv": "h:mm a v",
	"dateFormatItem-Hmv": "HH:mm v",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormatItem-MMM": "MMM",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-MMMMEd": "E, d MMMM",
	"dateFormatItem-MMMMW": "εβδομάδα W του MMM",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y",
	"dateFormatItem-yM": "M/y",
	"dateFormatItem-yMd": "d/M/y",
	"dateFormatItem-yMEd": "E, d/M/y",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yMMMd": "d MMM y",
	"dateFormatItem-yMMMEd": "E, d MMM y",
	"dateFormatItem-yMMMM": "LLLL y",
	"dateFormatItem-yQQQ": "y QQQ",
	"dateFormatItem-yQQQQ": "y QQQQ",
	"dateFormatItem-yw": "εβδομάδα w του y",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-era": "περίοδος",
	"field-year": "έτος",
	"field-year-relative+-1": "πέρσι",
	"field-year-relative+0": "φέτος",
	"field-year-relative+1": "επόμενο έτος",
	"field-year-short": "έτ.",
	"field-year-short-relative+-1": "πέρσι",
	"field-year-short-relative+0": "φέτος",
	"field-year-short-relative+1": "επόμενο έτος",
	"field-year-narrow": "έτ.",
	"field-year-narrow-relative+-1": "πέρσι",
	"field-year-narrow-relative+0": "φέτος",
	"field-year-narrow-relative+1": "επόμενο έτος",
	"field-quarter": "τρίμηνο",
	"field-quarter-relative+-1": "προηγούμενο τρίμηνο",
	"field-quarter-relative+0": "τρέχον τρίμηνο",
	"field-quarter-relative+1": "επόμενο τρίμηνο",
	"field-quarter-short": "τρίμ.",
	"field-quarter-short-relative+-1": "προηγ. τρίμ.",
	"field-quarter-short-relative+0": "τρέχον τρίμ.",
	"field-quarter-short-relative+1": "επόμ. τρίμ.",
	"field-quarter-narrow": "τρίμ.",
	"field-quarter-narrow-relative+-1": "προηγ. τρίμ.",
	"field-quarter-narrow-relative+0": "τρέχον τρίμ.",
	"field-quarter-narrow-relative+1": "επόμ. τρίμ.",
	"field-month": "μήνας",
	"field-month-relative+-1": "προηγούμενος μήνας",
	"field-month-relative+0": "τρέχων μήνας",
	"field-month-relative+1": "επόμενος μήνας",
	"field-month-short": "μήν.",
	"field-month-narrow": "μήν.",
	"field-week": "εβδομάδα",
	"field-week-relative+-1": "προηγούμενη εβδομάδα",
	"field-week-relative+0": "αυτήν την εβδομάδα",
	"field-week-relative+1": "επόμενη εβδομάδα",
	"field-week-short": "εβδ.",
	"field-week-narrow": "εβδ.",
	"field-day": "ημέρα",
	"field-day-relative+-2": "προχθές",
	"field-day-relative+-1": "χθες",
	"field-day-relative+0": "σήμερα",
	"field-day-relative+1": "αύριο",
	"field-day-relative+2": "μεθαύριο",
	"field-day-short": "ημέρα",
	"field-day-narrow": "ημέρα",
	"field-weekday": "καθημερινή",
	"field-sun-relative+-1": "προηγούμενη Κυριακή",
	"field-sun-relative+0": "αυτήν την Κυριακή",
	"field-sun-relative+1": "επόμενη Κυριακή",
	"field-sun-short-relative+-1": "προηγ. Κυρ.",
	"field-sun-short-relative+0": "αυτήν την Κυρ.",
	"field-sun-short-relative+1": "επόμ. Κυρ.",
	"field-sun-narrow-relative+-1": "προηγ. Κυ",
	"field-sun-narrow-relative+0": "αυτήν την Κυ",
	"field-sun-narrow-relative+1": "επόμ. Κυ",
	"field-mon-relative+-1": "προηγούμενη Δευτέρα",
	"field-mon-relative+0": "αυτήν τη Δευτέρα",
	"field-mon-relative+1": "επόμενη Δευτέρα",
	"field-mon-short-relative+-1": "προηγ. Δευτ.",
	"field-mon-short-relative+0": "αυτήν τη Δευτ.",
	"field-mon-short-relative+1": "επόμ. Δευτ.",
	"field-mon-narrow-relative+-1": "προηγ. Δε",
	"field-mon-narrow-relative+0": "αυτήν τη Δε",
	"field-mon-narrow-relative+1": "επόμ. Δε",
	"field-tue-relative+-1": "προηγούμενη Τρίτη",
	"field-tue-relative+0": "αυτήν την Τρίτη",
	"field-tue-relative+1": "επόμενη Τρίτη",
	"field-tue-short-relative+-1": "προηγ. Τρ.",
	"field-tue-short-relative+0": "αυτήν την Τρ.",
	"field-tue-short-relative+1": "επόμ. Τρ.",
	"field-tue-narrow-relative+-1": "προηγ. Τρ",
	"field-tue-narrow-relative+0": "αυτήν την Τρ",
	"field-tue-narrow-relative+1": "επόμ. Τρ",
	"field-wed-relative+-1": "προηγούμενη Τετάρτη",
	"field-wed-relative+0": "αυτήν την Τετάρτη",
	"field-wed-relative+1": "επόμενη Τετάρτη",
	"field-wed-short-relative+-1": "προηγ. Τετ.",
	"field-wed-short-relative+0": "αυτήν την Τετ.",
	"field-wed-short-relative+1": "επόμ. Τετ.",
	"field-wed-narrow-relative+-1": "προηγ. Τε",
	"field-wed-narrow-relative+0": "αυτήν την Τε",
	"field-wed-narrow-relative+1": "επόμ. Τε",
	"field-thu-relative+-1": "προηγούμενη Πέμπτη",
	"field-thu-relative+0": "αυτήν την Πέμπτη",
	"field-thu-relative+1": "επόμενη Πέμπτη",
	"field-thu-short-relative+-1": "προηγ. Πέμ.",
	"field-thu-short-relative+0": "αυτήν την Πέμ.",
	"field-thu-short-relative+1": "επόμ. Πέμ.",
	"field-thu-narrow-relative+-1": "προηγ. Πέ",
	"field-thu-narrow-relative+0": "αυτήν την Πέ",
	"field-thu-narrow-relative+1": "επόμ. Πέ",
	"field-fri-relative+-1": "προηγούμενη Παρασκευή",
	"field-fri-relative+0": "αυτήν την Παρασκευή",
	"field-fri-relative+1": "επόμενη Παρασκευή",
	"field-fri-short-relative+-1": "προηγ. Παρ.",
	"field-fri-short-relative+0": "αυτήν την Παρ.",
	"field-fri-short-relative+1": "επόμ. Παρ.",
	"field-fri-narrow-relative+-1": "προηγ. Πα",
	"field-fri-narrow-relative+0": "αυτήν την Πα",
	"field-fri-narrow-relative+1": "επόμ. Πα",
	"field-sat-relative+-1": "προηγούμενο Σάββατο",
	"field-sat-relative+0": "αυτό το Σάββατο",
	"field-sat-relative+1": "επόμενο Σάββατο",
	"field-sat-short-relative+-1": "προηγ. Σάβ.",
	"field-sat-short-relative+0": "αυτό το Σάβ.",
	"field-sat-short-relative+1": "επόμ. Σάβ.",
	"field-sat-narrow-relative+-1": "προηγ. Σά",
	"field-sat-narrow-relative+0": "αυτό το Σά",
	"field-sat-narrow-relative+1": "επόμ. Σά",
	"field-dayperiod": "π.μ./μ.μ.",
	"field-hour": "ώρα",
	"field-hour-relative+0": "αυτήν την ώρα",
	"field-hour-short": "ώρ.",
	"field-hour-narrow": "ώ",
	"field-minute": "λεπτό",
	"field-minute-relative+0": "αυτό το λεπτό",
	"field-minute-short": "λεπ.",
	"field-minute-narrow": "λ",
	"field-second": "δευτερόλεπτο",
	"field-second-relative+0": "τώρα",
	"field-second-short": "δευτ.",
	"field-second-narrow": "δ",
	"field-zone": "ζώνη ώρας",
	"eraNarrow": [
		"π.Χ.",
		"μ.Χ."
	]
}
//end v1.x content
);