define(
//begin v1.x content
{
	"dateFormat-full": "EEEE, d MMMM, y G",
	"dateFormat-long": "d MMMM, y G",
	"dateFormat-medium": "d MMM, y G",
	"dateFormat-short": "d/M/yy",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yM": "MM/y GGGGG",
	"dateFormatItem-yMd": "dd/MM/y GGGGG",
	"dateFormatItem-yMEd": "E, dd/MM/y GGGGG",
	"dateFormatItem-yMMM": "LLL y GGGGG",
	"dateFormatItem-yMMMd": "d MMM, y G",
	"dateFormatItem-yMMMEd": "E, d MMM, y G",
	"dateFormatItem-yQQQ": "y GGGGG QQQ",
	"field-era": "περίοδος",
	"field-year": "έτος",
	"field-year-relative+-1": "πέρσι",
	"field-year-relative+0": "φέτος",
	"field-year-relative+1": "επόμενο έτος",
	"field-year-short": "έτ.",
	"field-year-short-relative+-1": "πέρσι",
	"field-year-short-relative+0": "φέτος",
	"field-year-short-relative+1": "επόμενο έτος",
	"field-year-narrow": "έτ.",
	"field-year-narrow-relative+-1": "πέρσι",
	"field-year-narrow-relative+0": "φέτος",
	"field-year-narrow-relative+1": "επόμενο έτος",
	"field-quarter": "τρίμηνο",
	"field-quarter-relative+-1": "προηγούμενο τρίμηνο",
	"field-quarter-relative+0": "τρέχον τρίμηνο",
	"field-quarter-relative+1": "επόμενο τρίμηνο",
	"field-quarter-short": "τρίμ.",
	"field-quarter-short-relative+-1": "προηγ. τρίμ.",
	"field-quarter-short-relative+0": "τρέχον τρίμ.",
	"field-quarter-short-relative+1": "επόμ. τρίμ.",
	"field-quarter-narrow": "τρίμ.",
	"field-quarter-narrow-relative+-1": "προηγ. τρίμ.",
	"field-quarter-narrow-relative+0": "τρέχον τρίμ.",
	"field-quarter-narrow-relative+1": "επόμ. τρίμ.",
	"field-month": "μήνας",
	"field-month-relative+-1": "προηγούμενος μήνας",
	"field-month-relative+0": "τρέχων μήνας",
	"field-month-relative+1": "επόμενος μήνας",
	"field-month-short": "μήν.",
	"field-month-narrow": "μήν.",
	"field-week": "εβδομάδα",
	"field-week-relative+-1": "προηγούμενη εβδομάδα",
	"field-week-relative+0": "αυτήν την εβδομάδα",
	"field-week-relative+1": "επόμενη εβδομάδα",
	"field-week-short": "εβδ.",
	"field-week-narrow": "εβδ.",
	"field-day": "ημέρα",
	"field-day-relative+-2": "προχθές",
	"field-day-relative+-1": "χθες",
	"field-day-relative+0": "σήμερα",
	"field-day-relative+1": "αύριο",
	"field-day-relative+2": "μεθαύριο",
	"field-day-short": "ημέρα",
	"field-day-narrow": "ημέρα",
	"field-weekday": "καθημερινή",
	"field-sun-relative+-1": "προηγούμενη Κυριακή",
	"field-sun-relative+0": "αυτήν την Κυριακή",
	"field-sun-relative+1": "επόμενη Κυριακή",
	"field-sun-short-relative+-1": "προηγ. Κυρ.",
	"field-sun-short-relative+0": "αυτήν την Κυρ.",
	"field-sun-short-relative+1": "επόμ. Κυρ.",
	"field-sun-narrow-relative+-1": "προηγ. Κυ",
	"field-sun-narrow-relative+0": "αυτήν την Κυ",
	"field-sun-narrow-relative+1": "επόμ. Κυ",
	"field-mon-relative+-1": "προηγούμενη Δευτέρα",
	"field-mon-relative+0": "αυτήν τη Δευτέρα",
	"field-mon-relative+1": "επόμενη Δευτέρα",
	"field-mon-short-relative+-1": "προηγ. Δευτ.",
	"field-mon-short-relative+0": "αυτήν τη Δευτ.",
	"field-mon-short-relative+1": "επόμ. Δευτ.",
	"field-mon-narrow-relative+-1": "προηγ. Δε",
	"field-mon-narrow-relative+0": "αυτήν τη Δε",
	"field-mon-narrow-relative+1": "επόμ. Δε",
	"field-tue-relative+-1": "προηγούμενη Τρίτη",
	"field-tue-relative+0": "αυτήν την Τρίτη",
	"field-tue-relative+1": "επόμενη Τρίτη",
	"field-tue-short-relative+-1": "προηγ. Τρ.",
	"field-tue-short-relative+0": "αυτήν την Τρ.",
	"field-tue-short-relative+1": "επόμ. Τρ.",
	"field-tue-narrow-relative+-1": "προηγ. Τρ",
	"field-tue-narrow-relative+0": "αυτήν την Τρ",
	"field-tue-narrow-relative+1": "επόμ. Τρ",
	"field-wed-relative+-1": "προηγούμενη Τετάρτη",
	"field-wed-relative+0": "αυτήν την Τετάρτη",
	"field-wed-relative+1": "επόμενη Τετάρτη",
	"field-wed-short-relative+-1": "προηγ. Τετ.",
	"field-wed-short-relative+0": "αυτήν την Τετ.",
	"field-wed-short-relative+1": "επόμ. Τετ.",
	"field-wed-narrow-relative+-1": "προηγ. Τε",
	"field-wed-narrow-relative+0": "αυτήν την Τε",
	"field-wed-narrow-relative+1": "επόμ. Τε",
	"field-thu-relative+-1": "προηγούμενη Πέμπτη",
	"field-thu-relative+0": "αυτήν την Πέμπτη",
	"field-thu-relative+1": "επόμενη Πέμπτη",
	"field-thu-short-relative+-1": "προηγ. Πέμ.",
	"field-thu-short-relative+0": "αυτήν την Πέμ.",
	"field-thu-short-relative+1": "επόμ. Πέμ.",
	"field-thu-narrow-relative+-1": "προηγ. Πέ",
	"field-thu-narrow-relative+0": "αυτήν την Πέ",
	"field-thu-narrow-relative+1": "επόμ. Πέ",
	"field-fri-relative+-1": "προηγούμενη Παρασκευή",
	"field-fri-relative+0": "αυτήν την Παρασκευή",
	"field-fri-relative+1": "επόμενη Παρασκευή",
	"field-fri-short-relative+-1": "προηγ. Παρ.",
	"field-fri-short-relative+0": "αυτήν την Παρ.",
	"field-fri-short-relative+1": "επόμ. Παρ.",
	"field-fri-narrow-relative+-1": "προηγ. Πα",
	"field-fri-narrow-relative+0": "αυτήν την Πα",
	"field-fri-narrow-relative+1": "επόμ. Πα",
	"field-sat-relative+-1": "προηγούμενο Σάββατο",
	"field-sat-relative+0": "αυτό το Σάββατο",
	"field-sat-relative+1": "επόμενο Σάββατο",
	"field-sat-short-relative+-1": "προηγ. Σάβ.",
	"field-sat-short-relative+0": "αυτό το Σάβ.",
	"field-sat-short-relative+1": "επόμ. Σάβ.",
	"field-sat-narrow-relative+-1": "προηγ. Σά",
	"field-sat-narrow-relative+0": "αυτό το Σά",
	"field-sat-narrow-relative+1": "επόμ. Σά",
	"field-dayperiod": "π.μ./μ.μ.",
	"field-hour": "ώρα",
	"field-hour-relative+0": "αυτήν την ώρα",
	"field-hour-short": "ώρ.",
	"field-hour-narrow": "ώ",
	"field-minute": "λεπτό",
	"field-minute-relative+0": "αυτό το λεπτό",
	"field-minute-short": "λεπ.",
	"field-minute-narrow": "λ",
	"field-second": "δευτερόλεπτο",
	"field-second-relative+0": "τώρα",
	"field-second-short": "δευτ.",
	"field-second-narrow": "δ",
	"field-zone": "ζώνη ώρας"
}
//end v1.x content
);