define(
//begin v1.x content
{
	"months-format-abbr": [
		"M1",
		"M2",
		"M3",
		"M4",
		"M5",
		"M6",
		"M7",
		"M8",
		"M9",
		"M10",
		"M11",
		"M12"
	],
	"months-standAlone-abbr": [
		"M1",
		"M2",
		"M3",
		"M4",
		"M5",
		"M6",
		"M7",
		"M8",
		"M9",
		"M10",
		"M11",
		"M12"
	],
	"dateFormat-medium": "d 'de' MMM 'de' U",
	"field-quarter-relative+-1": "trimestre passado",
	"field-quarter-relative+0": "este trimestre",
	"field-quarter-relative+1": "próximo trimestre",
	"field-quarter-short-relative+-1": "trim. passado",
	"field-quarter-short-relative+0": "este trim.",
	"field-quarter-short-relative+1": "próximo trim.",
	"field-quarter-narrow-relative+-1": "trim. passado",
	"field-quarter-narrow-relative+0": "este trim.",
	"field-quarter-narrow-relative+1": "próximo trim.",
	"field-sun-short-relative+-1": "domingo passado",
	"field-sun-short-relative+0": "este domingo",
	"field-sun-short-relative+1": "próximo domingo",
	"field-mon-short-relative+-1": "segunda passada",
	"field-mon-short-relative+0": "esta segunda",
	"field-mon-short-relative+1": "próxima segunda",
	"field-tue-short-relative+-1": "terça passada",
	"field-tue-short-relative+0": "esta terça",
	"field-tue-short-relative+1": "próxima terça",
	"field-wed-short-relative+-1": "quarta passada",
	"field-wed-short-relative+0": "esta quarta",
	"field-wed-short-relative+1": "próxima quarta",
	"field-thu-short-relative+-1": "quinta passada",
	"field-thu-short-relative+0": "esta quinta",
	"field-thu-short-relative+1": "próxima quinta",
	"field-thu-narrow-relative+-1": "qui. passada",
	"field-thu-narrow-relative+0": "esta qui.",
	"field-thu-narrow-relative+1": "próxima qui.",
	"field-fri-short-relative+-1": "sexta passada",
	"field-fri-short-relative+0": "esta sexta",
	"field-fri-short-relative+1": "próxima sexta",
	"field-sat-short-relative+-1": "sábado passado",
	"field-sat-short-relative+0": "este sábado",
	"field-sat-short-relative+1": "próximo sábado",
	"field-minute-short": "min",
	"field-minute-narrow": "min",
	"field-second-short": "s"
}
//end v1.x content
);