define(
//begin v1.x content
{
	"days-format-abbr": [
		"domingo",
		"segunda",
		"terça",
		"quarta",
		"quinta",
		"sexta",
		"sábado"
	],
	"days-standAlone-abbr": [
		"domingo",
		"segunda",
		"terça",
		"quarta",
		"quinta",
		"sexta",
		"sábado"
	],
	"quarters-format-wide": [
		"1.º trimestre",
		"2.º trimestre",
		"3.º trimestre",
		"4.º trimestre"
	],
	"quarters-standAlone-wide": [
		"1.º trimestre",
		"2.º trimestre",
		"3.º trimestre",
		"4.º trimestre"
	],
	"dayPeriods-format-abbr-am": "a.m.",
	"dayPeriods-format-abbr-pm": "p.m.",
	"dayPeriods-format-narrow-midnight": "meia-noite",
	"dayPeriods-format-narrow-am": "a.m.",
	"dayPeriods-format-narrow-noon": "meio-dia",
	"dayPeriods-format-narrow-pm": "p.m.",
	"dayPeriods-format-narrow-morning1": "manhã",
	"dayPeriods-format-narrow-afternoon1": "tarde",
	"dayPeriods-format-narrow-evening1": "noite",
	"dayPeriods-format-narrow-night1": "madrugada",
	"dayPeriods-format-wide-am": "da manhã",
	"dayPeriods-format-wide-pm": "da tarde",
	"dayPeriods-standAlone-abbr-am": "a.m.",
	"dayPeriods-standAlone-abbr-pm": "p.m.",
	"dayPeriods-standAlone-narrow-am": "a.m.",
	"dayPeriods-standAlone-narrow-pm": "p.m.",
	"dayPeriods-standAlone-wide-am": "manhã",
	"dayPeriods-standAlone-wide-pm": "tarde",
	"eraAbbr": [
		"a.C.",
		"d.C."
	],
	"dateFormat-medium": "dd/MM/y",
	"dateFormat-short": "dd/MM/yy",
	"dateTimeFormat-full": "{1} 'às' {0}",
	"dateTimeFormat-long": "{1} 'às' {0}",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-Md": "dd/MM",
	"dateFormatItem-MMMd": "d/MM",
	"dateFormatItem-MMMEd": "E, d/MM",
	"dateFormatItem-MMMMEd": "ccc, d 'de' MMMM",
	"dateFormatItem-MMMMW": "W.'ª' 'semana' 'de' MMM",
	"dateFormatItem-yMMM": "MM/y",
	"dateFormatItem-yMMMd": "d/MM/y",
	"dateFormatItem-yMMMEd": "E, d/MM/y",
	"dateFormatItem-yMMMEEEEd": "EEEE, d/MM/y",
	"dateFormatItem-yMMMMEd": "ccc, d 'de' MMMM 'de' y",
	"dateFormatItem-yQQQ": "QQQQ 'de' y",
	"dateFormatItem-yw": "w.'ª' 'semana' 'de' y",
	"field-quarter-relative+-1": "trimestre passado",
	"field-quarter-relative+0": "este trimestre",
	"field-quarter-relative+1": "próximo trimestre",
	"field-quarter-short-relative+-1": "trim. passado",
	"field-quarter-short-relative+0": "este trim.",
	"field-quarter-short-relative+1": "próximo trim.",
	"field-quarter-narrow-relative+-1": "trim. passado",
	"field-quarter-narrow-relative+0": "este trim.",
	"field-quarter-narrow-relative+1": "próximo trim.",
	"field-sun-short-relative+-1": "domingo passado",
	"field-sun-short-relative+0": "este domingo",
	"field-sun-short-relative+1": "próximo domingo",
	"field-mon-short-relative+-1": "segunda passada",
	"field-mon-short-relative+0": "esta segunda",
	"field-mon-short-relative+1": "próxima segunda",
	"field-tue-short-relative+-1": "terça passada",
	"field-tue-short-relative+0": "esta terça",
	"field-tue-short-relative+1": "próxima terça",
	"field-wed-short-relative+-1": "quarta passada",
	"field-wed-short-relative+0": "esta quarta",
	"field-wed-short-relative+1": "próxima quarta",
	"field-thu-short-relative+-1": "quinta passada",
	"field-thu-short-relative+0": "esta quinta",
	"field-thu-short-relative+1": "próxima quinta",
	"field-thu-narrow-relative+-1": "qui. passada",
	"field-thu-narrow-relative+0": "esta qui.",
	"field-thu-narrow-relative+1": "próxima qui.",
	"field-fri-short-relative+-1": "sexta passada",
	"field-fri-short-relative+0": "esta sexta",
	"field-fri-short-relative+1": "próxima sexta",
	"field-sat-short-relative+-1": "sábado passado",
	"field-sat-short-relative+0": "este sábado",
	"field-sat-short-relative+1": "próximo sábado",
	"field-minute-short": "min",
	"field-minute-narrow": "min",
	"field-second-short": "s",
	"days-format-short": [
		"domingo",
		"segunda",
		"terça",
		"quarta",
		"quinta",
		"sexta",
		"sábado"
	],
	"days-standAlone-short": [
		"domingo",
		"segunda",
		"terça",
		"quarta",
		"quinta",
		"sexta",
		"sábado"
	],
	"quarters-format-abbr": [
		"1.º trimestre",
		"2.º trimestre",
		"3.º trimestre",
		"4.º trimestre"
	],
	"quarters-standAlone-abbr": [
		"1.º trimestre",
		"2.º trimestre",
		"3.º trimestre",
		"4.º trimestre"
	],
	"eraNames": [
		"a.C.",
		"d.C."
	],
	"eraNarrow": [
		"a.C.",
		"d.C."
	]
}
//end v1.x content
);