define(
//begin v1.x content
{
	"dateFormat-short": "d/M/y G",
	"field-quarter-relative+-1": "trimestre passado",
	"field-quarter-relative+0": "este trimestre",
	"field-quarter-relative+1": "próximo trimestre",
	"field-quarter-short-relative+-1": "trim. passado",
	"field-quarter-short-relative+0": "este trim.",
	"field-quarter-short-relative+1": "próximo trim.",
	"field-quarter-narrow-relative+-1": "trim. passado",
	"field-quarter-narrow-relative+0": "este trim.",
	"field-quarter-narrow-relative+1": "próximo trim.",
	"field-sun-short-relative+-1": "domingo passado",
	"field-sun-short-relative+0": "este domingo",
	"field-sun-short-relative+1": "próximo domingo",
	"field-mon-short-relative+-1": "segunda passada",
	"field-mon-short-relative+0": "esta segunda",
	"field-mon-short-relative+1": "próxima segunda",
	"field-tue-short-relative+-1": "terça passada",
	"field-tue-short-relative+0": "esta terça",
	"field-tue-short-relative+1": "próxima terça",
	"field-wed-short-relative+-1": "quarta passada",
	"field-wed-short-relative+0": "esta quarta",
	"field-wed-short-relative+1": "próxima quarta",
	"field-thu-short-relative+-1": "quinta passada",
	"field-thu-short-relative+0": "esta quinta",
	"field-thu-short-relative+1": "próxima quinta",
	"field-thu-narrow-relative+-1": "qui. passada",
	"field-thu-narrow-relative+0": "esta qui.",
	"field-thu-narrow-relative+1": "próxima qui.",
	"field-fri-short-relative+-1": "sexta passada",
	"field-fri-short-relative+0": "esta sexta",
	"field-fri-short-relative+1": "próxima sexta",
	"field-sat-short-relative+-1": "sábado passado",
	"field-sat-short-relative+0": "este sábado",
	"field-sat-short-relative+1": "próximo sábado",
	"field-minute-short": "min",
	"field-minute-narrow": "min",
	"field-second-short": "s",
	"days-format-abbr": [
		"domingo",
		"segunda",
		"terça",
		"quarta",
		"quinta",
		"sexta",
		"sábado"
	],
	"days-format-narrow": [
		"D",
		"S",
		"T",
		"Q",
		"Q",
		"S",
		"S"
	],
	"days-format-short": [
		"domingo",
		"segunda",
		"terça",
		"quarta",
		"quinta",
		"sexta",
		"sábado"
	],
	"days-format-wide": [
		"domingo",
		"segunda-feira",
		"terça-feira",
		"quarta-feira",
		"quinta-feira",
		"sexta-feira",
		"sábado"
	],
	"days-standAlone-abbr": [
		"domingo",
		"segunda",
		"terça",
		"quarta",
		"quinta",
		"sexta",
		"sábado"
	],
	"days-standAlone-narrow": [
		"D",
		"S",
		"T",
		"Q",
		"Q",
		"S",
		"S"
	],
	"days-standAlone-short": [
		"domingo",
		"segunda",
		"terça",
		"quarta",
		"quinta",
		"sexta",
		"sábado"
	],
	"days-standAlone-wide": [
		"domingo",
		"segunda-feira",
		"terça-feira",
		"quarta-feira",
		"quinta-feira",
		"sexta-feira",
		"sábado"
	],
	"quarters-format-abbr": [
		"1.º trimestre",
		"2.º trimestre",
		"3.º trimestre",
		"4.º trimestre"
	],
	"quarters-format-wide": [
		"1.º trimestre",
		"2.º trimestre",
		"3.º trimestre",
		"4.º trimestre"
	],
	"quarters-standAlone-abbr": [
		"1.º trimestre",
		"2.º trimestre",
		"3.º trimestre",
		"4.º trimestre"
	],
	"quarters-standAlone-wide": [
		"1.º trimestre",
		"2.º trimestre",
		"3.º trimestre",
		"4.º trimestre"
	],
	"dayPeriods-format-abbr-am": "a.m.",
	"dayPeriods-format-abbr-pm": "p.m.",
	"dayPeriods-format-narrow-am": "a.m.",
	"dayPeriods-format-narrow-pm": "p.m.",
	"dayPeriods-format-wide-am": "da manhã",
	"dayPeriods-format-wide-pm": "da tarde",
	"dayPeriods-standAlone-abbr-am": "a.m.",
	"dayPeriods-standAlone-abbr-pm": "p.m.",
	"dayPeriods-standAlone-narrow-am": "a.m.",
	"dayPeriods-standAlone-narrow-pm": "p.m.",
	"dayPeriods-standAlone-wide-am": "manhã",
	"dayPeriods-standAlone-wide-pm": "tarde",
	"dateFormat-full": "EEEE, d 'de' MMMM 'de' y G",
	"dateFormat-long": "d 'de' MMMM 'de' y G",
	"dateFormat-medium": "dd/MM/y G",
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "MMM 'de' y G",
	"dateFormatItem-GyMMMd": "d 'de' MMM 'de' y G",
	"dateFormatItem-GyMMMEd": "E, d 'de' MMM 'de' y G",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-MEd": "E, dd/MM",
	"dateFormatItem-MMMd": "d 'de' MMM",
	"dateFormatItem-MMMEd": "E, d 'de' MMM",
	"dateFormatItem-MMMMd": "d 'de' MMMM",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-yyyyM": "MM/y GGGGG",
	"dateFormatItem-yyyyMd": "dd/MM/y GGGGG",
	"dateFormatItem-yyyyMEd": "E, dd/MM/y GGGGG",
	"dateFormatItem-yyyyMMM": "MM/y G",
	"dateFormatItem-yyyyMMMd": "d/MM/y G",
	"dateFormatItem-yyyyMMMEd": "E, d/MM/y G",
	"dateFormatItem-yyyyMMMM": "MMMM 'de' y G",
	"dateFormatItem-yyyyQQQ": "QQQQ 'de' y G",
	"dateFormatItem-yyyyQQQQ": "QQQQ 'de' y G",
	"dateTimeFormat-full": "{1} 'às' {0}",
	"dateTimeFormat-long": "{1} 'às' {0}",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateTimeFormat-short": "{1}, {0}"
}
//end v1.x content
);