define(
//begin v1.x content
{
	"months-format-abbr": [
		"sty",
		"lut",
		"mar",
		"kwi",
		"maj",
		"cze",
		"lip",
		"sie",
		"wrz",
		"paź",
		"lis",
		"gru"
	],
	"months-format-narrow": [
		"s",
		"l",
		"m",
		"k",
		"m",
		"c",
		"l",
		"s",
		"w",
		"p",
		"l",
		"g"
	],
	"months-format-wide": [
		"stycznia",
		"lutego",
		"marca",
		"kwietnia",
		"maja",
		"czerwca",
		"lipca",
		"sierpnia",
		"września",
		"października",
		"listopada",
		"grudnia"
	],
	"months-standAlone-abbr": [
		"sty",
		"lut",
		"mar",
		"kwi",
		"maj",
		"cze",
		"lip",
		"sie",
		"wrz",
		"paź",
		"lis",
		"gru"
	],
	"months-standAlone-narrow": [
		"S",
		"L",
		"M",
		"K",
		"M",
		"C",
		"L",
		"S",
		"W",
		"P",
		"L",
		"G"
	],
	"months-standAlone-wide": [
		"styczeń",
		"luty",
		"marzec",
		"kwiecień",
		"maj",
		"czerwiec",
		"lipiec",
		"sierpień",
		"wrzesień",
		"październik",
		"listopad",
		"grudzień"
	],
	"days-format-abbr": [
		"niedz.",
		"pon.",
		"wt.",
		"śr.",
		"czw.",
		"pt.",
		"sob."
	],
	"days-format-narrow": [
		"n",
		"p",
		"w",
		"ś",
		"c",
		"p",
		"s"
	],
	"days-format-short": [
		"nie",
		"pon",
		"wto",
		"śro",
		"czw",
		"pią",
		"sob"
	],
	"days-format-wide": [
		"niedziela",
		"poniedziałek",
		"wtorek",
		"środa",
		"czwartek",
		"piątek",
		"sobota"
	],
	"days-standAlone-abbr": [
		"niedz.",
		"pon.",
		"wt.",
		"śr.",
		"czw.",
		"pt.",
		"sob."
	],
	"days-standAlone-narrow": [
		"N",
		"P",
		"W",
		"Ś",
		"C",
		"P",
		"S"
	],
	"days-standAlone-short": [
		"nie",
		"pon",
		"wto",
		"śro",
		"czw",
		"pią",
		"sob"
	],
	"days-standAlone-wide": [
		"niedziela",
		"poniedziałek",
		"wtorek",
		"środa",
		"czwartek",
		"piątek",
		"sobota"
	],
	"quarters-format-abbr": [
		"I kw.",
		"II kw.",
		"III kw.",
		"IV kw."
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"I kwartał",
		"II kwartał",
		"III kwartał",
		"IV kwartał"
	],
	"quarters-standAlone-abbr": [
		"I kw.",
		"II kw.",
		"III kw.",
		"IV kw."
	],
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-standAlone-wide": [
		"I kwartał",
		"II kwartał",
		"III kwartał",
		"IV kwartał"
	],
	"dayPeriods-format-abbr-midnight": "o północy",
	"dayPeriods-format-abbr-am": "AM",
	"dayPeriods-format-abbr-noon": "w południe",
	"dayPeriods-format-abbr-pm": "PM",
	"dayPeriods-format-abbr-morning1": "rano",
	"dayPeriods-format-abbr-morning2": "przed południem",
	"dayPeriods-format-abbr-afternoon1": "po południu",
	"dayPeriods-format-abbr-evening1": "wieczorem",
	"dayPeriods-format-abbr-night1": "w nocy",
	"dayPeriods-format-narrow-midnight": "o półn.",
	"dayPeriods-format-narrow-am": "a",
	"dayPeriods-format-narrow-noon": "w poł.",
	"dayPeriods-format-narrow-pm": "p",
	"dayPeriods-format-narrow-morning1": "rano",
	"dayPeriods-format-narrow-morning2": "przed poł.",
	"dayPeriods-format-narrow-afternoon1": "po poł.",
	"dayPeriods-format-narrow-evening1": "wiecz.",
	"dayPeriods-format-narrow-night1": "w nocy",
	"dayPeriods-format-wide-midnight": "o północy",
	"dayPeriods-format-wide-am": "AM",
	"dayPeriods-format-wide-noon": "w południe",
	"dayPeriods-format-wide-pm": "PM",
	"dayPeriods-format-wide-morning1": "rano",
	"dayPeriods-format-wide-morning2": "przed południem",
	"dayPeriods-format-wide-afternoon1": "po południu",
	"dayPeriods-format-wide-evening1": "wieczorem",
	"dayPeriods-format-wide-night1": "w nocy",
	"dayPeriods-standAlone-abbr-midnight": "północ",
	"dayPeriods-standAlone-abbr-am": "AM",
	"dayPeriods-standAlone-abbr-noon": "południe",
	"dayPeriods-standAlone-abbr-pm": "PM",
	"dayPeriods-standAlone-abbr-morning1": "rano",
	"dayPeriods-standAlone-abbr-morning2": "przedpołudnie",
	"dayPeriods-standAlone-abbr-afternoon1": "popołudnie",
	"dayPeriods-standAlone-abbr-evening1": "wieczór",
	"dayPeriods-standAlone-abbr-night1": "noc",
	"dayPeriods-standAlone-narrow-midnight": "półn.",
	"dayPeriods-standAlone-narrow-am": "a",
	"dayPeriods-standAlone-narrow-noon": "poł.",
	"dayPeriods-standAlone-narrow-pm": "p",
	"dayPeriods-standAlone-narrow-morning1": "rano",
	"dayPeriods-standAlone-narrow-morning2": "przedpoł.",
	"dayPeriods-standAlone-narrow-afternoon1": "popoł.",
	"dayPeriods-standAlone-narrow-evening1": "wiecz.",
	"dayPeriods-standAlone-narrow-night1": "noc",
	"dayPeriods-standAlone-wide-midnight": "północ",
	"dayPeriods-standAlone-wide-am": "AM",
	"dayPeriods-standAlone-wide-noon": "południe",
	"dayPeriods-standAlone-wide-pm": "PM",
	"dayPeriods-standAlone-wide-morning1": "rano",
	"dayPeriods-standAlone-wide-morning2": "przedpołudnie",
	"dayPeriods-standAlone-wide-afternoon1": "popołudnie",
	"dayPeriods-standAlone-wide-evening1": "wieczór",
	"dayPeriods-standAlone-wide-night1": "noc",
	"eraNames": [
		"przed naszą erą",
		"naszej ery"
	],
	"eraAbbr": [
		"p.n.e.",
		"n.e."
	],
	"dateFormat-full": "EEEE, d MMMM y",
	"dateFormat-long": "d MMMM y",
	"dateFormat-medium": "d MMM y",
	"dateFormat-short": "dd.MM.y",
	"timeFormat-full": "HH:mm:ss zzzz",
	"timeFormat-long": "HH:mm:ss z",
	"timeFormat-medium": "HH:mm:ss",
	"timeFormat-short": "HH:mm",
	"dateTimeFormat-full": "{1} {0}",
	"dateTimeFormat-long": "{1} {0}",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-d": "d",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-Ehm": "E, h:mm a",
	"dateFormatItem-EHm": "E, HH:mm",
	"dateFormatItem-Ehms": "E, h:mm:ss a",
	"dateFormatItem-EHms": "E, HH:mm:ss",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"dateFormatItem-GyMMMEd": "E, d MMM y G",
	"dateFormatItem-GyMMMM": "LLLL y G",
	"dateFormatItem-GyMMMMd": "d MMMM y G",
	"dateFormatItem-GyMMMMEd": "E, d MMMM y G",
	"dateFormatItem-h": "h a",
	"dateFormatItem-H": "HH",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hmsv": "h:mm:ss a v",
	"dateFormatItem-Hmsv": "HH:mm:ss v",
	"dateFormatItem-hmv": "h:mm a v",
	"dateFormatItem-Hmv": "HH:mm v",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "d.MM",
	"dateFormatItem-MEd": "E, d.MM",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-MMMMEd": "E, d MMMM",
	"dateFormatItem-MMMMW": "MMM, 'tydz'. W",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y",
	"dateFormatItem-yM": "MM.y",
	"dateFormatItem-yMd": "d.MM.y",
	"dateFormatItem-yMEd": "E, d.MM.y",
	"dateFormatItem-yMMM": "LLL y",
	"dateFormatItem-yMMMd": "d MMM y",
	"dateFormatItem-yMMMEd": "E, d MMM y",
	"dateFormatItem-yMMMM": "LLLL y",
	"dateFormatItem-yMMMMd": "d MMMM y",
	"dateFormatItem-yMMMMEd": "E, d MMMM y",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"dateFormatItem-yw": "y, 'tydz'. w",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-era": "era",
	"field-year": "rok",
	"field-year-relative+-1": "w zeszłym roku",
	"field-year-relative+0": "w tym roku",
	"field-year-relative+1": "w przyszłym roku",
	"field-year-short": "r.",
	"field-year-narrow": "r.",
	"field-quarter": "kwartał",
	"field-quarter-relative+-1": "w zeszłym kwartale",
	"field-quarter-relative+0": "w tym kwartale",
	"field-quarter-relative+1": "w przyszłym kwartale",
	"field-quarter-short": "kw.",
	"field-quarter-short-relative+-1": "w zeszłym kwartale",
	"field-quarter-short-relative+0": "w tym kwartale",
	"field-quarter-short-relative+1": "w przyszłym kwartale",
	"field-quarter-narrow": "kw.",
	"field-quarter-narrow-relative+-1": "w zeszłym kwartale",
	"field-quarter-narrow-relative+0": "w tym kwartale",
	"field-quarter-narrow-relative+1": "w przyszłym kwartale",
	"field-month": "miesiąc",
	"field-month-relative+-1": "w zeszłym miesiącu",
	"field-month-relative+0": "w tym miesiącu",
	"field-month-relative+1": "w przyszłym miesiącu",
	"field-month-short": "mies.",
	"field-month-narrow": "mc",
	"field-week": "tydzień",
	"field-week-relative+-1": "w zeszłym tygodniu",
	"field-week-relative+0": "w tym tygodniu",
	"field-week-relative+1": "w przyszłym tygodniu",
	"field-week-short": "tydz.",
	"field-week-narrow": "tydz.",
	"field-day": "dzień",
	"field-day-relative+-2": "przedwczoraj",
	"field-day-relative+-1": "wczoraj",
	"field-day-relative+0": "dzisiaj",
	"field-day-relative+1": "jutro",
	"field-day-relative+2": "pojutrze",
	"field-day-short": "dzień",
	"field-day-narrow": "dzień",
	"field-weekday": "dzień tygodnia",
	"field-sun-relative+-1": "w zeszłą niedzielę",
	"field-sun-relative+0": "w tę niedzielę",
	"field-sun-relative+1": "w przyszłą niedzielę",
	"field-sun-short-relative+-1": "w zeszłą niedzielę",
	"field-sun-short-relative+0": "w tę niedzielę",
	"field-sun-short-relative+1": "w przyszłą niedzielę",
	"field-sun-narrow-relative+-1": "w zeszłą niedzielę",
	"field-sun-narrow-relative+0": "w tę niedzielę",
	"field-sun-narrow-relative+1": "w przyszłą niedzielę",
	"field-mon-relative+-1": "w zeszły poniedziałek",
	"field-mon-relative+0": "w ten poniedziałek",
	"field-mon-relative+1": "w przyszły poniedziałek",
	"field-mon-short-relative+-1": "w zeszły poniedziałek",
	"field-mon-short-relative+0": "w ten poniedziałek",
	"field-mon-short-relative+1": "w przyszły poniedziałek",
	"field-mon-narrow-relative+-1": "w zeszły poniedziałek",
	"field-mon-narrow-relative+0": "w ten poniedziałek",
	"field-mon-narrow-relative+1": "w przyszły poniedziałek",
	"field-tue-relative+-1": "w zeszły wtorek",
	"field-tue-relative+0": "w ten wtorek",
	"field-tue-relative+1": "w przyszły wtorek",
	"field-tue-short-relative+-1": "w zeszły wtorek",
	"field-tue-short-relative+0": "w ten wtorek",
	"field-tue-short-relative+1": "w przyszły wtorek",
	"field-tue-narrow-relative+-1": "w zeszły wtorek",
	"field-tue-narrow-relative+0": "w ten wtorek",
	"field-tue-narrow-relative+1": "w przyszły wtorek",
	"field-wed-relative+-1": "w zeszłą środę",
	"field-wed-relative+0": "w tę środę",
	"field-wed-relative+1": "w przyszłą środę",
	"field-wed-short-relative+-1": "w zeszłą środę",
	"field-wed-short-relative+0": "w tę środę",
	"field-wed-short-relative+1": "w przyszłą środę",
	"field-wed-narrow-relative+-1": "w zeszłą środę",
	"field-wed-narrow-relative+0": "w tę środę",
	"field-wed-narrow-relative+1": "w przyszłą środę",
	"field-thu-relative+-1": "w zeszły czwartek",
	"field-thu-relative+0": "w ten czwartek",
	"field-thu-relative+1": "w przyszły czwartek",
	"field-thu-short-relative+-1": "w zeszły czwartek",
	"field-thu-short-relative+0": "w ten czwartek",
	"field-thu-short-relative+1": "w przyszły czwartek",
	"field-thu-narrow-relative+-1": "w zeszły czwartek",
	"field-thu-narrow-relative+0": "w ten czwartek",
	"field-thu-narrow-relative+1": "w przyszły czwartek",
	"field-fri-relative+-1": "w zeszły piątek",
	"field-fri-relative+0": "w ten piątek",
	"field-fri-relative+1": "w przyszły piątek",
	"field-fri-short-relative+-1": "w zeszły piątek",
	"field-fri-short-relative+0": "w ten piątek",
	"field-fri-short-relative+1": "w przyszły piątek",
	"field-fri-narrow-relative+-1": "w zeszły piątek",
	"field-fri-narrow-relative+0": "w ten piątek",
	"field-fri-narrow-relative+1": "w przyszły piątek",
	"field-sat-relative+-1": "w zeszłą sobotę",
	"field-sat-relative+0": "w tę sobotę",
	"field-sat-relative+1": "w przyszłą sobotę",
	"field-sat-short-relative+-1": "w zeszłą sobotę",
	"field-sat-short-relative+0": "w tę sobotę",
	"field-sat-short-relative+1": "w przyszłą sobotę",
	"field-sat-narrow-relative+-1": "w zeszłą sobotę",
	"field-sat-narrow-relative+0": "w tę sobotę",
	"field-sat-narrow-relative+1": "w przyszłą sobotę",
	"field-dayperiod": "rano / po południu / wieczorem",
	"field-hour": "godzina",
	"field-hour-relative+0": "ta godzina",
	"field-hour-short": "godz.",
	"field-hour-narrow": "g.",
	"field-minute": "minuta",
	"field-minute-relative+0": "ta minuta",
	"field-minute-short": "min",
	"field-minute-narrow": "min",
	"field-second": "sekunda",
	"field-second-relative+0": "teraz",
	"field-second-short": "sek.",
	"field-second-narrow": "s",
	"field-zone": "strefa czasowa",
	"eraNarrow": [
		"p.n.e.",
		"n.e."
	]
}
//end v1.x content
);