define(
//begin v1.x content
{
	"months-format-abbr": [
		"Muh.",
		"Saf.",
		"Rab. I",
		"Rab. II",
		"Dżu. I",
		"Dżu. II",
		"Ra.",
		"Sza.",
		"Ram.",
		"Szaw.",
		"Zu al-k.",
		"Zu al-h."
	],
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-format-wide": [
		"Muharram",
		"Safar",
		"Rabiʻ I",
		"Rabiʻ II",
		"Dżumada I",
		"Dżumada II",
		"Radżab",
		"Szaban",
		"Ramadan",
		"Szawwal",
		"Zu al-kada",
		"Zu al-hidżdża"
	],
	"months-standAlone-abbr": [
		"Muh.",
		"Saf.",
		"Rab. I",
		"Rab. II",
		"Dżu. I",
		"Dżu. II",
		"Ra.",
		"Sza.",
		"Ram.",
		"Szaw.",
		"Zu al-k.",
		"Zu al-h."
	],
	"months-standAlone-wide": [
		"Muharram",
		"Safar",
		"Rabiʻ I",
		"Rabiʻ II",
		"Dżumada I",
		"Dżumada II",
		"Radżab",
		"Szaban",
		"Ramadan",
		"Szawwal",
		"Zu al-kada",
		"Zu al-hidżdża"
	],
	"field-era": "era",
	"field-year": "rok",
	"field-year-relative+-1": "w zeszłym roku",
	"field-year-relative+0": "w tym roku",
	"field-year-relative+1": "w przyszłym roku",
	"field-year-short": "r.",
	"field-year-narrow": "r.",
	"field-quarter": "kwartał",
	"field-quarter-relative+-1": "w zeszłym kwartale",
	"field-quarter-relative+0": "w tym kwartale",
	"field-quarter-relative+1": "w przyszłym kwartale",
	"field-quarter-short": "kw.",
	"field-quarter-short-relative+-1": "w zeszłym kwartale",
	"field-quarter-short-relative+0": "w tym kwartale",
	"field-quarter-short-relative+1": "w przyszłym kwartale",
	"field-quarter-narrow": "kw.",
	"field-quarter-narrow-relative+-1": "w zeszłym kwartale",
	"field-quarter-narrow-relative+0": "w tym kwartale",
	"field-quarter-narrow-relative+1": "w przyszłym kwartale",
	"field-month": "miesiąc",
	"field-month-relative+-1": "w zeszłym miesiącu",
	"field-month-relative+0": "w tym miesiącu",
	"field-month-relative+1": "w przyszłym miesiącu",
	"field-month-short": "mies.",
	"field-month-narrow": "mc",
	"field-week": "tydzień",
	"field-week-relative+-1": "w zeszłym tygodniu",
	"field-week-relative+0": "w tym tygodniu",
	"field-week-relative+1": "w przyszłym tygodniu",
	"field-week-short": "tydz.",
	"field-week-narrow": "tydz.",
	"field-day": "dzień",
	"field-day-relative+-2": "przedwczoraj",
	"field-day-relative+-1": "wczoraj",
	"field-day-relative+0": "dzisiaj",
	"field-day-relative+1": "jutro",
	"field-day-relative+2": "pojutrze",
	"field-day-short": "dzień",
	"field-day-narrow": "dzień",
	"field-weekday": "dzień tygodnia",
	"field-sun-relative+-1": "w zeszłą niedzielę",
	"field-sun-relative+0": "w tę niedzielę",
	"field-sun-relative+1": "w przyszłą niedzielę",
	"field-sun-short-relative+-1": "w zeszłą niedzielę",
	"field-sun-short-relative+0": "w tę niedzielę",
	"field-sun-short-relative+1": "w przyszłą niedzielę",
	"field-sun-narrow-relative+-1": "w zeszłą niedzielę",
	"field-sun-narrow-relative+0": "w tę niedzielę",
	"field-sun-narrow-relative+1": "w przyszłą niedzielę",
	"field-mon-relative+-1": "w zeszły poniedziałek",
	"field-mon-relative+0": "w ten poniedziałek",
	"field-mon-relative+1": "w przyszły poniedziałek",
	"field-mon-short-relative+-1": "w zeszły poniedziałek",
	"field-mon-short-relative+0": "w ten poniedziałek",
	"field-mon-short-relative+1": "w przyszły poniedziałek",
	"field-mon-narrow-relative+-1": "w zeszły poniedziałek",
	"field-mon-narrow-relative+0": "w ten poniedziałek",
	"field-mon-narrow-relative+1": "w przyszły poniedziałek",
	"field-tue-relative+-1": "w zeszły wtorek",
	"field-tue-relative+0": "w ten wtorek",
	"field-tue-relative+1": "w przyszły wtorek",
	"field-tue-short-relative+-1": "w zeszły wtorek",
	"field-tue-short-relative+0": "w ten wtorek",
	"field-tue-short-relative+1": "w przyszły wtorek",
	"field-tue-narrow-relative+-1": "w zeszły wtorek",
	"field-tue-narrow-relative+0": "w ten wtorek",
	"field-tue-narrow-relative+1": "w przyszły wtorek",
	"field-wed-relative+-1": "w zeszłą środę",
	"field-wed-relative+0": "w tę środę",
	"field-wed-relative+1": "w przyszłą środę",
	"field-wed-short-relative+-1": "w zeszłą środę",
	"field-wed-short-relative+0": "w tę środę",
	"field-wed-short-relative+1": "w przyszłą środę",
	"field-wed-narrow-relative+-1": "w zeszłą środę",
	"field-wed-narrow-relative+0": "w tę środę",
	"field-wed-narrow-relative+1": "w przyszłą środę",
	"field-thu-relative+-1": "w zeszły czwartek",
	"field-thu-relative+0": "w ten czwartek",
	"field-thu-relative+1": "w przyszły czwartek",
	"field-thu-short-relative+-1": "w zeszły czwartek",
	"field-thu-short-relative+0": "w ten czwartek",
	"field-thu-short-relative+1": "w przyszły czwartek",
	"field-thu-narrow-relative+-1": "w zeszły czwartek",
	"field-thu-narrow-relative+0": "w ten czwartek",
	"field-thu-narrow-relative+1": "w przyszły czwartek",
	"field-fri-relative+-1": "w zeszły piątek",
	"field-fri-relative+0": "w ten piątek",
	"field-fri-relative+1": "w przyszły piątek",
	"field-fri-short-relative+-1": "w zeszły piątek",
	"field-fri-short-relative+0": "w ten piątek",
	"field-fri-short-relative+1": "w przyszły piątek",
	"field-fri-narrow-relative+-1": "w zeszły piątek",
	"field-fri-narrow-relative+0": "w ten piątek",
	"field-fri-narrow-relative+1": "w przyszły piątek",
	"field-sat-relative+-1": "w zeszłą sobotę",
	"field-sat-relative+0": "w tę sobotę",
	"field-sat-relative+1": "w przyszłą sobotę",
	"field-sat-short-relative+-1": "w zeszłą sobotę",
	"field-sat-short-relative+0": "w tę sobotę",
	"field-sat-short-relative+1": "w przyszłą sobotę",
	"field-sat-narrow-relative+-1": "w zeszłą sobotę",
	"field-sat-narrow-relative+0": "w tę sobotę",
	"field-sat-narrow-relative+1": "w przyszłą sobotę",
	"field-dayperiod": "rano / po południu / wieczorem",
	"field-hour": "godzina",
	"field-hour-relative+0": "ta godzina",
	"field-hour-short": "godz.",
	"field-hour-narrow": "g.",
	"field-minute": "minuta",
	"field-minute-relative+0": "ta minuta",
	"field-minute-short": "min",
	"field-minute-narrow": "min",
	"field-second": "sekunda",
	"field-second-relative+0": "teraz",
	"field-second-short": "sek.",
	"field-second-narrow": "s",
	"field-zone": "strefa czasowa",
	"days-format-abbr": [
		"niedz.",
		"pon.",
		"wt.",
		"śr.",
		"czw.",
		"pt.",
		"sob."
	],
	"days-format-narrow": [
		"n",
		"p",
		"w",
		"ś",
		"c",
		"p",
		"s"
	],
	"days-format-short": [
		"nie",
		"pon",
		"wto",
		"śro",
		"czw",
		"pią",
		"sob"
	],
	"days-format-wide": [
		"niedziela",
		"poniedziałek",
		"wtorek",
		"środa",
		"czwartek",
		"piątek",
		"sobota"
	],
	"days-standAlone-abbr": [
		"niedz.",
		"pon.",
		"wt.",
		"śr.",
		"czw.",
		"pt.",
		"sob."
	],
	"days-standAlone-narrow": [
		"N",
		"P",
		"W",
		"Ś",
		"C",
		"P",
		"S"
	],
	"days-standAlone-short": [
		"nie",
		"pon",
		"wto",
		"śro",
		"czw",
		"pią",
		"sob"
	],
	"days-standAlone-wide": [
		"niedziela",
		"poniedziałek",
		"wtorek",
		"środa",
		"czwartek",
		"piątek",
		"sobota"
	],
	"quarters-format-abbr": [
		"I kw.",
		"II kw.",
		"III kw.",
		"IV kw."
	],
	"quarters-format-wide": [
		"I kwartał",
		"II kwartał",
		"III kwartał",
		"IV kwartał"
	],
	"quarters-standAlone-abbr": [
		"I kw.",
		"II kw.",
		"III kw.",
		"IV kw."
	],
	"quarters-standAlone-wide": [
		"I kwartał",
		"II kwartał",
		"III kwartał",
		"IV kwartał"
	],
	"dayPeriods-format-narrow-am": "a",
	"dayPeriods-format-narrow-pm": "p",
	"dayPeriods-standAlone-narrow-am": "a",
	"dayPeriods-standAlone-narrow-pm": "p",
	"dateFormat-full": "EEEE, d MMMM y G",
	"dateFormat-long": "d MMMM y G",
	"dateFormat-medium": "d MMM y G",
	"dateFormat-short": "dd.MM.y G",
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "LLL y G",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"dateFormatItem-GyMMMEd": "E, d MMM y G",
	"dateFormatItem-h": "hh a",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-Md": "d.MM",
	"dateFormatItem-MEd": "E, d.MM",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-yyyyM": "MM.y G",
	"dateFormatItem-yyyyMd": "d.MM.y G",
	"dateFormatItem-yyyyMEd": "E, d.MM.y G",
	"dateFormatItem-yyyyMMM": "LLL y G",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-yyyyMMMEd": "E, d MMM y G",
	"dateFormatItem-yyyyMMMM": "LLLL y G",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"dateTimeFormat-full": "{1}, {0}",
	"dateTimeFormat-long": "{1}, {0}",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateTimeFormat-short": "{1}, {0}"
}
//end v1.x content
);