define(
//begin v1.x content
{
	"dateFormat-full": "EEEE, d. M. y G",
	"dateFormat-long": "d. M. y G",
	"dateFormat-medium": "d. M. y G",
	"dateFormat-short": "d.M.y GGGGG",
	"dateTimeFormat-full": "{1}, {0}",
	"dateTimeFormat-long": "{1}, {0}",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-d": "d.",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E d.",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "LLL y G",
	"dateFormatItem-GyMMMd": "d. M. y G",
	"dateFormatItem-GyMMMEd": "E d. M. y G",
	"dateFormatItem-GyMMMMd": "d. M. y G",
	"dateFormatItem-h": "h a",
	"dateFormatItem-H": "H",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-M": "M.",
	"dateFormatItem-Md": "d. M.",
	"dateFormatItem-MEd": "E d. M.",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d. M.",
	"dateFormatItem-MMMEd": "E d. M.",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-MMMMEd": "E d. MMMM",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-yyyyM": "M/y GGGGG",
	"dateFormatItem-yyyyMd": "d. M. y GGGGG",
	"dateFormatItem-yyyyMEd": "E d. M. y GGGGG",
	"dateFormatItem-yyyyMMM": "LLL y G",
	"dateFormatItem-yyyyMMMd": "d. M. y G",
	"dateFormatItem-yyyyMMMEd": "E d. M. y G",
	"dateFormatItem-yyyyMMMM": "LLLL y G",
	"dateFormatItem-yyyyMMMMd": "d. MMMM y G",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"field-era": "letopočet",
	"field-year": "rok",
	"field-year-relative+-1": "minulý rok",
	"field-year-relative+0": "tento rok",
	"field-year-relative+1": "budúci rok",
	"field-year-short": "r.",
	"field-year-narrow": "r.",
	"field-quarter": "štvrťrok",
	"field-quarter-relative+-1": "minulý štvrťrok",
	"field-quarter-relative+0": "tento štvrťrok",
	"field-quarter-relative+1": "budúci štvrťrok",
	"field-quarter-short": "Q",
	"field-quarter-short-relative+-1": "minulý štvrťr.",
	"field-quarter-short-relative+0": "tento štvrťr.",
	"field-quarter-short-relative+1": "budúci štvrťr.",
	"field-quarter-narrow": "Q",
	"field-quarter-narrow-relative+-1": "minulý štvrťr.",
	"field-quarter-narrow-relative+0": "tento štvrťr.",
	"field-quarter-narrow-relative+1": "budúci štvrťr.",
	"field-month": "mesiac",
	"field-month-relative+-1": "minulý mesiac",
	"field-month-relative+0": "tento mesiac",
	"field-month-relative+1": "budúci mesiac",
	"field-month-short": "mes.",
	"field-month-narrow": "mes.",
	"field-week": "týždeň",
	"field-week-relative+-1": "minulý týždeň",
	"field-week-relative+0": "tento týždeň",
	"field-week-relative+1": "budúci týždeň",
	"field-week-short": "týž.",
	"field-week-narrow": "týž.",
	"field-day": "deň",
	"field-day-relative+-2": "predvčerom",
	"field-day-relative+-1": "včera",
	"field-day-relative+0": "dnes",
	"field-day-relative+1": "zajtra",
	"field-day-relative+2": "pozajtra",
	"field-day-short": "d.",
	"field-day-narrow": "d.",
	"field-weekday": "deň týždňa",
	"field-sun-relative+-1": "minulú nedeľu",
	"field-sun-relative+0": "túto nedeľu",
	"field-sun-relative+1": "budúcu nedeľu",
	"field-sun-short-relative+-1": "minulú ned.",
	"field-sun-short-relative+0": "túto ned.",
	"field-sun-short-relative+1": "budúcu ned.",
	"field-sun-narrow-relative+-1": "minulú ne.",
	"field-sun-narrow-relative+0": "túto ne.",
	"field-sun-narrow-relative+1": "budúcu ne.",
	"field-mon-relative+-1": "minulý pondelok",
	"field-mon-relative+0": "tento pondelok",
	"field-mon-relative+1": "budúci pondelok",
	"field-mon-short-relative+-1": "minulý pond.",
	"field-mon-short-relative+0": "tento pond.",
	"field-mon-short-relative+1": "budúci pond.",
	"field-mon-narrow-relative+-1": "minulý po.",
	"field-mon-narrow-relative+0": "tento po.",
	"field-mon-narrow-relative+1": "budúci po.",
	"field-tue-relative+-1": "minulý utorok",
	"field-tue-relative+0": "tento utorok",
	"field-tue-relative+1": "budúci utorok",
	"field-tue-short-relative+-1": "minulý utor.",
	"field-tue-short-relative+0": "tento utor.",
	"field-tue-short-relative+1": "budúci utor.",
	"field-tue-narrow-relative+-1": "minulý ut.",
	"field-tue-narrow-relative+0": "tento ut.",
	"field-tue-narrow-relative+1": "budúci ut.",
	"field-wed-relative+-1": "minulú stredu",
	"field-wed-relative+0": "túto stredu",
	"field-wed-relative+1": "budúcu stredu",
	"field-wed-short-relative+-1": "minulú str.",
	"field-wed-short-relative+0": "túto str.",
	"field-wed-short-relative+1": "budúcu str.",
	"field-wed-narrow-relative+-1": "minulú st.",
	"field-wed-narrow-relative+0": "túto st.",
	"field-wed-narrow-relative+1": "budúcu st.",
	"field-thu-relative+-1": "minulý štvrtok",
	"field-thu-relative+0": "tento štvrtok",
	"field-thu-relative+1": "budúci štvrtok",
	"field-thu-short-relative+-1": "minulý št.",
	"field-thu-short-relative+0": "tento št.",
	"field-thu-short-relative+1": "budúci št.",
	"field-thu-narrow-relative+-1": "minulý št.",
	"field-thu-narrow-relative+0": "tento št.",
	"field-thu-narrow-relative+1": "budúci št.",
	"field-fri-relative+-1": "minulý piatok",
	"field-fri-relative+0": "tento piatok",
	"field-fri-relative+1": "budúci piatok",
	"field-fri-short-relative+-1": "minulý pi.",
	"field-fri-short-relative+0": "tento pi.",
	"field-fri-short-relative+1": "budúci pi.",
	"field-fri-narrow-relative+-1": "minulý pi.",
	"field-fri-narrow-relative+0": "tento pi.",
	"field-fri-narrow-relative+1": "budúci pi.",
	"field-sat-relative+-1": "minulú sobotu",
	"field-sat-relative+0": "túto sobotu",
	"field-sat-relative+1": "budúcu sobotu",
	"field-sat-short-relative+-1": "minulú so.",
	"field-sat-short-relative+0": "túto so.",
	"field-sat-short-relative+1": "budúcu so.",
	"field-sat-narrow-relative+-1": "minulú so.",
	"field-sat-narrow-relative+0": "túto so.",
	"field-sat-narrow-relative+1": "budúcu so.",
	"field-dayperiod": "časť dňa",
	"field-hour": "hodina",
	"field-hour-relative+0": "v tejto hodine",
	"field-hour-short": "h",
	"field-hour-narrow": "h",
	"field-minute": "minúta",
	"field-minute-relative+0": "v tejto minúte",
	"field-minute-short": "min",
	"field-minute-narrow": "min",
	"field-second": "sekunda",
	"field-second-relative+0": "teraz",
	"field-second-short": "s",
	"field-second-narrow": "s",
	"field-zone": "časové pásmo"
}
//end v1.x content
);