define(
//begin v1.x content
{
	"months-format-abbr": [
		"jan",
		"feb",
		"mar",
		"apr",
		"máj",
		"jún",
		"júl",
		"aug",
		"sep",
		"okt",
		"nov",
		"dec"
	],
	"months-format-narrow": [
		"j",
		"f",
		"m",
		"a",
		"m",
		"j",
		"j",
		"a",
		"s",
		"o",
		"n",
		"d"
	],
	"months-format-wide": [
		"januára",
		"februára",
		"marca",
		"apríla",
		"mája",
		"júna",
		"júla",
		"augusta",
		"septembra",
		"októbra",
		"novembra",
		"decembra"
	],
	"months-standAlone-abbr": [
		"jan",
		"feb",
		"mar",
		"apr",
		"máj",
		"jún",
		"júl",
		"aug",
		"sep",
		"okt",
		"nov",
		"dec"
	],
	"months-standAlone-narrow": [
		"j",
		"f",
		"m",
		"a",
		"m",
		"j",
		"j",
		"a",
		"s",
		"o",
		"n",
		"d"
	],
	"months-standAlone-wide": [
		"január",
		"február",
		"marec",
		"apríl",
		"máj",
		"jún",
		"júl",
		"august",
		"september",
		"október",
		"november",
		"december"
	],
	"days-format-abbr": [
		"ne",
		"po",
		"ut",
		"st",
		"št",
		"pi",
		"so"
	],
	"days-format-narrow": [
		"n",
		"p",
		"u",
		"s",
		"š",
		"p",
		"s"
	],
	"days-format-short": [
		"ne",
		"po",
		"ut",
		"st",
		"št",
		"pi",
		"so"
	],
	"days-format-wide": [
		"nedeľa",
		"pondelok",
		"utorok",
		"streda",
		"štvrtok",
		"piatok",
		"sobota"
	],
	"days-standAlone-abbr": [
		"ne",
		"po",
		"ut",
		"st",
		"št",
		"pi",
		"so"
	],
	"days-standAlone-narrow": [
		"n",
		"p",
		"u",
		"s",
		"š",
		"p",
		"s"
	],
	"days-standAlone-short": [
		"ne",
		"po",
		"ut",
		"st",
		"št",
		"pi",
		"so"
	],
	"days-standAlone-wide": [
		"nedeľa",
		"pondelok",
		"utorok",
		"streda",
		"štvrtok",
		"piatok",
		"sobota"
	],
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"1. štvrťrok",
		"2. štvrťrok",
		"3. štvrťrok",
		"4. štvrťrok"
	],
	"quarters-standAlone-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-standAlone-wide": [
		"1. štvrťrok",
		"2. štvrťrok",
		"3. štvrťrok",
		"4. štvrťrok"
	],
	"dayPeriods-format-abbr-midnight": "o poln.",
	"dayPeriods-format-abbr-am": "AM",
	"dayPeriods-format-abbr-noon": "napol.",
	"dayPeriods-format-abbr-pm": "PM",
	"dayPeriods-format-abbr-morning1": "ráno",
	"dayPeriods-format-abbr-morning2": "dopol.",
	"dayPeriods-format-abbr-afternoon1": "popol.",
	"dayPeriods-format-abbr-evening1": "večer",
	"dayPeriods-format-abbr-night1": "v noci",
	"dayPeriods-format-narrow-midnight": "o poln.",
	"dayPeriods-format-narrow-am": "AM",
	"dayPeriods-format-narrow-noon": "nap.",
	"dayPeriods-format-narrow-pm": "PM",
	"dayPeriods-format-narrow-morning1": "ráno",
	"dayPeriods-format-narrow-morning2": "dop.",
	"dayPeriods-format-narrow-afternoon1": "pop.",
	"dayPeriods-format-narrow-evening1": "več.",
	"dayPeriods-format-narrow-night1": "v n.",
	"dayPeriods-format-wide-midnight": "o polnoci",
	"dayPeriods-format-wide-am": "AM",
	"dayPeriods-format-wide-noon": "napoludnie",
	"dayPeriods-format-wide-pm": "PM",
	"dayPeriods-format-wide-morning1": "ráno",
	"dayPeriods-format-wide-morning2": "dopoludnia",
	"dayPeriods-format-wide-afternoon1": "popoludní",
	"dayPeriods-format-wide-evening1": "večer",
	"dayPeriods-format-wide-night1": "v noci",
	"dayPeriods-standAlone-abbr-midnight": "poln.",
	"dayPeriods-standAlone-abbr-am": "AM",
	"dayPeriods-standAlone-abbr-noon": "pol.",
	"dayPeriods-standAlone-abbr-pm": "PM",
	"dayPeriods-standAlone-abbr-morning1": "ráno",
	"dayPeriods-standAlone-abbr-morning2": "dopol.",
	"dayPeriods-standAlone-abbr-afternoon1": "popol.",
	"dayPeriods-standAlone-abbr-evening1": "večer",
	"dayPeriods-standAlone-abbr-night1": "noc",
	"dayPeriods-standAlone-narrow-midnight": "poln.",
	"dayPeriods-standAlone-narrow-am": "AM",
	"dayPeriods-standAlone-narrow-noon": "pol.",
	"dayPeriods-standAlone-narrow-pm": "PM",
	"dayPeriods-standAlone-narrow-morning1": "ráno",
	"dayPeriods-standAlone-narrow-morning2": "dop.",
	"dayPeriods-standAlone-narrow-afternoon1": "pop.",
	"dayPeriods-standAlone-narrow-evening1": "več.",
	"dayPeriods-standAlone-narrow-night1": "noc",
	"dayPeriods-standAlone-wide-midnight": "polnoc",
	"dayPeriods-standAlone-wide-am": "AM",
	"dayPeriods-standAlone-wide-noon": "poludnie",
	"dayPeriods-standAlone-wide-pm": "PM",
	"dayPeriods-standAlone-wide-morning1": "ráno",
	"dayPeriods-standAlone-wide-morning2": "dopoludnie",
	"dayPeriods-standAlone-wide-afternoon1": "popoludnie",
	"dayPeriods-standAlone-wide-evening1": "večer",
	"dayPeriods-standAlone-wide-night1": "noc",
	"eraNames": [
		"pred Kristom",
		"po Kristovi"
	],
	"eraAbbr": [
		"pred Kr.",
		"po Kr."
	],
	"dateFormat-full": "EEEE, d. MMMM y",
	"dateFormat-long": "d. MMMM y",
	"dateFormat-medium": "d. M. y",
	"dateFormat-short": "d. M. y",
	"timeFormat-full": "H:mm:ss zzzz",
	"timeFormat-long": "H:mm:ss z",
	"timeFormat-medium": "H:mm:ss",
	"timeFormat-short": "H:mm",
	"dateTimeFormat-full": "{1}, {0}",
	"dateTimeFormat-long": "{1}, {0}",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "d.",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E d.",
	"dateFormatItem-Ehm": "E h:mm a",
	"dateFormatItem-EHm": "E HH:mm",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "LLLL y G",
	"dateFormatItem-GyMMMd": "d. M. y G",
	"dateFormatItem-GyMMMEd": "E, d. M. y G",
	"dateFormatItem-GyMMMMd": "d. M. y G",
	"dateFormatItem-h": "h a",
	"dateFormatItem-H": "H",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-hmsv": "h:mm:ss a v",
	"dateFormatItem-Hmsv": "H:mm:ss v",
	"dateFormatItem-hmv": "h:mm a v",
	"dateFormatItem-Hmv": "H:mm v",
	"dateFormatItem-M": "L.",
	"dateFormatItem-Md": "d. M.",
	"dateFormatItem-MEd": "E d. M.",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d. M.",
	"dateFormatItem-MMMEd": "E d. M.",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-MMMMEd": "E d. MMMM",
	"dateFormatItem-MMMMW": "W. 'týždeň' 'v' MMM",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y",
	"dateFormatItem-yM": "M/y",
	"dateFormatItem-yMd": "d. M. y",
	"dateFormatItem-yMEd": "E d. M. y",
	"dateFormatItem-yMMM": "M/y",
	"dateFormatItem-yMMMd": "d. M. y",
	"dateFormatItem-yMMMEd": "E d. M. y",
	"dateFormatItem-yMMMM": "LLLL y",
	"dateFormatItem-yMMMMd": "d. MMMM y",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"dateFormatItem-yw": "w. 'týždeň' 'v' 'roku' y",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-era": "letopočet",
	"field-year": "rok",
	"field-year-relative+-1": "minulý rok",
	"field-year-relative+0": "tento rok",
	"field-year-relative+1": "budúci rok",
	"field-year-short": "r.",
	"field-year-narrow": "r.",
	"field-quarter": "štvrťrok",
	"field-quarter-relative+-1": "minulý štvrťrok",
	"field-quarter-relative+0": "tento štvrťrok",
	"field-quarter-relative+1": "budúci štvrťrok",
	"field-quarter-short": "Q",
	"field-quarter-short-relative+-1": "minulý štvrťr.",
	"field-quarter-short-relative+0": "tento štvrťr.",
	"field-quarter-short-relative+1": "budúci štvrťr.",
	"field-quarter-narrow": "Q",
	"field-quarter-narrow-relative+-1": "minulý štvrťr.",
	"field-quarter-narrow-relative+0": "tento štvrťr.",
	"field-quarter-narrow-relative+1": "budúci štvrťr.",
	"field-month": "mesiac",
	"field-month-relative+-1": "minulý mesiac",
	"field-month-relative+0": "tento mesiac",
	"field-month-relative+1": "budúci mesiac",
	"field-month-short": "mes.",
	"field-month-narrow": "mes.",
	"field-week": "týždeň",
	"field-week-relative+-1": "minulý týždeň",
	"field-week-relative+0": "tento týždeň",
	"field-week-relative+1": "budúci týždeň",
	"field-week-short": "týž.",
	"field-week-narrow": "týž.",
	"field-day": "deň",
	"field-day-relative+-2": "predvčerom",
	"field-day-relative+-1": "včera",
	"field-day-relative+0": "dnes",
	"field-day-relative+1": "zajtra",
	"field-day-relative+2": "pozajtra",
	"field-day-short": "d.",
	"field-day-narrow": "d.",
	"field-weekday": "deň týždňa",
	"field-sun-relative+-1": "minulú nedeľu",
	"field-sun-relative+0": "túto nedeľu",
	"field-sun-relative+1": "budúcu nedeľu",
	"field-sun-short-relative+-1": "minulú ned.",
	"field-sun-short-relative+0": "túto ned.",
	"field-sun-short-relative+1": "budúcu ned.",
	"field-sun-narrow-relative+-1": "minulú ne.",
	"field-sun-narrow-relative+0": "túto ne.",
	"field-sun-narrow-relative+1": "budúcu ne.",
	"field-mon-relative+-1": "minulý pondelok",
	"field-mon-relative+0": "tento pondelok",
	"field-mon-relative+1": "budúci pondelok",
	"field-mon-short-relative+-1": "minulý pond.",
	"field-mon-short-relative+0": "tento pond.",
	"field-mon-short-relative+1": "budúci pond.",
	"field-mon-narrow-relative+-1": "minulý po.",
	"field-mon-narrow-relative+0": "tento po.",
	"field-mon-narrow-relative+1": "budúci po.",
	"field-tue-relative+-1": "minulý utorok",
	"field-tue-relative+0": "tento utorok",
	"field-tue-relative+1": "budúci utorok",
	"field-tue-short-relative+-1": "minulý utor.",
	"field-tue-short-relative+0": "tento utor.",
	"field-tue-short-relative+1": "budúci utor.",
	"field-tue-narrow-relative+-1": "minulý ut.",
	"field-tue-narrow-relative+0": "tento ut.",
	"field-tue-narrow-relative+1": "budúci ut.",
	"field-wed-relative+-1": "minulú stredu",
	"field-wed-relative+0": "túto stredu",
	"field-wed-relative+1": "budúcu stredu",
	"field-wed-short-relative+-1": "minulú str.",
	"field-wed-short-relative+0": "túto str.",
	"field-wed-short-relative+1": "budúcu str.",
	"field-wed-narrow-relative+-1": "minulú st.",
	"field-wed-narrow-relative+0": "túto st.",
	"field-wed-narrow-relative+1": "budúcu st.",
	"field-thu-relative+-1": "minulý štvrtok",
	"field-thu-relative+0": "tento štvrtok",
	"field-thu-relative+1": "budúci štvrtok",
	"field-thu-short-relative+-1": "minulý št.",
	"field-thu-short-relative+0": "tento št.",
	"field-thu-short-relative+1": "budúci št.",
	"field-thu-narrow-relative+-1": "minulý št.",
	"field-thu-narrow-relative+0": "tento št.",
	"field-thu-narrow-relative+1": "budúci št.",
	"field-fri-relative+-1": "minulý piatok",
	"field-fri-relative+0": "tento piatok",
	"field-fri-relative+1": "budúci piatok",
	"field-fri-short-relative+-1": "minulý pi.",
	"field-fri-short-relative+0": "tento pi.",
	"field-fri-short-relative+1": "budúci pi.",
	"field-fri-narrow-relative+-1": "minulý pi.",
	"field-fri-narrow-relative+0": "tento pi.",
	"field-fri-narrow-relative+1": "budúci pi.",
	"field-sat-relative+-1": "minulú sobotu",
	"field-sat-relative+0": "túto sobotu",
	"field-sat-relative+1": "budúcu sobotu",
	"field-sat-short-relative+-1": "minulú so.",
	"field-sat-short-relative+0": "túto so.",
	"field-sat-short-relative+1": "budúcu so.",
	"field-sat-narrow-relative+-1": "minulú so.",
	"field-sat-narrow-relative+0": "túto so.",
	"field-sat-narrow-relative+1": "budúcu so.",
	"field-dayperiod": "časť dňa",
	"field-hour": "hodina",
	"field-hour-relative+0": "v tejto hodine",
	"field-hour-short": "h",
	"field-hour-narrow": "h",
	"field-minute": "minúta",
	"field-minute-relative+0": "v tejto minúte",
	"field-minute-short": "min",
	"field-minute-narrow": "min",
	"field-second": "sekunda",
	"field-second-relative+0": "teraz",
	"field-second-short": "s",
	"field-second-narrow": "s",
	"field-zone": "časové pásmo",
	"eraNarrow": [
		"pred Kr.",
		"po Kr."
	]
}
//end v1.x content
);