define(
//begin v1.x content
{
	"months-format-abbr": [
		"jan.",
		"feb.",
		"mar.",
		"apr.",
		"maj",
		"jun.",
		"jul.",
		"aug.",
		"sep.",
		"okt.",
		"nov.",
		"dec."
	],
	"months-format-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"months-format-wide": [
		"januar",
		"februar",
		"marts",
		"april",
		"maj",
		"juni",
		"juli",
		"august",
		"september",
		"oktober",
		"november",
		"december"
	],
	"months-standAlone-abbr": [
		"jan.",
		"feb.",
		"mar.",
		"apr.",
		"maj",
		"jun.",
		"jul.",
		"aug.",
		"sep.",
		"okt.",
		"nov.",
		"dec."
	],
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"months-standAlone-wide": [
		"januar",
		"februar",
		"marts",
		"april",
		"maj",
		"juni",
		"juli",
		"august",
		"september",
		"oktober",
		"november",
		"december"
	],
	"days-format-abbr": [
		"søn.",
		"man.",
		"tir.",
		"ons.",
		"tor.",
		"fre.",
		"lør."
	],
	"days-format-narrow": [
		"S",
		"M",
		"T",
		"O",
		"T",
		"F",
		"L"
	],
	"days-format-short": [
		"sø",
		"ma",
		"ti",
		"on",
		"to",
		"fr",
		"lø"
	],
	"days-format-wide": [
		"søndag",
		"mandag",
		"tirsdag",
		"onsdag",
		"torsdag",
		"fredag",
		"lørdag"
	],
	"days-standAlone-abbr": [
		"søn",
		"man",
		"tir",
		"ons",
		"tor",
		"fre",
		"lør"
	],
	"days-standAlone-narrow": [
		"S",
		"M",
		"T",
		"O",
		"T",
		"F",
		"L"
	],
	"days-standAlone-short": [
		"sø",
		"ma",
		"ti",
		"on",
		"to",
		"fr",
		"lø"
	],
	"days-standAlone-wide": [
		"søndag",
		"mandag",
		"tirsdag",
		"onsdag",
		"torsdag",
		"fredag",
		"lørdag"
	],
	"quarters-format-abbr": [
		"1. kvt.",
		"2. kvt.",
		"3. kvt.",
		"4. kvt."
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"1. kvartal",
		"2. kvartal",
		"3. kvartal",
		"4. kvartal"
	],
	"quarters-standAlone-abbr": [
		"1. kvt.",
		"2. kvt.",
		"3. kvt.",
		"4. kvt."
	],
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-standAlone-wide": [
		"1. kvartal",
		"2. kvartal",
		"3. kvartal",
		"4. kvartal"
	],
	"dayPeriods-format-abbr-midnight": "midnat",
	"dayPeriods-format-abbr-am": "AM",
	"dayPeriods-format-abbr-pm": "PM",
	"dayPeriods-format-abbr-morning1": "om morgenen",
	"dayPeriods-format-abbr-morning2": "om formiddagen",
	"dayPeriods-format-abbr-afternoon1": "om eftermiddagen",
	"dayPeriods-format-abbr-evening1": "om aftenen",
	"dayPeriods-format-abbr-night1": "om natten",
	"dayPeriods-format-narrow-midnight": "midnat",
	"dayPeriods-format-narrow-am": "a",
	"dayPeriods-format-narrow-pm": "p",
	"dayPeriods-format-narrow-morning1": "om morgenen",
	"dayPeriods-format-narrow-morning2": "om formiddagen",
	"dayPeriods-format-narrow-afternoon1": "om eftermiddagen",
	"dayPeriods-format-narrow-evening1": "om aftenen",
	"dayPeriods-format-narrow-night1": "om natten",
	"dayPeriods-format-wide-midnight": "midnat",
	"dayPeriods-format-wide-am": "AM",
	"dayPeriods-format-wide-pm": "PM",
	"dayPeriods-format-wide-morning1": "om morgenen",
	"dayPeriods-format-wide-morning2": "om formiddagen",
	"dayPeriods-format-wide-afternoon1": "om eftermiddagen",
	"dayPeriods-format-wide-evening1": "om aftenen",
	"dayPeriods-format-wide-night1": "om natten",
	"dayPeriods-standAlone-abbr-midnight": "midnat",
	"dayPeriods-standAlone-abbr-am": "AM",
	"dayPeriods-standAlone-abbr-pm": "PM",
	"dayPeriods-standAlone-abbr-morning1": "morgen",
	"dayPeriods-standAlone-abbr-morning2": "formiddag",
	"dayPeriods-standAlone-abbr-afternoon1": "eftermiddag",
	"dayPeriods-standAlone-abbr-evening1": "aften",
	"dayPeriods-standAlone-abbr-night1": "nat",
	"dayPeriods-standAlone-narrow-midnight": "midnat",
	"dayPeriods-standAlone-narrow-am": "AM",
	"dayPeriods-standAlone-narrow-pm": "PM",
	"dayPeriods-standAlone-narrow-morning1": "morgen",
	"dayPeriods-standAlone-narrow-morning2": "formiddag",
	"dayPeriods-standAlone-narrow-afternoon1": "eftermiddag",
	"dayPeriods-standAlone-narrow-evening1": "aften",
	"dayPeriods-standAlone-narrow-night1": "nat",
	"dayPeriods-standAlone-wide-midnight": "midnat",
	"dayPeriods-standAlone-wide-am": "AM",
	"dayPeriods-standAlone-wide-pm": "PM",
	"dayPeriods-standAlone-wide-morning1": "morgen",
	"dayPeriods-standAlone-wide-morning2": "formiddag",
	"dayPeriods-standAlone-wide-afternoon1": "eftermiddag",
	"dayPeriods-standAlone-wide-evening1": "aften",
	"dayPeriods-standAlone-wide-night1": "nat",
	"eraNames": [
		"f.Kr.",
		"e.Kr."
	],
	"eraAbbr": [
		"f.Kr.",
		"e.Kr."
	],
	"eraNarrow": [
		"fKr",
		"fvt",
		"eKr",
		"vt"
	],
	"dateFormat-full": "EEEE 'den' d. MMMM y",
	"dateFormat-long": "d. MMMM y",
	"dateFormat-medium": "d. MMM y",
	"dateFormat-short": "dd/MM/y",
	"timeFormat-full": "HH.mm.ss zzzz",
	"timeFormat-long": "HH.mm.ss z",
	"timeFormat-medium": "HH.mm.ss",
	"timeFormat-short": "HH.mm",
	"dateTimeFormat-full": "{1} 'kl'. {0}",
	"dateTimeFormat-long": "{1} 'kl'. {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "d.",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E 'den' d.",
	"dateFormatItem-Ehm": "E h.mm a",
	"dateFormatItem-EHm": "E HH.mm",
	"dateFormatItem-Ehms": "E h.mm.ss a",
	"dateFormatItem-EHms": "E HH.mm.ss",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-GyMMMd": "d. MMM y G",
	"dateFormatItem-GyMMMEd": "E d. MMM y G",
	"dateFormatItem-h": "h a",
	"dateFormatItem-H": "HH",
	"dateFormatItem-hm": "h.mm a",
	"dateFormatItem-Hm": "HH.mm",
	"dateFormatItem-hms": "h.mm.ss a",
	"dateFormatItem-Hms": "HH.mm.ss",
	"dateFormatItem-hmsv": "h.mm.ss a v",
	"dateFormatItem-Hmsv": "HH.mm.ss v",
	"dateFormatItem-hmv": "h.mm a v",
	"dateFormatItem-Hmv": "HH.mm v",
	"dateFormatItem-M": "M",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-MMdd": "dd/MM",
	"dateFormatItem-MMM": "MMM",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MMMEd": "E d. MMM",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-MMMMEd": "E d. MMMM",
	"dateFormatItem-MMMMW": "'uge' W 'i' MMM",
	"dateFormatItem-ms": "mm.ss",
	"dateFormatItem-y": "y",
	"dateFormatItem-yM": "M/y",
	"dateFormatItem-yMd": "d/M/y",
	"dateFormatItem-yMEd": "E d/M/y",
	"dateFormatItem-yMM": "MM/y",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yMMMd": "d. MMM y",
	"dateFormatItem-yMMMEd": "E d. MMM y",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"dateFormatItem-yw": "'uge' w 'i' y",
	"dateTimeFormats-appendItem-Day": "{0} ({2}: {1})",
	"dateTimeFormats-appendItem-Day-Of-Week": "{0} {1}",
	"dateTimeFormats-appendItem-Era": "{1} {0}",
	"dateTimeFormats-appendItem-Hour": "{0} ({2}: {1})",
	"dateTimeFormats-appendItem-Minute": "{0} ({2}: {1})",
	"dateTimeFormats-appendItem-Month": "{0} ({2}: {1})",
	"dateTimeFormats-appendItem-Quarter": "{0} ({2}: {1})",
	"dateTimeFormats-appendItem-Second": "{0} ({2}: {1})",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"dateTimeFormats-appendItem-Week": "{0} ({2}: {1})",
	"dateTimeFormats-appendItem-Year": "{1} {0}",
	"field-era": "æra",
	"field-year": "år",
	"field-year-relative+-1": "sidste år",
	"field-year-relative+0": "i år",
	"field-year-relative+1": "næste år",
	"field-year-short": "år",
	"field-year-short-relative+-1": "sidste år",
	"field-year-short-relative+0": "i år",
	"field-year-short-relative+1": "næste år",
	"field-year-narrow": "år",
	"field-year-narrow-relative+-1": "sidste år",
	"field-year-narrow-relative+0": "i år",
	"field-year-narrow-relative+1": "næste år",
	"field-quarter": "kvartal",
	"field-quarter-relative+-1": "sidste kvartal",
	"field-quarter-relative+0": "dette kvartal",
	"field-quarter-relative+1": "næste kvartal",
	"field-quarter-short": "kvt.",
	"field-quarter-short-relative+-1": "sidste kvt.",
	"field-quarter-short-relative+0": "dette kvt.",
	"field-quarter-short-relative+1": "næste kvt.",
	"field-quarter-narrow": "kvt.",
	"field-quarter-narrow-relative+-1": "sidste kvt.",
	"field-quarter-narrow-relative+0": "dette kvt.",
	"field-quarter-narrow-relative+1": "næste kvt.",
	"field-month": "måned",
	"field-month-relative+-1": "sidste måned",
	"field-month-relative+0": "denne måned",
	"field-month-relative+1": "næste måned",
	"field-month-short": "md.",
	"field-month-short-relative+-1": "sidste md.",
	"field-month-short-relative+0": "denne md.",
	"field-month-short-relative+1": "næste md.",
	"field-month-narrow": "md.",
	"field-month-narrow-relative+-1": "sidste md.",
	"field-month-narrow-relative+0": "denne md.",
	"field-month-narrow-relative+1": "næste md.",
	"field-week": "uge",
	"field-week-relative+-1": "sidste uge",
	"field-week-relative+0": "denne uge",
	"field-week-relative+1": "næste uge",
	"field-week-short": "uge",
	"field-week-short-relative+-1": "sidste uge",
	"field-week-short-relative+0": "denne uge",
	"field-week-short-relative+1": "næste uge",
	"field-week-narrow": "uge",
	"field-week-narrow-relative+-1": "sidste uge",
	"field-week-narrow-relative+0": "denne uge",
	"field-week-narrow-relative+1": "næste uge",
	"field-day": "dag",
	"field-day-relative+-2": "i forgårs",
	"field-day-relative+-1": "i går",
	"field-day-relative+0": "i dag",
	"field-day-relative+1": "i morgen",
	"field-day-relative+2": "i overmorgen",
	"field-day-short": "dag",
	"field-day-short-relative+-2": "i forgårs",
	"field-day-short-relative+-1": "i går",
	"field-day-short-relative+0": "i dag",
	"field-day-short-relative+1": "i morgen",
	"field-day-short-relative+2": "i overmorgen",
	"field-day-narrow": "dag",
	"field-day-narrow-relative+-2": "i forgårs",
	"field-day-narrow-relative+-1": "i går",
	"field-day-narrow-relative+0": "i dag",
	"field-day-narrow-relative+1": "i morgen",
	"field-day-narrow-relative+2": "i overmorgen",
	"field-weekday": "ugedag",
	"field-sun-relative+-1": "sidste søndag",
	"field-sun-relative+0": "på søndag",
	"field-sun-relative+1": "næste søndag",
	"field-sun-short-relative+-1": "sidste søn.",
	"field-sun-short-relative+0": "på søn.",
	"field-sun-short-relative+1": "næste søn.",
	"field-sun-narrow-relative+-1": "sidste sø.",
	"field-sun-narrow-relative+0": "på sø.",
	"field-sun-narrow-relative+1": "næste sø.",
	"field-mon-relative+-1": "sidste mandag",
	"field-mon-relative+0": "på mandag",
	"field-mon-relative+1": "næste mandag",
	"field-mon-short-relative+-1": "sidste man.",
	"field-mon-short-relative+0": "på man.",
	"field-mon-short-relative+1": "næste man.",
	"field-mon-narrow-relative+-1": "sidste ma.",
	"field-mon-narrow-relative+0": "på ma.",
	"field-mon-narrow-relative+1": "næste ma.",
	"field-tue-relative+-1": "sidste tirsdag",
	"field-tue-relative+0": "på tirsdag",
	"field-tue-relative+1": "næste tirsdag",
	"field-tue-short-relative+-1": "sidste tir.",
	"field-tue-short-relative+0": "på tir.",
	"field-tue-short-relative+1": "næste tir.",
	"field-tue-narrow-relative+-1": "sidste ti.",
	"field-tue-narrow-relative+0": "på ti.",
	"field-tue-narrow-relative+1": "næste ti.",
	"field-wed-relative+-1": "sidste onsdag",
	"field-wed-relative+0": "på onsdag",
	"field-wed-relative+1": "næste onsdag",
	"field-wed-short-relative+-1": "sidste ons.",
	"field-wed-short-relative+0": "på ons.",
	"field-wed-short-relative+1": "næste ons.",
	"field-wed-narrow-relative+-1": "sidste on.",
	"field-wed-narrow-relative+0": "på on.",
	"field-wed-narrow-relative+1": "næste on.",
	"field-thu-relative+-1": "sidste torsdag",
	"field-thu-relative+0": "på torsdag",
	"field-thu-relative+1": "næste torsdag",
	"field-thu-short-relative+-1": "sidste tor.",
	"field-thu-short-relative+0": "på tor.",
	"field-thu-short-relative+1": "næste tor.",
	"field-thu-narrow-relative+-1": "sidste to.",
	"field-thu-narrow-relative+0": "på to.",
	"field-thu-narrow-relative+1": "næste to.",
	"field-fri-relative+-1": "sidste fredag",
	"field-fri-relative+0": "på fredag",
	"field-fri-relative+1": "næste fredag",
	"field-fri-short-relative+-1": "sidste fre.",
	"field-fri-short-relative+0": "på fre.",
	"field-fri-short-relative+1": "næste fre.",
	"field-fri-narrow-relative+-1": "sidste fr.",
	"field-fri-narrow-relative+0": "på fr.",
	"field-fri-narrow-relative+1": "næste fr.",
	"field-sat-relative+-1": "sidste lørdag",
	"field-sat-relative+0": "på lørdag",
	"field-sat-relative+1": "næste lørdag",
	"field-sat-short-relative+-1": "sidste lør.",
	"field-sat-short-relative+0": "på lør.",
	"field-sat-short-relative+1": "næste lør.",
	"field-sat-narrow-relative+-1": "sidste lø.",
	"field-sat-narrow-relative+0": "på lø.",
	"field-sat-narrow-relative+1": "næste lø.",
	"field-dayperiod": "AM/PM",
	"field-hour": "time",
	"field-hour-relative+0": "i den kommende time",
	"field-hour-short": "t.",
	"field-hour-short-relative+0": "denne time",
	"field-hour-narrow": "t",
	"field-hour-narrow-relative+0": "denne time",
	"field-minute": "minut",
	"field-minute-relative+0": "i det kommende minut",
	"field-minute-short": "min.",
	"field-minute-short-relative+0": "denne minut",
	"field-minute-narrow": "min",
	"field-minute-narrow-relative+0": "denne minut",
	"field-second": "sekund",
	"field-second-relative+0": "nu",
	"field-second-short": "sek.",
	"field-second-narrow": "s",
	"field-zone": "tidszone"
}
//end v1.x content
);