define(
//begin v1.x content
{
	"eraAbbr": [
		"AM"
	],
	"field-era": "æra",
	"field-year": "år",
	"field-year-relative+-1": "sidste år",
	"field-year-relative+0": "i år",
	"field-year-relative+1": "næste år",
	"field-year-short": "år",
	"field-year-short-relative+-1": "sidste år",
	"field-year-short-relative+0": "i år",
	"field-year-short-relative+1": "næste år",
	"field-year-narrow": "år",
	"field-year-narrow-relative+-1": "sidste år",
	"field-year-narrow-relative+0": "i år",
	"field-year-narrow-relative+1": "næste år",
	"field-quarter": "kvartal",
	"field-quarter-relative+-1": "sidste kvartal",
	"field-quarter-relative+0": "dette kvartal",
	"field-quarter-relative+1": "næste kvartal",
	"field-quarter-short": "kvt.",
	"field-quarter-short-relative+-1": "sidste kvt.",
	"field-quarter-short-relative+0": "dette kvt.",
	"field-quarter-short-relative+1": "næste kvt.",
	"field-quarter-narrow": "kvt.",
	"field-quarter-narrow-relative+-1": "sidste kvt.",
	"field-quarter-narrow-relative+0": "dette kvt.",
	"field-quarter-narrow-relative+1": "næste kvt.",
	"field-month": "måned",
	"field-month-relative+-1": "sidste måned",
	"field-month-relative+0": "denne måned",
	"field-month-relative+1": "næste måned",
	"field-month-short": "md.",
	"field-month-short-relative+-1": "sidste md.",
	"field-month-short-relative+0": "denne md.",
	"field-month-short-relative+1": "næste md.",
	"field-month-narrow": "md.",
	"field-month-narrow-relative+-1": "sidste md.",
	"field-month-narrow-relative+0": "denne md.",
	"field-month-narrow-relative+1": "næste md.",
	"field-week": "uge",
	"field-week-relative+-1": "sidste uge",
	"field-week-relative+0": "denne uge",
	"field-week-relative+1": "næste uge",
	"field-week-short": "uge",
	"field-week-short-relative+-1": "sidste uge",
	"field-week-short-relative+0": "denne uge",
	"field-week-short-relative+1": "næste uge",
	"field-week-narrow": "uge",
	"field-week-narrow-relative+-1": "sidste uge",
	"field-week-narrow-relative+0": "denne uge",
	"field-week-narrow-relative+1": "næste uge",
	"field-day": "dag",
	"field-day-relative+-2": "i forgårs",
	"field-day-relative+-1": "i går",
	"field-day-relative+0": "i dag",
	"field-day-relative+1": "i morgen",
	"field-day-relative+2": "i overmorgen",
	"field-day-short": "dag",
	"field-day-short-relative+-2": "i forgårs",
	"field-day-short-relative+-1": "i går",
	"field-day-short-relative+0": "i dag",
	"field-day-short-relative+1": "i morgen",
	"field-day-short-relative+2": "i overmorgen",
	"field-day-narrow": "dag",
	"field-day-narrow-relative+-2": "i forgårs",
	"field-day-narrow-relative+-1": "i går",
	"field-day-narrow-relative+0": "i dag",
	"field-day-narrow-relative+1": "i morgen",
	"field-day-narrow-relative+2": "i overmorgen",
	"field-weekday": "ugedag",
	"field-sun-relative+-1": "sidste søndag",
	"field-sun-relative+0": "på søndag",
	"field-sun-relative+1": "næste søndag",
	"field-sun-short-relative+-1": "sidste søn.",
	"field-sun-short-relative+0": "på søn.",
	"field-sun-short-relative+1": "næste søn.",
	"field-sun-narrow-relative+-1": "sidste sø.",
	"field-sun-narrow-relative+0": "på sø.",
	"field-sun-narrow-relative+1": "næste sø.",
	"field-mon-relative+-1": "sidste mandag",
	"field-mon-relative+0": "på mandag",
	"field-mon-relative+1": "næste mandag",
	"field-mon-short-relative+-1": "sidste man.",
	"field-mon-short-relative+0": "på man.",
	"field-mon-short-relative+1": "næste man.",
	"field-mon-narrow-relative+-1": "sidste ma.",
	"field-mon-narrow-relative+0": "på ma.",
	"field-mon-narrow-relative+1": "næste ma.",
	"field-tue-relative+-1": "sidste tirsdag",
	"field-tue-relative+0": "på tirsdag",
	"field-tue-relative+1": "næste tirsdag",
	"field-tue-short-relative+-1": "sidste tir.",
	"field-tue-short-relative+0": "på tir.",
	"field-tue-short-relative+1": "næste tir.",
	"field-tue-narrow-relative+-1": "sidste ti.",
	"field-tue-narrow-relative+0": "på ti.",
	"field-tue-narrow-relative+1": "næste ti.",
	"field-wed-relative+-1": "sidste onsdag",
	"field-wed-relative+0": "på onsdag",
	"field-wed-relative+1": "næste onsdag",
	"field-wed-short-relative+-1": "sidste ons.",
	"field-wed-short-relative+0": "på ons.",
	"field-wed-short-relative+1": "næste ons.",
	"field-wed-narrow-relative+-1": "sidste on.",
	"field-wed-narrow-relative+0": "på on.",
	"field-wed-narrow-relative+1": "næste on.",
	"field-thu-relative+-1": "sidste torsdag",
	"field-thu-relative+0": "på torsdag",
	"field-thu-relative+1": "næste torsdag",
	"field-thu-short-relative+-1": "sidste tor.",
	"field-thu-short-relative+0": "på tor.",
	"field-thu-short-relative+1": "næste tor.",
	"field-thu-narrow-relative+-1": "sidste to.",
	"field-thu-narrow-relative+0": "på to.",
	"field-thu-narrow-relative+1": "næste to.",
	"field-fri-relative+-1": "sidste fredag",
	"field-fri-relative+0": "på fredag",
	"field-fri-relative+1": "næste fredag",
	"field-fri-short-relative+-1": "sidste fre.",
	"field-fri-short-relative+0": "på fre.",
	"field-fri-short-relative+1": "næste fre.",
	"field-fri-narrow-relative+-1": "sidste fr.",
	"field-fri-narrow-relative+0": "på fr.",
	"field-fri-narrow-relative+1": "næste fr.",
	"field-sat-relative+-1": "sidste lørdag",
	"field-sat-relative+0": "på lørdag",
	"field-sat-relative+1": "næste lørdag",
	"field-sat-short-relative+-1": "sidste lør.",
	"field-sat-short-relative+0": "på lør.",
	"field-sat-short-relative+1": "næste lør.",
	"field-sat-narrow-relative+-1": "sidste lø.",
	"field-sat-narrow-relative+0": "på lø.",
	"field-sat-narrow-relative+1": "næste lø.",
	"field-dayperiod": "AM/PM",
	"field-hour": "time",
	"field-hour-relative+0": "i den kommende time",
	"field-hour-short": "t.",
	"field-hour-short-relative+0": "denne time",
	"field-hour-narrow": "t",
	"field-hour-narrow-relative+0": "denne time",
	"field-minute": "minut",
	"field-minute-relative+0": "i det kommende minut",
	"field-minute-short": "min.",
	"field-minute-short-relative+0": "denne minut",
	"field-minute-narrow": "min",
	"field-minute-narrow-relative+0": "denne minut",
	"field-second": "sekund",
	"field-second-relative+0": "nu",
	"field-second-short": "sek.",
	"field-second-narrow": "s",
	"field-zone": "tidszone",
	"days-format-abbr": [
		"søn.",
		"man.",
		"tir.",
		"ons.",
		"tor.",
		"fre.",
		"lør."
	],
	"days-format-narrow": [
		"S",
		"M",
		"T",
		"O",
		"T",
		"F",
		"L"
	],
	"days-format-short": [
		"sø",
		"ma",
		"ti",
		"on",
		"to",
		"fr",
		"lø"
	],
	"days-format-wide": [
		"søndag",
		"mandag",
		"tirsdag",
		"onsdag",
		"torsdag",
		"fredag",
		"lørdag"
	],
	"days-standAlone-abbr": [
		"søn",
		"man",
		"tir",
		"ons",
		"tor",
		"fre",
		"lør"
	],
	"days-standAlone-narrow": [
		"S",
		"M",
		"T",
		"O",
		"T",
		"F",
		"L"
	],
	"days-standAlone-short": [
		"sø",
		"ma",
		"ti",
		"on",
		"to",
		"fr",
		"lø"
	],
	"days-standAlone-wide": [
		"søndag",
		"mandag",
		"tirsdag",
		"onsdag",
		"torsdag",
		"fredag",
		"lørdag"
	],
	"quarters-format-abbr": [
		"1. kvt.",
		"2. kvt.",
		"3. kvt.",
		"4. kvt."
	],
	"quarters-format-wide": [
		"1. kvartal",
		"2. kvartal",
		"3. kvartal",
		"4. kvartal"
	],
	"quarters-standAlone-abbr": [
		"1. kvt.",
		"2. kvt.",
		"3. kvt.",
		"4. kvt."
	],
	"quarters-standAlone-wide": [
		"1. kvartal",
		"2. kvartal",
		"3. kvartal",
		"4. kvartal"
	],
	"dayPeriods-format-narrow-am": "a",
	"dayPeriods-format-narrow-pm": "p",
	"dateFormat-full": "EEEE d. MMMM y G",
	"dateFormat-long": "d. MMMM y G",
	"dateFormat-medium": "d. MMM y G",
	"dateFormat-short": "d/M/y",
	"dateFormatItem-d": "d.",
	"dateFormatItem-Ed": "E 'd'. d.",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-GyMMMd": "d. MMM y G",
	"dateFormatItem-GyMMMEd": "E d. MMM y G",
	"dateFormatItem-hm": "h.mm a",
	"dateFormatItem-Hm": "HH.mm",
	"dateFormatItem-hms": "h.mm.ss a",
	"dateFormatItem-Hms": "HH.mm.ss",
	"dateFormatItem-M": "M",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-MMM": "MMM",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MMMEd": "E d. MMM",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-ms": "mm.ss",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-yyyyM": "M/y G",
	"dateFormatItem-yyyyMd": "d/M/y G",
	"dateFormatItem-yyyyMEd": "E d/M/y G",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-yyyyMMMd": "d. MMM y G",
	"dateFormatItem-yyyyMMMEd": "E d. MMM y G",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"timeFormat-full": "HH.mm.ss zzzz",
	"timeFormat-long": "HH.mm.ss z",
	"timeFormat-medium": "HH.mm.ss",
	"timeFormat-short": "HH.mm"
}
//end v1.x content
);