define(
//begin v1.x content
{
	"months-format-abbr": [
		"Jan.",
		"Feb.",
		"März",
		"Apr.",
		"Mai",
		"Juni",
		"Juli",
		"Aug.",
		"Sep.",
		"Okt.",
		"Nov.",
		"Dez."
	],
	"months-format-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"months-format-wide": [
		"Januar",
		"Februar",
		"März",
		"April",
		"Mai",
		"Juni",
		"Juli",
		"August",
		"September",
		"Oktober",
		"November",
		"Dezember"
	],
	"months-standAlone-abbr": [
		"Jan",
		"Feb",
		"Mär",
		"Apr",
		"Mai",
		"Jun",
		"Jul",
		"Aug",
		"Sep",
		"Okt",
		"Nov",
		"Dez"
	],
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"months-standAlone-wide": [
		"Januar",
		"Februar",
		"März",
		"April",
		"Mai",
		"Juni",
		"Juli",
		"August",
		"September",
		"Oktober",
		"November",
		"Dezember"
	],
	"days-format-abbr": [
		"So.",
		"Mo.",
		"Di.",
		"Mi.",
		"Do.",
		"Fr.",
		"Sa."
	],
	"days-format-narrow": [
		"S",
		"M",
		"D",
		"M",
		"D",
		"F",
		"S"
	],
	"days-format-short": [
		"So.",
		"Mo.",
		"Di.",
		"Mi.",
		"Do.",
		"Fr.",
		"Sa."
	],
	"days-format-wide": [
		"Sonntag",
		"Montag",
		"Dienstag",
		"Mittwoch",
		"Donnerstag",
		"Freitag",
		"Samstag"
	],
	"days-standAlone-abbr": [
		"So",
		"Mo",
		"Di",
		"Mi",
		"Do",
		"Fr",
		"Sa"
	],
	"days-standAlone-narrow": [
		"S",
		"M",
		"D",
		"M",
		"D",
		"F",
		"S"
	],
	"days-standAlone-short": [
		"So.",
		"Mo.",
		"Di.",
		"Mi.",
		"Do.",
		"Fr.",
		"Sa."
	],
	"days-standAlone-wide": [
		"Sonntag",
		"Montag",
		"Dienstag",
		"Mittwoch",
		"Donnerstag",
		"Freitag",
		"Samstag"
	],
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"1. Quartal",
		"2. Quartal",
		"3. Quartal",
		"4. Quartal"
	],
	"quarters-standAlone-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-standAlone-wide": [
		"1. Quartal",
		"2. Quartal",
		"3. Quartal",
		"4. Quartal"
	],
	"dayPeriods-format-abbr-midnight": "Mitternacht",
	"dayPeriods-format-abbr-am": "vorm.",
	"dayPeriods-format-abbr-pm": "nachm.",
	"dayPeriods-format-abbr-morning1": "morgens",
	"dayPeriods-format-abbr-morning2": "vormittags",
	"dayPeriods-format-abbr-afternoon1": "mittags",
	"dayPeriods-format-abbr-afternoon2": "nachmittags",
	"dayPeriods-format-abbr-evening1": "abends",
	"dayPeriods-format-abbr-night1": "nachts",
	"dayPeriods-format-narrow-midnight": "Mitternacht",
	"dayPeriods-format-narrow-am": "vm.",
	"dayPeriods-format-narrow-pm": "nm.",
	"dayPeriods-format-narrow-morning1": "morgens",
	"dayPeriods-format-narrow-morning2": "vormittags",
	"dayPeriods-format-narrow-afternoon1": "mittags",
	"dayPeriods-format-narrow-afternoon2": "nachmittags",
	"dayPeriods-format-narrow-evening1": "abends",
	"dayPeriods-format-narrow-night1": "nachts",
	"dayPeriods-format-wide-midnight": "Mitternacht",
	"dayPeriods-format-wide-am": "vorm.",
	"dayPeriods-format-wide-pm": "nachm.",
	"dayPeriods-format-wide-morning1": "morgens",
	"dayPeriods-format-wide-morning2": "vormittags",
	"dayPeriods-format-wide-afternoon1": "mittags",
	"dayPeriods-format-wide-afternoon2": "nachmittags",
	"dayPeriods-format-wide-evening1": "abends",
	"dayPeriods-format-wide-night1": "nachts",
	"dayPeriods-standAlone-abbr-midnight": "Mitternacht",
	"dayPeriods-standAlone-abbr-am": "vorm.",
	"dayPeriods-standAlone-abbr-pm": "nachm.",
	"dayPeriods-standAlone-abbr-morning1": "Morgen",
	"dayPeriods-standAlone-abbr-morning2": "Vormittag",
	"dayPeriods-standAlone-abbr-afternoon1": "Mittag",
	"dayPeriods-standAlone-abbr-afternoon2": "Nachmittag",
	"dayPeriods-standAlone-abbr-evening1": "Abend",
	"dayPeriods-standAlone-abbr-night1": "Nacht",
	"dayPeriods-standAlone-narrow-midnight": "Mitternacht",
	"dayPeriods-standAlone-narrow-am": "vorm.",
	"dayPeriods-standAlone-narrow-pm": "nachm.",
	"dayPeriods-standAlone-narrow-morning1": "Morgen",
	"dayPeriods-standAlone-narrow-morning2": "Vormittag",
	"dayPeriods-standAlone-narrow-afternoon1": "Mittag",
	"dayPeriods-standAlone-narrow-afternoon2": "Nachmittag",
	"dayPeriods-standAlone-narrow-evening1": "Abend",
	"dayPeriods-standAlone-narrow-night1": "Nacht",
	"dayPeriods-standAlone-wide-midnight": "Mitternacht",
	"dayPeriods-standAlone-wide-am": "vorm.",
	"dayPeriods-standAlone-wide-pm": "nachm.",
	"dayPeriods-standAlone-wide-morning1": "Morgen",
	"dayPeriods-standAlone-wide-morning2": "Vormittag",
	"dayPeriods-standAlone-wide-afternoon1": "Mittag",
	"dayPeriods-standAlone-wide-afternoon2": "Nachmittag",
	"dayPeriods-standAlone-wide-evening1": "Abend",
	"dayPeriods-standAlone-wide-night1": "Nacht",
	"eraNames": [
		"v. Chr.",
		"n. Chr."
	],
	"eraAbbr": [
		"v. Chr.",
		"n. Chr."
	],
	"eraNarrow": [
		"v. Chr.",
		"v. u. Z.",
		"n. Chr.",
		"u. Z."
	],
	"dateFormat-full": "EEEE, d. MMMM y",
	"dateFormat-long": "d. MMMM y",
	"dateFormat-medium": "dd.MM.y",
	"dateFormat-short": "dd.MM.yy",
	"timeFormat-full": "HH:mm:ss zzzz",
	"timeFormat-long": "HH:mm:ss z",
	"timeFormat-medium": "HH:mm:ss",
	"timeFormat-short": "HH:mm",
	"dateTimeFormat-full": "{1} 'um' {0}",
	"dateTimeFormat-long": "{1} 'um' {0}",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-d": "d",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E, d.",
	"dateFormatItem-Ehm": "E h:mm a",
	"dateFormatItem-EHm": "E, HH:mm",
	"dateFormatItem-Ehms": "E, h:mm:ss a",
	"dateFormatItem-EHms": "E, HH:mm:ss",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-GyMMMd": "d. MMM y G",
	"dateFormatItem-GyMMMEd": "E, d. MMM y G",
	"dateFormatItem-h": "h 'Uhr' a",
	"dateFormatItem-H": "HH 'Uhr'",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hmsv": "h:mm:ss a v",
	"dateFormatItem-Hmsv": "HH:mm:ss v",
	"dateFormatItem-hmv": "h:mm a v",
	"dateFormatItem-Hmv": "HH:mm v",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-MEd": "E, d.M.",
	"dateFormatItem-MMd": "d.MM.",
	"dateFormatItem-MMdd": "dd.MM.",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-MMMMEd": "E, d. MMMM",
	"dateFormatItem-MMMMW": "'Woche' W 'im' MMM",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y",
	"dateFormatItem-yM": "M.y",
	"dateFormatItem-yMd": "d.M.y",
	"dateFormatItem-yMEd": "E, d.M.y",
	"dateFormatItem-yMM": "MM.y",
	"dateFormatItem-yMMdd": "dd.MM.y",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yMMMd": "d. MMM y",
	"dateFormatItem-yMMMEd": "E, d. MMM y",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"dateFormatItem-yw": "'Woche' w 'des' 'Jahres' y",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-era": "Epoche",
	"field-year": "Jahr",
	"field-year-relative+-1": "letztes Jahr",
	"field-year-relative+0": "dieses Jahr",
	"field-year-relative+1": "nächstes Jahr",
	"field-year-short": "Jahr",
	"field-year-short-relative+-1": "letztes Jahr",
	"field-year-short-relative+0": "dieses Jahr",
	"field-year-short-relative+1": "nächstes Jahr",
	"field-year-narrow": "J",
	"field-year-narrow-relative+-1": "letztes Jahr",
	"field-year-narrow-relative+0": "dieses Jahr",
	"field-year-narrow-relative+1": "nächstes Jahr",
	"field-quarter": "Quartal",
	"field-quarter-relative+-1": "letztes Quartal",
	"field-quarter-relative+0": "dieses Quartal",
	"field-quarter-relative+1": "nächstes Quartal",
	"field-quarter-short": "Quart.",
	"field-quarter-narrow": "Q",
	"field-quarter-narrow-relative+-1": "letztes Quartal",
	"field-quarter-narrow-relative+0": "dieses Quartal",
	"field-quarter-narrow-relative+1": "nächstes Quartal",
	"field-month": "Monat",
	"field-month-relative+-1": "letzten Monat",
	"field-month-relative+0": "diesen Monat",
	"field-month-relative+1": "nächsten Monat",
	"field-month-short": "Monat",
	"field-month-short-relative+-1": "letzten Monat",
	"field-month-short-relative+0": "diesen Monat",
	"field-month-short-relative+1": "nächsten Monat",
	"field-month-narrow": "M",
	"field-month-narrow-relative+-1": "letzten Monat",
	"field-month-narrow-relative+0": "diesen Monat",
	"field-month-narrow-relative+1": "nächsten Monat",
	"field-week": "Woche",
	"field-week-relative+-1": "letzte Woche",
	"field-week-relative+0": "diese Woche",
	"field-week-relative+1": "nächste Woche",
	"field-week-short": "Woche",
	"field-week-short-relative+-1": "letzte Woche",
	"field-week-short-relative+0": "diese Woche",
	"field-week-short-relative+1": "nächste Woche",
	"field-week-narrow": "W",
	"field-week-narrow-relative+-1": "letzte Woche",
	"field-week-narrow-relative+0": "diese Woche",
	"field-week-narrow-relative+1": "nächste Woche",
	"field-day": "Tag",
	"field-day-relative+-2": "vorgestern",
	"field-day-relative+-1": "gestern",
	"field-day-relative+0": "heute",
	"field-day-relative+1": "morgen",
	"field-day-relative+2": "übermorgen",
	"field-day-short": "Tag",
	"field-day-short-relative+-2": "vorgestern",
	"field-day-short-relative+-1": "gestern",
	"field-day-short-relative+0": "heute",
	"field-day-short-relative+1": "morgen",
	"field-day-short-relative+2": "übermorgen",
	"field-day-narrow": "Tag",
	"field-day-narrow-relative+-2": "vorgestern",
	"field-day-narrow-relative+-1": "gestern",
	"field-day-narrow-relative+0": "heute",
	"field-day-narrow-relative+1": "morgen",
	"field-day-narrow-relative+2": "übermorgen",
	"field-weekday": "Wochentag",
	"field-sun-relative+-1": "letzten Sonntag",
	"field-sun-relative+0": "diesen Sonntag",
	"field-sun-relative+1": "nächsten Sonntag",
	"field-sun-short-relative+-1": "letzten So.",
	"field-sun-short-relative+0": "diesen So.",
	"field-sun-short-relative+1": "nächsten So.",
	"field-sun-narrow-relative+-1": "letzten So.",
	"field-sun-narrow-relative+0": "diesen So.",
	"field-sun-narrow-relative+1": "nächsten So.",
	"field-mon-relative+-1": "letzten Montag",
	"field-mon-relative+0": "diesen Montag",
	"field-mon-relative+1": "nächsten Montag",
	"field-mon-short-relative+-1": "letzten Mo.",
	"field-mon-short-relative+0": "diesen Mo.",
	"field-mon-short-relative+1": "nächsten Mo.",
	"field-mon-narrow-relative+-1": "letzten Mo.",
	"field-mon-narrow-relative+0": "diesen Mo.",
	"field-mon-narrow-relative+1": "nächsten Mo.",
	"field-tue-relative+-1": "letzten Dienstag",
	"field-tue-relative+0": "diesen Dienstag",
	"field-tue-relative+1": "nächsten Dienstag",
	"field-tue-short-relative+-1": "letzten Di.",
	"field-tue-short-relative+0": "diesen Di.",
	"field-tue-short-relative+1": "nächsten Di.",
	"field-tue-narrow-relative+-1": "letzten Di.",
	"field-tue-narrow-relative+0": "diesen Di.",
	"field-tue-narrow-relative+1": "nächsten Di.",
	"field-wed-relative+-1": "letzten Mittwoch",
	"field-wed-relative+0": "diesen Mittwoch",
	"field-wed-relative+1": "nächsten Mittwoch",
	"field-wed-short-relative+-1": "letzten Mi.",
	"field-wed-short-relative+0": "diesen Mi.",
	"field-wed-short-relative+1": "nächsten Mi.",
	"field-wed-narrow-relative+-1": "letzten Mi.",
	"field-wed-narrow-relative+0": "diesen Mi.",
	"field-wed-narrow-relative+1": "nächsten Mi.",
	"field-thu-relative+-1": "letzten Donnerstag",
	"field-thu-relative+0": "diesen Donnerstag",
	"field-thu-relative+1": "nächsten Donnerstag",
	"field-thu-short-relative+-1": "letzten Do.",
	"field-thu-short-relative+0": "diesen Do.",
	"field-thu-short-relative+1": "nächsten Do.",
	"field-thu-narrow-relative+-1": "letzten Do.",
	"field-thu-narrow-relative+0": "diesen Do.",
	"field-thu-narrow-relative+1": "nächsten Do.",
	"field-fri-relative+-1": "letzten Freitag",
	"field-fri-relative+0": "diesen Freitag",
	"field-fri-relative+1": "nächsten Freitag",
	"field-fri-short-relative+-1": "letzten Fr.",
	"field-fri-short-relative+0": "diesen Fr.",
	"field-fri-short-relative+1": "nächsten Fr.",
	"field-fri-narrow-relative+-1": "letzten Fr.",
	"field-fri-narrow-relative+0": "diesen Fr.",
	"field-fri-narrow-relative+1": "nächsten Fr.",
	"field-sat-relative+-1": "letzten Samstag",
	"field-sat-relative+0": "diesen Samstag",
	"field-sat-relative+1": "nächsten Samstag",
	"field-sat-short-relative+-1": "letzten Sa.",
	"field-sat-short-relative+0": "diesen Sa.",
	"field-sat-short-relative+1": "nächsten Sa.",
	"field-sat-narrow-relative+-1": "letzten Sa.",
	"field-sat-narrow-relative+0": "diesen Sa.",
	"field-sat-narrow-relative+1": "nächsten Sa.",
	"field-dayperiod": "Tageshälfte",
	"field-hour": "Stunde",
	"field-hour-relative+0": "in dieser Stunde",
	"field-hour-short": "Std.",
	"field-hour-short-relative+0": "in dieser Stunde",
	"field-hour-narrow": "Std.",
	"field-hour-narrow-relative+0": "in dieser Stunde",
	"field-minute": "Minute",
	"field-minute-relative+0": "in dieser Minute",
	"field-minute-short": "Min.",
	"field-minute-short-relative+0": "in dieser Minute",
	"field-minute-narrow": "Min.",
	"field-minute-narrow-relative+0": "in dieser Minute",
	"field-second": "Sekunde",
	"field-second-relative+0": "jetzt",
	"field-second-short": "Sek.",
	"field-second-narrow": "Sek.",
	"field-zone": "Zeitzone"
}
//end v1.x content
);