define(
//begin v1.x content
{
	"dateFormat-full": "EEEE, 'ngày' dd 'tháng' MM 'năm' y G",
	"dateFormat-long": "'Ngày' dd 'tháng' M 'năm' y G",
	"dateFormat-medium": "dd-MM-y G",
	"dateFormat-short": "dd/MM/y GGGGG",
	"dateTimeFormat-full": "{1} 'lúc' {0}",
	"dateTimeFormat-long": "{1} 'lúc' {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "'Ngày' dd",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E, dd",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-GyMMMd": "d MMM, y G",
	"dateFormatItem-GyMMMEd": "E, d MMM, y G",
	"dateFormatItem-h": "h'h' a",
	"dateFormatItem-H": "HH'h'",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "dd-M",
	"dateFormatItem-MEd": "E, dd-M",
	"dateFormatItem-MMdd": "dd-MM",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateFormatItem-MMMMd": "dd MMMM",
	"dateFormatItem-MMMMEd": "E, dd MMMM",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-yyyyM": "M/y G",
	"dateFormatItem-yyyyMd": "d/M/y G",
	"dateFormatItem-yyyyMEd": "E, d/M/y GGGGG",
	"dateFormatItem-yyyyMM": "MM-y G",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-yyyyMMMd": "d MMM, y G",
	"dateFormatItem-yyyyMMMEd": "E, d MMM, y G",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"field-era": "Thời đại",
	"field-year": "Năm",
	"field-year-relative+-1": "năm ngoái",
	"field-year-relative+0": "năm nay",
	"field-year-relative+1": "năm sau",
	"field-year-short": "Năm",
	"field-year-short-relative+-1": "năm ngoái",
	"field-year-short-relative+0": "năm nay",
	"field-year-short-relative+1": "năm sau",
	"field-year-narrow": "Năm",
	"field-year-narrow-relative+-1": "năm ngoái",
	"field-year-narrow-relative+0": "năm nay",
	"field-year-narrow-relative+1": "năm sau",
	"field-quarter": "Quý",
	"field-quarter-relative+-1": "quý trước",
	"field-quarter-relative+0": "quý này",
	"field-quarter-relative+1": "quý sau",
	"field-quarter-short": "Quý",
	"field-quarter-short-relative+-1": "quý trước",
	"field-quarter-short-relative+0": "quý này",
	"field-quarter-short-relative+1": "quý sau",
	"field-quarter-narrow": "Quý",
	"field-quarter-narrow-relative+-1": "quý trước",
	"field-quarter-narrow-relative+0": "quý này",
	"field-quarter-narrow-relative+1": "quý sau",
	"field-month": "Tháng",
	"field-month-relative+-1": "tháng trước",
	"field-month-relative+0": "tháng này",
	"field-month-relative+1": "tháng sau",
	"field-month-short": "Tháng",
	"field-month-short-relative+-1": "tháng trước",
	"field-month-short-relative+0": "tháng này",
	"field-month-short-relative+1": "tháng sau",
	"field-month-narrow": "Tháng",
	"field-month-narrow-relative+-1": "tháng trước",
	"field-month-narrow-relative+0": "tháng này",
	"field-month-narrow-relative+1": "tháng sau",
	"field-week": "Tuần",
	"field-week-relative+-1": "tuần trước",
	"field-week-relative+0": "tuần này",
	"field-week-relative+1": "tuần sau",
	"field-week-short": "Tuần",
	"field-week-short-relative+-1": "tuần trước",
	"field-week-short-relative+0": "tuần này",
	"field-week-short-relative+1": "tuần sau",
	"field-week-narrow": "Tuần",
	"field-week-narrow-relative+-1": "tuần trước",
	"field-week-narrow-relative+0": "tuần này",
	"field-week-narrow-relative+1": "tuần sau",
	"field-day": "Ngày",
	"field-day-relative+-2": "Hôm kia",
	"field-day-relative+-1": "Hôm qua",
	"field-day-relative+0": "Hôm nay",
	"field-day-relative+1": "Ngày mai",
	"field-day-relative+2": "Ngày kia",
	"field-day-short": "Ngày",
	"field-day-narrow": "Ngày",
	"field-weekday": "Ngày trong tuần",
	"field-sun-relative+-1": "Chủ Nhật tuần trước",
	"field-sun-relative+0": "Chủ Nhật tuần này",
	"field-sun-relative+1": "Chủ Nhật tuần sau",
	"field-sun-short-relative+-1": "Chủ Nhật tuần trước",
	"field-sun-short-relative+0": "Chủ Nhật tuần này",
	"field-sun-short-relative+1": "Chủ Nhật tuần sau",
	"field-sun-narrow-relative+-1": "Chủ Nhật tuần trước",
	"field-sun-narrow-relative+0": "Chủ Nhật tuần này",
	"field-sun-narrow-relative+1": "Chủ Nhật tuần sau",
	"field-mon-relative+-1": "Thứ Hai tuần trước",
	"field-mon-relative+0": "Thứ Hai tuần này",
	"field-mon-relative+1": "Thứ Hai tuần sau",
	"field-mon-short-relative+-1": "Thứ Hai tuần trước",
	"field-mon-short-relative+0": "Thứ Hai tuần này",
	"field-mon-short-relative+1": "Thứ Hai tuần sau",
	"field-mon-narrow-relative+-1": "Thứ Hai tuần trước",
	"field-mon-narrow-relative+0": "Thứ Hai tuần này",
	"field-mon-narrow-relative+1": "Thứ Hai tuần sau",
	"field-tue-relative+-1": "Thứ Ba tuần trước",
	"field-tue-relative+0": "Thứ Ba tuần này",
	"field-tue-relative+1": "Thứ Ba tuần sau",
	"field-tue-short-relative+-1": "Thứ Ba tuần trước",
	"field-tue-short-relative+0": "Thứ Ba tuần này",
	"field-tue-short-relative+1": "Thứ Ba tuần sau",
	"field-tue-narrow-relative+-1": "Thứ Ba tuần trước",
	"field-tue-narrow-relative+0": "Thứ Ba tuần này",
	"field-tue-narrow-relative+1": "Thứ Ba tuần sau",
	"field-wed-relative+-1": "Thứ Tư tuần trước",
	"field-wed-relative+0": "Thứ Tư tuần này",
	"field-wed-relative+1": "Thứ Tư tuần sau",
	"field-wed-short-relative+-1": "Thứ Tư tuần trước",
	"field-wed-short-relative+0": "Thứ Tư tuần này",
	"field-wed-short-relative+1": "Thứ Tư tuần sau",
	"field-wed-narrow-relative+-1": "Thứ Tư tuần trước",
	"field-wed-narrow-relative+0": "Thứ Tư tuần này",
	"field-wed-narrow-relative+1": "Thứ Tư tuần sau",
	"field-thu-relative+-1": "Thứ Năm tuần trước",
	"field-thu-relative+0": "Thứ Năm tuần này",
	"field-thu-relative+1": "Thứ Năm tuần sau",
	"field-thu-short-relative+-1": "Thứ Năm tuần trước",
	"field-thu-short-relative+0": "Thứ Năm tuần này",
	"field-thu-short-relative+1": "Thứ Năm tuần sau",
	"field-thu-narrow-relative+-1": "Thứ Năm tuần trước",
	"field-thu-narrow-relative+0": "Thứ Năm tuần này",
	"field-thu-narrow-relative+1": "Thứ Năm tuần sau",
	"field-fri-relative+-1": "Thứ Sáu tuần trước",
	"field-fri-relative+0": "Thứ Sáu tuần này",
	"field-fri-relative+1": "Thứ Sáu tuần sau",
	"field-fri-short-relative+-1": "Thứ Sáu tuần trước",
	"field-fri-short-relative+0": "Thứ Sáu tuần này",
	"field-fri-short-relative+1": "Thứ Sáu tuần sau",
	"field-fri-narrow-relative+-1": "Thứ Sáu tuần trước",
	"field-fri-narrow-relative+0": "Thứ Sáu tuần này",
	"field-fri-narrow-relative+1": "Thứ Sáu tuần sau",
	"field-sat-relative+-1": "Thứ Bảy tuần trước",
	"field-sat-relative+0": "Thứ Bảy tuần này",
	"field-sat-relative+1": "Thứ Bảy tuần sau",
	"field-sat-short-relative+-1": "Thứ Bảy tuần trước",
	"field-sat-short-relative+0": "Thứ Bảy tuần này",
	"field-sat-short-relative+1": "Thứ Bảy tuần sau",
	"field-sat-narrow-relative+-1": "Thứ Bảy tuần trước",
	"field-sat-narrow-relative+0": "Thứ Bảy tuần này",
	"field-sat-narrow-relative+1": "Thứ Bảy tuần sau",
	"field-dayperiod": "SA/CH",
	"field-hour": "Giờ",
	"field-hour-relative+0": "giờ này",
	"field-hour-short": "Giờ",
	"field-hour-narrow": "Giờ",
	"field-minute": "Phút",
	"field-minute-relative+0": "phút này",
	"field-minute-short": "Phút",
	"field-minute-narrow": "Phút",
	"field-second": "Giây",
	"field-second-relative+0": "bây giờ",
	"field-second-short": "Giây",
	"field-second-narrow": "Giây",
	"field-zone": "Múi giờ"
}
//end v1.x content
);