define(
//begin v1.x content
{
	"months-format-abbr": [
		"thg 1",
		"thg 2",
		"thg 3",
		"thg 4",
		"thg 5",
		"thg 6",
		"thg 7",
		"thg 8",
		"thg 9",
		"thg 10",
		"thg 11",
		"thg 12"
	],
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-format-wide": [
		"tháng 1",
		"tháng 2",
		"tháng 3",
		"tháng 4",
		"tháng 5",
		"tháng 6",
		"tháng 7",
		"tháng 8",
		"tháng 9",
		"tháng 10",
		"tháng 11",
		"tháng 12"
	],
	"months-standAlone-abbr": [
		"Thg 1",
		"Thg 2",
		"Thg 3",
		"Thg 4",
		"Thg 5",
		"Thg 6",
		"Thg 7",
		"Thg 8",
		"Thg 9",
		"Thg 10",
		"Thg 11",
		"Thg 12"
	],
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-standAlone-wide": [
		"Tháng 1",
		"Tháng 2",
		"Tháng 3",
		"Tháng 4",
		"Tháng 5",
		"Tháng 6",
		"Tháng 7",
		"Tháng 8",
		"Tháng 9",
		"Tháng 10",
		"Tháng 11",
		"Tháng 12"
	],
	"days-format-abbr": [
		"CN",
		"Th 2",
		"Th 3",
		"Th 4",
		"Th 5",
		"Th 6",
		"Th 7"
	],
	"days-format-narrow": [
		"CN",
		"T2",
		"T3",
		"T4",
		"T5",
		"T6",
		"T7"
	],
	"days-format-short": [
		"CN",
		"T2",
		"T3",
		"T4",
		"T5",
		"T6",
		"T7"
	],
	"days-format-wide": [
		"Chủ Nhật",
		"Thứ Hai",
		"Thứ Ba",
		"Thứ Tư",
		"Thứ Năm",
		"Thứ Sáu",
		"Thứ Bảy"
	],
	"days-standAlone-abbr": [
		"CN",
		"Th 2",
		"Th 3",
		"Th 4",
		"Th 5",
		"Th 6",
		"Th 7"
	],
	"days-standAlone-narrow": [
		"CN",
		"T2",
		"T3",
		"T4",
		"T5",
		"T6",
		"T7"
	],
	"days-standAlone-short": [
		"CN",
		"T2",
		"T3",
		"T4",
		"T5",
		"T6",
		"T7"
	],
	"days-standAlone-wide": [
		"Chủ Nhật",
		"Thứ Hai",
		"Thứ Ba",
		"Thứ Tư",
		"Thứ Năm",
		"Thứ Sáu",
		"Thứ Bảy"
	],
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"Quý 1",
		"Quý 2",
		"Quý 3",
		"Quý 4"
	],
	"quarters-standAlone-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-standAlone-wide": [
		"quý 1",
		"quý 2",
		"quý 3",
		"quý 4"
	],
	"dayPeriods-format-abbr-midnight": "nửa đêm",
	"dayPeriods-format-abbr-am": "SA",
	"dayPeriods-format-abbr-noon": "TR",
	"dayPeriods-format-abbr-pm": "CH",
	"dayPeriods-format-abbr-morning1": "sáng",
	"dayPeriods-format-abbr-afternoon1": "chiều",
	"dayPeriods-format-abbr-evening1": "tối",
	"dayPeriods-format-abbr-night1": "đêm",
	"dayPeriods-format-narrow-midnight": "nửa đêm",
	"dayPeriods-format-narrow-am": "s",
	"dayPeriods-format-narrow-noon": "tr",
	"dayPeriods-format-narrow-pm": "c",
	"dayPeriods-format-narrow-morning1": "sáng",
	"dayPeriods-format-narrow-afternoon1": "chiều",
	"dayPeriods-format-narrow-evening1": "tối",
	"dayPeriods-format-narrow-night1": "đêm",
	"dayPeriods-format-wide-midnight": "nửa đêm",
	"dayPeriods-format-wide-am": "SA",
	"dayPeriods-format-wide-noon": "TR",
	"dayPeriods-format-wide-pm": "CH",
	"dayPeriods-format-wide-morning1": "sáng",
	"dayPeriods-format-wide-afternoon1": "chiều",
	"dayPeriods-format-wide-evening1": "tối",
	"dayPeriods-format-wide-night1": "đêm",
	"dayPeriods-standAlone-abbr-midnight": "nửa đêm",
	"dayPeriods-standAlone-abbr-am": "SA",
	"dayPeriods-standAlone-abbr-noon": "TR",
	"dayPeriods-standAlone-abbr-pm": "CH",
	"dayPeriods-standAlone-abbr-morning1": "sáng",
	"dayPeriods-standAlone-abbr-afternoon1": "chiều",
	"dayPeriods-standAlone-abbr-evening1": "tối",
	"dayPeriods-standAlone-abbr-night1": "đêm",
	"dayPeriods-standAlone-narrow-midnight": "nửa đêm",
	"dayPeriods-standAlone-narrow-am": "SA",
	"dayPeriods-standAlone-narrow-noon": "trưa",
	"dayPeriods-standAlone-narrow-pm": "CH",
	"dayPeriods-standAlone-narrow-morning1": "sáng",
	"dayPeriods-standAlone-narrow-afternoon1": "chiều",
	"dayPeriods-standAlone-narrow-evening1": "tối",
	"dayPeriods-standAlone-narrow-night1": "đêm",
	"dayPeriods-standAlone-wide-midnight": "nửa đêm",
	"dayPeriods-standAlone-wide-am": "SA",
	"dayPeriods-standAlone-wide-noon": "trưa",
	"dayPeriods-standAlone-wide-pm": "CH",
	"dayPeriods-standAlone-wide-morning1": "sáng",
	"dayPeriods-standAlone-wide-afternoon1": "chiều",
	"dayPeriods-standAlone-wide-evening1": "tối",
	"dayPeriods-standAlone-wide-night1": "đêm",
	"eraNames": [
		"Trước CN",
		"sau CN"
	],
	"eraAbbr": [
		"Trước CN",
		"sau CN"
	],
	"eraNarrow": [
		"tr. CN",
		"sau CN"
	],
	"dateFormat-full": "EEEE, d MMMM, y",
	"dateFormat-long": "d MMMM, y",
	"dateFormat-medium": "d MMM, y",
	"dateFormat-short": "dd/MM/y",
	"timeFormat-full": "HH:mm:ss zzzz",
	"timeFormat-long": "HH:mm:ss z",
	"timeFormat-medium": "HH:mm:ss",
	"timeFormat-short": "HH:mm",
	"dateTimeFormat-full": "{0} {1}",
	"dateTimeFormat-long": "{0} {1}",
	"dateTimeFormat-medium": "{0}, {1}",
	"dateTimeFormat-short": "{0}, {1}",
	"dateFormatItem-d": "d",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E, 'ngày' d",
	"dateFormatItem-Ehm": "E h:mm a",
	"dateFormatItem-EHm": "E HH:mm",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-GyMMMd": "dd MMM, y G",
	"dateFormatItem-GyMMMEd": "E, dd/MM/y G",
	"dateFormatItem-h": "h a",
	"dateFormatItem-H": "HH",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hmsv": "h:mm:ss a v",
	"dateFormatItem-Hmsv": "HH:mm:ss v",
	"dateFormatItem-hmv": "h:mm a v",
	"dateFormatItem-Hmv": "HH:mm v",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "dd/M",
	"dateFormatItem-MEd": "E, dd/M",
	"dateFormatItem-MMdd": "dd-MM",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-MMMMEd": "E, d MMMM",
	"dateFormatItem-MMMMW": "'tuần' W 'của' 'tháng' M",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y",
	"dateFormatItem-yM": "M/y",
	"dateFormatItem-yMd": "d/M/y",
	"dateFormatItem-yMEd": "E, dd/M/y",
	"dateFormatItem-yMM": "'tháng' MM, y",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yMMMd": "d MMM, y",
	"dateFormatItem-yMMMEd": "E, d MMM, y",
	"dateFormatItem-yMMMM": "MMMM 'năm' y",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yQQQQ": "QQQQ 'năm' y",
	"dateFormatItem-yw": "'tuần' w 'của' 'năm' y",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-era": "Thời đại",
	"field-year": "Năm",
	"field-year-relative+-1": "năm ngoái",
	"field-year-relative+0": "năm nay",
	"field-year-relative+1": "năm sau",
	"field-year-short": "Năm",
	"field-year-short-relative+-1": "năm ngoái",
	"field-year-short-relative+0": "năm nay",
	"field-year-short-relative+1": "năm sau",
	"field-year-narrow": "Năm",
	"field-year-narrow-relative+-1": "năm ngoái",
	"field-year-narrow-relative+0": "năm nay",
	"field-year-narrow-relative+1": "năm sau",
	"field-quarter": "Quý",
	"field-quarter-relative+-1": "quý trước",
	"field-quarter-relative+0": "quý này",
	"field-quarter-relative+1": "quý sau",
	"field-quarter-short": "Quý",
	"field-quarter-short-relative+-1": "quý trước",
	"field-quarter-short-relative+0": "quý này",
	"field-quarter-short-relative+1": "quý sau",
	"field-quarter-narrow": "Quý",
	"field-quarter-narrow-relative+-1": "quý trước",
	"field-quarter-narrow-relative+0": "quý này",
	"field-quarter-narrow-relative+1": "quý sau",
	"field-month": "Tháng",
	"field-month-relative+-1": "tháng trước",
	"field-month-relative+0": "tháng này",
	"field-month-relative+1": "tháng sau",
	"field-month-short": "Tháng",
	"field-month-short-relative+-1": "tháng trước",
	"field-month-short-relative+0": "tháng này",
	"field-month-short-relative+1": "tháng sau",
	"field-month-narrow": "Tháng",
	"field-month-narrow-relative+-1": "tháng trước",
	"field-month-narrow-relative+0": "tháng này",
	"field-month-narrow-relative+1": "tháng sau",
	"field-week": "Tuần",
	"field-week-relative+-1": "tuần trước",
	"field-week-relative+0": "tuần này",
	"field-week-relative+1": "tuần sau",
	"field-week-short": "Tuần",
	"field-week-short-relative+-1": "tuần trước",
	"field-week-short-relative+0": "tuần này",
	"field-week-short-relative+1": "tuần sau",
	"field-week-narrow": "Tuần",
	"field-week-narrow-relative+-1": "tuần trước",
	"field-week-narrow-relative+0": "tuần này",
	"field-week-narrow-relative+1": "tuần sau",
	"field-day": "Ngày",
	"field-day-relative+-2": "Hôm kia",
	"field-day-relative+-1": "Hôm qua",
	"field-day-relative+0": "Hôm nay",
	"field-day-relative+1": "Ngày mai",
	"field-day-relative+2": "Ngày kia",
	"field-day-short": "Ngày",
	"field-day-narrow": "Ngày",
	"field-weekday": "Ngày trong tuần",
	"field-sun-relative+-1": "Chủ Nhật tuần trước",
	"field-sun-relative+0": "Chủ Nhật tuần này",
	"field-sun-relative+1": "Chủ Nhật tuần sau",
	"field-sun-short-relative+-1": "Chủ Nhật tuần trước",
	"field-sun-short-relative+0": "Chủ Nhật tuần này",
	"field-sun-short-relative+1": "Chủ Nhật tuần sau",
	"field-sun-narrow-relative+-1": "Chủ Nhật tuần trước",
	"field-sun-narrow-relative+0": "Chủ Nhật tuần này",
	"field-sun-narrow-relative+1": "Chủ Nhật tuần sau",
	"field-mon-relative+-1": "Thứ Hai tuần trước",
	"field-mon-relative+0": "Thứ Hai tuần này",
	"field-mon-relative+1": "Thứ Hai tuần sau",
	"field-mon-short-relative+-1": "Thứ Hai tuần trước",
	"field-mon-short-relative+0": "Thứ Hai tuần này",
	"field-mon-short-relative+1": "Thứ Hai tuần sau",
	"field-mon-narrow-relative+-1": "Thứ Hai tuần trước",
	"field-mon-narrow-relative+0": "Thứ Hai tuần này",
	"field-mon-narrow-relative+1": "Thứ Hai tuần sau",
	"field-tue-relative+-1": "Thứ Ba tuần trước",
	"field-tue-relative+0": "Thứ Ba tuần này",
	"field-tue-relative+1": "Thứ Ba tuần sau",
	"field-tue-short-relative+-1": "Thứ Ba tuần trước",
	"field-tue-short-relative+0": "Thứ Ba tuần này",
	"field-tue-short-relative+1": "Thứ Ba tuần sau",
	"field-tue-narrow-relative+-1": "Thứ Ba tuần trước",
	"field-tue-narrow-relative+0": "Thứ Ba tuần này",
	"field-tue-narrow-relative+1": "Thứ Ba tuần sau",
	"field-wed-relative+-1": "Thứ Tư tuần trước",
	"field-wed-relative+0": "Thứ Tư tuần này",
	"field-wed-relative+1": "Thứ Tư tuần sau",
	"field-wed-short-relative+-1": "Thứ Tư tuần trước",
	"field-wed-short-relative+0": "Thứ Tư tuần này",
	"field-wed-short-relative+1": "Thứ Tư tuần sau",
	"field-wed-narrow-relative+-1": "Thứ Tư tuần trước",
	"field-wed-narrow-relative+0": "Thứ Tư tuần này",
	"field-wed-narrow-relative+1": "Thứ Tư tuần sau",
	"field-thu-relative+-1": "Thứ Năm tuần trước",
	"field-thu-relative+0": "Thứ Năm tuần này",
	"field-thu-relative+1": "Thứ Năm tuần sau",
	"field-thu-short-relative+-1": "Thứ Năm tuần trước",
	"field-thu-short-relative+0": "Thứ Năm tuần này",
	"field-thu-short-relative+1": "Thứ Năm tuần sau",
	"field-thu-narrow-relative+-1": "Thứ Năm tuần trước",
	"field-thu-narrow-relative+0": "Thứ Năm tuần này",
	"field-thu-narrow-relative+1": "Thứ Năm tuần sau",
	"field-fri-relative+-1": "Thứ Sáu tuần trước",
	"field-fri-relative+0": "Thứ Sáu tuần này",
	"field-fri-relative+1": "Thứ Sáu tuần sau",
	"field-fri-short-relative+-1": "Thứ Sáu tuần trước",
	"field-fri-short-relative+0": "Thứ Sáu tuần này",
	"field-fri-short-relative+1": "Thứ Sáu tuần sau",
	"field-fri-narrow-relative+-1": "Thứ Sáu tuần trước",
	"field-fri-narrow-relative+0": "Thứ Sáu tuần này",
	"field-fri-narrow-relative+1": "Thứ Sáu tuần sau",
	"field-sat-relative+-1": "Thứ Bảy tuần trước",
	"field-sat-relative+0": "Thứ Bảy tuần này",
	"field-sat-relative+1": "Thứ Bảy tuần sau",
	"field-sat-short-relative+-1": "Thứ Bảy tuần trước",
	"field-sat-short-relative+0": "Thứ Bảy tuần này",
	"field-sat-short-relative+1": "Thứ Bảy tuần sau",
	"field-sat-narrow-relative+-1": "Thứ Bảy tuần trước",
	"field-sat-narrow-relative+0": "Thứ Bảy tuần này",
	"field-sat-narrow-relative+1": "Thứ Bảy tuần sau",
	"field-dayperiod": "SA/CH",
	"field-hour": "Giờ",
	"field-hour-relative+0": "giờ này",
	"field-hour-short": "Giờ",
	"field-hour-narrow": "Giờ",
	"field-minute": "Phút",
	"field-minute-relative+0": "phút này",
	"field-minute-short": "Phút",
	"field-minute-narrow": "Phút",
	"field-second": "Giây",
	"field-second-relative+0": "bây giờ",
	"field-second-short": "Giây",
	"field-second-narrow": "Giây",
	"field-zone": "Múi giờ"
}
//end v1.x content
);