define(
//begin v1.x content
{
	"eraAbbr": [
		"БЕ"
	],
	"field-era": "ера",
	"field-year": "година",
	"field-year-relative+-1": "прошле године",
	"field-year-relative+0": "ове године",
	"field-year-relative+1": "следеће године",
	"field-year-short": "год.",
	"field-year-narrow": "г.",
	"field-quarter": "квартал",
	"field-quarter-relative+-1": "прошлог квартала",
	"field-quarter-relative+0": "овог квартала",
	"field-quarter-relative+1": "следећег квартала",
	"field-quarter-short": "кв.",
	"field-quarter-short-relative+-1": "прошлог квартала",
	"field-quarter-short-relative+0": "овог квартала",
	"field-quarter-short-relative+1": "следећег квартала",
	"field-quarter-narrow": "кв.",
	"field-quarter-narrow-relative+-1": "прошлог квартала",
	"field-quarter-narrow-relative+0": "овог квартала",
	"field-quarter-narrow-relative+1": "следећег квартала",
	"field-month": "месец",
	"field-month-relative+-1": "прошлог месеца",
	"field-month-relative+0": "овог месеца",
	"field-month-relative+1": "следећег месеца",
	"field-month-short": "мес.",
	"field-month-narrow": "м.",
	"field-week": "недеља",
	"field-week-relative+-1": "прошле недеље",
	"field-week-relative+0": "ове недеље",
	"field-week-relative+1": "следеће недеље",
	"field-week-short": "нед.",
	"field-week-narrow": "н.",
	"field-day": "дан",
	"field-day-relative+-2": "прекјуче",
	"field-day-relative+-1": "јуче",
	"field-day-relative+0": "данас",
	"field-day-relative+1": "сутра",
	"field-day-relative+2": "прекосутра",
	"field-day-short": "д.",
	"field-day-narrow": "д.",
	"field-weekday": "дан у недељи",
	"field-sun-relative+-1": "прошле недеље",
	"field-sun-relative+0": "у недељу",
	"field-sun-relative+1": "следеће недеље",
	"field-sun-short-relative+-1": "прошле нед",
	"field-sun-short-relative+0": "у нед",
	"field-sun-short-relative+1": "следеће нед",
	"field-sun-narrow-relative+-1": "прошле нед",
	"field-sun-narrow-relative+0": "у нед",
	"field-sun-narrow-relative+1": "следеће нед",
	"field-mon-relative+-1": "прошлог понедељка",
	"field-mon-relative+0": "у понедељак",
	"field-mon-relative+1": "следећег понедељка",
	"field-mon-short-relative+-1": "прошлог пон",
	"field-mon-short-relative+0": "у пон",
	"field-mon-short-relative+1": "следећег пон",
	"field-mon-narrow-relative+-1": "прошлог пон",
	"field-mon-narrow-relative+0": "у пон",
	"field-mon-narrow-relative+1": "следећег пон",
	"field-tue-relative+-1": "прошлог уторка",
	"field-tue-relative+0": "у уторак",
	"field-tue-relative+1": "следећег уторка",
	"field-tue-short-relative+-1": "прошлог уто",
	"field-tue-short-relative+0": "у уто",
	"field-tue-short-relative+1": "следећег уто",
	"field-tue-narrow-relative+-1": "прошлог уто",
	"field-tue-narrow-relative+0": "у уто",
	"field-tue-narrow-relative+1": "следећег уто",
	"field-wed-relative+-1": "прошле среде",
	"field-wed-relative+0": "у среду",
	"field-wed-relative+1": "следеће среде",
	"field-wed-short-relative+-1": "прошле сре",
	"field-wed-short-relative+0": "у сре",
	"field-wed-short-relative+1": "следеће сре",
	"field-wed-narrow-relative+-1": "прошле сре",
	"field-wed-narrow-relative+0": "у сре",
	"field-wed-narrow-relative+1": "следеће сре",
	"field-thu-relative+-1": "прошлог четвртка",
	"field-thu-relative+0": "у четвртак",
	"field-thu-relative+1": "следећег четвртка",
	"field-thu-short-relative+-1": "прошлог чет",
	"field-thu-short-relative+0": "у чет",
	"field-thu-short-relative+1": "следећег чет",
	"field-thu-narrow-relative+-1": "прошлог чет",
	"field-thu-narrow-relative+0": "у чет",
	"field-thu-narrow-relative+1": "следећег чет",
	"field-fri-relative+-1": "прошлог петка",
	"field-fri-relative+0": "у петак",
	"field-fri-relative+1": "следећег петка",
	"field-fri-short-relative+-1": "прошлог пет",
	"field-fri-short-relative+0": "у пет",
	"field-fri-short-relative+1": "следећег пет",
	"field-fri-narrow-relative+-1": "прошлог пет",
	"field-fri-narrow-relative+0": "у пет",
	"field-fri-narrow-relative+1": "следећег пет",
	"field-sat-relative+-1": "прошле суботе",
	"field-sat-relative+0": "у суботу",
	"field-sat-relative+1": "следеће суботе",
	"field-sat-short-relative+-1": "прошле суб",
	"field-sat-short-relative+0": "у суб",
	"field-sat-short-relative+1": "следеће суб",
	"field-sat-narrow-relative+-1": "прошле суб",
	"field-sat-narrow-relative+0": "у суб",
	"field-sat-narrow-relative+1": "следеће суб",
	"field-dayperiod": "пре подне/по подне",
	"field-hour": "сат",
	"field-hour-relative+0": "овог сата",
	"field-hour-short": "ч.",
	"field-hour-narrow": "ч.",
	"field-minute": "минут",
	"field-minute-relative+0": "овог минута",
	"field-minute-short": "мин.",
	"field-minute-narrow": "мин.",
	"field-second": "секунд",
	"field-second-relative+0": "сада",
	"field-second-short": "сек.",
	"field-second-narrow": "с.",
	"field-zone": "временска зона",
	"eraNames": [
		"БЕ"
	],
	"eraNarrow": [
		"БЕ"
	],
	"days-format-abbr": [
		"нед",
		"пон",
		"уто",
		"сре",
		"чет",
		"пет",
		"суб"
	],
	"days-format-narrow": [
		"н",
		"п",
		"у",
		"с",
		"ч",
		"п",
		"с"
	],
	"days-format-short": [
		"не",
		"по",
		"ут",
		"ср",
		"че",
		"пе",
		"су"
	],
	"days-format-wide": [
		"недеља",
		"понедељак",
		"уторак",
		"среда",
		"четвртак",
		"петак",
		"субота"
	],
	"days-standAlone-abbr": [
		"нед",
		"пон",
		"уто",
		"сре",
		"чет",
		"пет",
		"суб"
	],
	"days-standAlone-narrow": [
		"н",
		"п",
		"у",
		"с",
		"ч",
		"п",
		"с"
	],
	"days-standAlone-short": [
		"не",
		"по",
		"ут",
		"ср",
		"че",
		"пе",
		"су"
	],
	"days-standAlone-wide": [
		"недеља",
		"понедељак",
		"уторак",
		"среда",
		"четвртак",
		"петак",
		"субота"
	],
	"quarters-format-abbr": [
		"К1",
		"К2",
		"К3",
		"К4"
	],
	"quarters-format-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"quarters-format-wide": [
		"први квартал",
		"други квартал",
		"трећи квартал",
		"четврти квартал"
	],
	"quarters-standAlone-abbr": [
		"К1",
		"К2",
		"К3",
		"К4"
	],
	"quarters-standAlone-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"quarters-standAlone-wide": [
		"први квартал",
		"други квартал",
		"трећи квартал",
		"четврти квартал"
	],
	"dayPeriods-format-abbr-am": "пре подне",
	"dayPeriods-format-abbr-pm": "по подне",
	"dayPeriods-format-narrow-am": "a",
	"dayPeriods-format-narrow-pm": "p",
	"dayPeriods-format-wide-am": "пре подне",
	"dayPeriods-format-wide-pm": "по подне",
	"dayPeriods-standAlone-abbr-am": "пре подне",
	"dayPeriods-standAlone-abbr-pm": "по подне",
	"dayPeriods-standAlone-narrow-am": "пре подне",
	"dayPeriods-standAlone-narrow-pm": "по подне",
	"dayPeriods-standAlone-wide-am": "пре подне",
	"dayPeriods-standAlone-wide-pm": "по подне",
	"dateFormat-full": "EEEE, d. MMMM y. G",
	"dateFormat-long": "d. MMMM y. G",
	"dateFormat-medium": "d.MM.y. G",
	"dateFormat-short": "d.M.y. GGGGG",
	"dateFormatItem-Ed": "E d.",
	"dateFormatItem-Gy": "y. G",
	"dateFormatItem-GyMMM": "MMM y. G",
	"dateFormatItem-GyMMMd": "d. MMM y. G",
	"dateFormatItem-GyMMMEd": "E, d. MMM y. G",
	"dateFormatItem-h": "hh a",
	"dateFormatItem-hm": "hh.mm a",
	"dateFormatItem-Hm": "HH.mm",
	"dateFormatItem-hms": "hh.mm.ss a",
	"dateFormatItem-Hms": "HH.mm.ss",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-MEd": "E, d.M.",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-ms": "mm.ss",
	"dateFormatItem-y": "y. G",
	"dateFormatItem-yyyy": "y. G",
	"dateFormatItem-yyyyM": "M.y. GGGGG",
	"dateFormatItem-yyyyMd": "d.M.y. GGGGG",
	"dateFormatItem-yyyyMEd": "E, d.M.y. GGGGG",
	"dateFormatItem-yyyyMMM": "MMM y. G",
	"dateFormatItem-yyyyMMMd": "d. MMM y. G",
	"dateFormatItem-yyyyMMMEd": "E, d. MMM y. G",
	"dateFormatItem-yyyyMMMM": "MMMM y. G",
	"dateFormatItem-yyyyQQQ": "QQQ, y. G",
	"dateFormatItem-yyyyQQQQ": "QQQQ y. G",
	"months-format-abbr": [
		"јан",
		"феб",
		"мар",
		"апр",
		"мај",
		"јун",
		"јул",
		"авг",
		"сеп",
		"окт",
		"нов",
		"дец"
	],
	"months-format-narrow": [
		"ј",
		"ф",
		"м",
		"а",
		"м",
		"ј",
		"ј",
		"а",
		"с",
		"о",
		"н",
		"д"
	],
	"months-format-wide": [
		"јануар",
		"фебруар",
		"март",
		"април",
		"мај",
		"јун",
		"јул",
		"август",
		"септембар",
		"октобар",
		"новембар",
		"децембар"
	],
	"months-standAlone-abbr": [
		"јан",
		"феб",
		"мар",
		"апр",
		"мај",
		"јун",
		"јул",
		"авг",
		"сеп",
		"окт",
		"нов",
		"дец"
	],
	"months-standAlone-narrow": [
		"ј",
		"ф",
		"м",
		"а",
		"м",
		"ј",
		"ј",
		"а",
		"с",
		"о",
		"н",
		"д"
	],
	"months-standAlone-wide": [
		"јануар",
		"фебруар",
		"март",
		"април",
		"мај",
		"јун",
		"јул",
		"август",
		"септембар",
		"октобар",
		"новембар",
		"децембар"
	]
}
//end v1.x content
);