define(
//begin v1.x content
{
	"months-format-abbr": [
		"محرم",
		"صفر",
		"ربيع الأول",
		"ربيع الآخر",
		"جمادى الأولى",
		"جمادى الآخرة",
		"رجب",
		"شعبان",
		"رمضان",
		"شوال",
		"ذو القعدة",
		"ذو الحجة"
	],
	"months-format-narrow": [
		"١",
		"٢",
		"٣",
		"٤",
		"٥",
		"٦",
		"٧",
		"٨",
		"٩",
		"١٠",
		"١١",
		"١٢"
	],
	"months-format-wide": [
		"محرم",
		"صفر",
		"ربيع الأول",
		"ربيع الآخر",
		"جمادى الأولى",
		"جمادى الآخرة",
		"رجب",
		"شعبان",
		"رمضان",
		"شوال",
		"ذو القعدة",
		"ذو الحجة"
	],
	"months-standAlone-abbr": [
		"محرم",
		"صفر",
		"ربيع الأول",
		"ربيع الآخر",
		"جمادى الأولى",
		"جمادى الآخرة",
		"رجب",
		"شعبان",
		"رمضان",
		"شوال",
		"ذو القعدة",
		"ذو الحجة"
	],
	"months-standAlone-narrow": [
		"١",
		"٢",
		"٣",
		"٤",
		"٥",
		"٦",
		"٧",
		"٨",
		"٩",
		"١٠",
		"١١",
		"١٢"
	],
	"months-standAlone-wide": [
		"محرم",
		"صفر",
		"ربيع الأول",
		"ربيع الآخر",
		"جمادى الأولى",
		"جمادى الآخرة",
		"رجب",
		"شعبان",
		"رمضان",
		"شوال",
		"ذو القعدة",
		"ذو الحجة"
	],
	"eraAbbr": [
		"هـ"
	],
	"dateFormat-full": "EEEE، d MMMM، y G",
	"dateFormat-long": "d MMMM، y G",
	"dateFormat-medium": "d MMM، y G",
	"dateFormat-short": "d‏/M‏/y GGGGG",
	"dateFormatItem-d": "d",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E، d",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-GyMMMd": "d MMM، y G",
	"dateFormatItem-GyMMMEd": "E، d MMM، y G",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "d/‏M",
	"dateFormatItem-MEd": "E، d/M",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MMMEd": "E، d MMM",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-yyyyM": "M‏/y G",
	"dateFormatItem-yyyyMd": "d‏/M‏/y G",
	"dateFormatItem-yyyyMEd": "E، d/‏M/‏y G",
	"dateFormatItem-yyyyMMM": "MMM، y G",
	"dateFormatItem-yyyyMMMd": "d MMM، y G",
	"dateFormatItem-yyyyMMMEd": "E، d MMM، y G",
	"dateFormatItem-yyyyMMMM": "MMMM، y G",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"field-era": "العصر",
	"field-year": "السنة",
	"field-year-relative+-1": "السنة الماضية",
	"field-year-relative+0": "السنة الحالية",
	"field-year-relative+1": "السنة القادمة",
	"field-year-short": "السنة",
	"field-year-narrow": "السنة",
	"field-quarter": "ربع السنة",
	"field-quarter-relative+-1": "الربع الأخير",
	"field-quarter-relative+0": "هذا الربع",
	"field-quarter-relative+1": "الربع القادم",
	"field-quarter-short": "ربع السنة",
	"field-quarter-short-relative+-1": "الربع الأخير",
	"field-quarter-short-relative+0": "هذا الربع",
	"field-quarter-short-relative+1": "الربع القادم",
	"field-quarter-narrow": "ربع السنة",
	"field-quarter-narrow-relative+-1": "الربع الأخير",
	"field-quarter-narrow-relative+0": "هذا الربع",
	"field-quarter-narrow-relative+1": "الربع القادم",
	"field-month": "الشهر",
	"field-month-relative+-1": "الشهر الماضي",
	"field-month-relative+0": "هذا الشهر",
	"field-month-relative+1": "الشهر القادم",
	"field-month-short": "الشهر",
	"field-month-narrow": "الشهر",
	"field-week": "الأسبوع",
	"field-week-relative+-1": "الأسبوع الماضي",
	"field-week-relative+0": "هذا الأسبوع",
	"field-week-relative+1": "الأسبوع القادم",
	"field-week-short": "الأسبوع",
	"field-week-narrow": "الأسبوع",
	"field-day": "يوم",
	"field-day-relative+-2": "أول أمس",
	"field-day-relative+-1": "أمس",
	"field-day-relative+0": "اليوم",
	"field-day-relative+1": "غدًا",
	"field-day-relative+2": "بعد الغد",
	"field-day-short": "يوم",
	"field-day-narrow": "يوم",
	"field-weekday": "اليوم",
	"field-sun-relative+-1": "الأحد الماضي",
	"field-sun-relative+0": "الأحد الحالي",
	"field-sun-relative+1": "الأحد القادم",
	"field-sun-short-relative+-1": "الأحد الماضي",
	"field-sun-short-relative+0": "الأحد الحالي",
	"field-sun-short-relative+1": "الأحد القادم",
	"field-sun-narrow-relative+-1": "الأحد الماضي",
	"field-sun-narrow-relative+0": "الأحد الحالي",
	"field-sun-narrow-relative+1": "الأحد القادم",
	"field-mon-relative+-1": "الاثنين الماضي",
	"field-mon-relative+0": "الاثنين الحالي",
	"field-mon-relative+1": "الاثنين القادم",
	"field-mon-short-relative+-1": "الاثنين الماضي",
	"field-mon-short-relative+0": "الاثنين الحالي",
	"field-mon-short-relative+1": "الإثنين القادم",
	"field-mon-narrow-relative+-1": "الإثنين الماضي",
	"field-mon-narrow-relative+0": "الإثنين الحالي",
	"field-mon-narrow-relative+1": "الإثنين القادم",
	"field-tue-relative+-1": "الثلاثاء الماضي",
	"field-tue-relative+0": "الثلاثاء الحالي",
	"field-tue-relative+1": "الثلاثاء القادم",
	"field-tue-short-relative+-1": "الثلاثاء الماضي",
	"field-tue-short-relative+0": "الثلاثاء الحالي",
	"field-tue-short-relative+1": "الثلاثاء القادم",
	"field-tue-narrow-relative+-1": "الثلاثاء الماضي",
	"field-tue-narrow-relative+0": "الثلاثاء الحالي",
	"field-tue-narrow-relative+1": "الثلاثاء القادم",
	"field-wed-relative+-1": "الأربعاء الماضي",
	"field-wed-relative+0": "الأربعاء الحالي",
	"field-wed-relative+1": "الأربعاء القادم",
	"field-wed-short-relative+-1": "الأربعاء الماضي",
	"field-wed-short-relative+0": "الأربعاء الحالي",
	"field-wed-short-relative+1": "الأربعاء القادم",
	"field-wed-narrow-relative+-1": "الأربعاء الماضي",
	"field-wed-narrow-relative+0": "الأربعاء الحالي",
	"field-wed-narrow-relative+1": "الأربعاء القادم",
	"field-thu-relative+-1": "الخميس الماضي",
	"field-thu-relative+0": "الخميس الحالي",
	"field-thu-relative+1": "الخميس القادم",
	"field-thu-short-relative+-1": "الخميس الماضي",
	"field-thu-short-relative+0": "الخميس الحالي",
	"field-thu-short-relative+1": "الخميس القادم",
	"field-thu-narrow-relative+-1": "الخميس الماضي",
	"field-thu-narrow-relative+0": "الخميس الحالي",
	"field-thu-narrow-relative+1": "الخميس القادم",
	"field-fri-relative+-1": "الجمعة الماضي",
	"field-fri-relative+0": "الجمعة الحالي",
	"field-fri-relative+1": "الجمعة القادم",
	"field-fri-short-relative+-1": "الجمعة الماضي",
	"field-fri-short-relative+0": "الجمعة الحالي",
	"field-fri-short-relative+1": "الجمعة القادم",
	"field-fri-narrow-relative+-1": "الجمعة الماضي",
	"field-fri-narrow-relative+0": "الجمعة الحالي",
	"field-fri-narrow-relative+1": "الجمعة القادم",
	"field-sat-relative+-1": "السبت الماضي",
	"field-sat-relative+0": "السبت الحالي",
	"field-sat-relative+1": "السبت القادم",
	"field-sat-short-relative+-1": "السبت الماضي",
	"field-sat-short-relative+0": "السبت الحالي",
	"field-sat-short-relative+1": "السبت القادم",
	"field-sat-narrow-relative+-1": "السبت الماضي",
	"field-sat-narrow-relative+0": "السبت الحالي",
	"field-sat-narrow-relative+1": "السبت القادم",
	"field-dayperiod": "ص/م",
	"field-hour": "الساعات",
	"field-hour-relative+0": "الساعة الحالية",
	"field-hour-short": "الساعات",
	"field-hour-narrow": "الساعات",
	"field-minute": "الدقائق",
	"field-minute-relative+0": "هذه الدقيقة",
	"field-minute-short": "الدقائق",
	"field-minute-narrow": "الدقائق",
	"field-second": "الثواني",
	"field-second-relative+0": "الآن",
	"field-second-short": "الثواني",
	"field-second-narrow": "الثواني",
	"field-zone": "التوقيت",
	"eraNames": [
		"هـ"
	],
	"eraNarrow": [
		"هـ"
	],
	"days-format-abbr": [
		"الأحد",
		"الاثنين",
		"الثلاثاء",
		"الأربعاء",
		"الخميس",
		"الجمعة",
		"السبت"
	],
	"days-format-narrow": [
		"ح",
		"ن",
		"ث",
		"ر",
		"خ",
		"ج",
		"س"
	],
	"days-format-short": [
		"الأحد",
		"الاثنين",
		"الثلاثاء",
		"الأربعاء",
		"الخميس",
		"الجمعة",
		"السبت"
	],
	"days-format-wide": [
		"الأحد",
		"الاثنين",
		"الثلاثاء",
		"الأربعاء",
		"الخميس",
		"الجمعة",
		"السبت"
	],
	"days-standAlone-abbr": [
		"الأحد",
		"الاثنين",
		"الثلاثاء",
		"الأربعاء",
		"الخميس",
		"الجمعة",
		"السبت"
	],
	"days-standAlone-narrow": [
		"ح",
		"ن",
		"ث",
		"ر",
		"خ",
		"ج",
		"س"
	],
	"days-standAlone-short": [
		"الأحد",
		"الاثنين",
		"الثلاثاء",
		"الأربعاء",
		"الخميس",
		"الجمعة",
		"السبت"
	],
	"days-standAlone-wide": [
		"الأحد",
		"الاثنين",
		"الثلاثاء",
		"الأربعاء",
		"الخميس",
		"الجمعة",
		"السبت"
	],
	"quarters-format-abbr": [
		"الربع الأول",
		"الربع الثاني",
		"الربع الثالث",
		"الربع الرابع"
	],
	"quarters-format-narrow": [
		"١",
		"٢",
		"٣",
		"٤"
	],
	"quarters-format-wide": [
		"الربع الأول",
		"الربع الثاني",
		"الربع الثالث",
		"الربع الرابع"
	],
	"quarters-standAlone-abbr": [
		"الربع الأول",
		"الربع الثاني",
		"الربع الثالث",
		"الربع الرابع"
	],
	"quarters-standAlone-narrow": [
		"١",
		"٢",
		"٣",
		"٤"
	],
	"quarters-standAlone-wide": [
		"الربع الأول",
		"الربع الثاني",
		"الربع الثالث",
		"الربع الرابع"
	],
	"dayPeriods-format-abbr-am": "ص",
	"dayPeriods-format-abbr-pm": "م",
	"dayPeriods-format-narrow-am": "ص",
	"dayPeriods-format-narrow-pm": "م",
	"dayPeriods-format-wide-am": "ص",
	"dayPeriods-format-wide-pm": "م",
	"dayPeriods-standAlone-abbr-am": "ص",
	"dayPeriods-standAlone-abbr-pm": "م",
	"dayPeriods-standAlone-narrow-am": "ص",
	"dayPeriods-standAlone-narrow-pm": "م",
	"dayPeriods-standAlone-wide-am": "صباحًا",
	"dayPeriods-standAlone-wide-pm": "مساءً",
	"timeFormat-full": "h:mm:ss a zzzz",
	"timeFormat-long": "h:mm:ss a z",
	"timeFormat-medium": "h:mm:ss a",
	"timeFormat-short": "h:mm a"
}
//end v1.x content
);