define(
//begin v1.x content
{
	"eraAbbr": [
		"تيكا",
		"هاكتشي",
		"هاكهو",
		"شتشو",
		"تيهو",
		"كيين",
		"وادو",
		"رييكي",
		"يورو",
		"جينكي",
		"تمبيو",
		"تمبيو-كامبو",
		"تمبيو-شوهو",
		"تمبيو-هوجي",
		"تمفو-جينجو",
		"جينجو-كيين",
		"هوكي",
		"تن-أو",
		"إنرياكو",
		"ديدو",
		"كونين",
		"تنتشو",
		"شووا (٨٣٤–٨٤٨)‏",
		"كاجو",
		"نينجو",
		"سيكو",
		"تنان",
		"جوجان",
		"جينكيي",
		"نينا",
		"كامبيو",
		"شوتاي",
		"انجي",
		"انتشو",
		"شوهيي",
		"تنجيو",
		"تنرياكو",
		"تنتوكو",
		"أووا",
		"كوهو",
		"آنا",
		"تينروكو",
		"تن-نن",
		"جوجن",
		"تنجن",
		"إيكان",
		"كانا",
		"اي-ان",
		"ايسو",
		"شورياكو (٩٩٠–٩٩٥)‏",
		"تشوتوكو",
		"تشوهو",
		"كانكو",
		"تشووا",
		"كانين",
		"جاين",
		"مانجو",
		"تشوجين",
		"تشورياكو",
		"تشوكيو (١٠٤٠–١٠٤٤)‏",
		"كانتوكو",
		"ايشو (١٠٤٦–١٠٥٣)‏",
		"تينجي",
		"كوهيي",
		"جيرياكو",
		"انكيو (١٠٦٩–١٠٧٤)‏",
		"شوهو (١٠٧٤–١٠٧٧)‏",
		"شورياكو (١٠٧٧–١٠٨١)‏",
		"ايهو",
		"أوتوكو",
		"كانجي",
		"كاهو",
		"ايتشو",
		"شوتوكو",
		"كووا (١٠٩٩–١١٠٤)‏",
		"تشوجي",
		"كاشو",
		"تنين",
		"تن-اي",
		"ايكيو (١١١٣–١١١٨)‏",
		"جن-اي",
		"هوان",
		"تنجي",
		"ديجي",
		"تنشو (١١٣١–١١٣٢)‏",
		"تشوشو",
		"هوين",
		"ايجي",
		"كوجي (١١٤٢–١١٤٤)‏",
		"تنيو",
		"كيوان",
		"نينبيي",
		"كيوجو",
		"هجين",
		"هيجي",
		"ايرياكو",
		"أوهو",
		"تشوكان",
		"ايمان",
		"نين-ان",
		"كاو",
		"شون",
		"أنجين",
		"جيشو",
		"يووا",
		"جيي",
		"جنريوكو",
		"بنجي",
		"كنكيو",
		"شوجي",
		"كنين",
		"جنكيو (١٢٠٤–١٢٠٦)‏",
		"كن-اي",
		"شوجن (١٢٠٧–١٢١١)‏",
		"كنرياكو",
		"كنبو (١٢١٣–١٢١٩)‏",
		"شوكيو",
		"جو",
		"جيننين",
		"كروكو",
		"أنتيي",
		"كنكي",
		"جويي",
		"تمبكو",
		"بنرياكو",
		"كاتيي",
		"رياكنين",
		"ان-أو",
		"نينجي",
		"كنجين",
		"هوجي",
		"كنتشو",
		"كوجن",
		"شوكا",
		"شوجن (١٢٥٩–١٢٦٠)‏",
		"بن-أو",
		"كوتشو",
		"بن-اي",
		"كنجي",
		"كوان",
		"شوو (١٢٨٨–١٢٩٣)‏",
		"اينين",
		"شوان",
		"كنجن",
		"كجن",
		"توكجي",
		"انكي",
		"أوتشو",
		"شووا (١٣١٢–١٣١٧)‏",
		"بنبو",
		"جنو",
		"جنكيو (١٣٢١–١٣٢٤)‏",
		"شوتشو (١٣٢٤–١٣٢٦)‏",
		"كريكي",
		"جنتكو",
		"جنكو",
		"كمو",
		"إنجن",
		"كوككو",
		"شوهي",
		"كنتكو",
		"بنتشو",
		"تنجو",
		"كورياكو",
		"كووا (١٣٨١–١٣٨٤)‏",
		"جنتشو",
		"مييتكو (١٣٨٤–١٣٨٧)‏",
		"كاكي",
		"كو",
		"مييتكو (١٣٩٠–١٣٩٤)‏",
		"أويي",
		"شوتشو (١٤٢٨–١٤٢٩)‏",
		"ايكيو (١٤٢٩–١٤٤١)‏",
		"ككيتسو",
		"بن-أن",
		"هوتكو",
		"كيوتكو",
		"كوشو",
		"تشوركو",
		"كنشو",
		"بنشو",
		"أونين",
		"بنمي",
		"تشوكيو (١٤٨٧–١٤٨٩)‏",
		"انتكو",
		"ميو",
		"بنكي",
		"ايشو (١٥٠٤–١٥٢١)‏",
		"تييي",
		"كيوركو",
		"تنمن",
		"كوجي (١٥٥٥–١٥٥٨)‏",
		"ايركو",
		"جنكي",
		"تنشو (١٥٧٣–١٥٩٢)‏",
		"بنركو",
		"كيتشو",
		"جنوا",
		"كان-اي",
		"شوهو (١٦٤٤–١٦٤٨)‏",
		"كيان",
		"شوو (١٦٥٢–١٦٥٥)‏",
		"ميرياكو",
		"منجي",
		"كنبن",
		"انبو",
		"تنوا",
		"جوكيو",
		"جنركو",
		"هويي",
		"شوتكو",
		"كيوهو",
		"جنبن",
		"كنبو (١٧٤١–١٧٤٤)‏",
		"انكيو (١٧٤٤–١٧٤٨)‏",
		"كان-ان",
		"هورياكو",
		"مييوا",
		"ان-اي",
		"تنمي",
		"كنسي",
		"كيووا",
		"بنكا",
		"بنسي",
		"تنبو",
		"كوكا",
		"كاي",
		"أنسي",
		"من-ان",
		"بنكيو",
		"جنجي",
		"كيو",
		"ميجي",
		"تيشو",
		"شووا",
		"هيسي"
	],
	"field-era": "العصر",
	"field-year": "السنة",
	"field-year-relative+-1": "السنة الماضية",
	"field-year-relative+0": "السنة الحالية",
	"field-year-relative+1": "السنة القادمة",
	"field-year-short": "السنة",
	"field-year-narrow": "السنة",
	"field-quarter": "ربع السنة",
	"field-quarter-relative+-1": "الربع الأخير",
	"field-quarter-relative+0": "هذا الربع",
	"field-quarter-relative+1": "الربع القادم",
	"field-quarter-short": "ربع السنة",
	"field-quarter-short-relative+-1": "الربع الأخير",
	"field-quarter-short-relative+0": "هذا الربع",
	"field-quarter-short-relative+1": "الربع القادم",
	"field-quarter-narrow": "ربع السنة",
	"field-quarter-narrow-relative+-1": "الربع الأخير",
	"field-quarter-narrow-relative+0": "هذا الربع",
	"field-quarter-narrow-relative+1": "الربع القادم",
	"field-month": "الشهر",
	"field-month-relative+-1": "الشهر الماضي",
	"field-month-relative+0": "هذا الشهر",
	"field-month-relative+1": "الشهر القادم",
	"field-month-short": "الشهر",
	"field-month-narrow": "الشهر",
	"field-week": "الأسبوع",
	"field-week-relative+-1": "الأسبوع الماضي",
	"field-week-relative+0": "هذا الأسبوع",
	"field-week-relative+1": "الأسبوع القادم",
	"field-week-short": "الأسبوع",
	"field-week-narrow": "الأسبوع",
	"field-day": "يوم",
	"field-day-relative+-2": "أول أمس",
	"field-day-relative+-1": "أمس",
	"field-day-relative+0": "اليوم",
	"field-day-relative+1": "غدًا",
	"field-day-relative+2": "بعد الغد",
	"field-day-short": "يوم",
	"field-day-narrow": "يوم",
	"field-weekday": "اليوم",
	"field-sun-relative+-1": "الأحد الماضي",
	"field-sun-relative+0": "الأحد الحالي",
	"field-sun-relative+1": "الأحد القادم",
	"field-sun-short-relative+-1": "الأحد الماضي",
	"field-sun-short-relative+0": "الأحد الحالي",
	"field-sun-short-relative+1": "الأحد القادم",
	"field-sun-narrow-relative+-1": "الأحد الماضي",
	"field-sun-narrow-relative+0": "الأحد الحالي",
	"field-sun-narrow-relative+1": "الأحد القادم",
	"field-mon-relative+-1": "الاثنين الماضي",
	"field-mon-relative+0": "الاثنين الحالي",
	"field-mon-relative+1": "الاثنين القادم",
	"field-mon-short-relative+-1": "الاثنين الماضي",
	"field-mon-short-relative+0": "الاثنين الحالي",
	"field-mon-short-relative+1": "الإثنين القادم",
	"field-mon-narrow-relative+-1": "الإثنين الماضي",
	"field-mon-narrow-relative+0": "الإثنين الحالي",
	"field-mon-narrow-relative+1": "الإثنين القادم",
	"field-tue-relative+-1": "الثلاثاء الماضي",
	"field-tue-relative+0": "الثلاثاء الحالي",
	"field-tue-relative+1": "الثلاثاء القادم",
	"field-tue-short-relative+-1": "الثلاثاء الماضي",
	"field-tue-short-relative+0": "الثلاثاء الحالي",
	"field-tue-short-relative+1": "الثلاثاء القادم",
	"field-tue-narrow-relative+-1": "الثلاثاء الماضي",
	"field-tue-narrow-relative+0": "الثلاثاء الحالي",
	"field-tue-narrow-relative+1": "الثلاثاء القادم",
	"field-wed-relative+-1": "الأربعاء الماضي",
	"field-wed-relative+0": "الأربعاء الحالي",
	"field-wed-relative+1": "الأربعاء القادم",
	"field-wed-short-relative+-1": "الأربعاء الماضي",
	"field-wed-short-relative+0": "الأربعاء الحالي",
	"field-wed-short-relative+1": "الأربعاء القادم",
	"field-wed-narrow-relative+-1": "الأربعاء الماضي",
	"field-wed-narrow-relative+0": "الأربعاء الحالي",
	"field-wed-narrow-relative+1": "الأربعاء القادم",
	"field-thu-relative+-1": "الخميس الماضي",
	"field-thu-relative+0": "الخميس الحالي",
	"field-thu-relative+1": "الخميس القادم",
	"field-thu-short-relative+-1": "الخميس الماضي",
	"field-thu-short-relative+0": "الخميس الحالي",
	"field-thu-short-relative+1": "الخميس القادم",
	"field-thu-narrow-relative+-1": "الخميس الماضي",
	"field-thu-narrow-relative+0": "الخميس الحالي",
	"field-thu-narrow-relative+1": "الخميس القادم",
	"field-fri-relative+-1": "الجمعة الماضي",
	"field-fri-relative+0": "الجمعة الحالي",
	"field-fri-relative+1": "الجمعة القادم",
	"field-fri-short-relative+-1": "الجمعة الماضي",
	"field-fri-short-relative+0": "الجمعة الحالي",
	"field-fri-short-relative+1": "الجمعة القادم",
	"field-fri-narrow-relative+-1": "الجمعة الماضي",
	"field-fri-narrow-relative+0": "الجمعة الحالي",
	"field-fri-narrow-relative+1": "الجمعة القادم",
	"field-sat-relative+-1": "السبت الماضي",
	"field-sat-relative+0": "السبت الحالي",
	"field-sat-relative+1": "السبت القادم",
	"field-sat-short-relative+-1": "السبت الماضي",
	"field-sat-short-relative+0": "السبت الحالي",
	"field-sat-short-relative+1": "السبت القادم",
	"field-sat-narrow-relative+-1": "السبت الماضي",
	"field-sat-narrow-relative+0": "السبت الحالي",
	"field-sat-narrow-relative+1": "السبت القادم",
	"field-dayperiod": "ص/م",
	"field-hour": "الساعات",
	"field-hour-relative+0": "الساعة الحالية",
	"field-hour-short": "الساعات",
	"field-hour-narrow": "الساعات",
	"field-minute": "الدقائق",
	"field-minute-relative+0": "هذه الدقيقة",
	"field-minute-short": "الدقائق",
	"field-minute-narrow": "الدقائق",
	"field-second": "الثواني",
	"field-second-relative+0": "الآن",
	"field-second-short": "الثواني",
	"field-second-narrow": "الثواني",
	"field-zone": "التوقيت"
}
//end v1.x content
);