define(
//begin v1.x content
{
	"months-format-abbr": [
		"ינו׳",
		"פבר׳",
		"מרץ",
		"אפר׳",
		"מאי",
		"יוני",
		"יולי",
		"אוג׳",
		"ספט׳",
		"אוק׳",
		"נוב׳",
		"דצמ׳"
	],
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-format-wide": [
		"ינואר",
		"פברואר",
		"מרץ",
		"אפריל",
		"מאי",
		"יוני",
		"יולי",
		"אוגוסט",
		"ספטמבר",
		"אוקטובר",
		"נובמבר",
		"דצמבר"
	],
	"months-standAlone-abbr": [
		"ינו׳",
		"פבר׳",
		"מרץ",
		"אפר׳",
		"מאי",
		"יוני",
		"יולי",
		"אוג׳",
		"ספט׳",
		"אוק׳",
		"נוב׳",
		"דצמ׳"
	],
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-standAlone-wide": [
		"ינואר",
		"פברואר",
		"מרץ",
		"אפריל",
		"מאי",
		"יוני",
		"יולי",
		"אוגוסט",
		"ספטמבר",
		"אוקטובר",
		"נובמבר",
		"דצמבר"
	],
	"days-format-abbr": [
		"יום א׳",
		"יום ב׳",
		"יום ג׳",
		"יום ד׳",
		"יום ה׳",
		"יום ו׳",
		"שבת"
	],
	"days-format-narrow": [
		"א׳",
		"ב׳",
		"ג׳",
		"ד׳",
		"ה׳",
		"ו׳",
		"ש׳"
	],
	"days-format-short": [
		"א׳",
		"ב׳",
		"ג׳",
		"ד׳",
		"ה׳",
		"ו׳",
		"ש׳"
	],
	"days-format-wide": [
		"יום ראשון",
		"יום שני",
		"יום שלישי",
		"יום רביעי",
		"יום חמישי",
		"יום שישי",
		"יום שבת"
	],
	"days-standAlone-abbr": [
		"יום א׳",
		"יום ב׳",
		"יום ג׳",
		"יום ד׳",
		"יום ה׳",
		"יום ו׳",
		"שבת"
	],
	"days-standAlone-narrow": [
		"א׳",
		"ב׳",
		"ג׳",
		"ד׳",
		"ה׳",
		"ו׳",
		"ש׳"
	],
	"days-standAlone-short": [
		"א׳",
		"ב׳",
		"ג׳",
		"ד׳",
		"ה׳",
		"ו׳",
		"ש׳"
	],
	"days-standAlone-wide": [
		"יום ראשון",
		"יום שני",
		"יום שלישי",
		"יום רביעי",
		"יום חמישי",
		"יום שישי",
		"יום שבת"
	],
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"רבעון 1",
		"רבעון 2",
		"רבעון 3",
		"רבעון 4"
	],
	"quarters-standAlone-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-standAlone-wide": [
		"רבעון 1",
		"רבעון 2",
		"רבעון 3",
		"רבעון 4"
	],
	"dayPeriods-format-abbr-midnight": "חצות",
	"dayPeriods-format-abbr-am": "לפנה״צ",
	"dayPeriods-format-abbr-pm": "אחה״צ",
	"dayPeriods-format-abbr-morning1": "בוקר",
	"dayPeriods-format-abbr-afternoon1": "צהריים",
	"dayPeriods-format-abbr-afternoon2": "אחר הצהריים",
	"dayPeriods-format-abbr-evening1": "ערב",
	"dayPeriods-format-abbr-night1": "לילה",
	"dayPeriods-format-abbr-night2": "לפנות בוקר",
	"dayPeriods-format-narrow-midnight": "חצות",
	"dayPeriods-format-narrow-morning1": "בוקר",
	"dayPeriods-format-narrow-afternoon1": "צהריים",
	"dayPeriods-format-narrow-afternoon2": "אחר הצהריים",
	"dayPeriods-format-narrow-evening1": "ערב",
	"dayPeriods-format-narrow-night1": "לילה",
	"dayPeriods-format-narrow-night2": "לפנות בוקר",
	"dayPeriods-format-wide-midnight": "חצות",
	"dayPeriods-format-wide-am": "לפנה״צ",
	"dayPeriods-format-wide-pm": "אחה״צ",
	"dayPeriods-format-wide-morning1": "בוקר",
	"dayPeriods-format-wide-afternoon1": "צהריים",
	"dayPeriods-format-wide-afternoon2": "אחר הצהריים",
	"dayPeriods-format-wide-evening1": "ערב",
	"dayPeriods-format-wide-night1": "לילה",
	"dayPeriods-format-wide-night2": "לפנות בוקר",
	"dayPeriods-standAlone-abbr-midnight": "חצות",
	"dayPeriods-standAlone-abbr-morning1": "בוקר",
	"dayPeriods-standAlone-abbr-afternoon1": "צהריים",
	"dayPeriods-standAlone-abbr-afternoon2": "אחר הצהריים",
	"dayPeriods-standAlone-abbr-evening1": "ערב",
	"dayPeriods-standAlone-abbr-night1": "לילה",
	"dayPeriods-standAlone-abbr-night2": "לפנות בוקר",
	"dayPeriods-standAlone-narrow-midnight": "חצות",
	"dayPeriods-standAlone-narrow-morning1": "בוקר",
	"dayPeriods-standAlone-narrow-afternoon1": "צהריים",
	"dayPeriods-standAlone-narrow-afternoon2": "אחר הצהריים",
	"dayPeriods-standAlone-narrow-evening1": "ערב",
	"dayPeriods-standAlone-narrow-night1": "לילה",
	"dayPeriods-standAlone-narrow-night2": "לפנות בוקר",
	"dayPeriods-standAlone-wide-midnight": "חצות",
	"dayPeriods-standAlone-wide-morning1": "בוקר",
	"dayPeriods-standAlone-wide-afternoon1": "צהריים",
	"dayPeriods-standAlone-wide-afternoon2": "אחר הצהריים",
	"dayPeriods-standAlone-wide-evening1": "ערב",
	"dayPeriods-standAlone-wide-night1": "לילה",
	"dayPeriods-standAlone-wide-night2": "לפנות בוקר",
	"eraNames": [
		"לפני הספירה",
		"לספירה"
	],
	"eraAbbr": [
		"לפנה״ס",
		"לספירה"
	],
	"dateFormat-full": "EEEE, d בMMMM y",
	"dateFormat-long": "d בMMMM y",
	"dateFormat-medium": "d בMMM y",
	"dateFormat-short": "d.M.y",
	"timeFormat-full": "H:mm:ss zzzz",
	"timeFormat-long": "H:mm:ss z",
	"timeFormat-medium": "H:mm:ss",
	"timeFormat-short": "H:mm",
	"dateTimeFormat-full": "{1} בשעה {0}",
	"dateTimeFormat-long": "{1} בשעה {0}",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-d": "d",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E ה-d",
	"dateFormatItem-Ehm": "E h:mm a",
	"dateFormatItem-EHm": "E H:mm",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"dateFormatItem-EHms": "E H:mm:ss",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-GyMMMd": "d בMMM y G",
	"dateFormatItem-GyMMMEd": "E, d בMMM y G",
	"dateFormatItem-h": "‏h a",
	"dateFormatItem-H": "H",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-hmsv": "h:mm:ss a v",
	"dateFormatItem-Hmsv": "HH:mm:ss v",
	"dateFormatItem-hmv": "h:mm a v",
	"dateFormatItem-Hmv": "HH:mm v",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "d.M",
	"dateFormatItem-MEd": "E, d.M",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d בMMM",
	"dateFormatItem-MMMEd": "E, d בMMM",
	"dateFormatItem-MMMMd": "d בMMMM",
	"dateFormatItem-MMMMW": "שבוע W בMMM",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y",
	"dateFormatItem-yM": "M.y",
	"dateFormatItem-yMd": "d.M.y",
	"dateFormatItem-yMEd": "E, d.M.y",
	"dateFormatItem-yMM": "M.y",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yMMMd": "d בMMM y",
	"dateFormatItem-yMMMEd": "E, d בMMM y",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"dateFormatItem-yw": "שבוע w בשנת y",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-era": "תקופה",
	"field-year": "שנה",
	"field-year-relative+-1": "השנה שעברה",
	"field-year-relative+0": "השנה",
	"field-year-relative+1": "השנה הבאה",
	"field-year-short": "שנ׳",
	"field-year-narrow": "שנ׳",
	"field-quarter": "רבעון",
	"field-quarter-relative+-1": "הרבעון הקודם",
	"field-quarter-relative+0": "רבעון זה",
	"field-quarter-relative+1": "הרבעון הבא",
	"field-quarter-short": "רבע׳",
	"field-quarter-narrow": "רבע׳",
	"field-month": "חודש",
	"field-month-relative+-1": "החודש שעבר",
	"field-month-relative+0": "החודש",
	"field-month-relative+1": "החודש הבא",
	"field-month-short": "חו׳",
	"field-month-narrow": "חו׳",
	"field-week": "שבוע",
	"field-week-relative+-1": "השבוע שעבר",
	"field-week-relative+0": "השבוע",
	"field-week-relative+1": "השבוע הבא",
	"field-week-short": "שב׳",
	"field-week-narrow": "שב׳",
	"field-day": "יום",
	"field-day-relative+-2": "שלשום",
	"field-day-relative+-1": "אתמול",
	"field-day-relative+0": "היום",
	"field-day-relative+1": "מחר",
	"field-day-relative+2": "מחרתיים",
	"field-day-short": "יום",
	"field-day-narrow": "יום",
	"field-weekday": "יום בשבוע",
	"field-sun-relative+-1": "ביום ראשון שעבר",
	"field-sun-relative+0": "ביום ראשון הזה",
	"field-sun-relative+1": "ביום ראשון הבא",
	"field-sun-short-relative+-1": "יום א׳ שעבר",
	"field-sun-short-relative+0": "יום א׳",
	"field-sun-short-relative+1": "יום א׳ הבא",
	"field-sun-narrow-relative+-1": "יום א׳ שעבר",
	"field-sun-narrow-relative+0": "יום א׳",
	"field-sun-narrow-relative+1": "יום א׳ הבא",
	"field-mon-relative+-1": "יום שני שעבר",
	"field-mon-relative+0": "יום שני",
	"field-mon-relative+1": "יום שני הבא",
	"field-mon-short-relative+-1": "יום ב׳ שעבר",
	"field-mon-short-relative+0": "יום ב׳",
	"field-mon-short-relative+1": "יום ב׳ הבא",
	"field-mon-narrow-relative+-1": "יום ב׳ שעבר",
	"field-mon-narrow-relative+0": "יום ב׳",
	"field-mon-narrow-relative+1": "יום ב׳ הבא",
	"field-tue-relative+-1": "יום שלישי שעבר",
	"field-tue-relative+0": "יום שלישי",
	"field-tue-relative+1": "יום שלישי הבא",
	"field-tue-short-relative+-1": "יום ג׳ שעבר",
	"field-tue-short-relative+0": "יום ג׳",
	"field-tue-short-relative+1": "יום ג׳ הבא",
	"field-tue-narrow-relative+-1": "יום ג׳ שעבר",
	"field-tue-narrow-relative+0": "יום ג׳",
	"field-tue-narrow-relative+1": "יום ג׳ הבא",
	"field-wed-relative+-1": "יום רביעי שעבר",
	"field-wed-relative+0": "יום רביעי",
	"field-wed-relative+1": "יום רביעי הבא",
	"field-wed-short-relative+-1": "יום ד׳ שעבר",
	"field-wed-short-relative+0": "יום ד׳",
	"field-wed-short-relative+1": "יום ד׳ הבא",
	"field-wed-narrow-relative+-1": "יום ד׳ שעבר",
	"field-wed-narrow-relative+0": "יום ד׳",
	"field-wed-narrow-relative+1": "יום ד׳ הבא",
	"field-thu-relative+-1": "יום חמישי שעבר",
	"field-thu-relative+0": "יום חמישי",
	"field-thu-relative+1": "יום חמישי הבא",
	"field-thu-short-relative+-1": "יום ה׳ שעבר",
	"field-thu-short-relative+0": "יום ה׳",
	"field-thu-short-relative+1": "יום ה׳ הבא",
	"field-thu-narrow-relative+-1": "יום ה׳ שעבר",
	"field-thu-narrow-relative+0": "יום ה׳",
	"field-thu-narrow-relative+1": "יום ה׳ הבא",
	"field-fri-relative+-1": "יום שישי שעבר",
	"field-fri-relative+0": "יום שישי",
	"field-fri-relative+1": "יום שישי הבא",
	"field-fri-short-relative+-1": "יום ו׳ שעבר",
	"field-fri-short-relative+0": "יום ו׳",
	"field-fri-short-relative+1": "ביום ו׳ הבא",
	"field-fri-narrow-relative+-1": "יום ו׳ שעבר",
	"field-fri-narrow-relative+0": "יום ו׳",
	"field-fri-narrow-relative+1": "יום ו׳ הבא",
	"field-sat-relative+-1": "יום שבת שעבר",
	"field-sat-relative+0": "יום שבת",
	"field-sat-relative+1": "יום שבת הבא",
	"field-sat-short-relative+-1": "שבת שעברה",
	"field-sat-short-relative+0": "שבת",
	"field-sat-short-relative+1": "שבת הבאה",
	"field-sat-narrow-relative+-1": "שבת שעברה",
	"field-sat-narrow-relative+0": "שבת",
	"field-sat-narrow-relative+1": "שבת הבאה",
	"field-dayperiod": "לפנה״צ/אחה״צ",
	"field-hour": "שעה",
	"field-hour-relative+0": "בשעה זו",
	"field-hour-short": "שעה",
	"field-hour-narrow": "שע׳",
	"field-minute": "דקה",
	"field-minute-relative+0": "בדקה זו",
	"field-minute-short": "דק׳",
	"field-minute-narrow": "דק׳",
	"field-second": "שנייה",
	"field-second-relative+0": "עכשיו",
	"field-second-short": "שנ׳",
	"field-second-narrow": "שנ׳",
	"field-zone": "אזור",
	"eraNarrow": [
		"לפנה״ס",
		"לספירה"
	]
}
//end v1.x content
);