define(
//begin v1.x content
{
	"months-format-abbr": [
		"תשרי",
		"חשון",
		"כסלו",
		"טבת",
		"שבט",
		"אדר א׳",
		"אדר",
		"ניסן",
		"אייר",
		"סיון",
		"תמוז",
		"אב",
		"אלול"
	],
	"months-format-abbr-leap": "אדר ב׳",
	"months-format-narrow": [
		"תש׳",
		"חש׳",
		"כס׳",
		"טב׳",
		"שב׳",
		"א״א",
		"אד׳",
		"ני׳",
		"אי׳",
		"סי׳",
		"תמ׳",
		"אב",
		"אל׳"
	],
	"months-format-narrow-leap": "א״ב",
	"months-format-wide": [
		"תשרי",
		"חשוון",
		"כסלו",
		"טבת",
		"שבט",
		"אדר א׳",
		"אדר",
		"ניסן",
		"אייר",
		"סיוון",
		"תמוז",
		"אב",
		"אלול"
	],
	"months-format-wide-leap": "אדר ב׳",
	"months-standAlone-abbr": [
		"תשרי",
		"חשון",
		"כסלו",
		"טבת",
		"שבט",
		"אדר א׳",
		"אדר",
		"ניסן",
		"אייר",
		"סיון",
		"תמוז",
		"אב",
		"אלול"
	],
	"months-standAlone-abbr-leap": "אדר ב׳",
	"months-standAlone-narrow": [
		"תש׳",
		"חש׳",
		"כס׳",
		"טב׳",
		"שב׳",
		"א״א",
		"אד׳",
		"ני׳",
		"אי׳",
		"סי׳",
		"תמ׳",
		"אב",
		"אל׳"
	],
	"months-standAlone-narrow-leap": "א״ב",
	"months-standAlone-wide": [
		"תשרי",
		"חשוון",
		"כסלו",
		"טבת",
		"שבט",
		"אדר א׳",
		"אדר",
		"ניסן",
		"אייר",
		"סיוון",
		"תמוז",
		"אב",
		"אלול"
	],
	"months-standAlone-wide-leap": "אדר ב׳",
	"eraAbbr": [
		"לבה״ע"
	],
	"dateFormat-full": "EEEE, d בMMMM y",
	"dateFormat-long": "d בMMMM y",
	"dateFormat-medium": "d בMMMM y",
	"dateFormat-short": "d בMMMM y",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "MMMM y G",
	"dateFormatItem-GyMMMd": "d בMMMM y G",
	"dateFormatItem-GyMMMEd": "E, d בMMMM y G",
	"dateFormatItem-M": "MMMM",
	"dateFormatItem-Md": "d בMMMM",
	"dateFormatItem-MEd": "E, d בMMMM",
	"dateFormatItem-MMM": "MMMM",
	"dateFormatItem-MMMd": "d בMMMM",
	"dateFormatItem-MMMEd": "E, d בMMMM",
	"dateFormatItem-MMMMd": "d בMMMM",
	"dateFormatItem-MMMMEd": "E, d בMMMM",
	"dateFormatItem-yyyyM": "MMMM y",
	"dateFormatItem-yyyyMd": "d בMMMM y",
	"dateFormatItem-yyyyMEd": "E, d בMMMM y",
	"dateFormatItem-yyyyMMM": "MMMM y",
	"dateFormatItem-yyyyMMMd": "d בMMMM y",
	"dateFormatItem-yyyyMMMEd": "E, d בMMMM y",
	"dateFormatItem-yyyyMMMM": "MMMM y",
	"field-era": "תקופה",
	"field-year": "שנה",
	"field-year-relative+-1": "השנה שעברה",
	"field-year-relative+0": "השנה",
	"field-year-relative+1": "השנה הבאה",
	"field-year-short": "שנ׳",
	"field-year-narrow": "שנ׳",
	"field-quarter": "רבעון",
	"field-quarter-relative+-1": "הרבעון הקודם",
	"field-quarter-relative+0": "רבעון זה",
	"field-quarter-relative+1": "הרבעון הבא",
	"field-quarter-short": "רבע׳",
	"field-quarter-narrow": "רבע׳",
	"field-month": "חודש",
	"field-month-relative+-1": "החודש שעבר",
	"field-month-relative+0": "החודש",
	"field-month-relative+1": "החודש הבא",
	"field-month-short": "חו׳",
	"field-month-narrow": "חו׳",
	"field-week": "שבוע",
	"field-week-relative+-1": "השבוע שעבר",
	"field-week-relative+0": "השבוע",
	"field-week-relative+1": "השבוע הבא",
	"field-week-short": "שב׳",
	"field-week-narrow": "שב׳",
	"field-day": "יום",
	"field-day-relative+-2": "שלשום",
	"field-day-relative+-1": "אתמול",
	"field-day-relative+0": "היום",
	"field-day-relative+1": "מחר",
	"field-day-relative+2": "מחרתיים",
	"field-day-short": "יום",
	"field-day-narrow": "יום",
	"field-weekday": "יום בשבוע",
	"field-sun-relative+-1": "ביום ראשון שעבר",
	"field-sun-relative+0": "ביום ראשון הזה",
	"field-sun-relative+1": "ביום ראשון הבא",
	"field-sun-short-relative+-1": "יום א׳ שעבר",
	"field-sun-short-relative+0": "יום א׳",
	"field-sun-short-relative+1": "יום א׳ הבא",
	"field-sun-narrow-relative+-1": "יום א׳ שעבר",
	"field-sun-narrow-relative+0": "יום א׳",
	"field-sun-narrow-relative+1": "יום א׳ הבא",
	"field-mon-relative+-1": "יום שני שעבר",
	"field-mon-relative+0": "יום שני",
	"field-mon-relative+1": "יום שני הבא",
	"field-mon-short-relative+-1": "יום ב׳ שעבר",
	"field-mon-short-relative+0": "יום ב׳",
	"field-mon-short-relative+1": "יום ב׳ הבא",
	"field-mon-narrow-relative+-1": "יום ב׳ שעבר",
	"field-mon-narrow-relative+0": "יום ב׳",
	"field-mon-narrow-relative+1": "יום ב׳ הבא",
	"field-tue-relative+-1": "יום שלישי שעבר",
	"field-tue-relative+0": "יום שלישי",
	"field-tue-relative+1": "יום שלישי הבא",
	"field-tue-short-relative+-1": "יום ג׳ שעבר",
	"field-tue-short-relative+0": "יום ג׳",
	"field-tue-short-relative+1": "יום ג׳ הבא",
	"field-tue-narrow-relative+-1": "יום ג׳ שעבר",
	"field-tue-narrow-relative+0": "יום ג׳",
	"field-tue-narrow-relative+1": "יום ג׳ הבא",
	"field-wed-relative+-1": "יום רביעי שעבר",
	"field-wed-relative+0": "יום רביעי",
	"field-wed-relative+1": "יום רביעי הבא",
	"field-wed-short-relative+-1": "יום ד׳ שעבר",
	"field-wed-short-relative+0": "יום ד׳",
	"field-wed-short-relative+1": "יום ד׳ הבא",
	"field-wed-narrow-relative+-1": "יום ד׳ שעבר",
	"field-wed-narrow-relative+0": "יום ד׳",
	"field-wed-narrow-relative+1": "יום ד׳ הבא",
	"field-thu-relative+-1": "יום חמישי שעבר",
	"field-thu-relative+0": "יום חמישי",
	"field-thu-relative+1": "יום חמישי הבא",
	"field-thu-short-relative+-1": "יום ה׳ שעבר",
	"field-thu-short-relative+0": "יום ה׳",
	"field-thu-short-relative+1": "יום ה׳ הבא",
	"field-thu-narrow-relative+-1": "יום ה׳ שעבר",
	"field-thu-narrow-relative+0": "יום ה׳",
	"field-thu-narrow-relative+1": "יום ה׳ הבא",
	"field-fri-relative+-1": "יום שישי שעבר",
	"field-fri-relative+0": "יום שישי",
	"field-fri-relative+1": "יום שישי הבא",
	"field-fri-short-relative+-1": "יום ו׳ שעבר",
	"field-fri-short-relative+0": "יום ו׳",
	"field-fri-short-relative+1": "ביום ו׳ הבא",
	"field-fri-narrow-relative+-1": "יום ו׳ שעבר",
	"field-fri-narrow-relative+0": "יום ו׳",
	"field-fri-narrow-relative+1": "יום ו׳ הבא",
	"field-sat-relative+-1": "יום שבת שעבר",
	"field-sat-relative+0": "יום שבת",
	"field-sat-relative+1": "יום שבת הבא",
	"field-sat-short-relative+-1": "שבת שעברה",
	"field-sat-short-relative+0": "שבת",
	"field-sat-short-relative+1": "שבת הבאה",
	"field-sat-narrow-relative+-1": "שבת שעברה",
	"field-sat-narrow-relative+0": "שבת",
	"field-sat-narrow-relative+1": "שבת הבאה",
	"field-dayperiod": "לפנה״צ/אחה״צ",
	"field-hour": "שעה",
	"field-hour-relative+0": "בשעה זו",
	"field-hour-short": "שעה",
	"field-hour-narrow": "שע׳",
	"field-minute": "דקה",
	"field-minute-relative+0": "בדקה זו",
	"field-minute-short": "דק׳",
	"field-minute-narrow": "דק׳",
	"field-second": "שנייה",
	"field-second-relative+0": "עכשיו",
	"field-second-short": "שנ׳",
	"field-second-narrow": "שנ׳",
	"field-zone": "אזור",
	"eraNames": [
		"לבה״ע"
	],
	"eraNarrow": [
		"לבה״ע"
	],
	"days-format-abbr": [
		"יום א׳",
		"יום ב׳",
		"יום ג׳",
		"יום ד׳",
		"יום ה׳",
		"יום ו׳",
		"שבת"
	],
	"days-format-narrow": [
		"א׳",
		"ב׳",
		"ג׳",
		"ד׳",
		"ה׳",
		"ו׳",
		"ש׳"
	],
	"days-format-short": [
		"א׳",
		"ב׳",
		"ג׳",
		"ד׳",
		"ה׳",
		"ו׳",
		"ש׳"
	],
	"days-format-wide": [
		"יום ראשון",
		"יום שני",
		"יום שלישי",
		"יום רביעי",
		"יום חמישי",
		"יום שישי",
		"יום שבת"
	],
	"days-standAlone-abbr": [
		"יום א׳",
		"יום ב׳",
		"יום ג׳",
		"יום ד׳",
		"יום ה׳",
		"יום ו׳",
		"שבת"
	],
	"days-standAlone-narrow": [
		"א׳",
		"ב׳",
		"ג׳",
		"ד׳",
		"ה׳",
		"ו׳",
		"ש׳"
	],
	"days-standAlone-short": [
		"א׳",
		"ב׳",
		"ג׳",
		"ד׳",
		"ה׳",
		"ו׳",
		"ש׳"
	],
	"days-standAlone-wide": [
		"יום ראשון",
		"יום שני",
		"יום שלישי",
		"יום רביעי",
		"יום חמישי",
		"יום שישי",
		"יום שבת"
	],
	"quarters-format-wide": [
		"רבעון 1",
		"רבעון 2",
		"רבעון 3",
		"רבעון 4"
	],
	"quarters-standAlone-wide": [
		"רבעון 1",
		"רבעון 2",
		"רבעון 3",
		"רבעון 4"
	],
	"dayPeriods-format-abbr-am": "לפנה״צ",
	"dayPeriods-format-abbr-pm": "אחה״צ",
	"dayPeriods-format-wide-am": "לפנה״צ",
	"dayPeriods-format-wide-pm": "אחה״צ",
	"dateFormatItem-Ed": "E ה-d",
	"dateFormatItem-h": "‏h a",
	"dateFormatItem-H": "H",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"timeFormat-full": "H:mm:ss zzzz",
	"timeFormat-long": "H:mm:ss z",
	"timeFormat-medium": "H:mm:ss",
	"timeFormat-short": "H:mm",
	"dateTimeFormat-full": "{1} בשעה {0}",
	"dateTimeFormat-long": "{1} בשעה {0}",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateTimeFormat-short": "{1}, {0}"
}
//end v1.x content
);