define(
//begin v1.x content
{
	"eraNames": [
		"仏暦"
	],
	"eraAbbr": [
		"BE"
	],
	"dateFormat-full": "GGGGy年M月d日EEEE",
	"dateFormat-long": "GGGGy年M月d日",
	"dateFormat-medium": "Gy/MM/dd",
	"dateFormat-short": "Gy/MM/dd",
	"dateFormatItem-d": "d日",
	"dateFormatItem-Ed": "d日(E)",
	"dateFormatItem-EEEEd": "d日EEEE",
	"dateFormatItem-Gy": "GGGGy年",
	"dateFormatItem-GyMd": "GGGGy年M月d日",
	"dateFormatItem-GyMMM": "GGGGy年M月",
	"dateFormatItem-GyMMMd": "GGGGy年M月d日",
	"dateFormatItem-GyMMMEd": "GGGGy年M月d日(E)",
	"dateFormatItem-GyMMMEEEEd": "GGGGy年M月d日EEEE",
	"dateFormatItem-h": "aK時",
	"dateFormatItem-H": "H時",
	"dateFormatItem-hm": "aK:mm",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-hms": "aK:mm:ss",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-M": "M月",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-MEd": "M/d(E)",
	"dateFormatItem-MEEEEd": "M/dEEEE",
	"dateFormatItem-MMM": "M月",
	"dateFormatItem-MMMd": "M月d日",
	"dateFormatItem-MMMEd": "M月d日(E)",
	"dateFormatItem-MMMEEEEd": "M月d日EEEE",
	"dateFormatItem-MMMMd": "M月d日",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "GGGGy年",
	"dateFormatItem-yyyy": "GGGGy年",
	"dateFormatItem-yyyyM": "GGGGy年M月",
	"dateFormatItem-yyyyMd": "Gy/M/d",
	"dateFormatItem-yyyyMEd": "GGGGy年M/d(E)",
	"dateFormatItem-yyyyMEEEEd": "GGGGy年M/dEEEE",
	"dateFormatItem-yyyyMM": "Gy/MM",
	"dateFormatItem-yyyyMMM": "GGGGy年M月",
	"dateFormatItem-yyyyMMMd": "GGGGy年M月d日",
	"dateFormatItem-yyyyMMMEd": "GGGGy年M月d日(E)",
	"dateFormatItem-yyyyMMMEEEEd": "GGGGy年M月d日EEEE",
	"dateFormatItem-yyyyMMMM": "GGGGy年M月",
	"field-era": "時代",
	"field-year": "年",
	"field-year-relative+-1": "昨年",
	"field-year-relative+0": "今年",
	"field-year-relative+1": "翌年",
	"field-year-short": "年",
	"field-year-short-relative+-1": "昨年",
	"field-year-short-relative+0": "今年",
	"field-year-short-relative+1": "翌年",
	"field-year-narrow": "年",
	"field-year-narrow-relative+-1": "昨年",
	"field-year-narrow-relative+0": "今年",
	"field-year-narrow-relative+1": "翌年",
	"field-quarter": "四半期",
	"field-quarter-relative+-1": "前四半期",
	"field-quarter-relative+0": "今四半期",
	"field-quarter-relative+1": "翌四半期",
	"field-quarter-short": "四半期",
	"field-quarter-narrow": "四半期",
	"field-month": "月",
	"field-month-relative+-1": "先月",
	"field-month-relative+0": "今月",
	"field-month-relative+1": "翌月",
	"field-month-short": "月",
	"field-month-short-relative+-1": "先月",
	"field-month-short-relative+0": "今月",
	"field-month-short-relative+1": "翌月",
	"field-month-narrow": "月",
	"field-month-narrow-relative+-1": "先月",
	"field-month-narrow-relative+0": "今月",
	"field-month-narrow-relative+1": "翌月",
	"field-week": "週",
	"field-week-relative+-1": "先週",
	"field-week-relative+0": "今週",
	"field-week-relative+1": "翌週",
	"field-week-short": "週",
	"field-week-short-relative+-1": "先週",
	"field-week-short-relative+0": "今週",
	"field-week-short-relative+1": "翌週",
	"field-week-narrow": "週",
	"field-week-narrow-relative+-1": "先週",
	"field-week-narrow-relative+0": "今週",
	"field-week-narrow-relative+1": "翌週",
	"field-day": "日",
	"field-day-relative+-2": "一昨日",
	"field-day-relative+-1": "昨日",
	"field-day-relative+0": "今日",
	"field-day-relative+1": "明日",
	"field-day-relative+2": "明後日",
	"field-day-short": "日",
	"field-day-short-relative+-2": "一昨日",
	"field-day-short-relative+-1": "昨日",
	"field-day-short-relative+0": "今日",
	"field-day-short-relative+1": "明日",
	"field-day-short-relative+2": "明後日",
	"field-day-narrow": "日",
	"field-day-narrow-relative+-2": "一昨日",
	"field-day-narrow-relative+-1": "昨日",
	"field-day-narrow-relative+0": "今日",
	"field-day-narrow-relative+1": "明日",
	"field-day-narrow-relative+2": "明後日",
	"field-weekday": "曜日",
	"field-sun-relative+-1": "先週の日曜日",
	"field-sun-relative+0": "今週の日曜日",
	"field-sun-relative+1": "来週の日曜日",
	"field-sun-short-relative+-1": "先週の日曜",
	"field-sun-short-relative+0": "今週の日曜",
	"field-sun-short-relative+1": "来週の日曜",
	"field-sun-narrow-relative+-1": "先週の日曜",
	"field-sun-narrow-relative+0": "今週の日曜",
	"field-sun-narrow-relative+1": "来週の日曜",
	"field-mon-relative+-1": "先週の月曜日",
	"field-mon-relative+0": "今週の月曜日",
	"field-mon-relative+1": "来週の月曜日",
	"field-mon-short-relative+-1": "先週の月曜",
	"field-mon-short-relative+0": "今週の月曜",
	"field-mon-short-relative+1": "来週の月曜",
	"field-mon-narrow-relative+-1": "先週の月曜",
	"field-mon-narrow-relative+0": "今週の月曜",
	"field-mon-narrow-relative+1": "来週の月曜",
	"field-tue-relative+-1": "先週の火曜日",
	"field-tue-relative+0": "今週の火曜日",
	"field-tue-relative+1": "来週の火曜日",
	"field-tue-short-relative+-1": "先週の火曜",
	"field-tue-short-relative+0": "今週の火曜",
	"field-tue-short-relative+1": "来週の火曜",
	"field-tue-narrow-relative+-1": "先週の火曜",
	"field-tue-narrow-relative+0": "今週の火曜",
	"field-tue-narrow-relative+1": "来週の火曜",
	"field-wed-relative+-1": "先週の水曜日",
	"field-wed-relative+0": "今週の水曜日",
	"field-wed-relative+1": "来週の水曜日",
	"field-wed-short-relative+-1": "先週の水曜",
	"field-wed-short-relative+0": "今週の水曜",
	"field-wed-short-relative+1": "来週の水曜",
	"field-wed-narrow-relative+-1": "先週の水曜",
	"field-wed-narrow-relative+0": "今週の水曜",
	"field-wed-narrow-relative+1": "来週の水曜",
	"field-thu-relative+-1": "先週の木曜日",
	"field-thu-relative+0": "今週の木曜日",
	"field-thu-relative+1": "来週の木曜日",
	"field-thu-short-relative+-1": "先週の木曜",
	"field-thu-short-relative+0": "今週の木曜",
	"field-thu-short-relative+1": "来週の木曜",
	"field-thu-narrow-relative+-1": "先週の木曜",
	"field-thu-narrow-relative+0": "今週の木曜",
	"field-thu-narrow-relative+1": "来週の木曜",
	"field-fri-relative+-1": "先週の金曜日",
	"field-fri-relative+0": "今週の金曜日",
	"field-fri-relative+1": "来週の金曜日",
	"field-fri-short-relative+-1": "先週の金曜",
	"field-fri-short-relative+0": "今週の金曜",
	"field-fri-short-relative+1": "来週の金曜",
	"field-fri-narrow-relative+-1": "先週の金曜",
	"field-fri-narrow-relative+0": "今週の金曜",
	"field-fri-narrow-relative+1": "来週の金曜",
	"field-sat-relative+-1": "先週の土曜日",
	"field-sat-relative+0": "今週の土曜日",
	"field-sat-relative+1": "来週の土曜日",
	"field-sat-short-relative+-1": "先週の土曜",
	"field-sat-short-relative+0": "今週の土曜",
	"field-sat-short-relative+1": "来週の土曜",
	"field-sat-narrow-relative+-1": "先週の土曜",
	"field-sat-narrow-relative+0": "今週の土曜",
	"field-sat-narrow-relative+1": "来週の土曜",
	"field-dayperiod": "午前/午後",
	"field-hour": "時",
	"field-hour-relative+0": "1 時間以内",
	"field-hour-short": "時",
	"field-hour-narrow": "時",
	"field-minute": "分",
	"field-minute-relative+0": "1 分以内",
	"field-minute-short": "分",
	"field-minute-narrow": "分",
	"field-second": "秒",
	"field-second-relative+0": "今",
	"field-second-short": "秒",
	"field-second-narrow": "秒",
	"field-zone": "タイムゾーン",
	"days-format-abbr": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"days-format-narrow": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"days-format-short": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"days-format-wide": [
		"日曜日",
		"月曜日",
		"火曜日",
		"水曜日",
		"木曜日",
		"金曜日",
		"土曜日"
	],
	"days-standAlone-abbr": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"days-standAlone-narrow": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"days-standAlone-short": [
		"日",
		"月",
		"火",
		"水",
		"木",
		"金",
		"土"
	],
	"days-standAlone-wide": [
		"日曜日",
		"月曜日",
		"火曜日",
		"水曜日",
		"木曜日",
		"金曜日",
		"土曜日"
	],
	"quarters-format-wide": [
		"第1四半期",
		"第2四半期",
		"第3四半期",
		"第4四半期"
	],
	"quarters-standAlone-wide": [
		"第1四半期",
		"第2四半期",
		"第3四半期",
		"第4四半期"
	],
	"dayPeriods-format-abbr-am": "午前",
	"dayPeriods-format-abbr-pm": "午後",
	"dayPeriods-format-narrow-am": "午前",
	"dayPeriods-format-narrow-pm": "午後",
	"dayPeriods-format-wide-am": "午前",
	"dayPeriods-format-wide-pm": "午後",
	"dayPeriods-standAlone-abbr-am": "午前",
	"dayPeriods-standAlone-abbr-pm": "午後",
	"dayPeriods-standAlone-narrow-am": "午前",
	"dayPeriods-standAlone-narrow-pm": "午後",
	"dayPeriods-standAlone-wide-am": "午前",
	"dayPeriods-standAlone-wide-pm": "午後",
	"dateFormatItem-yyyyQQQ": "Gy/QQQ",
	"dateFormatItem-yyyyQQQQ": "Gy年QQQQ",
	"timeFormat-full": "H時mm分ss秒 zzzz",
	"timeFormat-long": "H:mm:ss z",
	"timeFormat-medium": "H:mm:ss",
	"timeFormat-short": "H:mm",
	"months-format-abbr": [
		"1月",
		"2月",
		"3月",
		"4月",
		"5月",
		"6月",
		"7月",
		"8月",
		"9月",
		"10月",
		"11月",
		"12月"
	],
	"months-format-wide": [
		"1月",
		"2月",
		"3月",
		"4月",
		"5月",
		"6月",
		"7月",
		"8月",
		"9月",
		"10月",
		"11月",
		"12月"
	],
	"months-standAlone-abbr": [
		"1月",
		"2月",
		"3月",
		"4月",
		"5月",
		"6月",
		"7月",
		"8月",
		"9月",
		"10月",
		"11月",
		"12月"
	],
	"months-standAlone-wide": [
		"1月",
		"2月",
		"3月",
		"4月",
		"5月",
		"6月",
		"7月",
		"8月",
		"9月",
		"10月",
		"11月",
		"12月"
	]
}
//end v1.x content
);