define(
//begin v1.x content
{
	"months-format-wide": [
		"Tût",
		"Bâbe",
		"Hatur",
		"Keyhek",
		"Tûbe",
		"Imşir",
		"Bermuhat",
		"Bermude",
		"Peyştes",
		"Bune",
		"Ebip",
		"Mısrî",
		"Nesî"
	],
	"field-era": "Miladi Dönem",
	"field-year": "yıl",
	"field-year-relative+-1": "geçen yıl",
	"field-year-relative+0": "bu yıl",
	"field-year-relative+1": "gelecek yıl",
	"field-year-short": "yıl",
	"field-year-short-relative+-1": "geçen yıl",
	"field-year-short-relative+0": "bu yıl",
	"field-year-short-relative+1": "gelecek yıl",
	"field-year-narrow": "yıl",
	"field-year-narrow-relative+-1": "geçen yıl",
	"field-year-narrow-relative+0": "bu yıl",
	"field-year-narrow-relative+1": "gelecek yıl",
	"field-quarter": "çeyrek",
	"field-quarter-relative+-1": "geçen çeyrek",
	"field-quarter-relative+0": "bu çeyrek",
	"field-quarter-relative+1": "gelecek çeyrek",
	"field-quarter-short": "çyr.",
	"field-quarter-narrow": "çyr.",
	"field-month": "ay",
	"field-month-relative+-1": "geçen ay",
	"field-month-relative+0": "bu ay",
	"field-month-relative+1": "gelecek ay",
	"field-month-short": "ay",
	"field-month-short-relative+-1": "geçen ay",
	"field-month-short-relative+0": "bu ay",
	"field-month-short-relative+1": "gelecek ay",
	"field-month-narrow": "ay",
	"field-month-narrow-relative+-1": "geçen ay",
	"field-month-narrow-relative+0": "bu ay",
	"field-month-narrow-relative+1": "gelecek ay",
	"field-week": "hafta",
	"field-week-relative+-1": "geçen hafta",
	"field-week-relative+0": "bu hafta",
	"field-week-relative+1": "gelecek hafta",
	"field-week-short": "hf.",
	"field-week-narrow": "hf.",
	"field-day": "gün",
	"field-day-relative+-2": "evvelsi gün",
	"field-day-relative+-1": "dün",
	"field-day-relative+0": "bugün",
	"field-day-relative+1": "yarın",
	"field-day-relative+2": "öbür gün",
	"field-day-short": "gün",
	"field-day-short-relative+-2": "evvelsi gün",
	"field-day-short-relative+-1": "dün",
	"field-day-short-relative+0": "bugün",
	"field-day-short-relative+1": "yarın",
	"field-day-short-relative+2": "öbür gün",
	"field-day-narrow": "gün",
	"field-day-narrow-relative+-2": "evvelsi gün",
	"field-day-narrow-relative+-1": "dün",
	"field-day-narrow-relative+0": "bugün",
	"field-day-narrow-relative+1": "yarın",
	"field-day-narrow-relative+2": "öbür gün",
	"field-weekday": "haftanın günü",
	"field-sun-relative+-1": "geçen pazar",
	"field-sun-relative+0": "bu pazar",
	"field-sun-relative+1": "gelecek pazar",
	"field-sun-short-relative+-1": "geçen paz.",
	"field-sun-short-relative+0": "bu paz.",
	"field-sun-short-relative+1": "gelecek paz.",
	"field-sun-narrow-relative+-1": "geçen paz.",
	"field-sun-narrow-relative+0": "bu paz.",
	"field-sun-narrow-relative+1": "gelecek paz.",
	"field-mon-relative+-1": "geçen pazartesi",
	"field-mon-relative+0": "bu pazartesi",
	"field-mon-relative+1": "gelecek pazartesi",
	"field-mon-short-relative+-1": "geçen pzt.",
	"field-mon-short-relative+0": "bu pzt.",
	"field-mon-short-relative+1": "gelecek pzt.",
	"field-mon-narrow-relative+-1": "geçen pzt.",
	"field-mon-narrow-relative+0": "bu pzt.",
	"field-mon-narrow-relative+1": "gelecek pzt.",
	"field-tue-relative+-1": "geçen salı",
	"field-tue-relative+0": "bu salı",
	"field-tue-relative+1": "gelecek salı",
	"field-tue-short-relative+-1": "geçen salı",
	"field-tue-short-relative+0": "bu salı",
	"field-tue-short-relative+1": "gelecek salı",
	"field-tue-narrow-relative+-1": "geçen salı",
	"field-tue-narrow-relative+0": "bu salı",
	"field-tue-narrow-relative+1": "gelecek salı",
	"field-wed-relative+-1": "geçen çarşamba",
	"field-wed-relative+0": "bu çarşamba",
	"field-wed-relative+1": "gelecek çarşamba",
	"field-wed-short-relative+-1": "geçen çar.",
	"field-wed-short-relative+0": "bu çar.",
	"field-wed-short-relative+1": "gelecek çar.",
	"field-wed-narrow-relative+-1": "geçen çar.",
	"field-wed-narrow-relative+0": "bu çar.",
	"field-wed-narrow-relative+1": "gelecek çar.",
	"field-thu-relative+-1": "geçen perşembe",
	"field-thu-relative+0": "bu perşembe",
	"field-thu-relative+1": "gelecek perşembe",
	"field-thu-short-relative+-1": "geçen per.",
	"field-thu-short-relative+0": "bu per.",
	"field-thu-short-relative+1": "gelecek per.",
	"field-thu-narrow-relative+-1": "geçen per.",
	"field-thu-narrow-relative+0": "bu per.",
	"field-thu-narrow-relative+1": "gelecek per.",
	"field-fri-relative+-1": "geçen cuma",
	"field-fri-relative+0": "bu cuma",
	"field-fri-relative+1": "gelecek cuma",
	"field-fri-short-relative+-1": "geçen cuma",
	"field-fri-short-relative+0": "bu cuma",
	"field-fri-short-relative+1": "gelecek cuma",
	"field-fri-narrow-relative+-1": "geçen cuma",
	"field-fri-narrow-relative+0": "bu cuma",
	"field-fri-narrow-relative+1": "gelecek cuma",
	"field-sat-relative+-1": "geçen cumartesi",
	"field-sat-relative+0": "bu cumartesi",
	"field-sat-relative+1": "gelecek cumartesi",
	"field-sat-short-relative+-1": "geçen cmt.",
	"field-sat-short-relative+0": "bu cmt.",
	"field-sat-short-relative+1": "gelecek cmt.",
	"field-sat-narrow-relative+-1": "geçen cmt.",
	"field-sat-narrow-relative+0": "bu cmt.",
	"field-sat-narrow-relative+1": "gelecek cmt.",
	"field-dayperiod": "ÖÖ/ÖS",
	"field-hour": "saat",
	"field-hour-relative+0": "bu saat",
	"field-hour-short": "sa.",
	"field-hour-narrow": "sa.",
	"field-minute": "dakika",
	"field-minute-relative+0": "bu dakika",
	"field-minute-short": "dk.",
	"field-minute-narrow": "dk.",
	"field-second": "saniye",
	"field-second-relative+0": "şimdi",
	"field-second-short": "sn.",
	"field-second-narrow": "sn.",
	"field-zone": "saat dilimi"
}
//end v1.x content
);