define(
//begin v1.x content
{
	"months-format-abbr": [
		"Oca",
		"Şub",
		"Mar",
		"Nis",
		"May",
		"Haz",
		"Tem",
		"Ağu",
		"Eyl",
		"Eki",
		"Kas",
		"Ara"
	],
	"months-format-narrow": [
		"O",
		"Ş",
		"M",
		"N",
		"M",
		"H",
		"T",
		"A",
		"E",
		"E",
		"K",
		"A"
	],
	"months-format-wide": [
		"Ocak",
		"Şubat",
		"Mart",
		"Nisan",
		"Mayıs",
		"Haziran",
		"Temmuz",
		"Ağustos",
		"Eylül",
		"Ekim",
		"Kasım",
		"Aralık"
	],
	"months-standAlone-abbr": [
		"Oca",
		"Şub",
		"Mar",
		"Nis",
		"May",
		"Haz",
		"Tem",
		"Ağu",
		"Eyl",
		"Eki",
		"Kas",
		"Ara"
	],
	"months-standAlone-narrow": [
		"O",
		"Ş",
		"M",
		"N",
		"M",
		"H",
		"T",
		"A",
		"E",
		"E",
		"K",
		"A"
	],
	"months-standAlone-wide": [
		"Ocak",
		"Şubat",
		"Mart",
		"Nisan",
		"Mayıs",
		"Haziran",
		"Temmuz",
		"Ağustos",
		"Eylül",
		"Ekim",
		"Kasım",
		"Aralık"
	],
	"days-format-abbr": [
		"Paz",
		"Pzt",
		"Sal",
		"Çar",
		"Per",
		"Cum",
		"Cmt"
	],
	"days-format-narrow": [
		"P",
		"P",
		"S",
		"Ç",
		"P",
		"C",
		"C"
	],
	"days-format-short": [
		"Pa",
		"Pt",
		"Sa",
		"Ça",
		"Pe",
		"Cu",
		"Ct"
	],
	"days-format-wide": [
		"Pazar",
		"Pazartesi",
		"Salı",
		"Çarşamba",
		"Perşembe",
		"Cuma",
		"Cumartesi"
	],
	"days-standAlone-abbr": [
		"Paz",
		"Pzt",
		"Sal",
		"Çar",
		"Per",
		"Cum",
		"Cmt"
	],
	"days-standAlone-narrow": [
		"P",
		"P",
		"S",
		"Ç",
		"P",
		"C",
		"C"
	],
	"days-standAlone-short": [
		"Pa",
		"Pt",
		"Sa",
		"Ça",
		"Pe",
		"Cu",
		"Ct"
	],
	"days-standAlone-wide": [
		"Pazar",
		"Pazartesi",
		"Salı",
		"Çarşamba",
		"Perşembe",
		"Cuma",
		"Cumartesi"
	],
	"quarters-format-abbr": [
		"Ç1",
		"Ç2",
		"Ç3",
		"Ç4"
	],
	"quarters-format-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"quarters-format-wide": [
		"1. çeyrek",
		"2. çeyrek",
		"3. çeyrek",
		"4. çeyrek"
	],
	"quarters-standAlone-abbr": [
		"Ç1",
		"Ç2",
		"Ç3",
		"Ç4"
	],
	"quarters-standAlone-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"quarters-standAlone-wide": [
		"1. çeyrek",
		"2. çeyrek",
		"3. çeyrek",
		"4. çeyrek"
	],
	"dayPeriods-format-abbr-midnight": "gece yarısı",
	"dayPeriods-format-abbr-am": "ÖÖ",
	"dayPeriods-format-abbr-noon": "öğle",
	"dayPeriods-format-abbr-pm": "ÖS",
	"dayPeriods-format-abbr-morning1": "sabah",
	"dayPeriods-format-abbr-morning2": "öğleden önce",
	"dayPeriods-format-abbr-afternoon1": "öğleden sonra",
	"dayPeriods-format-abbr-afternoon2": "akşamüstü",
	"dayPeriods-format-abbr-evening1": "akşam",
	"dayPeriods-format-abbr-night1": "gece",
	"dayPeriods-format-narrow-midnight": "gece",
	"dayPeriods-format-narrow-am": "öö",
	"dayPeriods-format-narrow-noon": "ö",
	"dayPeriods-format-narrow-pm": "ös",
	"dayPeriods-format-narrow-morning1": "sabah",
	"dayPeriods-format-narrow-morning2": "öğleden önce",
	"dayPeriods-format-narrow-afternoon1": "öğleden sonra",
	"dayPeriods-format-narrow-afternoon2": "akşamüstü",
	"dayPeriods-format-narrow-evening1": "akşam",
	"dayPeriods-format-narrow-night1": "gece",
	"dayPeriods-format-wide-midnight": "gece yarısı",
	"dayPeriods-format-wide-am": "ÖÖ",
	"dayPeriods-format-wide-noon": "öğle",
	"dayPeriods-format-wide-pm": "ÖS",
	"dayPeriods-format-wide-morning1": "sabah",
	"dayPeriods-format-wide-morning2": "öğleden önce",
	"dayPeriods-format-wide-afternoon1": "öğleden sonra",
	"dayPeriods-format-wide-afternoon2": "akşamüstü",
	"dayPeriods-format-wide-evening1": "akşam",
	"dayPeriods-format-wide-night1": "gece",
	"dayPeriods-standAlone-abbr-midnight": "gece yarısı",
	"dayPeriods-standAlone-abbr-am": "ÖÖ",
	"dayPeriods-standAlone-abbr-noon": "öğle",
	"dayPeriods-standAlone-abbr-pm": "ÖS",
	"dayPeriods-standAlone-abbr-morning1": "sabah",
	"dayPeriods-standAlone-abbr-morning2": "öğleden önce",
	"dayPeriods-standAlone-abbr-afternoon1": "öğleden sonra",
	"dayPeriods-standAlone-abbr-afternoon2": "akşamüstü",
	"dayPeriods-standAlone-abbr-evening1": "akşam",
	"dayPeriods-standAlone-abbr-night1": "gece",
	"dayPeriods-standAlone-narrow-midnight": "gece yarısı",
	"dayPeriods-standAlone-narrow-am": "ÖÖ",
	"dayPeriods-standAlone-narrow-noon": "öğle",
	"dayPeriods-standAlone-narrow-pm": "ÖS",
	"dayPeriods-standAlone-narrow-morning1": "sabah",
	"dayPeriods-standAlone-narrow-morning2": "öğleden önce",
	"dayPeriods-standAlone-narrow-afternoon1": "öğleden sonra",
	"dayPeriods-standAlone-narrow-afternoon2": "akşamüstü",
	"dayPeriods-standAlone-narrow-evening1": "akşam",
	"dayPeriods-standAlone-narrow-night1": "gece",
	"dayPeriods-standAlone-wide-midnight": "gece yarısı",
	"dayPeriods-standAlone-wide-am": "ÖÖ",
	"dayPeriods-standAlone-wide-noon": "öğle",
	"dayPeriods-standAlone-wide-pm": "ÖS",
	"dayPeriods-standAlone-wide-morning1": "sabah",
	"dayPeriods-standAlone-wide-morning2": "öğleden önce",
	"dayPeriods-standAlone-wide-afternoon1": "öğleden sonra",
	"dayPeriods-standAlone-wide-afternoon2": "akşamüstü",
	"dayPeriods-standAlone-wide-evening1": "akşam",
	"dayPeriods-standAlone-wide-night1": "gece",
	"eraNames": [
		"Milattan Önce",
		"Milattan Sonra"
	],
	"eraAbbr": [
		"MÖ",
		"MS"
	],
	"dateFormat-full": "d MMMM y EEEE",
	"dateFormat-long": "d MMMM y",
	"dateFormat-medium": "d MMM y",
	"dateFormat-short": "d.MM.y",
	"timeFormat-full": "HH:mm:ss zzzz",
	"timeFormat-long": "HH:mm:ss z",
	"timeFormat-medium": "HH:mm:ss",
	"timeFormat-short": "HH:mm",
	"dateTimeFormat-full": "{1} {0}",
	"dateTimeFormat-long": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "d",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-Ehm": "E a h:mm",
	"dateFormatItem-EHm": "E HH:mm",
	"dateFormatItem-Ehms": "E a h:mm:ss",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-Gy": "G y",
	"dateFormatItem-GyMMM": "G MMM y",
	"dateFormatItem-GyMMMd": "G d MMM y",
	"dateFormatItem-GyMMMEd": "G d MMM y E",
	"dateFormatItem-h": "a h",
	"dateFormatItem-H": "HH",
	"dateFormatItem-hm": "a h:mm",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-hms": "a h:mm:ss",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hmsv": "a h:mm:ss v",
	"dateFormatItem-Hmsv": "HH:mm:ss v",
	"dateFormatItem-hmv": "a h:mm v",
	"dateFormatItem-Hmv": "HH:mm v",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-MEd": "d/MM E",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MMMEd": "d MMMM E",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-MMMMEd": "d MMMM E",
	"dateFormatItem-MMMMW": "MMMM 'ayının' W. 'haftası'",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y",
	"dateFormatItem-yM": "MM/y",
	"dateFormatItem-yMd": "dd.MM.y",
	"dateFormatItem-yMEd": "d.M.y E",
	"dateFormatItem-yMM": "MM.y",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yMMMd": "d MMM y",
	"dateFormatItem-yMMMEd": "d MMM y E",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-yQQQ": "y QQQ",
	"dateFormatItem-yQQQQ": "y QQQQ",
	"dateFormatItem-yw": "y 'yılının' w. 'haftası'",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-era": "Miladi Dönem",
	"field-year": "yıl",
	"field-year-relative+-1": "geçen yıl",
	"field-year-relative+0": "bu yıl",
	"field-year-relative+1": "gelecek yıl",
	"field-year-short": "yıl",
	"field-year-short-relative+-1": "geçen yıl",
	"field-year-short-relative+0": "bu yıl",
	"field-year-short-relative+1": "gelecek yıl",
	"field-year-narrow": "yıl",
	"field-year-narrow-relative+-1": "geçen yıl",
	"field-year-narrow-relative+0": "bu yıl",
	"field-year-narrow-relative+1": "gelecek yıl",
	"field-quarter": "çeyrek",
	"field-quarter-relative+-1": "geçen çeyrek",
	"field-quarter-relative+0": "bu çeyrek",
	"field-quarter-relative+1": "gelecek çeyrek",
	"field-quarter-short": "çyr.",
	"field-quarter-narrow": "çyr.",
	"field-month": "ay",
	"field-month-relative+-1": "geçen ay",
	"field-month-relative+0": "bu ay",
	"field-month-relative+1": "gelecek ay",
	"field-month-short": "ay",
	"field-month-short-relative+-1": "geçen ay",
	"field-month-short-relative+0": "bu ay",
	"field-month-short-relative+1": "gelecek ay",
	"field-month-narrow": "ay",
	"field-month-narrow-relative+-1": "geçen ay",
	"field-month-narrow-relative+0": "bu ay",
	"field-month-narrow-relative+1": "gelecek ay",
	"field-week": "hafta",
	"field-week-relative+-1": "geçen hafta",
	"field-week-relative+0": "bu hafta",
	"field-week-relative+1": "gelecek hafta",
	"field-week-short": "hf.",
	"field-week-narrow": "hf.",
	"field-day": "gün",
	"field-day-relative+-2": "evvelsi gün",
	"field-day-relative+-1": "dün",
	"field-day-relative+0": "bugün",
	"field-day-relative+1": "yarın",
	"field-day-relative+2": "öbür gün",
	"field-day-short": "gün",
	"field-day-short-relative+-2": "evvelsi gün",
	"field-day-short-relative+-1": "dün",
	"field-day-short-relative+0": "bugün",
	"field-day-short-relative+1": "yarın",
	"field-day-short-relative+2": "öbür gün",
	"field-day-narrow": "gün",
	"field-day-narrow-relative+-2": "evvelsi gün",
	"field-day-narrow-relative+-1": "dün",
	"field-day-narrow-relative+0": "bugün",
	"field-day-narrow-relative+1": "yarın",
	"field-day-narrow-relative+2": "öbür gün",
	"field-weekday": "haftanın günü",
	"field-sun-relative+-1": "geçen pazar",
	"field-sun-relative+0": "bu pazar",
	"field-sun-relative+1": "gelecek pazar",
	"field-sun-short-relative+-1": "geçen paz.",
	"field-sun-short-relative+0": "bu paz.",
	"field-sun-short-relative+1": "gelecek paz.",
	"field-sun-narrow-relative+-1": "geçen paz.",
	"field-sun-narrow-relative+0": "bu paz.",
	"field-sun-narrow-relative+1": "gelecek paz.",
	"field-mon-relative+-1": "geçen pazartesi",
	"field-mon-relative+0": "bu pazartesi",
	"field-mon-relative+1": "gelecek pazartesi",
	"field-mon-short-relative+-1": "geçen pzt.",
	"field-mon-short-relative+0": "bu pzt.",
	"field-mon-short-relative+1": "gelecek pzt.",
	"field-mon-narrow-relative+-1": "geçen pzt.",
	"field-mon-narrow-relative+0": "bu pzt.",
	"field-mon-narrow-relative+1": "gelecek pzt.",
	"field-tue-relative+-1": "geçen salı",
	"field-tue-relative+0": "bu salı",
	"field-tue-relative+1": "gelecek salı",
	"field-tue-short-relative+-1": "geçen salı",
	"field-tue-short-relative+0": "bu salı",
	"field-tue-short-relative+1": "gelecek salı",
	"field-tue-narrow-relative+-1": "geçen salı",
	"field-tue-narrow-relative+0": "bu salı",
	"field-tue-narrow-relative+1": "gelecek salı",
	"field-wed-relative+-1": "geçen çarşamba",
	"field-wed-relative+0": "bu çarşamba",
	"field-wed-relative+1": "gelecek çarşamba",
	"field-wed-short-relative+-1": "geçen çar.",
	"field-wed-short-relative+0": "bu çar.",
	"field-wed-short-relative+1": "gelecek çar.",
	"field-wed-narrow-relative+-1": "geçen çar.",
	"field-wed-narrow-relative+0": "bu çar.",
	"field-wed-narrow-relative+1": "gelecek çar.",
	"field-thu-relative+-1": "geçen perşembe",
	"field-thu-relative+0": "bu perşembe",
	"field-thu-relative+1": "gelecek perşembe",
	"field-thu-short-relative+-1": "geçen per.",
	"field-thu-short-relative+0": "bu per.",
	"field-thu-short-relative+1": "gelecek per.",
	"field-thu-narrow-relative+-1": "geçen per.",
	"field-thu-narrow-relative+0": "bu per.",
	"field-thu-narrow-relative+1": "gelecek per.",
	"field-fri-relative+-1": "geçen cuma",
	"field-fri-relative+0": "bu cuma",
	"field-fri-relative+1": "gelecek cuma",
	"field-fri-short-relative+-1": "geçen cuma",
	"field-fri-short-relative+0": "bu cuma",
	"field-fri-short-relative+1": "gelecek cuma",
	"field-fri-narrow-relative+-1": "geçen cuma",
	"field-fri-narrow-relative+0": "bu cuma",
	"field-fri-narrow-relative+1": "gelecek cuma",
	"field-sat-relative+-1": "geçen cumartesi",
	"field-sat-relative+0": "bu cumartesi",
	"field-sat-relative+1": "gelecek cumartesi",
	"field-sat-short-relative+-1": "geçen cmt.",
	"field-sat-short-relative+0": "bu cmt.",
	"field-sat-short-relative+1": "gelecek cmt.",
	"field-sat-narrow-relative+-1": "geçen cmt.",
	"field-sat-narrow-relative+0": "bu cmt.",
	"field-sat-narrow-relative+1": "gelecek cmt.",
	"field-dayperiod": "ÖÖ/ÖS",
	"field-hour": "saat",
	"field-hour-relative+0": "bu saat",
	"field-hour-short": "sa.",
	"field-hour-narrow": "sa.",
	"field-minute": "dakika",
	"field-minute-relative+0": "bu dakika",
	"field-minute-short": "dk.",
	"field-minute-narrow": "dk.",
	"field-second": "saniye",
	"field-second-relative+0": "şimdi",
	"field-second-short": "sn.",
	"field-second-narrow": "sn.",
	"field-zone": "saat dilimi",
	"eraNarrow": [
		"MÖ",
		"MS"
	]
}
//end v1.x content
);