define(
//begin v1.x content
{
	"months-format-wide": [
		"Ferverdin",
		"Ordibeheşt",
		"Hordad",
		"Tir",
		"Mordad",
		"Şehriver",
		"Mehr",
		"Aban",
		"Azer",
		"Dey",
		"Behmen",
		"Esfend"
	],
	"field-era": "Miladi Dönem",
	"field-year": "yıl",
	"field-year-relative+-1": "geçen yıl",
	"field-year-relative+0": "bu yıl",
	"field-year-relative+1": "gelecek yıl",
	"field-year-short": "yıl",
	"field-year-short-relative+-1": "geçen yıl",
	"field-year-short-relative+0": "bu yıl",
	"field-year-short-relative+1": "gelecek yıl",
	"field-year-narrow": "yıl",
	"field-year-narrow-relative+-1": "geçen yıl",
	"field-year-narrow-relative+0": "bu yıl",
	"field-year-narrow-relative+1": "gelecek yıl",
	"field-quarter": "çeyrek",
	"field-quarter-relative+-1": "geçen çeyrek",
	"field-quarter-relative+0": "bu çeyrek",
	"field-quarter-relative+1": "gelecek çeyrek",
	"field-quarter-short": "çyr.",
	"field-quarter-narrow": "çyr.",
	"field-month": "ay",
	"field-month-relative+-1": "geçen ay",
	"field-month-relative+0": "bu ay",
	"field-month-relative+1": "gelecek ay",
	"field-month-short": "ay",
	"field-month-short-relative+-1": "geçen ay",
	"field-month-short-relative+0": "bu ay",
	"field-month-short-relative+1": "gelecek ay",
	"field-month-narrow": "ay",
	"field-month-narrow-relative+-1": "geçen ay",
	"field-month-narrow-relative+0": "bu ay",
	"field-month-narrow-relative+1": "gelecek ay",
	"field-week": "hafta",
	"field-week-relative+-1": "geçen hafta",
	"field-week-relative+0": "bu hafta",
	"field-week-relative+1": "gelecek hafta",
	"field-week-short": "hf.",
	"field-week-narrow": "hf.",
	"field-day": "gün",
	"field-day-relative+-2": "evvelsi gün",
	"field-day-relative+-1": "dün",
	"field-day-relative+0": "bugün",
	"field-day-relative+1": "yarın",
	"field-day-relative+2": "öbür gün",
	"field-day-short": "gün",
	"field-day-short-relative+-2": "evvelsi gün",
	"field-day-short-relative+-1": "dün",
	"field-day-short-relative+0": "bugün",
	"field-day-short-relative+1": "yarın",
	"field-day-short-relative+2": "öbür gün",
	"field-day-narrow": "gün",
	"field-day-narrow-relative+-2": "evvelsi gün",
	"field-day-narrow-relative+-1": "dün",
	"field-day-narrow-relative+0": "bugün",
	"field-day-narrow-relative+1": "yarın",
	"field-day-narrow-relative+2": "öbür gün",
	"field-weekday": "haftanın günü",
	"field-sun-relative+-1": "geçen pazar",
	"field-sun-relative+0": "bu pazar",
	"field-sun-relative+1": "gelecek pazar",
	"field-sun-short-relative+-1": "geçen paz.",
	"field-sun-short-relative+0": "bu paz.",
	"field-sun-short-relative+1": "gelecek paz.",
	"field-sun-narrow-relative+-1": "geçen paz.",
	"field-sun-narrow-relative+0": "bu paz.",
	"field-sun-narrow-relative+1": "gelecek paz.",
	"field-mon-relative+-1": "geçen pazartesi",
	"field-mon-relative+0": "bu pazartesi",
	"field-mon-relative+1": "gelecek pazartesi",
	"field-mon-short-relative+-1": "geçen pzt.",
	"field-mon-short-relative+0": "bu pzt.",
	"field-mon-short-relative+1": "gelecek pzt.",
	"field-mon-narrow-relative+-1": "geçen pzt.",
	"field-mon-narrow-relative+0": "bu pzt.",
	"field-mon-narrow-relative+1": "gelecek pzt.",
	"field-tue-relative+-1": "geçen salı",
	"field-tue-relative+0": "bu salı",
	"field-tue-relative+1": "gelecek salı",
	"field-tue-short-relative+-1": "geçen salı",
	"field-tue-short-relative+0": "bu salı",
	"field-tue-short-relative+1": "gelecek salı",
	"field-tue-narrow-relative+-1": "geçen salı",
	"field-tue-narrow-relative+0": "bu salı",
	"field-tue-narrow-relative+1": "gelecek salı",
	"field-wed-relative+-1": "geçen çarşamba",
	"field-wed-relative+0": "bu çarşamba",
	"field-wed-relative+1": "gelecek çarşamba",
	"field-wed-short-relative+-1": "geçen çar.",
	"field-wed-short-relative+0": "bu çar.",
	"field-wed-short-relative+1": "gelecek çar.",
	"field-wed-narrow-relative+-1": "geçen çar.",
	"field-wed-narrow-relative+0": "bu çar.",
	"field-wed-narrow-relative+1": "gelecek çar.",
	"field-thu-relative+-1": "geçen perşembe",
	"field-thu-relative+0": "bu perşembe",
	"field-thu-relative+1": "gelecek perşembe",
	"field-thu-short-relative+-1": "geçen per.",
	"field-thu-short-relative+0": "bu per.",
	"field-thu-short-relative+1": "gelecek per.",
	"field-thu-narrow-relative+-1": "geçen per.",
	"field-thu-narrow-relative+0": "bu per.",
	"field-thu-narrow-relative+1": "gelecek per.",
	"field-fri-relative+-1": "geçen cuma",
	"field-fri-relative+0": "bu cuma",
	"field-fri-relative+1": "gelecek cuma",
	"field-fri-short-relative+-1": "geçen cuma",
	"field-fri-short-relative+0": "bu cuma",
	"field-fri-short-relative+1": "gelecek cuma",
	"field-fri-narrow-relative+-1": "geçen cuma",
	"field-fri-narrow-relative+0": "bu cuma",
	"field-fri-narrow-relative+1": "gelecek cuma",
	"field-sat-relative+-1": "geçen cumartesi",
	"field-sat-relative+0": "bu cumartesi",
	"field-sat-relative+1": "gelecek cumartesi",
	"field-sat-short-relative+-1": "geçen cmt.",
	"field-sat-short-relative+0": "bu cmt.",
	"field-sat-short-relative+1": "gelecek cmt.",
	"field-sat-narrow-relative+-1": "geçen cmt.",
	"field-sat-narrow-relative+0": "bu cmt.",
	"field-sat-narrow-relative+1": "gelecek cmt.",
	"field-dayperiod": "ÖÖ/ÖS",
	"field-hour": "saat",
	"field-hour-relative+0": "bu saat",
	"field-hour-short": "sa.",
	"field-hour-narrow": "sa.",
	"field-minute": "dakika",
	"field-minute-relative+0": "bu dakika",
	"field-minute-short": "dk.",
	"field-minute-narrow": "dk.",
	"field-second": "saniye",
	"field-second-relative+0": "şimdi",
	"field-second-short": "sn.",
	"field-second-narrow": "sn.",
	"field-zone": "saat dilimi",
	"months-format-abbr": [
		"Ferverdin",
		"Ordibeheşt",
		"Hordad",
		"Tir",
		"Mordad",
		"Şehriver",
		"Mehr",
		"Aban",
		"Azer",
		"Dey",
		"Behmen",
		"Esfend"
	],
	"months-standAlone-abbr": [
		"Ferverdin",
		"Ordibeheşt",
		"Hordad",
		"Tir",
		"Mordad",
		"Şehriver",
		"Mehr",
		"Aban",
		"Azer",
		"Dey",
		"Behmen",
		"Esfend"
	],
	"months-standAlone-wide": [
		"Ferverdin",
		"Ordibeheşt",
		"Hordad",
		"Tir",
		"Mordad",
		"Şehriver",
		"Mehr",
		"Aban",
		"Azer",
		"Dey",
		"Behmen",
		"Esfend"
	],
	"days-format-abbr": [
		"Paz",
		"Pzt",
		"Sal",
		"Çar",
		"Per",
		"Cum",
		"Cmt"
	],
	"days-format-narrow": [
		"P",
		"P",
		"S",
		"Ç",
		"P",
		"C",
		"C"
	],
	"days-format-short": [
		"Pa",
		"Pt",
		"Sa",
		"Ça",
		"Pe",
		"Cu",
		"Ct"
	],
	"days-format-wide": [
		"Pazar",
		"Pazartesi",
		"Salı",
		"Çarşamba",
		"Perşembe",
		"Cuma",
		"Cumartesi"
	],
	"days-standAlone-abbr": [
		"Paz",
		"Pzt",
		"Sal",
		"Çar",
		"Per",
		"Cum",
		"Cmt"
	],
	"days-standAlone-narrow": [
		"P",
		"P",
		"S",
		"Ç",
		"P",
		"C",
		"C"
	],
	"days-standAlone-short": [
		"Pa",
		"Pt",
		"Sa",
		"Ça",
		"Pe",
		"Cu",
		"Ct"
	],
	"days-standAlone-wide": [
		"Pazar",
		"Pazartesi",
		"Salı",
		"Çarşamba",
		"Perşembe",
		"Cuma",
		"Cumartesi"
	],
	"quarters-format-abbr": [
		"Ç1",
		"Ç2",
		"Ç3",
		"Ç4"
	],
	"quarters-format-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"quarters-format-wide": [
		"1. çeyrek",
		"2. çeyrek",
		"3. çeyrek",
		"4. çeyrek"
	],
	"quarters-standAlone-abbr": [
		"Ç1",
		"Ç2",
		"Ç3",
		"Ç4"
	],
	"quarters-standAlone-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"quarters-standAlone-wide": [
		"1. çeyrek",
		"2. çeyrek",
		"3. çeyrek",
		"4. çeyrek"
	],
	"dayPeriods-format-abbr-am": "ÖÖ",
	"dayPeriods-format-abbr-pm": "ÖS",
	"dayPeriods-format-narrow-am": "öö",
	"dayPeriods-format-narrow-pm": "ös",
	"dayPeriods-format-wide-am": "ÖÖ",
	"dayPeriods-format-wide-pm": "ÖS",
	"dayPeriods-standAlone-abbr-am": "ÖÖ",
	"dayPeriods-standAlone-abbr-pm": "ÖS",
	"dayPeriods-standAlone-narrow-am": "ÖÖ",
	"dayPeriods-standAlone-narrow-pm": "ÖS",
	"dayPeriods-standAlone-wide-am": "ÖÖ",
	"dayPeriods-standAlone-wide-pm": "ÖS",
	"dateFormat-full": "G d MMMM y EEEE",
	"dateFormat-long": "G d MMMM y",
	"dateFormat-medium": "G d MMM y",
	"dateFormat-short": "GGGGG d.MM.y",
	"dateFormatItem-Ed": "d E",
	"dateFormatItem-GyMMM": "G MMM y",
	"dateFormatItem-GyMMMd": "G d MMM y",
	"dateFormatItem-GyMMMEd": "G d MMM y E",
	"dateFormatItem-Md": "dd/MM",
	"dateFormatItem-MEd": "dd/MM E",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MMMEd": "d MMM E",
	"dateFormatItem-MMMMd": "dd MMMM",
	"dateFormatItem-yyyyM": "GGGGG M/y",
	"dateFormatItem-yyyyMd": "GGGGG dd.MM.y",
	"dateFormatItem-yyyyMEd": "GGGGG dd.MM.y E",
	"dateFormatItem-yyyyMMM": "G MMM y",
	"dateFormatItem-yyyyMMMd": "G dd MMM y",
	"dateFormatItem-yyyyMMMEd": "G d MMM y E",
	"dateFormatItem-yyyyMMMM": "G MMMM y",
	"dateFormatItem-yyyyQQQ": "G y/QQQ",
	"dateFormatItem-yyyyQQQQ": "G y/QQQQ",
	"months-format-narrow": [
		"O",
		"Ş",
		"M",
		"N",
		"M",
		"H",
		"T",
		"A",
		"E",
		"E",
		"K",
		"A"
	],
	"months-standAlone-narrow": [
		"O",
		"Ş",
		"M",
		"N",
		"M",
		"H",
		"T",
		"A",
		"E",
		"E",
		"K",
		"A"
	]
}
//end v1.x content
);