define(
//begin v1.x content
{
	"dateFormat-full": "EEEE, dd. MMMM y G",
	"dateFormat-long": "dd. MMMM y G",
	"dateFormat-medium": "d. MMM y G",
	"dateFormat-short": "d. MM. yy GGGGG",
	"dateTimeFormat-full": "{1} {0}",
	"dateTimeFormat-long": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "d",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E, d.",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyM": "M/y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-GyMMMd": "d. MMM y G",
	"dateFormatItem-GyMMMEd": "E, d. MMM y G",
	"dateFormatItem-h": "h a",
	"dateFormatItem-H": "HH",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "d. M.",
	"dateFormatItem-MEd": "E, d. MM.",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-yyyyM": "M/y G",
	"dateFormatItem-yyyyMd": "d. M. y G",
	"dateFormatItem-yyyyMEd": "E, d. M. y G",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-yyyyMMMd": "d. MMM y G",
	"dateFormatItem-yyyyMMMEd": "E, d. MMM y G",
	"dateFormatItem-yyyyMMMM": "MMMM y G",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"field-era": "doba",
	"field-year": "leto",
	"field-year-relative+-1": "lani",
	"field-year-relative+0": "letos",
	"field-year-relative+1": "naslednje leto",
	"field-year-short": "leto",
	"field-year-narrow": "leto",
	"field-quarter": "četrtletje",
	"field-quarter-relative+-1": "zadnje četrtletje",
	"field-quarter-relative+0": "to četrtletje",
	"field-quarter-relative+1": "naslednje četrtletje",
	"field-quarter-short": "četrtl.",
	"field-quarter-short-relative+-1": "zadnje četrtletje",
	"field-quarter-short-relative+0": "to četrtletje",
	"field-quarter-short-relative+1": "naslednje četrtletje",
	"field-quarter-narrow": "četr.",
	"field-quarter-narrow-relative+-1": "zadnje četrtletje",
	"field-quarter-narrow-relative+0": "to četrtletje",
	"field-quarter-narrow-relative+1": "naslednje četrtletje",
	"field-month": "mesec",
	"field-month-relative+-1": "prejšnji mesec",
	"field-month-relative+0": "ta mesec",
	"field-month-relative+1": "naslednji mesec",
	"field-month-short": "mes.",
	"field-month-narrow": "mes.",
	"field-week": "teden",
	"field-week-relative+-1": "prejšnji teden",
	"field-week-relative+0": "ta teden",
	"field-week-relative+1": "naslednji teden",
	"field-week-short": "ted.",
	"field-week-narrow": "ted.",
	"field-day": "dan",
	"field-day-relative+-2": "predvčerajšnjim",
	"field-day-relative+-1": "včeraj",
	"field-day-relative+0": "danes",
	"field-day-relative+1": "jutri",
	"field-day-relative+2": "pojutrišnjem",
	"field-day-short": "dan",
	"field-day-narrow": "dan",
	"field-weekday": "dan v tednu",
	"field-sun-relative+-1": "prejšnjo nedeljo",
	"field-sun-relative+0": "to nedeljo",
	"field-sun-relative+1": "naslednjo nedeljo",
	"field-sun-short-relative+-1": "prejšnjo ned.",
	"field-sun-short-relative+0": "to ned.",
	"field-sun-short-relative+1": "naslednjo ned.",
	"field-sun-narrow-relative+-1": "prejš. ned.",
	"field-sun-narrow-relative+0": "to ned.",
	"field-sun-narrow-relative+1": "nasl. ned.",
	"field-mon-relative+-1": "prejšnji ponedeljek",
	"field-mon-relative+0": "ta ponedeljek",
	"field-mon-relative+1": "naslednji ponedeljek",
	"field-mon-short-relative+-1": "prejšnji pon.",
	"field-mon-short-relative+0": "ta pon.",
	"field-mon-short-relative+1": "naslednji pon.",
	"field-mon-narrow-relative+-1": "prejš. pon.",
	"field-mon-narrow-relative+0": "ta pon.",
	"field-mon-narrow-relative+1": "nasl. pon.",
	"field-tue-relative+-1": "prejšnji torek",
	"field-tue-relative+0": "ta torek",
	"field-tue-relative+1": "naslednji torek",
	"field-tue-short-relative+-1": "prejšnji tor.",
	"field-tue-short-relative+0": "ta tor.",
	"field-tue-short-relative+1": "naslednji tor.",
	"field-tue-narrow-relative+-1": "prejš. tor.",
	"field-tue-narrow-relative+0": "ta tor.",
	"field-tue-narrow-relative+1": "nasl. tor.",
	"field-wed-relative+-1": "prejšnjo sredo",
	"field-wed-relative+0": "to sredo",
	"field-wed-relative+1": "naslednjo sredo",
	"field-wed-short-relative+-1": "prejšnjo sre.",
	"field-wed-short-relative+0": "to sre.",
	"field-wed-short-relative+1": "naslednjo sre.",
	"field-wed-narrow-relative+-1": "prejš. sre.",
	"field-wed-narrow-relative+0": "to sre.",
	"field-wed-narrow-relative+1": "nasl. sre.",
	"field-thu-relative+-1": "prejšnji četrtek",
	"field-thu-relative+0": "ta četrtek",
	"field-thu-relative+1": "naslednji četrtek",
	"field-thu-short-relative+-1": "prejšnji čet.",
	"field-thu-short-relative+0": "ta čet.",
	"field-thu-short-relative+1": "naslednji čet.",
	"field-thu-narrow-relative+-1": "prejš. čet.",
	"field-thu-narrow-relative+0": "ta čet.",
	"field-thu-narrow-relative+1": "nasl. čet.",
	"field-fri-relative+-1": "prejšnji petek",
	"field-fri-relative+0": "ta petek",
	"field-fri-relative+1": "naslednji petek",
	"field-fri-short-relative+-1": "prejšnji pet.",
	"field-fri-short-relative+0": "ta pet.",
	"field-fri-short-relative+1": "naslednji pet.",
	"field-fri-narrow-relative+-1": "prejš. pet.",
	"field-fri-narrow-relative+0": "ta pet.",
	"field-fri-narrow-relative+1": "nasl. pet.",
	"field-sat-relative+-1": "prejšnjo soboto",
	"field-sat-relative+0": "to soboto",
	"field-sat-relative+1": "naslednjo soboto",
	"field-sat-short-relative+-1": "prejšnjo sob.",
	"field-sat-short-relative+0": "to sob.",
	"field-sat-short-relative+1": "naslednjo sob.",
	"field-sat-narrow-relative+-1": "prejš. sob.",
	"field-sat-narrow-relative+0": "to sob.",
	"field-sat-narrow-relative+1": "nasl. sob.",
	"field-dayperiod": "dop/pop",
	"field-hour": "ura",
	"field-hour-relative+0": "v tej uri",
	"field-hour-short": "ura",
	"field-hour-narrow": "h",
	"field-minute": "minuta",
	"field-minute-relative+0": "to minuto",
	"field-minute-short": "min.",
	"field-minute-narrow": "min",
	"field-second": "sekunda",
	"field-second-relative+0": "zdaj",
	"field-second-short": "sek.",
	"field-second-narrow": "s",
	"field-zone": "časovni pas"
}
//end v1.x content
);