define(
//begin v1.x content
{
	"months-format-abbr": [
		"jan.",
		"feb.",
		"mar.",
		"apr.",
		"maj",
		"jun.",
		"jul.",
		"avg.",
		"sep.",
		"okt.",
		"nov.",
		"dec."
	],
	"months-format-narrow": [
		"j",
		"f",
		"m",
		"a",
		"m",
		"j",
		"j",
		"a",
		"s",
		"o",
		"n",
		"d"
	],
	"months-format-wide": [
		"januar",
		"februar",
		"marec",
		"april",
		"maj",
		"junij",
		"julij",
		"avgust",
		"september",
		"oktober",
		"november",
		"december"
	],
	"months-standAlone-abbr": [
		"jan.",
		"feb.",
		"mar.",
		"apr.",
		"maj",
		"jun.",
		"jul.",
		"avg.",
		"sep.",
		"okt.",
		"nov.",
		"dec."
	],
	"months-standAlone-narrow": [
		"j",
		"f",
		"m",
		"a",
		"m",
		"j",
		"j",
		"a",
		"s",
		"o",
		"n",
		"d"
	],
	"months-standAlone-wide": [
		"januar",
		"februar",
		"marec",
		"april",
		"maj",
		"junij",
		"julij",
		"avgust",
		"september",
		"oktober",
		"november",
		"december"
	],
	"days-format-abbr": [
		"ned.",
		"pon.",
		"tor.",
		"sre.",
		"čet.",
		"pet.",
		"sob."
	],
	"days-format-narrow": [
		"n",
		"p",
		"t",
		"s",
		"č",
		"p",
		"s"
	],
	"days-format-short": [
		"ned.",
		"pon.",
		"tor.",
		"sre.",
		"čet.",
		"pet.",
		"sob."
	],
	"days-format-wide": [
		"nedelja",
		"ponedeljek",
		"torek",
		"sreda",
		"četrtek",
		"petek",
		"sobota"
	],
	"days-standAlone-abbr": [
		"ned.",
		"pon.",
		"tor.",
		"sre.",
		"čet.",
		"pet.",
		"sob."
	],
	"days-standAlone-narrow": [
		"n",
		"p",
		"t",
		"s",
		"č",
		"p",
		"s"
	],
	"days-standAlone-short": [
		"ned.",
		"pon.",
		"tor.",
		"sre.",
		"čet.",
		"pet.",
		"sob."
	],
	"days-standAlone-wide": [
		"nedelja",
		"ponedeljek",
		"torek",
		"sreda",
		"četrtek",
		"petek",
		"sobota"
	],
	"quarters-format-abbr": [
		"1. čet.",
		"2. čet.",
		"3. čet.",
		"4. čet."
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"1. četrtletje",
		"2. četrtletje",
		"3. četrtletje",
		"4. četrtletje"
	],
	"quarters-standAlone-abbr": [
		"1. čet.",
		"2. čet.",
		"3. čet.",
		"4. čet."
	],
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-standAlone-wide": [
		"1. četrtletje",
		"2. četrtletje",
		"3. četrtletje",
		"4. četrtletje"
	],
	"dayPeriods-format-abbr-midnight": "opoln.",
	"dayPeriods-format-abbr-am": "dop.",
	"dayPeriods-format-abbr-noon": "opold.",
	"dayPeriods-format-abbr-pm": "pop.",
	"dayPeriods-format-abbr-morning1": "zjut.",
	"dayPeriods-format-abbr-morning2": "dop.",
	"dayPeriods-format-abbr-afternoon1": "pop.",
	"dayPeriods-format-abbr-evening1": "zveč.",
	"dayPeriods-format-abbr-night1": "noč",
	"dayPeriods-format-narrow-midnight": "24.00",
	"dayPeriods-format-narrow-am": "d",
	"dayPeriods-format-narrow-noon": "12.00",
	"dayPeriods-format-narrow-pm": "p",
	"dayPeriods-format-narrow-morning1": "zj",
	"dayPeriods-format-narrow-morning2": "d",
	"dayPeriods-format-narrow-afternoon1": "p",
	"dayPeriods-format-narrow-evening1": "zv",
	"dayPeriods-format-narrow-night1": "po",
	"dayPeriods-format-wide-midnight": "opolnoči",
	"dayPeriods-format-wide-am": "dop.",
	"dayPeriods-format-wide-noon": "opoldne",
	"dayPeriods-format-wide-pm": "pop.",
	"dayPeriods-format-wide-morning1": "zjutraj",
	"dayPeriods-format-wide-morning2": "dopoldan",
	"dayPeriods-format-wide-afternoon1": "popoldan",
	"dayPeriods-format-wide-evening1": "zvečer",
	"dayPeriods-format-wide-night1": "ponoči",
	"dayPeriods-standAlone-abbr-midnight": "poln.",
	"dayPeriods-standAlone-abbr-am": "dop.",
	"dayPeriods-standAlone-abbr-noon": "pold.",
	"dayPeriods-standAlone-abbr-pm": "pop.",
	"dayPeriods-standAlone-abbr-morning1": "jut.",
	"dayPeriods-standAlone-abbr-morning2": "dop.",
	"dayPeriods-standAlone-abbr-afternoon1": "pop.",
	"dayPeriods-standAlone-abbr-evening1": "zveč.",
	"dayPeriods-standAlone-abbr-night1": "noč",
	"dayPeriods-standAlone-narrow-midnight": "24.00",
	"dayPeriods-standAlone-narrow-am": "d",
	"dayPeriods-standAlone-narrow-noon": "12.00",
	"dayPeriods-standAlone-narrow-pm": "p",
	"dayPeriods-standAlone-narrow-morning1": "j",
	"dayPeriods-standAlone-narrow-morning2": "d",
	"dayPeriods-standAlone-narrow-afternoon1": "p",
	"dayPeriods-standAlone-narrow-evening1": "v",
	"dayPeriods-standAlone-narrow-night1": "n",
	"dayPeriods-standAlone-wide-midnight": "polnoč",
	"dayPeriods-standAlone-wide-am": "dopoldne",
	"dayPeriods-standAlone-wide-noon": "poldne",
	"dayPeriods-standAlone-wide-pm": "popoldne",
	"dayPeriods-standAlone-wide-morning1": "jutro",
	"dayPeriods-standAlone-wide-morning2": "dopoldne",
	"dayPeriods-standAlone-wide-afternoon1": "popoldne",
	"dayPeriods-standAlone-wide-evening1": "večer",
	"dayPeriods-standAlone-wide-night1": "noč",
	"eraNames": [
		"pred Kristusom",
		"po Kristusu"
	],
	"eraAbbr": [
		"pr. Kr.",
		"po Kr."
	],
	"dateFormat-full": "EEEE, dd. MMMM y",
	"dateFormat-long": "dd. MMMM y",
	"dateFormat-medium": "d. MMM y",
	"dateFormat-short": "d. MM. yy",
	"timeFormat-full": "HH:mm:ss zzzz",
	"timeFormat-long": "HH:mm:ss z",
	"timeFormat-medium": "HH:mm:ss",
	"timeFormat-short": "HH:mm",
	"dateTimeFormat-full": "{1} {0}",
	"dateTimeFormat-long": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "d.",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E, d.",
	"dateFormatItem-Ehm": "E, h:mm a",
	"dateFormatItem-EHm": "E HH:mm",
	"dateFormatItem-Ehms": "E, h:mm:ss a",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyM": "MMM y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-GyMMMd": "d. MMM y G",
	"dateFormatItem-GyMMMEd": "E, d. MMM y G",
	"dateFormatItem-h": "h a",
	"dateFormatItem-H": "HH'h'",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hmsv": "h:mm:ss a v",
	"dateFormatItem-Hmsv": "HH:mm:ss v",
	"dateFormatItem-hmv": "h:mm a v",
	"dateFormatItem-Hmv": "HH:mm v",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "d. M.",
	"dateFormatItem-MEd": "E, d. M.",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-MMMMW": "W. 'teden' 'v' MMM",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y",
	"dateFormatItem-yM": "M/y",
	"dateFormatItem-yMd": "d. M. y",
	"dateFormatItem-yMEd": "E, d. M. y",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yMMMd": "d. MMM y",
	"dateFormatItem-yMMMEd": "E, d. MMM y",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"dateFormatItem-yw": "w. 'teden' 'v' y",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-era": "doba",
	"field-year": "leto",
	"field-year-relative+-1": "lani",
	"field-year-relative+0": "letos",
	"field-year-relative+1": "naslednje leto",
	"field-year-short": "leto",
	"field-year-narrow": "leto",
	"field-quarter": "četrtletje",
	"field-quarter-relative+-1": "zadnje četrtletje",
	"field-quarter-relative+0": "to četrtletje",
	"field-quarter-relative+1": "naslednje četrtletje",
	"field-quarter-short": "četrtl.",
	"field-quarter-short-relative+-1": "zadnje četrtletje",
	"field-quarter-short-relative+0": "to četrtletje",
	"field-quarter-short-relative+1": "naslednje četrtletje",
	"field-quarter-narrow": "četr.",
	"field-quarter-narrow-relative+-1": "zadnje četrtletje",
	"field-quarter-narrow-relative+0": "to četrtletje",
	"field-quarter-narrow-relative+1": "naslednje četrtletje",
	"field-month": "mesec",
	"field-month-relative+-1": "prejšnji mesec",
	"field-month-relative+0": "ta mesec",
	"field-month-relative+1": "naslednji mesec",
	"field-month-short": "mes.",
	"field-month-narrow": "mes.",
	"field-week": "teden",
	"field-week-relative+-1": "prejšnji teden",
	"field-week-relative+0": "ta teden",
	"field-week-relative+1": "naslednji teden",
	"field-week-short": "ted.",
	"field-week-narrow": "ted.",
	"field-day": "dan",
	"field-day-relative+-2": "predvčerajšnjim",
	"field-day-relative+-1": "včeraj",
	"field-day-relative+0": "danes",
	"field-day-relative+1": "jutri",
	"field-day-relative+2": "pojutrišnjem",
	"field-day-short": "dan",
	"field-day-narrow": "dan",
	"field-weekday": "dan v tednu",
	"field-sun-relative+-1": "prejšnjo nedeljo",
	"field-sun-relative+0": "to nedeljo",
	"field-sun-relative+1": "naslednjo nedeljo",
	"field-sun-short-relative+-1": "prejšnjo ned.",
	"field-sun-short-relative+0": "to ned.",
	"field-sun-short-relative+1": "naslednjo ned.",
	"field-sun-narrow-relative+-1": "prejš. ned.",
	"field-sun-narrow-relative+0": "to ned.",
	"field-sun-narrow-relative+1": "nasl. ned.",
	"field-mon-relative+-1": "prejšnji ponedeljek",
	"field-mon-relative+0": "ta ponedeljek",
	"field-mon-relative+1": "naslednji ponedeljek",
	"field-mon-short-relative+-1": "prejšnji pon.",
	"field-mon-short-relative+0": "ta pon.",
	"field-mon-short-relative+1": "naslednji pon.",
	"field-mon-narrow-relative+-1": "prejš. pon.",
	"field-mon-narrow-relative+0": "ta pon.",
	"field-mon-narrow-relative+1": "nasl. pon.",
	"field-tue-relative+-1": "prejšnji torek",
	"field-tue-relative+0": "ta torek",
	"field-tue-relative+1": "naslednji torek",
	"field-tue-short-relative+-1": "prejšnji tor.",
	"field-tue-short-relative+0": "ta tor.",
	"field-tue-short-relative+1": "naslednji tor.",
	"field-tue-narrow-relative+-1": "prejš. tor.",
	"field-tue-narrow-relative+0": "ta tor.",
	"field-tue-narrow-relative+1": "nasl. tor.",
	"field-wed-relative+-1": "prejšnjo sredo",
	"field-wed-relative+0": "to sredo",
	"field-wed-relative+1": "naslednjo sredo",
	"field-wed-short-relative+-1": "prejšnjo sre.",
	"field-wed-short-relative+0": "to sre.",
	"field-wed-short-relative+1": "naslednjo sre.",
	"field-wed-narrow-relative+-1": "prejš. sre.",
	"field-wed-narrow-relative+0": "to sre.",
	"field-wed-narrow-relative+1": "nasl. sre.",
	"field-thu-relative+-1": "prejšnji četrtek",
	"field-thu-relative+0": "ta četrtek",
	"field-thu-relative+1": "naslednji četrtek",
	"field-thu-short-relative+-1": "prejšnji čet.",
	"field-thu-short-relative+0": "ta čet.",
	"field-thu-short-relative+1": "naslednji čet.",
	"field-thu-narrow-relative+-1": "prejš. čet.",
	"field-thu-narrow-relative+0": "ta čet.",
	"field-thu-narrow-relative+1": "nasl. čet.",
	"field-fri-relative+-1": "prejšnji petek",
	"field-fri-relative+0": "ta petek",
	"field-fri-relative+1": "naslednji petek",
	"field-fri-short-relative+-1": "prejšnji pet.",
	"field-fri-short-relative+0": "ta pet.",
	"field-fri-short-relative+1": "naslednji pet.",
	"field-fri-narrow-relative+-1": "prejš. pet.",
	"field-fri-narrow-relative+0": "ta pet.",
	"field-fri-narrow-relative+1": "nasl. pet.",
	"field-sat-relative+-1": "prejšnjo soboto",
	"field-sat-relative+0": "to soboto",
	"field-sat-relative+1": "naslednjo soboto",
	"field-sat-short-relative+-1": "prejšnjo sob.",
	"field-sat-short-relative+0": "to sob.",
	"field-sat-short-relative+1": "naslednjo sob.",
	"field-sat-narrow-relative+-1": "prejš. sob.",
	"field-sat-narrow-relative+0": "to sob.",
	"field-sat-narrow-relative+1": "nasl. sob.",
	"field-dayperiod": "dop/pop",
	"field-hour": "ura",
	"field-hour-relative+0": "v tej uri",
	"field-hour-short": "ura",
	"field-hour-narrow": "h",
	"field-minute": "minuta",
	"field-minute-relative+0": "to minuto",
	"field-minute-short": "min.",
	"field-minute-narrow": "min",
	"field-second": "sekunda",
	"field-second-relative+0": "zdaj",
	"field-second-short": "sek.",
	"field-second-narrow": "s",
	"field-zone": "časovni pas",
	"eraNarrow": [
		"pr. Kr.",
		"po Kr."
	]
}
//end v1.x content
);