define(
//begin v1.x content
{
	"months-format-abbr": [
		"Tout",
		"Baba",
		"Hator",
		"Kiahk",
		"Toba",
		"Amshir",
		"Baramhat",
		"Baramouda",
		"Bashans",
		"Paona",
		"Epep",
		"Mesra",
		"Nasie"
	],
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12",
		"13"
	],
	"months-standAlone-abbr": [
		"Tout",
		"Baba",
		"Hator",
		"Kiahk",
		"Toba",
		"Amshir",
		"Baramhat",
		"Baramouda",
		"Bashans",
		"Paona",
		"Epep",
		"Mesra",
		"Nasie"
	],
	"months-standAlone-wide": [
		"Tout",
		"Baba",
		"Hator",
		"Kiahk",
		"Toba",
		"Amshir",
		"Baramhat",
		"Baramouda",
		"Bashans",
		"Paona",
		"Epep",
		"Mesra",
		"Nasie"
	],
	"field-era": "éra",
	"field-year": "év",
	"field-year-relative+-1": "előző év",
	"field-year-relative+0": "ez az év",
	"field-year-relative+1": "következő év",
	"field-year-short": "év",
	"field-year-short-relative+-1": "előző év",
	"field-year-short-relative+0": "ez az év",
	"field-year-short-relative+1": "következő év",
	"field-year-narrow": "év",
	"field-year-narrow-relative+-1": "előző év",
	"field-year-narrow-relative+0": "ez az év",
	"field-year-narrow-relative+1": "következő év",
	"field-quarter": "negyedév",
	"field-quarter-relative+-1": "előző negyedév",
	"field-quarter-relative+0": "ez a negyedév",
	"field-quarter-relative+1": "következő negyedév",
	"field-quarter-short": "negyedév",
	"field-quarter-short-relative+-1": "előző negyedév",
	"field-quarter-short-relative+0": "ez a negyedév",
	"field-quarter-short-relative+1": "következő negyedév",
	"field-quarter-narrow": "negyedév",
	"field-quarter-narrow-relative+-1": "előző negyedév",
	"field-quarter-narrow-relative+0": "ez a negyedév",
	"field-quarter-narrow-relative+1": "következő negyedév",
	"field-month": "hónap",
	"field-month-relative+-1": "előző hónap",
	"field-month-relative+0": "ez a hónap",
	"field-month-relative+1": "következő hónap",
	"field-month-short": "hónap",
	"field-month-short-relative+-1": "előző hónap",
	"field-month-short-relative+0": "ez a hónap",
	"field-month-short-relative+1": "következő hónap",
	"field-month-narrow": "hónap",
	"field-month-narrow-relative+-1": "előző hónap",
	"field-month-narrow-relative+0": "ez a hónap",
	"field-month-narrow-relative+1": "következő hónap",
	"field-week": "hét",
	"field-week-relative+-1": "előző hét",
	"field-week-relative+0": "ez a hét",
	"field-week-relative+1": "következő hét",
	"field-week-short": "hét",
	"field-week-short-relative+-1": "előző hét",
	"field-week-short-relative+0": "ez a hét",
	"field-week-short-relative+1": "következő hét",
	"field-week-narrow": "hét",
	"field-week-narrow-relative+-1": "előző hét",
	"field-week-narrow-relative+0": "ez a hét",
	"field-week-narrow-relative+1": "következő hét",
	"field-day": "nap",
	"field-day-relative+-2": "tegnapelőtt",
	"field-day-relative+-1": "tegnap",
	"field-day-relative+0": "ma",
	"field-day-relative+1": "holnap",
	"field-day-relative+2": "holnapután",
	"field-day-short": "nap",
	"field-day-short-relative+-2": "tegnapelőtt",
	"field-day-short-relative+-1": "tegnap",
	"field-day-short-relative+0": "ma",
	"field-day-short-relative+1": "holnap",
	"field-day-short-relative+2": "holnapután",
	"field-day-narrow": "nap",
	"field-day-narrow-relative+-2": "tegnapelőtt",
	"field-day-narrow-relative+-1": "tegnap",
	"field-day-narrow-relative+0": "ma",
	"field-day-narrow-relative+1": "holnap",
	"field-day-narrow-relative+2": "holnapután",
	"field-weekday": "hét napja",
	"field-sun-relative+-1": "előző vasárnap",
	"field-sun-relative+0": "ez a vasárnap",
	"field-sun-relative+1": "következő vasárnap",
	"field-sun-short-relative+-1": "előző vasárnap",
	"field-sun-short-relative+0": "ez a vasárnap",
	"field-sun-short-relative+1": "következő vasárnap",
	"field-sun-narrow-relative+-1": "előző vasárnap",
	"field-sun-narrow-relative+0": "ez a vasárnap",
	"field-sun-narrow-relative+1": "következő vasárnap",
	"field-mon-relative+-1": "előző hétfő",
	"field-mon-relative+0": "ez a hétfő",
	"field-mon-relative+1": "következő hétfő",
	"field-mon-short-relative+-1": "előző hétfő",
	"field-mon-short-relative+0": "ez a hétfő",
	"field-mon-short-relative+1": "következő hétfő",
	"field-mon-narrow-relative+-1": "előző hétfő",
	"field-mon-narrow-relative+0": "ez a hétfő",
	"field-mon-narrow-relative+1": "következő hétfő",
	"field-tue-relative+-1": "előző kedd",
	"field-tue-relative+0": "ez a kedd",
	"field-tue-relative+1": "következő kedd",
	"field-tue-short-relative+-1": "előző kedd",
	"field-tue-short-relative+0": "ez a kedd",
	"field-tue-short-relative+1": "következő kedd",
	"field-tue-narrow-relative+-1": "előző kedd",
	"field-tue-narrow-relative+0": "ez a kedd",
	"field-tue-narrow-relative+1": "következő kedd",
	"field-wed-relative+-1": "előző szerda",
	"field-wed-relative+0": "ez a szerda",
	"field-wed-relative+1": "következő szerda",
	"field-wed-short-relative+-1": "előző szerda",
	"field-wed-short-relative+0": "ez a szerda",
	"field-wed-short-relative+1": "következő szerda",
	"field-wed-narrow-relative+-1": "előző szerda",
	"field-wed-narrow-relative+0": "ez a szerda",
	"field-wed-narrow-relative+1": "következő szerda",
	"field-thu-relative+-1": "előző csütörtök",
	"field-thu-relative+0": "ez a csütörtök",
	"field-thu-relative+1": "következő csütörtök",
	"field-thu-short-relative+-1": "előző csütörtök",
	"field-thu-short-relative+0": "ez a csütörtök",
	"field-thu-short-relative+1": "következő csütörtök",
	"field-thu-narrow-relative+-1": "előző csütörtök",
	"field-thu-narrow-relative+0": "ez a csütörtök",
	"field-thu-narrow-relative+1": "következő csütörtök",
	"field-fri-relative+-1": "előző péntek",
	"field-fri-relative+0": "ez a péntek",
	"field-fri-relative+1": "következő péntek",
	"field-fri-short-relative+-1": "előző péntek",
	"field-fri-short-relative+0": "ez a péntek",
	"field-fri-short-relative+1": "következő péntek",
	"field-fri-narrow-relative+-1": "előző péntek",
	"field-fri-narrow-relative+0": "ez a péntek",
	"field-fri-narrow-relative+1": "következő péntek",
	"field-sat-relative+-1": "előző szombat",
	"field-sat-relative+0": "ez a szombat",
	"field-sat-relative+1": "következő szombat",
	"field-sat-short-relative+-1": "előző szombat",
	"field-sat-short-relative+0": "ez a szombat",
	"field-sat-short-relative+1": "következő szombat",
	"field-sat-narrow-relative+-1": "előző szombat",
	"field-sat-narrow-relative+0": "ez a szombat",
	"field-sat-narrow-relative+1": "következő szombat",
	"field-dayperiod": "napszak",
	"field-hour": "óra",
	"field-hour-relative+0": "ebben az órában",
	"field-hour-short": "óra",
	"field-hour-narrow": "óra",
	"field-minute": "perc",
	"field-minute-relative+0": "ebben a percben",
	"field-minute-short": "perc",
	"field-minute-narrow": "perc",
	"field-second": "másodperc",
	"field-second-relative+0": "most",
	"field-second-short": "másodperc",
	"field-second-narrow": "másodperc",
	"field-zone": "időzóna"
}
//end v1.x content
);