define(
//begin v1.x content
{
	"months-format-abbr": [
		"jan.",
		"febr.",
		"márc.",
		"ápr.",
		"máj.",
		"jún.",
		"júl.",
		"aug.",
		"szept.",
		"okt.",
		"nov.",
		"dec."
	],
	"months-format-narrow": [
		"J",
		"F",
		"M",
		"Á",
		"M",
		"J",
		"J",
		"A",
		"Sz",
		"O",
		"N",
		"D"
	],
	"months-format-wide": [
		"január",
		"február",
		"március",
		"április",
		"május",
		"június",
		"július",
		"augusztus",
		"szeptember",
		"október",
		"november",
		"december"
	],
	"months-standAlone-abbr": [
		"jan.",
		"febr.",
		"márc.",
		"ápr.",
		"máj.",
		"jún.",
		"júl.",
		"aug.",
		"szept.",
		"okt.",
		"nov.",
		"dec."
	],
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"Á",
		"M",
		"J",
		"J",
		"A",
		"Sz",
		"O",
		"N",
		"D"
	],
	"months-standAlone-wide": [
		"január",
		"február",
		"március",
		"április",
		"május",
		"június",
		"július",
		"augusztus",
		"szeptember",
		"október",
		"november",
		"december"
	],
	"days-format-abbr": [
		"V",
		"H",
		"K",
		"Sze",
		"Cs",
		"P",
		"Szo"
	],
	"days-format-narrow": [
		"V",
		"H",
		"K",
		"Sz",
		"Cs",
		"P",
		"Sz"
	],
	"days-format-short": [
		"V",
		"H",
		"K",
		"Sze",
		"Cs",
		"P",
		"Szo"
	],
	"days-format-wide": [
		"vasárnap",
		"hétfő",
		"kedd",
		"szerda",
		"csütörtök",
		"péntek",
		"szombat"
	],
	"days-standAlone-abbr": [
		"V",
		"H",
		"K",
		"Sze",
		"Cs",
		"P",
		"Szo"
	],
	"days-standAlone-narrow": [
		"V",
		"H",
		"K",
		"Sz",
		"Cs",
		"P",
		"Sz"
	],
	"days-standAlone-short": [
		"V",
		"H",
		"K",
		"Sze",
		"Cs",
		"P",
		"Szo"
	],
	"days-standAlone-wide": [
		"vasárnap",
		"hétfő",
		"kedd",
		"szerda",
		"csütörtök",
		"péntek",
		"szombat"
	],
	"quarters-format-abbr": [
		"N1",
		"N2",
		"N3",
		"N4"
	],
	"quarters-format-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"quarters-format-wide": [
		"I. negyedév",
		"II. negyedév",
		"III. negyedév",
		"IV. negyedév"
	],
	"quarters-standAlone-abbr": [
		"N1",
		"N2",
		"N3",
		"N4"
	],
	"quarters-standAlone-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"quarters-standAlone-wide": [
		"1. negyedév",
		"2. negyedév",
		"3. negyedév",
		"4. negyedév"
	],
	"dayPeriods-format-abbr-midnight": "éjfél",
	"dayPeriods-format-abbr-am": "de.",
	"dayPeriods-format-abbr-noon": "dél",
	"dayPeriods-format-abbr-pm": "du.",
	"dayPeriods-format-abbr-morning1": "reggel",
	"dayPeriods-format-abbr-morning2": "reggel",
	"dayPeriods-format-abbr-afternoon1": "délután",
	"dayPeriods-format-abbr-evening1": "este",
	"dayPeriods-format-abbr-night1": "éjszaka",
	"dayPeriods-format-abbr-night2": "éjszaka",
	"dayPeriods-format-narrow-midnight": "éjfél",
	"dayPeriods-format-narrow-am": "de.",
	"dayPeriods-format-narrow-noon": "dél",
	"dayPeriods-format-narrow-pm": "du.",
	"dayPeriods-format-narrow-morning1": "reggel",
	"dayPeriods-format-narrow-morning2": "reggel",
	"dayPeriods-format-narrow-afternoon1": "délután",
	"dayPeriods-format-narrow-evening1": "délután",
	"dayPeriods-format-narrow-night1": "éjszaka",
	"dayPeriods-format-narrow-night2": "éjszaka",
	"dayPeriods-format-wide-midnight": "éjfél",
	"dayPeriods-format-wide-am": "de.",
	"dayPeriods-format-wide-noon": "dél",
	"dayPeriods-format-wide-pm": "du.",
	"dayPeriods-format-wide-morning1": "reggel",
	"dayPeriods-format-wide-morning2": "reggel",
	"dayPeriods-format-wide-afternoon1": "délután",
	"dayPeriods-format-wide-evening1": "este",
	"dayPeriods-format-wide-night1": "éjszaka",
	"dayPeriods-format-wide-night2": "éjszaka",
	"dayPeriods-standAlone-abbr-midnight": "éjfél",
	"dayPeriods-standAlone-abbr-am": "de.",
	"dayPeriods-standAlone-abbr-noon": "dél",
	"dayPeriods-standAlone-abbr-pm": "du.",
	"dayPeriods-standAlone-abbr-morning1": "reggel",
	"dayPeriods-standAlone-abbr-morning2": "délelőtt",
	"dayPeriods-standAlone-abbr-afternoon1": "délután",
	"dayPeriods-standAlone-abbr-evening1": "este",
	"dayPeriods-standAlone-abbr-night1": "éjjel",
	"dayPeriods-standAlone-abbr-night2": "hajnal",
	"dayPeriods-standAlone-narrow-midnight": "éjfél",
	"dayPeriods-standAlone-narrow-am": "de.",
	"dayPeriods-standAlone-narrow-noon": "dél",
	"dayPeriods-standAlone-narrow-pm": "du.",
	"dayPeriods-standAlone-narrow-morning1": "reggel",
	"dayPeriods-standAlone-narrow-morning2": "délelőtt",
	"dayPeriods-standAlone-narrow-afternoon1": "délután",
	"dayPeriods-standAlone-narrow-evening1": "este",
	"dayPeriods-standAlone-narrow-night1": "éjjel",
	"dayPeriods-standAlone-narrow-night2": "hajnal",
	"dayPeriods-standAlone-wide-midnight": "éjfél",
	"dayPeriods-standAlone-wide-am": "de.",
	"dayPeriods-standAlone-wide-noon": "dél",
	"dayPeriods-standAlone-wide-pm": "du.",
	"dayPeriods-standAlone-wide-morning1": "reggel",
	"dayPeriods-standAlone-wide-morning2": "délelőtt",
	"dayPeriods-standAlone-wide-afternoon1": "délután",
	"dayPeriods-standAlone-wide-evening1": "este",
	"dayPeriods-standAlone-wide-night1": "éjjel",
	"dayPeriods-standAlone-wide-night2": "hajnal",
	"eraNames": [
		"időszámításunk előtt",
		"időszámításunk szerint"
	],
	"eraAbbr": [
		"i. e.",
		"i. sz."
	],
	"eraNarrow": [
		"ie.",
		"isz."
	],
	"dateFormat-full": "y. MMMM d., EEEE",
	"dateFormat-long": "y. MMMM d.",
	"dateFormat-medium": "y. MMM d.",
	"dateFormat-short": "y. MM. dd.",
	"timeFormat-full": "H:mm:ss zzzz",
	"timeFormat-long": "H:mm:ss z",
	"timeFormat-medium": "H:mm:ss",
	"timeFormat-short": "H:mm",
	"dateTimeFormat-full": "{1} {0}",
	"dateTimeFormat-long": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "d",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "d., E",
	"dateFormatItem-Ehm": "E h:mm a",
	"dateFormatItem-EHm": "E HH:mm",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-Gy": "G y.",
	"dateFormatItem-GyMMM": "G y. MMM",
	"dateFormatItem-GyMMMd": "G y. MMM d.",
	"dateFormatItem-GyMMMEd": "G y. MMM d., E",
	"dateFormatItem-h": "a h",
	"dateFormatItem-H": "H",
	"dateFormatItem-hm": "a h:mm",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-hms": "a h:mm:ss",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-hmsv": "h:mm:ss a v",
	"dateFormatItem-Hmsv": "HH:mm:ss v",
	"dateFormatItem-hmv": "h:mm a v",
	"dateFormatItem-Hmv": "HH:mm v",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "M. d.",
	"dateFormatItem-MEd": "M. d., E",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "MMM d.",
	"dateFormatItem-MMMEd": "MMM d., E",
	"dateFormatItem-MMMMd": "MMMM d.",
	"dateFormatItem-MMMMW": "MMM W. 'hete'",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y.",
	"dateFormatItem-yM": "y. M.",
	"dateFormatItem-yMd": "y. MM. dd.",
	"dateFormatItem-yMEd": "y. MM. dd., E",
	"dateFormatItem-yMMM": "y. MMM",
	"dateFormatItem-yMMMd": "y. MMM d.",
	"dateFormatItem-yMMMEd": "y. MMM d., E",
	"dateFormatItem-yMMMM": "y. MMMM",
	"dateFormatItem-yQQQ": "y. QQQ",
	"dateFormatItem-yQQQQ": "y. QQQQ",
	"dateFormatItem-yw": "y w. 'hete'",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-era": "éra",
	"field-year": "év",
	"field-year-relative+-1": "előző év",
	"field-year-relative+0": "ez az év",
	"field-year-relative+1": "következő év",
	"field-year-short": "év",
	"field-year-short-relative+-1": "előző év",
	"field-year-short-relative+0": "ez az év",
	"field-year-short-relative+1": "következő év",
	"field-year-narrow": "év",
	"field-year-narrow-relative+-1": "előző év",
	"field-year-narrow-relative+0": "ez az év",
	"field-year-narrow-relative+1": "következő év",
	"field-quarter": "negyedév",
	"field-quarter-relative+-1": "előző negyedév",
	"field-quarter-relative+0": "ez a negyedév",
	"field-quarter-relative+1": "következő negyedév",
	"field-quarter-short": "negyedév",
	"field-quarter-short-relative+-1": "előző negyedév",
	"field-quarter-short-relative+0": "ez a negyedév",
	"field-quarter-short-relative+1": "következő negyedév",
	"field-quarter-narrow": "negyedév",
	"field-quarter-narrow-relative+-1": "előző negyedév",
	"field-quarter-narrow-relative+0": "ez a negyedév",
	"field-quarter-narrow-relative+1": "következő negyedév",
	"field-month": "hónap",
	"field-month-relative+-1": "előző hónap",
	"field-month-relative+0": "ez a hónap",
	"field-month-relative+1": "következő hónap",
	"field-month-short": "hónap",
	"field-month-short-relative+-1": "előző hónap",
	"field-month-short-relative+0": "ez a hónap",
	"field-month-short-relative+1": "következő hónap",
	"field-month-narrow": "hónap",
	"field-month-narrow-relative+-1": "előző hónap",
	"field-month-narrow-relative+0": "ez a hónap",
	"field-month-narrow-relative+1": "következő hónap",
	"field-week": "hét",
	"field-week-relative+-1": "előző hét",
	"field-week-relative+0": "ez a hét",
	"field-week-relative+1": "következő hét",
	"field-week-short": "hét",
	"field-week-short-relative+-1": "előző hét",
	"field-week-short-relative+0": "ez a hét",
	"field-week-short-relative+1": "következő hét",
	"field-week-narrow": "hét",
	"field-week-narrow-relative+-1": "előző hét",
	"field-week-narrow-relative+0": "ez a hét",
	"field-week-narrow-relative+1": "következő hét",
	"field-day": "nap",
	"field-day-relative+-2": "tegnapelőtt",
	"field-day-relative+-1": "tegnap",
	"field-day-relative+0": "ma",
	"field-day-relative+1": "holnap",
	"field-day-relative+2": "holnapután",
	"field-day-short": "nap",
	"field-day-short-relative+-2": "tegnapelőtt",
	"field-day-short-relative+-1": "tegnap",
	"field-day-short-relative+0": "ma",
	"field-day-short-relative+1": "holnap",
	"field-day-short-relative+2": "holnapután",
	"field-day-narrow": "nap",
	"field-day-narrow-relative+-2": "tegnapelőtt",
	"field-day-narrow-relative+-1": "tegnap",
	"field-day-narrow-relative+0": "ma",
	"field-day-narrow-relative+1": "holnap",
	"field-day-narrow-relative+2": "holnapután",
	"field-weekday": "hét napja",
	"field-sun-relative+-1": "előző vasárnap",
	"field-sun-relative+0": "ez a vasárnap",
	"field-sun-relative+1": "következő vasárnap",
	"field-sun-short-relative+-1": "előző vasárnap",
	"field-sun-short-relative+0": "ez a vasárnap",
	"field-sun-short-relative+1": "következő vasárnap",
	"field-sun-narrow-relative+-1": "előző vasárnap",
	"field-sun-narrow-relative+0": "ez a vasárnap",
	"field-sun-narrow-relative+1": "következő vasárnap",
	"field-mon-relative+-1": "előző hétfő",
	"field-mon-relative+0": "ez a hétfő",
	"field-mon-relative+1": "következő hétfő",
	"field-mon-short-relative+-1": "előző hétfő",
	"field-mon-short-relative+0": "ez a hétfő",
	"field-mon-short-relative+1": "következő hétfő",
	"field-mon-narrow-relative+-1": "előző hétfő",
	"field-mon-narrow-relative+0": "ez a hétfő",
	"field-mon-narrow-relative+1": "következő hétfő",
	"field-tue-relative+-1": "előző kedd",
	"field-tue-relative+0": "ez a kedd",
	"field-tue-relative+1": "következő kedd",
	"field-tue-short-relative+-1": "előző kedd",
	"field-tue-short-relative+0": "ez a kedd",
	"field-tue-short-relative+1": "következő kedd",
	"field-tue-narrow-relative+-1": "előző kedd",
	"field-tue-narrow-relative+0": "ez a kedd",
	"field-tue-narrow-relative+1": "következő kedd",
	"field-wed-relative+-1": "előző szerda",
	"field-wed-relative+0": "ez a szerda",
	"field-wed-relative+1": "következő szerda",
	"field-wed-short-relative+-1": "előző szerda",
	"field-wed-short-relative+0": "ez a szerda",
	"field-wed-short-relative+1": "következő szerda",
	"field-wed-narrow-relative+-1": "előző szerda",
	"field-wed-narrow-relative+0": "ez a szerda",
	"field-wed-narrow-relative+1": "következő szerda",
	"field-thu-relative+-1": "előző csütörtök",
	"field-thu-relative+0": "ez a csütörtök",
	"field-thu-relative+1": "következő csütörtök",
	"field-thu-short-relative+-1": "előző csütörtök",
	"field-thu-short-relative+0": "ez a csütörtök",
	"field-thu-short-relative+1": "következő csütörtök",
	"field-thu-narrow-relative+-1": "előző csütörtök",
	"field-thu-narrow-relative+0": "ez a csütörtök",
	"field-thu-narrow-relative+1": "következő csütörtök",
	"field-fri-relative+-1": "előző péntek",
	"field-fri-relative+0": "ez a péntek",
	"field-fri-relative+1": "következő péntek",
	"field-fri-short-relative+-1": "előző péntek",
	"field-fri-short-relative+0": "ez a péntek",
	"field-fri-short-relative+1": "következő péntek",
	"field-fri-narrow-relative+-1": "előző péntek",
	"field-fri-narrow-relative+0": "ez a péntek",
	"field-fri-narrow-relative+1": "következő péntek",
	"field-sat-relative+-1": "előző szombat",
	"field-sat-relative+0": "ez a szombat",
	"field-sat-relative+1": "következő szombat",
	"field-sat-short-relative+-1": "előző szombat",
	"field-sat-short-relative+0": "ez a szombat",
	"field-sat-short-relative+1": "következő szombat",
	"field-sat-narrow-relative+-1": "előző szombat",
	"field-sat-narrow-relative+0": "ez a szombat",
	"field-sat-narrow-relative+1": "következő szombat",
	"field-dayperiod": "napszak",
	"field-hour": "óra",
	"field-hour-relative+0": "ebben az órában",
	"field-hour-short": "óra",
	"field-hour-narrow": "óra",
	"field-minute": "perc",
	"field-minute-relative+0": "ebben a percben",
	"field-minute-short": "perc",
	"field-minute-narrow": "perc",
	"field-second": "másodperc",
	"field-second-relative+0": "most",
	"field-second-short": "másodperc",
	"field-second-narrow": "másodperc",
	"field-zone": "időzóna"
}
//end v1.x content
);