define(
//begin v1.x content
{
	"eraAbbr": [
		"AM"
	],
	"field-era": "era",
	"field-year": "año",
	"field-year-relative+-1": "el año pasado",
	"field-year-relative+0": "este año",
	"field-year-relative+1": "el próximo año",
	"field-year-short": "a",
	"field-year-short-relative+-1": "el año pasado",
	"field-year-short-relative+0": "este año",
	"field-year-short-relative+1": "el próximo año",
	"field-year-narrow": "a",
	"field-year-narrow-relative+-1": "el año pasado",
	"field-year-narrow-relative+0": "este año",
	"field-year-narrow-relative+1": "el próximo año",
	"field-quarter": "trimestre",
	"field-quarter-relative+-1": "el trimestre pasado",
	"field-quarter-relative+0": "este trimestre",
	"field-quarter-relative+1": "el próximo trimestre",
	"field-quarter-short": "trim.",
	"field-quarter-narrow": "trim.",
	"field-month": "mes",
	"field-month-relative+-1": "el mes pasado",
	"field-month-relative+0": "este mes",
	"field-month-relative+1": "el próximo mes",
	"field-month-short": "m",
	"field-month-short-relative+-1": "el mes pasado",
	"field-month-short-relative+0": "este mes",
	"field-month-short-relative+1": "el próximo mes",
	"field-month-narrow": "m",
	"field-month-narrow-relative+-1": "el mes pasado",
	"field-month-narrow-relative+0": "este mes",
	"field-month-narrow-relative+1": "el próximo mes",
	"field-week": "semana",
	"field-week-relative+-1": "la semana pasada",
	"field-week-relative+0": "esta semana",
	"field-week-relative+1": "la próxima semana",
	"field-week-short": "sem.",
	"field-week-narrow": "sem.",
	"field-day": "día",
	"field-day-relative+-2": "anteayer",
	"field-day-relative+-1": "ayer",
	"field-day-relative+0": "hoy",
	"field-day-relative+1": "mañana",
	"field-day-relative+2": "pasado mañana",
	"field-day-short": "d",
	"field-day-short-relative+-2": "anteayer",
	"field-day-short-relative+-1": "ayer",
	"field-day-short-relative+0": "hoy",
	"field-day-short-relative+1": "mañana",
	"field-day-short-relative+2": "pasado mañana",
	"field-day-narrow": "d",
	"field-day-narrow-relative+-2": "anteayer",
	"field-day-narrow-relative+-1": "ayer",
	"field-day-narrow-relative+0": "hoy",
	"field-day-narrow-relative+1": "mañana",
	"field-day-narrow-relative+2": "pasado mañana",
	"field-weekday": "día de la semana",
	"field-sun-relative+-1": "el domingo pasado",
	"field-sun-relative+0": "este domingo",
	"field-sun-relative+1": "el próximo domingo",
	"field-sun-short-relative+-1": "el dom. pasado",
	"field-sun-short-relative+0": "este dom.",
	"field-sun-short-relative+1": "el próximo dom.",
	"field-sun-narrow-relative+-1": "el DO pasado",
	"field-sun-narrow-relative+0": "este DO",
	"field-sun-narrow-relative+1": "el próximo DO",
	"field-mon-relative+-1": "el lunes pasado",
	"field-mon-relative+0": "este lunes",
	"field-mon-relative+1": "el próximo lunes",
	"field-mon-short-relative+-1": "el lun. pasado",
	"field-mon-short-relative+0": "este lun.",
	"field-mon-short-relative+1": "el próximo lun.",
	"field-mon-narrow-relative+-1": "el LU pasado",
	"field-mon-narrow-relative+0": "este LU",
	"field-mon-narrow-relative+1": "el próximo LU",
	"field-tue-relative+-1": "el martes pasado",
	"field-tue-relative+0": "este martes",
	"field-tue-relative+1": "el próximo martes",
	"field-tue-short-relative+-1": "el mar. pasado",
	"field-tue-short-relative+0": "este mar.",
	"field-tue-short-relative+1": "el próximo mar.",
	"field-tue-narrow-relative+-1": "el MA pasado",
	"field-tue-narrow-relative+0": "este MA",
	"field-tue-narrow-relative+1": "el próximo MA",
	"field-wed-relative+-1": "el miércoles pasado",
	"field-wed-relative+0": "este miércoles",
	"field-wed-relative+1": "el próximo miércoles",
	"field-wed-short-relative+-1": "el mié. pasado",
	"field-wed-short-relative+0": "este mié.",
	"field-wed-short-relative+1": "el próximo mié.",
	"field-wed-narrow-relative+-1": "el MI pasado",
	"field-wed-narrow-relative+0": "este MI",
	"field-wed-narrow-relative+1": "el próximo MI",
	"field-thu-relative+-1": "el jueves pasado",
	"field-thu-relative+0": "este jueves",
	"field-thu-relative+1": "el próximo jueves",
	"field-thu-short-relative+-1": "el jue. pasado",
	"field-thu-short-relative+0": "este jue.",
	"field-thu-short-relative+1": "el próximo jue.",
	"field-thu-narrow-relative+-1": "el JU pasado",
	"field-thu-narrow-relative+0": "este JU",
	"field-thu-narrow-relative+1": "el próximo JU",
	"field-fri-relative+-1": "el viernes pasado",
	"field-fri-relative+0": "este viernes",
	"field-fri-relative+1": "el próximo viernes",
	"field-fri-short-relative+-1": "el vie. pasado",
	"field-fri-short-relative+0": "este vie.",
	"field-fri-short-relative+1": "el próximo vie.",
	"field-fri-narrow-relative+-1": "el VI pasado",
	"field-fri-narrow-relative+0": "este VI",
	"field-fri-narrow-relative+1": "el próximo VI",
	"field-sat-relative+-1": "el sábado pasado",
	"field-sat-relative+0": "este sábado",
	"field-sat-relative+1": "el próximo sábado",
	"field-sat-short-relative+-1": "el sáb. pasado",
	"field-sat-short-relative+0": "este sáb.",
	"field-sat-short-relative+1": "el próximo sáb.",
	"field-sat-narrow-relative+-1": "el SA pasado",
	"field-sat-narrow-relative+0": "este SA",
	"field-sat-narrow-relative+1": "el próximo SA",
	"field-dayperiod": "a. m./p. m.",
	"field-hour": "hora",
	"field-hour-relative+0": "esta hora",
	"field-hour-short": "h",
	"field-hour-narrow": "h",
	"field-minute": "minuto",
	"field-minute-relative+0": "este minuto",
	"field-minute-short": "min",
	"field-minute-narrow": "min",
	"field-second": "segundo",
	"field-second-relative+0": "ahora",
	"field-second-short": "s",
	"field-second-narrow": "s",
	"field-zone": "zona horaria",
	"days-format-abbr": [
		"dom.",
		"lun.",
		"mar.",
		"mié.",
		"jue.",
		"vie.",
		"sáb."
	],
	"days-format-narrow": [
		"D",
		"L",
		"M",
		"X",
		"J",
		"V",
		"S"
	],
	"days-format-short": [
		"DO",
		"LU",
		"MA",
		"MI",
		"JU",
		"VI",
		"SA"
	],
	"days-format-wide": [
		"domingo",
		"lunes",
		"martes",
		"miércoles",
		"jueves",
		"viernes",
		"sábado"
	],
	"days-standAlone-abbr": [
		"dom.",
		"lun.",
		"mar.",
		"mié.",
		"jue.",
		"vie.",
		"sáb."
	],
	"days-standAlone-narrow": [
		"D",
		"L",
		"M",
		"X",
		"J",
		"V",
		"S"
	],
	"days-standAlone-short": [
		"DO",
		"LU",
		"MA",
		"MI",
		"JU",
		"VI",
		"SA"
	],
	"days-standAlone-wide": [
		"domingo",
		"lunes",
		"martes",
		"miércoles",
		"jueves",
		"viernes",
		"sábado"
	],
	"quarters-format-abbr": [
		"T1",
		"T2",
		"T3",
		"T4"
	],
	"quarters-format-wide": [
		"1.er trimestre",
		"2.º trimestre",
		"3.er trimestre",
		"4.º trimestre"
	],
	"quarters-standAlone-abbr": [
		"T1",
		"T2",
		"T3",
		"T4"
	],
	"quarters-standAlone-wide": [
		"1.er trimestre",
		"2.º trimestre",
		"3.er trimestre",
		"4.º trimestre"
	],
	"dayPeriods-format-abbr-am": "a. m.",
	"dayPeriods-format-abbr-pm": "p. m.",
	"dayPeriods-format-narrow-am": "a. m.",
	"dayPeriods-format-narrow-pm": "p. m.",
	"dayPeriods-format-wide-am": "a. m.",
	"dayPeriods-format-wide-pm": "p. m.",
	"dayPeriods-standAlone-abbr-am": "a. m.",
	"dayPeriods-standAlone-abbr-pm": "p. m.",
	"dayPeriods-standAlone-narrow-am": "a. m.",
	"dayPeriods-standAlone-narrow-pm": "p. m.",
	"dayPeriods-standAlone-wide-am": "a. m.",
	"dayPeriods-standAlone-wide-pm": "p. m.",
	"dateFormat-full": "EEEE, d 'de' MMMM 'de' y G",
	"dateFormat-long": "d 'de' MMMM 'de' y G",
	"dateFormat-medium": "d/M/y G",
	"dateFormat-short": "d/M/yy G",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"dateFormatItem-GyMMMEd": "E, d MMM y G",
	"dateFormatItem-h": "hh a",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-MEd": "E, d/M",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MMMEd": "E, d MMM",
	"dateFormatItem-MMMMd": "d 'de' MMMM",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-yyyyM": "M/y GGGGG",
	"dateFormatItem-yyyyMd": "d/M/y GGGGG",
	"dateFormatItem-yyyyMEd": "E, d/M/y GGGGG",
	"dateFormatItem-yyyyMMM": "MMM y G",
	"dateFormatItem-yyyyMMMd": "d MMM y G",
	"dateFormatItem-yyyyMMMEd": "EEE, d MMM y G",
	"dateFormatItem-yyyyMMMM": "MMMM 'de' y G",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-yyyyQQQQ": "QQQQ 'de' y G",
	"timeFormat-full": "H:mm:ss (zzzz)",
	"timeFormat-long": "H:mm:ss z",
	"timeFormat-medium": "H:mm:ss",
	"timeFormat-short": "H:mm",
	"dateTimeFormat-full": "{1}, {0}",
	"dateTimeFormat-long": "{1}, {0}"
}
//end v1.x content
);