define(
//begin v1.x content
{
	"dateFormat-full": "EEEE, d 'de' MMMM 'de' y G",
	"dateFormat-long": "d 'de' MMMM 'de' y G",
	"dateFormat-medium": "dd/MM/y G",
	"dateFormat-short": "dd/MM/yy GGGGG",
	"field-era": "era",
	"field-year": "año",
	"field-year-relative+-1": "el año pasado",
	"field-year-relative+0": "este año",
	"field-year-relative+1": "el próximo año",
	"field-year-short": "a",
	"field-year-short-relative+-1": "el año pasado",
	"field-year-short-relative+0": "este año",
	"field-year-short-relative+1": "el próximo año",
	"field-year-narrow": "a",
	"field-year-narrow-relative+-1": "el año pasado",
	"field-year-narrow-relative+0": "este año",
	"field-year-narrow-relative+1": "el próximo año",
	"field-quarter": "trimestre",
	"field-quarter-relative+-1": "el trimestre pasado",
	"field-quarter-relative+0": "este trimestre",
	"field-quarter-relative+1": "el próximo trimestre",
	"field-quarter-short": "trim.",
	"field-quarter-narrow": "trim.",
	"field-month": "mes",
	"field-month-relative+-1": "el mes pasado",
	"field-month-relative+0": "este mes",
	"field-month-relative+1": "el próximo mes",
	"field-month-short": "m",
	"field-month-short-relative+-1": "el mes pasado",
	"field-month-short-relative+0": "este mes",
	"field-month-short-relative+1": "el próximo mes",
	"field-month-narrow": "m",
	"field-month-narrow-relative+-1": "el mes pasado",
	"field-month-narrow-relative+0": "este mes",
	"field-month-narrow-relative+1": "el próximo mes",
	"field-week": "semana",
	"field-week-relative+-1": "la semana pasada",
	"field-week-relative+0": "esta semana",
	"field-week-relative+1": "la próxima semana",
	"field-week-short": "sem.",
	"field-week-narrow": "sem.",
	"field-day": "día",
	"field-day-relative+-2": "anteayer",
	"field-day-relative+-1": "ayer",
	"field-day-relative+0": "hoy",
	"field-day-relative+1": "mañana",
	"field-day-relative+2": "pasado mañana",
	"field-day-short": "d",
	"field-day-short-relative+-2": "anteayer",
	"field-day-short-relative+-1": "ayer",
	"field-day-short-relative+0": "hoy",
	"field-day-short-relative+1": "mañana",
	"field-day-short-relative+2": "pasado mañana",
	"field-day-narrow": "d",
	"field-day-narrow-relative+-2": "anteayer",
	"field-day-narrow-relative+-1": "ayer",
	"field-day-narrow-relative+0": "hoy",
	"field-day-narrow-relative+1": "mañana",
	"field-day-narrow-relative+2": "pasado mañana",
	"field-weekday": "día de la semana",
	"field-sun-relative+-1": "el domingo pasado",
	"field-sun-relative+0": "este domingo",
	"field-sun-relative+1": "el próximo domingo",
	"field-sun-short-relative+-1": "el dom. pasado",
	"field-sun-short-relative+0": "este dom.",
	"field-sun-short-relative+1": "el próximo dom.",
	"field-sun-narrow-relative+-1": "el DO pasado",
	"field-sun-narrow-relative+0": "este DO",
	"field-sun-narrow-relative+1": "el próximo DO",
	"field-mon-relative+-1": "el lunes pasado",
	"field-mon-relative+0": "este lunes",
	"field-mon-relative+1": "el próximo lunes",
	"field-mon-short-relative+-1": "el lun. pasado",
	"field-mon-short-relative+0": "este lun.",
	"field-mon-short-relative+1": "el próximo lun.",
	"field-mon-narrow-relative+-1": "el LU pasado",
	"field-mon-narrow-relative+0": "este LU",
	"field-mon-narrow-relative+1": "el próximo LU",
	"field-tue-relative+-1": "el martes pasado",
	"field-tue-relative+0": "este martes",
	"field-tue-relative+1": "el próximo martes",
	"field-tue-short-relative+-1": "el mar. pasado",
	"field-tue-short-relative+0": "este mar.",
	"field-tue-short-relative+1": "el próximo mar.",
	"field-tue-narrow-relative+-1": "el MA pasado",
	"field-tue-narrow-relative+0": "este MA",
	"field-tue-narrow-relative+1": "el próximo MA",
	"field-wed-relative+-1": "el miércoles pasado",
	"field-wed-relative+0": "este miércoles",
	"field-wed-relative+1": "el próximo miércoles",
	"field-wed-short-relative+-1": "el mié. pasado",
	"field-wed-short-relative+0": "este mié.",
	"field-wed-short-relative+1": "el próximo mié.",
	"field-wed-narrow-relative+-1": "el MI pasado",
	"field-wed-narrow-relative+0": "este MI",
	"field-wed-narrow-relative+1": "el próximo MI",
	"field-thu-relative+-1": "el jueves pasado",
	"field-thu-relative+0": "este jueves",
	"field-thu-relative+1": "el próximo jueves",
	"field-thu-short-relative+-1": "el jue. pasado",
	"field-thu-short-relative+0": "este jue.",
	"field-thu-short-relative+1": "el próximo jue.",
	"field-thu-narrow-relative+-1": "el JU pasado",
	"field-thu-narrow-relative+0": "este JU",
	"field-thu-narrow-relative+1": "el próximo JU",
	"field-fri-relative+-1": "el viernes pasado",
	"field-fri-relative+0": "este viernes",
	"field-fri-relative+1": "el próximo viernes",
	"field-fri-short-relative+-1": "el vie. pasado",
	"field-fri-short-relative+0": "este vie.",
	"field-fri-short-relative+1": "el próximo vie.",
	"field-fri-narrow-relative+-1": "el VI pasado",
	"field-fri-narrow-relative+0": "este VI",
	"field-fri-narrow-relative+1": "el próximo VI",
	"field-sat-relative+-1": "el sábado pasado",
	"field-sat-relative+0": "este sábado",
	"field-sat-relative+1": "el próximo sábado",
	"field-sat-short-relative+-1": "el sáb. pasado",
	"field-sat-short-relative+0": "este sáb.",
	"field-sat-short-relative+1": "el próximo sáb.",
	"field-sat-narrow-relative+-1": "el SA pasado",
	"field-sat-narrow-relative+0": "este SA",
	"field-sat-narrow-relative+1": "el próximo SA",
	"field-dayperiod": "a. m./p. m.",
	"field-hour": "hora",
	"field-hour-relative+0": "esta hora",
	"field-hour-short": "h",
	"field-hour-narrow": "h",
	"field-minute": "minuto",
	"field-minute-relative+0": "este minuto",
	"field-minute-short": "min",
	"field-minute-narrow": "min",
	"field-second": "segundo",
	"field-second-relative+0": "ahora",
	"field-second-short": "s",
	"field-second-narrow": "s",
	"field-zone": "zona horaria"
}
//end v1.x content
);