define({ root:

//begin v1.x content
{
	"decimal": ".",
	"group": ",",
	"list": ";",
	"percentSign": "%",
	"plusSign": "+",
	"minusSign": "-",
	"exponential": "E",
	"superscriptingExponent": "×",
	"perMille": "‰",
	"infinity": "∞",
	"nan": "NaN",
	"timeSeparator": ":",
	"decimalFormat": "#,##0.###",
	"decimalFormat-long": "000T",
	"decimalFormat-short": "000T",
	"scientificFormat": "#E0",
	"percentFormat": "#,##0%",
	"currencySpacing-beforeCurrency-currencyMatch": "[:^S:]",
	"currencySpacing-beforeCurrency-surroundingMatch": "[:digit:]",
	"currencySpacing-beforeCurrency-insertBetween": " ",
	"currencySpacing-afterCurrency-currencyMatch": "[:^S:]",
	"currencySpacing-afterCurrency-surroundingMatch": "[:digit:]",
	"currencySpacing-afterCurrency-insertBetween": " ",
	"currencyFormat": "¤ #,##0.00",
	"currencyFormat-short": "¤ 000T"
}
//end v1.x content
,
	"ar": true,
	"bs": true,
	"ca": true,
	"cs": true,
	"da": true,
	"de": true,
	"de-ch": true,
	"el": true,
	"en": true,
	"en-au": true,
	"es": true,
	"es-mx": true,
	"et": true,
	"fi": true,
	"fr": true,
	"fr-ch": true,
	"he": true,
	"hi": true,
	"hr": true,
	"hu": true,
	"id": true,
	"it": true,
	"it-ch": true,
	"ja": true,
	"ko": true,
	"lt": true,
	"lv": true,
	"nb": true,
	"nl": true,
	"pl": true,
	"pt": true,
	"pt-pt": true,
	"ro": true,
	"ru": true,
	"sl": true,
	"sr": true,
	"sv": true,
	"th": true,
	"tr": true,
	"uk": true,
	"vi": true,
	"zh": true,
	"zh-hk": true,
	"zh-tw": true
});