define(
//begin v1.x content
{
	"months-format-wide": [
		"esimene kuu",
		"teine kuu",
		"kolmas kuu",
		"neljas kuu",
		"viies kuu",
		"kuues kuu",
		"seitsmes kuu",
		"kaheksas kuu",
		"üheksas kuu",
		"kümnes kuu",
		"üheteistkümnes kuu",
		"kaheteistkümnes kuu"
	],
	"field-era": "ajastu",
	"field-year": "aasta",
	"field-year-relative+-1": "eelmine aasta",
	"field-year-relative+0": "käesolev aasta",
	"field-year-relative+1": "järgmine aasta",
	"field-year-short": "a",
	"field-year-narrow": "a",
	"field-quarter": "kvartal",
	"field-quarter-relative+-1": "eelmine kvartal",
	"field-quarter-relative+0": "käesolev kvartal",
	"field-quarter-relative+1": "järgmine kvartal",
	"field-quarter-short": "kv",
	"field-quarter-short-relative+-1": "eelmine kv",
	"field-quarter-short-relative+0": "käesolev kv",
	"field-quarter-short-relative+1": "järgmine kv",
	"field-quarter-narrow": "kv",
	"field-quarter-narrow-relative+-1": "eelmine kv",
	"field-quarter-narrow-relative+0": "käesolev kv",
	"field-quarter-narrow-relative+1": "järgmine kv",
	"field-month": "kuu",
	"field-month-relative+-1": "eelmine kuu",
	"field-month-relative+0": "käesolev kuu",
	"field-month-relative+1": "järgmine kuu",
	"field-month-short": "k",
	"field-month-narrow": "k",
	"field-week": "nädal",
	"field-week-relative+-1": "eelmine nädal",
	"field-week-relative+0": "käesolev nädal",
	"field-week-relative+1": "järgmine nädal",
	"field-week-short": "näd",
	"field-week-narrow": "näd",
	"field-day": "päev",
	"field-day-relative+-2": "üleeile",
	"field-day-relative+-1": "eile",
	"field-day-relative+0": "täna",
	"field-day-relative+1": "homme",
	"field-day-relative+2": "ülehomme",
	"field-day-short": "p",
	"field-day-narrow": "p",
	"field-weekday": "nädalapäev",
	"field-sun-relative+-1": "eelmine pühapäev",
	"field-sun-relative+0": "käesolev pühapäev",
	"field-sun-relative+1": "järgmine pühapäev",
	"field-sun-short-relative+-1": "eelmine pühapäev",
	"field-sun-short-relative+0": "käesolev pühapäev",
	"field-sun-short-relative+1": "järgmine pühapäev",
	"field-sun-narrow-relative+-1": "eelmine pühapäev",
	"field-sun-narrow-relative+0": "käesolev pühapäev",
	"field-sun-narrow-relative+1": "järgmine pühapäev",
	"field-mon-relative+-1": "eelmine esmaspäev",
	"field-mon-relative+0": "käesolev esmaspäev",
	"field-mon-relative+1": "järgmine esmaspäev",
	"field-mon-short-relative+-1": "eelmine esmaspäev",
	"field-mon-short-relative+0": "käesolev esmaspäev",
	"field-mon-short-relative+1": "järgmine esmaspäev",
	"field-mon-narrow-relative+-1": "eelmine esmaspäev",
	"field-mon-narrow-relative+0": "käesolev esmaspäev",
	"field-mon-narrow-relative+1": "järgmine esmaspäev",
	"field-tue-relative+-1": "eelmine teisipäev",
	"field-tue-relative+0": "käesolev teisipäev",
	"field-tue-relative+1": "järgmine teisipäev",
	"field-tue-short-relative+-1": "eelmine teisipäev",
	"field-tue-short-relative+0": "käesolev teisipäev",
	"field-tue-short-relative+1": "järgmine teisipäev",
	"field-tue-narrow-relative+-1": "eelmine teisipäev",
	"field-tue-narrow-relative+0": "käesolev teisipäev",
	"field-tue-narrow-relative+1": "järgmine teisipäev",
	"field-wed-relative+-1": "eelmine kolmapäev",
	"field-wed-relative+0": "käesolev kolmapäev",
	"field-wed-relative+1": "järgmine kolmapäev",
	"field-wed-short-relative+-1": "eelmine kolmapäev",
	"field-wed-short-relative+0": "käesolev kolmapäev",
	"field-wed-short-relative+1": "järgmine kolmapäev",
	"field-wed-narrow-relative+-1": "eelmine kolmapäev",
	"field-wed-narrow-relative+0": "käesolev kolmapäev",
	"field-wed-narrow-relative+1": "järgmine kolmapäev",
	"field-thu-relative+-1": "eelmine neljapäev",
	"field-thu-relative+0": "käesolev neljapäev",
	"field-thu-relative+1": "järgmine neljapäev",
	"field-thu-short-relative+-1": "eelmine neljapäev",
	"field-thu-short-relative+0": "käesolev neljapäev",
	"field-thu-short-relative+1": "järgmine neljapäev",
	"field-thu-narrow-relative+-1": "eelmine neljapäev",
	"field-thu-narrow-relative+0": "käesolev neljapäev",
	"field-thu-narrow-relative+1": "järgmine neljapäev",
	"field-fri-relative+-1": "eelmine reede",
	"field-fri-relative+0": "käesolev reede",
	"field-fri-relative+1": "järgmine reede",
	"field-fri-short-relative+-1": "eelmine reede",
	"field-fri-short-relative+0": "käesolev reede",
	"field-fri-short-relative+1": "järgmine reede",
	"field-fri-narrow-relative+-1": "eelmine reede",
	"field-fri-narrow-relative+0": "käesolev reede",
	"field-fri-narrow-relative+1": "järgmine reede",
	"field-sat-relative+-1": "eelmine laupäev",
	"field-sat-relative+0": "käesolev laupäev",
	"field-sat-relative+1": "järgmine laupäev",
	"field-sat-short-relative+-1": "eelmine laupäev",
	"field-sat-short-relative+0": "käesolev laupäev",
	"field-sat-short-relative+1": "järgmine laupäev",
	"field-sat-narrow-relative+-1": "eelmine laupäev",
	"field-sat-narrow-relative+0": "käesolev laupäev",
	"field-sat-narrow-relative+1": "järgmine laupäev",
	"field-dayperiod": "enne/pärast lõunat",
	"field-hour": "tund",
	"field-hour-relative+0": "praegusel tunnil",
	"field-hour-short": "t",
	"field-hour-narrow": "t",
	"field-minute": "minut",
	"field-minute-relative+0": "praegusel minutil",
	"field-minute-short": "min",
	"field-minute-narrow": "min",
	"field-second": "sekund",
	"field-second-relative+0": "nüüd",
	"field-second-short": "sek",
	"field-second-narrow": "s",
	"field-zone": "ajavöönd"
}
//end v1.x content
);