define(
//begin v1.x content
{
	"months-format-abbr": [
		"jaan",
		"veebr",
		"märts",
		"apr",
		"mai",
		"juuni",
		"juuli",
		"aug",
		"sept",
		"okt",
		"nov",
		"dets"
	],
	"months-format-narrow": [
		"J",
		"V",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"months-format-wide": [
		"jaanuar",
		"veebruar",
		"märts",
		"aprill",
		"mai",
		"juuni",
		"juuli",
		"august",
		"september",
		"oktoober",
		"november",
		"detsember"
	],
	"months-standAlone-abbr": [
		"jaan",
		"veebr",
		"märts",
		"apr",
		"mai",
		"juuni",
		"juuli",
		"aug",
		"sept",
		"okt",
		"nov",
		"dets"
	],
	"months-standAlone-narrow": [
		"J",
		"V",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"months-standAlone-wide": [
		"jaanuar",
		"veebruar",
		"märts",
		"aprill",
		"mai",
		"juuni",
		"juuli",
		"august",
		"september",
		"oktoober",
		"november",
		"detsember"
	],
	"days-format-abbr": [
		"P",
		"E",
		"T",
		"K",
		"N",
		"R",
		"L"
	],
	"days-format-narrow": [
		"P",
		"E",
		"T",
		"K",
		"N",
		"R",
		"L"
	],
	"days-format-short": [
		"P",
		"E",
		"T",
		"K",
		"N",
		"R",
		"L"
	],
	"days-format-wide": [
		"pühapäev",
		"esmaspäev",
		"teisipäev",
		"kolmapäev",
		"neljapäev",
		"reede",
		"laupäev"
	],
	"days-standAlone-abbr": [
		"P",
		"E",
		"T",
		"K",
		"N",
		"R",
		"L"
	],
	"days-standAlone-narrow": [
		"P",
		"E",
		"T",
		"K",
		"N",
		"R",
		"L"
	],
	"days-standAlone-short": [
		"P",
		"E",
		"T",
		"K",
		"N",
		"R",
		"L"
	],
	"days-standAlone-wide": [
		"pühapäev",
		"esmaspäev",
		"teisipäev",
		"kolmapäev",
		"neljapäev",
		"reede",
		"laupäev"
	],
	"quarters-format-abbr": [
		"K1",
		"K2",
		"K3",
		"K4"
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"1. kvartal",
		"2. kvartal",
		"3. kvartal",
		"4. kvartal"
	],
	"quarters-standAlone-abbr": [
		"K1",
		"K2",
		"K3",
		"K4"
	],
	"quarters-standAlone-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"quarters-standAlone-wide": [
		"1. kvartal",
		"2. kvartal",
		"3. kvartal",
		"4. kvartal"
	],
	"dayPeriods-format-abbr-midnight": "keskööl",
	"dayPeriods-format-abbr-am": "AM",
	"dayPeriods-format-abbr-noon": "keskpäeval",
	"dayPeriods-format-abbr-pm": "PM",
	"dayPeriods-format-abbr-morning1": "hommikul",
	"dayPeriods-format-abbr-afternoon1": "pärastlõunal",
	"dayPeriods-format-abbr-evening1": "õhtul",
	"dayPeriods-format-abbr-night1": "öösel",
	"dayPeriods-format-narrow-midnight": "keskööl",
	"dayPeriods-format-narrow-am": "AM",
	"dayPeriods-format-narrow-noon": "keskpäeval",
	"dayPeriods-format-narrow-pm": "PM",
	"dayPeriods-format-narrow-morning1": "hommikul",
	"dayPeriods-format-narrow-afternoon1": "pärastlõunal",
	"dayPeriods-format-narrow-evening1": "õhtul",
	"dayPeriods-format-narrow-night1": "öösel",
	"dayPeriods-format-wide-midnight": "keskööl",
	"dayPeriods-format-wide-am": "AM",
	"dayPeriods-format-wide-noon": "keskpäeval",
	"dayPeriods-format-wide-pm": "PM",
	"dayPeriods-format-wide-morning1": "hommikul",
	"dayPeriods-format-wide-afternoon1": "pärastlõunal",
	"dayPeriods-format-wide-evening1": "õhtul",
	"dayPeriods-format-wide-night1": "öösel",
	"dayPeriods-standAlone-abbr-midnight": "kesköö",
	"dayPeriods-standAlone-abbr-am": "AM",
	"dayPeriods-standAlone-abbr-noon": "keskpäev",
	"dayPeriods-standAlone-abbr-pm": "PM",
	"dayPeriods-standAlone-abbr-morning1": "hommik",
	"dayPeriods-standAlone-abbr-afternoon1": "pärastlõuna",
	"dayPeriods-standAlone-abbr-evening1": "õhtu",
	"dayPeriods-standAlone-abbr-night1": "öö",
	"dayPeriods-standAlone-narrow-midnight": "kesköö",
	"dayPeriods-standAlone-narrow-am": "AM",
	"dayPeriods-standAlone-narrow-noon": "keskpäev",
	"dayPeriods-standAlone-narrow-pm": "PM",
	"dayPeriods-standAlone-narrow-morning1": "hommik",
	"dayPeriods-standAlone-narrow-afternoon1": "pärastlõuna",
	"dayPeriods-standAlone-narrow-evening1": "õhtu",
	"dayPeriods-standAlone-narrow-night1": "öö",
	"dayPeriods-standAlone-wide-midnight": "kesköö",
	"dayPeriods-standAlone-wide-am": "AM",
	"dayPeriods-standAlone-wide-noon": "keskpäev",
	"dayPeriods-standAlone-wide-pm": "PM",
	"dayPeriods-standAlone-wide-morning1": "hommik",
	"dayPeriods-standAlone-wide-afternoon1": "pärastlõuna",
	"dayPeriods-standAlone-wide-evening1": "õhtu",
	"dayPeriods-standAlone-wide-night1": "öö",
	"eraNames": [
		"enne Kristust",
		"pärast Kristust"
	],
	"eraAbbr": [
		"eKr",
		"pKr"
	],
	"eraNarrow": [
		"eKr",
		"pKr"
	],
	"dateFormat-full": "EEEE, d. MMMM y",
	"dateFormat-long": "d. MMMM y",
	"dateFormat-medium": "d. MMM y",
	"dateFormat-short": "dd.MM.yy",
	"timeFormat-full": "HH:mm:ss zzzz",
	"timeFormat-long": "HH:mm:ss z",
	"timeFormat-medium": "HH:mm:ss",
	"timeFormat-short": "HH:mm",
	"dateTimeFormat-full": "{1} {0}",
	"dateTimeFormat-long": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "d",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E, d",
	"dateFormatItem-Ehm": "E h:mm a",
	"dateFormatItem-EHm": "E HH:mm",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-GyMMMd": "d. MMM y G",
	"dateFormatItem-GyMMMEd": "E, d. MMMM y G",
	"dateFormatItem-h": "h a",
	"dateFormatItem-H": "HH",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hmsv": "h:mm:ss a v",
	"dateFormatItem-Hmsv": "HH:mm:ss v",
	"dateFormatItem-hmv": "h:mm a v",
	"dateFormatItem-Hmv": "HH:mm v",
	"dateFormatItem-M": "M",
	"dateFormatItem-Md": "d.M",
	"dateFormatItem-MEd": "E, d.M",
	"dateFormatItem-MMM": "MMMM",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-MMMMEd": "E, d. MMMM",
	"dateFormatItem-MMMMW": "MMM (W. 'nädal')",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y",
	"dateFormatItem-yM": "M.y",
	"dateFormatItem-yMd": "d.M.y",
	"dateFormatItem-yMEd": "E, d.M.y",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yMMMd": "d. MMM y",
	"dateFormatItem-yMMMEd": "E, d. MMMM y",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"dateFormatItem-yw": "y (w. 'nädal')",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-era": "ajastu",
	"field-year": "aasta",
	"field-year-relative+-1": "eelmine aasta",
	"field-year-relative+0": "käesolev aasta",
	"field-year-relative+1": "järgmine aasta",
	"field-year-short": "a",
	"field-year-narrow": "a",
	"field-quarter": "kvartal",
	"field-quarter-relative+-1": "eelmine kvartal",
	"field-quarter-relative+0": "käesolev kvartal",
	"field-quarter-relative+1": "järgmine kvartal",
	"field-quarter-short": "kv",
	"field-quarter-short-relative+-1": "eelmine kv",
	"field-quarter-short-relative+0": "käesolev kv",
	"field-quarter-short-relative+1": "järgmine kv",
	"field-quarter-narrow": "kv",
	"field-quarter-narrow-relative+-1": "eelmine kv",
	"field-quarter-narrow-relative+0": "käesolev kv",
	"field-quarter-narrow-relative+1": "järgmine kv",
	"field-month": "kuu",
	"field-month-relative+-1": "eelmine kuu",
	"field-month-relative+0": "käesolev kuu",
	"field-month-relative+1": "järgmine kuu",
	"field-month-short": "k",
	"field-month-narrow": "k",
	"field-week": "nädal",
	"field-week-relative+-1": "eelmine nädal",
	"field-week-relative+0": "käesolev nädal",
	"field-week-relative+1": "järgmine nädal",
	"field-week-short": "näd",
	"field-week-narrow": "näd",
	"field-day": "päev",
	"field-day-relative+-2": "üleeile",
	"field-day-relative+-1": "eile",
	"field-day-relative+0": "täna",
	"field-day-relative+1": "homme",
	"field-day-relative+2": "ülehomme",
	"field-day-short": "p",
	"field-day-narrow": "p",
	"field-weekday": "nädalapäev",
	"field-sun-relative+-1": "eelmine pühapäev",
	"field-sun-relative+0": "käesolev pühapäev",
	"field-sun-relative+1": "järgmine pühapäev",
	"field-sun-short-relative+-1": "eelmine pühapäev",
	"field-sun-short-relative+0": "käesolev pühapäev",
	"field-sun-short-relative+1": "järgmine pühapäev",
	"field-sun-narrow-relative+-1": "eelmine pühapäev",
	"field-sun-narrow-relative+0": "käesolev pühapäev",
	"field-sun-narrow-relative+1": "järgmine pühapäev",
	"field-mon-relative+-1": "eelmine esmaspäev",
	"field-mon-relative+0": "käesolev esmaspäev",
	"field-mon-relative+1": "järgmine esmaspäev",
	"field-mon-short-relative+-1": "eelmine esmaspäev",
	"field-mon-short-relative+0": "käesolev esmaspäev",
	"field-mon-short-relative+1": "järgmine esmaspäev",
	"field-mon-narrow-relative+-1": "eelmine esmaspäev",
	"field-mon-narrow-relative+0": "käesolev esmaspäev",
	"field-mon-narrow-relative+1": "järgmine esmaspäev",
	"field-tue-relative+-1": "eelmine teisipäev",
	"field-tue-relative+0": "käesolev teisipäev",
	"field-tue-relative+1": "järgmine teisipäev",
	"field-tue-short-relative+-1": "eelmine teisipäev",
	"field-tue-short-relative+0": "käesolev teisipäev",
	"field-tue-short-relative+1": "järgmine teisipäev",
	"field-tue-narrow-relative+-1": "eelmine teisipäev",
	"field-tue-narrow-relative+0": "käesolev teisipäev",
	"field-tue-narrow-relative+1": "järgmine teisipäev",
	"field-wed-relative+-1": "eelmine kolmapäev",
	"field-wed-relative+0": "käesolev kolmapäev",
	"field-wed-relative+1": "järgmine kolmapäev",
	"field-wed-short-relative+-1": "eelmine kolmapäev",
	"field-wed-short-relative+0": "käesolev kolmapäev",
	"field-wed-short-relative+1": "järgmine kolmapäev",
	"field-wed-narrow-relative+-1": "eelmine kolmapäev",
	"field-wed-narrow-relative+0": "käesolev kolmapäev",
	"field-wed-narrow-relative+1": "järgmine kolmapäev",
	"field-thu-relative+-1": "eelmine neljapäev",
	"field-thu-relative+0": "käesolev neljapäev",
	"field-thu-relative+1": "järgmine neljapäev",
	"field-thu-short-relative+-1": "eelmine neljapäev",
	"field-thu-short-relative+0": "käesolev neljapäev",
	"field-thu-short-relative+1": "järgmine neljapäev",
	"field-thu-narrow-relative+-1": "eelmine neljapäev",
	"field-thu-narrow-relative+0": "käesolev neljapäev",
	"field-thu-narrow-relative+1": "järgmine neljapäev",
	"field-fri-relative+-1": "eelmine reede",
	"field-fri-relative+0": "käesolev reede",
	"field-fri-relative+1": "järgmine reede",
	"field-fri-short-relative+-1": "eelmine reede",
	"field-fri-short-relative+0": "käesolev reede",
	"field-fri-short-relative+1": "järgmine reede",
	"field-fri-narrow-relative+-1": "eelmine reede",
	"field-fri-narrow-relative+0": "käesolev reede",
	"field-fri-narrow-relative+1": "järgmine reede",
	"field-sat-relative+-1": "eelmine laupäev",
	"field-sat-relative+0": "käesolev laupäev",
	"field-sat-relative+1": "järgmine laupäev",
	"field-sat-short-relative+-1": "eelmine laupäev",
	"field-sat-short-relative+0": "käesolev laupäev",
	"field-sat-short-relative+1": "järgmine laupäev",
	"field-sat-narrow-relative+-1": "eelmine laupäev",
	"field-sat-narrow-relative+0": "käesolev laupäev",
	"field-sat-narrow-relative+1": "järgmine laupäev",
	"field-dayperiod": "enne/pärast lõunat",
	"field-hour": "tund",
	"field-hour-relative+0": "praegusel tunnil",
	"field-hour-short": "t",
	"field-hour-narrow": "t",
	"field-minute": "minut",
	"field-minute-relative+0": "praegusel minutil",
	"field-minute-short": "min",
	"field-minute-narrow": "min",
	"field-second": "sekund",
	"field-second-relative+0": "nüüd",
	"field-second-short": "sek",
	"field-second-narrow": "s",
	"field-zone": "ajavöönd"
}
//end v1.x content
);