define(
//begin v1.x content
{
	"months-format-wide": [
		"मस्केरेम",
		"टेकेम्ट",
		"हेदर",
		"तहसास",
		"टर",
		"येकाटिट",
		"मेगाबिट",
		"मियाज़िया",
		"गनबोट",
		"सेन",
		"हम्ले",
		"नेहासे",
		"पागूमन"
	],
	"field-era": "युग",
	"field-year": "वर्ष",
	"field-year-relative+-1": "पिछला वर्ष",
	"field-year-relative+0": "इस वर्ष",
	"field-year-relative+1": "अगला वर्ष",
	"field-year-short": "वर्ष",
	"field-year-narrow": "वर्ष",
	"field-quarter": "तिमाही",
	"field-quarter-relative+-1": "अंतिम तिमाही",
	"field-quarter-relative+0": "इस तिमाही",
	"field-quarter-relative+1": "अगली तिमाही",
	"field-quarter-short": "तिमाही",
	"field-quarter-short-relative+-1": "अंतिम तिमाही",
	"field-quarter-short-relative+0": "इस तिमाही",
	"field-quarter-short-relative+1": "अगली तिमाही",
	"field-quarter-narrow": "तिमाही",
	"field-quarter-narrow-relative+-1": "अंतिम तिमाही",
	"field-quarter-narrow-relative+0": "इस तिमाही",
	"field-quarter-narrow-relative+1": "अगली तिमाही",
	"field-month": "माह",
	"field-month-relative+-1": "पिछला माह",
	"field-month-relative+0": "इस माह",
	"field-month-relative+1": "अगला माह",
	"field-month-short": "माह",
	"field-month-narrow": "माह",
	"field-week": "सप्ताह",
	"field-week-relative+-1": "पिछला सप्ताह",
	"field-week-relative+0": "इस सप्ताह",
	"field-week-relative+1": "अगला सप्ताह",
	"field-week-short": "सप्ताह",
	"field-week-narrow": "सप्ताह",
	"field-day": "दिन",
	"field-day-relative+-2": "बीता परसों",
	"field-day-relative+-1": "कल",
	"field-day-relative+0": "आज",
	"field-day-relative+1": "कल",
	"field-day-relative+2": "परसों",
	"field-day-short": "दिन",
	"field-day-narrow": "दिन",
	"field-weekday": "सप्ताह का दिन",
	"field-sun-relative+-1": "पिछला रविवार",
	"field-sun-relative+0": "इस रविवार",
	"field-sun-relative+1": "अगला रविवार",
	"field-sun-short-relative+-1": "पिछला रवि.",
	"field-sun-short-relative+0": "इस रवि.",
	"field-sun-short-relative+1": "अगला रवि.",
	"field-sun-narrow-relative+-1": "पिछला रवि.",
	"field-sun-narrow-relative+0": "इस रवि.",
	"field-sun-narrow-relative+1": "अगला रवि.",
	"field-mon-relative+-1": "पिछला सोमवार",
	"field-mon-relative+0": "इस सोमवार",
	"field-mon-relative+1": "अगला सोमवार",
	"field-mon-short-relative+-1": "पिछला सोम.",
	"field-mon-short-relative+0": "इस सोम.",
	"field-mon-short-relative+1": "अगला सोम.",
	"field-mon-narrow-relative+-1": "पिछला सोम.",
	"field-mon-narrow-relative+0": "इस सोम.",
	"field-mon-narrow-relative+1": "अगला सोम.",
	"field-tue-relative+-1": "पिछला मंगलवार",
	"field-tue-relative+0": "इस मंगलवार",
	"field-tue-relative+1": "अगला मंगलवार",
	"field-tue-short-relative+-1": "पिछला मंगल.",
	"field-tue-short-relative+0": "इस मंगल.",
	"field-tue-short-relative+1": "अगला मंगल.",
	"field-tue-narrow-relative+-1": "पिछला मंगल.",
	"field-tue-narrow-relative+0": "इस मंगल.",
	"field-tue-narrow-relative+1": "अगला मंगल.",
	"field-wed-relative+-1": "पिछला बुधवार",
	"field-wed-relative+0": "इस बुधवार",
	"field-wed-relative+1": "अगला बुधवार",
	"field-wed-short-relative+-1": "पिछला बुध.",
	"field-wed-short-relative+0": "इस बुध.",
	"field-wed-short-relative+1": "अगला बुध.",
	"field-wed-narrow-relative+-1": "पिछला बुध.",
	"field-wed-narrow-relative+0": "इस बुध.",
	"field-wed-narrow-relative+1": "अगला बुध.",
	"field-thu-relative+-1": "पिछला गुरुवार",
	"field-thu-relative+0": "इस गुरुवार",
	"field-thu-relative+1": "अगला गुरुवार",
	"field-thu-short-relative+-1": "पिछला गुरु.",
	"field-thu-short-relative+0": "इस गुरु.",
	"field-thu-short-relative+1": "अगला गुरु.",
	"field-thu-narrow-relative+-1": "पिछला गुरु.",
	"field-thu-narrow-relative+0": "इस गुरु.",
	"field-thu-narrow-relative+1": "अगला गुरु.",
	"field-fri-relative+-1": "पिछला शुक्रवार",
	"field-fri-relative+0": "इस शुक्रवार",
	"field-fri-relative+1": "अगला शुक्रवार",
	"field-fri-short-relative+-1": "पिछला शुक्र.",
	"field-fri-short-relative+0": "इस शुक्र.",
	"field-fri-short-relative+1": "अगला शुक्र.",
	"field-fri-narrow-relative+-1": "पिछला शुक्र.",
	"field-fri-narrow-relative+0": "इस शुक्र.",
	"field-fri-narrow-relative+1": "अगला शुक्र.",
	"field-sat-relative+-1": "पिछला शनिवार",
	"field-sat-relative+0": "इस शनिवार",
	"field-sat-relative+1": "अगला शनिवार",
	"field-sat-short-relative+-1": "पिछला शनि.",
	"field-sat-short-relative+0": "इस शनि.",
	"field-sat-short-relative+1": "अगला शनि.",
	"field-sat-narrow-relative+-1": "पिछला शनि.",
	"field-sat-narrow-relative+0": "इस शनि.",
	"field-sat-narrow-relative+1": "अगला शनि.",
	"field-dayperiod": "पूर्वाह्न/अपराह्न",
	"field-hour": "घंटा",
	"field-hour-relative+0": "यह घंटा",
	"field-hour-short": "घं.",
	"field-hour-narrow": "घं.",
	"field-minute": "मिनट",
	"field-minute-relative+0": "यह मिनट",
	"field-minute-short": "मि.",
	"field-minute-narrow": "मि.",
	"field-second": "सेकंड",
	"field-second-relative+0": "अब",
	"field-second-short": "से.",
	"field-second-narrow": "से.",
	"field-zone": "समय क्षेत्र"
}
//end v1.x content
);