define(
//begin v1.x content
{
	"months-format-abbr": [
		"正月",
		"二月",
		"三月",
		"四月",
		"五月",
		"六月",
		"七月",
		"八月",
		"九月",
		"十月",
		"十一月",
		"腊月"
	],
	"months-format-narrow": [
		"正",
		"二",
		"三",
		"四",
		"五",
		"六",
		"七",
		"八",
		"九",
		"十",
		"十一",
		"腊"
	],
	"months-format-wide": [
		"正月",
		"二月",
		"三月",
		"四月",
		"五月",
		"六月",
		"七月",
		"八月",
		"九月",
		"十月",
		"十一月",
		"腊月"
	],
	"months-standAlone-abbr": [
		"正月",
		"二月",
		"三月",
		"四月",
		"五月",
		"六月",
		"七月",
		"八月",
		"九月",
		"十月",
		"十一月",
		"腊月"
	],
	"months-standAlone-narrow": [
		"正",
		"二",
		"三",
		"四",
		"五",
		"六",
		"七",
		"八",
		"九",
		"十",
		"冬",
		"腊"
	],
	"months-standAlone-wide": [
		"正月",
		"二月",
		"三月",
		"四月",
		"五月",
		"六月",
		"七月",
		"八月",
		"九月",
		"十月",
		"十一月",
		"腊月"
	],
	"dateFormat-full": "rU年MMMdEEEE",
	"dateFormat-long": "rU年MMMd",
	"dateFormat-medium": "r年MMMd",
	"dateFormat-short": "r/M/d",
	"dateFormatItem-d": "d日",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "d日E",
	"dateFormatItem-Gy": "rU年",
	"dateFormatItem-GyMMM": "rU年MMM",
	"dateFormatItem-GyMMMd": "r年MMMd",
	"dateFormatItem-GyMMMEd": "rU年MMMdE",
	"dateFormatItem-M": "MMM",
	"dateFormatItem-Md": "M-d",
	"dateFormatItem-MEd": "M-dE",
	"dateFormatItem-MMMd": "MMMd日",
	"dateFormatItem-MMMEd": "MMMd日E",
	"dateFormatItem-MMMMd": "MMMMd日",
	"dateFormatItem-UM": "U年MMM",
	"dateFormatItem-UMd": "U年MMMd",
	"dateFormatItem-UMMM": "U年MMM",
	"dateFormatItem-UMMMd": "U年MMMd",
	"dateFormatItem-y": "rU年",
	"dateFormatItem-yMd": "r年MMMd",
	"dateFormatItem-yyyy": "rU年",
	"dateFormatItem-yyyyM": "rU年MMM",
	"dateFormatItem-yyyyMd": "r年MMMd",
	"dateFormatItem-yyyyMEd": "rU年MMMd，E",
	"dateFormatItem-yyyyMMM": "rU年MMM",
	"dateFormatItem-yyyyMMMd": "r年MMMd",
	"dateFormatItem-yyyyMMMEd": "rU年MMMdE",
	"dateFormatItem-yyyyMMMM": "rU年MMMM",
	"dateFormatItem-yyyyQQQ": "rU年QQQQ",
	"dateFormatItem-yyyyQQQQ": "rU年QQQQ",
	"field-era": "纪元",
	"field-year": "年",
	"field-year-relative+-1": "去年",
	"field-year-relative+0": "今年",
	"field-year-relative+1": "明年",
	"field-year-short": "年",
	"field-year-narrow": "年",
	"field-quarter": "季度",
	"field-quarter-relative+-1": "上季度",
	"field-quarter-relative+0": "本季度",
	"field-quarter-relative+1": "下季度",
	"field-quarter-short": "季",
	"field-quarter-narrow": "季",
	"field-month": "月",
	"field-month-relative+-1": "上个月",
	"field-month-relative+0": "本月",
	"field-month-relative+1": "下个月",
	"field-month-short": "月",
	"field-month-narrow": "月",
	"field-week": "周",
	"field-week-relative+-1": "上周",
	"field-week-relative+0": "本周",
	"field-week-relative+1": "下周",
	"field-week-short": "周",
	"field-week-narrow": "周",
	"field-day": "日",
	"field-day-relative+-2": "前天",
	"field-day-relative+-1": "昨天",
	"field-day-relative+0": "今天",
	"field-day-relative+1": "明天",
	"field-day-relative+2": "后天",
	"field-day-short": "日",
	"field-day-narrow": "日",
	"field-weekday": "工作日",
	"field-sun-relative+-1": "上周日",
	"field-sun-relative+0": "本周日",
	"field-sun-relative+1": "下周日",
	"field-sun-short-relative+-1": "上周日",
	"field-sun-short-relative+0": "本周日",
	"field-sun-short-relative+1": "下周日",
	"field-sun-narrow-relative+-1": "上周日",
	"field-sun-narrow-relative+0": "本周日",
	"field-sun-narrow-relative+1": "下周日",
	"field-mon-relative+-1": "上周一",
	"field-mon-relative+0": "本周一",
	"field-mon-relative+1": "下周一",
	"field-mon-short-relative+-1": "上周一",
	"field-mon-short-relative+0": "本周一",
	"field-mon-short-relative+1": "下周一",
	"field-mon-narrow-relative+-1": "上周一",
	"field-mon-narrow-relative+0": "本周一",
	"field-mon-narrow-relative+1": "下周一",
	"field-tue-relative+-1": "上周二",
	"field-tue-relative+0": "本周二",
	"field-tue-relative+1": "下周二",
	"field-tue-short-relative+-1": "上周二",
	"field-tue-short-relative+0": "本周二",
	"field-tue-short-relative+1": "下周二",
	"field-tue-narrow-relative+-1": "上周二",
	"field-tue-narrow-relative+0": "本周二",
	"field-tue-narrow-relative+1": "下周二",
	"field-wed-relative+-1": "上周三",
	"field-wed-relative+0": "本周三",
	"field-wed-relative+1": "下周三",
	"field-wed-short-relative+-1": "上周三",
	"field-wed-short-relative+0": "本周三",
	"field-wed-short-relative+1": "下周三",
	"field-wed-narrow-relative+-1": "上周三",
	"field-wed-narrow-relative+0": "本周三",
	"field-wed-narrow-relative+1": "下周三",
	"field-thu-relative+-1": "上周四",
	"field-thu-relative+0": "本周四",
	"field-thu-relative+1": "下周四",
	"field-thu-short-relative+-1": "上周四",
	"field-thu-short-relative+0": "本周四",
	"field-thu-short-relative+1": "下周四",
	"field-thu-narrow-relative+-1": "上周四",
	"field-thu-narrow-relative+0": "本周四",
	"field-thu-narrow-relative+1": "下周四",
	"field-fri-relative+-1": "上周五",
	"field-fri-relative+0": "本周五",
	"field-fri-relative+1": "下周五",
	"field-fri-short-relative+-1": "上周五",
	"field-fri-short-relative+0": "本周五",
	"field-fri-short-relative+1": "下周五",
	"field-fri-narrow-relative+-1": "上周五",
	"field-fri-narrow-relative+0": "本周五",
	"field-fri-narrow-relative+1": "下周五",
	"field-sat-relative+-1": "上周六",
	"field-sat-relative+0": "本周六",
	"field-sat-relative+1": "下周六",
	"field-sat-short-relative+-1": "上周六",
	"field-sat-short-relative+0": "本周六",
	"field-sat-short-relative+1": "下周六",
	"field-sat-narrow-relative+-1": "上周六",
	"field-sat-narrow-relative+0": "本周六",
	"field-sat-narrow-relative+1": "下周六",
	"field-dayperiod": "上午/下午",
	"field-hour": "小时",
	"field-hour-relative+0": "这一时间 / 此时",
	"field-hour-short": "小时",
	"field-hour-narrow": "小时",
	"field-minute": "分钟",
	"field-minute-relative+0": "此刻",
	"field-minute-short": "分",
	"field-minute-narrow": "分",
	"field-second": "秒",
	"field-second-relative+0": "现在",
	"field-second-short": "秒",
	"field-second-narrow": "秒",
	"field-zone": "时区"
}
//end v1.x content
);