define(
//begin v1.x content
{
	"months-format-abbr": [
		"1月",
		"2月",
		"3月",
		"4月",
		"5月",
		"6月",
		"7月",
		"8月",
		"9月",
		"10月",
		"11月",
		"12月"
	],
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-format-wide": [
		"一月",
		"二月",
		"三月",
		"四月",
		"五月",
		"六月",
		"七月",
		"八月",
		"九月",
		"十月",
		"十一月",
		"十二月"
	],
	"months-standAlone-abbr": [
		"1月",
		"2月",
		"3月",
		"4月",
		"5月",
		"6月",
		"7月",
		"8月",
		"9月",
		"10月",
		"11月",
		"12月"
	],
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-standAlone-wide": [
		"一月",
		"二月",
		"三月",
		"四月",
		"五月",
		"六月",
		"七月",
		"八月",
		"九月",
		"十月",
		"十一月",
		"十二月"
	],
	"days-format-abbr": [
		"周日",
		"周一",
		"周二",
		"周三",
		"周四",
		"周五",
		"周六"
	],
	"days-format-narrow": [
		"日",
		"一",
		"二",
		"三",
		"四",
		"五",
		"六"
	],
	"days-format-short": [
		"周日",
		"周一",
		"周二",
		"周三",
		"周四",
		"周五",
		"周六"
	],
	"days-format-wide": [
		"星期日",
		"星期一",
		"星期二",
		"星期三",
		"星期四",
		"星期五",
		"星期六"
	],
	"days-standAlone-abbr": [
		"周日",
		"周一",
		"周二",
		"周三",
		"周四",
		"周五",
		"周六"
	],
	"days-standAlone-narrow": [
		"日",
		"一",
		"二",
		"三",
		"四",
		"五",
		"六"
	],
	"days-standAlone-short": [
		"周日",
		"周一",
		"周二",
		"周三",
		"周四",
		"周五",
		"周六"
	],
	"days-standAlone-wide": [
		"星期日",
		"星期一",
		"星期二",
		"星期三",
		"星期四",
		"星期五",
		"星期六"
	],
	"quarters-format-abbr": [
		"1季度",
		"2季度",
		"3季度",
		"4季度"
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"第一季度",
		"第二季度",
		"第三季度",
		"第四季度"
	],
	"quarters-standAlone-abbr": [
		"1季度",
		"2季度",
		"3季度",
		"4季度"
	],
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-standAlone-wide": [
		"第一季度",
		"第二季度",
		"第三季度",
		"第四季度"
	],
	"dayPeriods-format-abbr-midnight": "午夜",
	"dayPeriods-format-abbr-am": "上午",
	"dayPeriods-format-abbr-pm": "下午",
	"dayPeriods-format-abbr-morning1": "清晨",
	"dayPeriods-format-abbr-morning2": "上午",
	"dayPeriods-format-abbr-afternoon1": "中午",
	"dayPeriods-format-abbr-afternoon2": "下午",
	"dayPeriods-format-abbr-evening1": "晚上",
	"dayPeriods-format-abbr-night1": "凌晨",
	"dayPeriods-format-narrow-midnight": "午夜",
	"dayPeriods-format-narrow-am": "上午",
	"dayPeriods-format-narrow-pm": "下午",
	"dayPeriods-format-narrow-morning1": "清晨",
	"dayPeriods-format-narrow-morning2": "上午",
	"dayPeriods-format-narrow-afternoon1": "中午",
	"dayPeriods-format-narrow-afternoon2": "下午",
	"dayPeriods-format-narrow-evening1": "晚上",
	"dayPeriods-format-narrow-night1": "凌晨",
	"dayPeriods-format-wide-midnight": "午夜",
	"dayPeriods-format-wide-am": "上午",
	"dayPeriods-format-wide-pm": "下午",
	"dayPeriods-format-wide-morning1": "清晨",
	"dayPeriods-format-wide-morning2": "上午",
	"dayPeriods-format-wide-afternoon1": "中午",
	"dayPeriods-format-wide-afternoon2": "下午",
	"dayPeriods-format-wide-evening1": "晚上",
	"dayPeriods-format-wide-night1": "凌晨",
	"dayPeriods-standAlone-abbr-midnight": "午夜",
	"dayPeriods-standAlone-abbr-am": "上午",
	"dayPeriods-standAlone-abbr-pm": "下午",
	"dayPeriods-standAlone-abbr-morning1": "清晨",
	"dayPeriods-standAlone-abbr-morning2": "上午",
	"dayPeriods-standAlone-abbr-afternoon1": "中午",
	"dayPeriods-standAlone-abbr-afternoon2": "下午",
	"dayPeriods-standAlone-abbr-evening1": "晚上",
	"dayPeriods-standAlone-abbr-night1": "凌晨",
	"dayPeriods-standAlone-narrow-midnight": "午夜",
	"dayPeriods-standAlone-narrow-am": "上午",
	"dayPeriods-standAlone-narrow-pm": "下午",
	"dayPeriods-standAlone-narrow-morning1": "早上",
	"dayPeriods-standAlone-narrow-morning2": "上午",
	"dayPeriods-standAlone-narrow-afternoon1": "中午",
	"dayPeriods-standAlone-narrow-afternoon2": "下午",
	"dayPeriods-standAlone-narrow-evening1": "晚上",
	"dayPeriods-standAlone-narrow-night1": "凌晨",
	"dayPeriods-standAlone-wide-midnight": "午夜",
	"dayPeriods-standAlone-wide-am": "上午",
	"dayPeriods-standAlone-wide-pm": "下午",
	"dayPeriods-standAlone-wide-morning1": "早上",
	"dayPeriods-standAlone-wide-morning2": "上午",
	"dayPeriods-standAlone-wide-afternoon1": "中午",
	"dayPeriods-standAlone-wide-afternoon2": "下午",
	"dayPeriods-standAlone-wide-evening1": "晚上",
	"dayPeriods-standAlone-wide-night1": "凌晨",
	"eraNames": [
		"公元前",
		"公元"
	],
	"eraAbbr": [
		"公元前",
		"公元"
	],
	"eraNarrow": [
		"公元前",
		"公元"
	],
	"dateFormat-full": "y年M月d日EEEE",
	"dateFormat-long": "y年M月d日",
	"dateFormat-medium": "y年M月d日",
	"dateFormat-short": "y/M/d",
	"timeFormat-full": "zzzz ah:mm:ss",
	"timeFormat-long": "z ah:mm:ss",
	"timeFormat-medium": "ah:mm:ss",
	"timeFormat-short": "ah:mm",
	"dateTimeFormat-full": "{1} {0}",
	"dateTimeFormat-long": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "d日",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "d日E",
	"dateFormatItem-Ehm": "Eah:mm",
	"dateFormatItem-EHm": "EHH:mm",
	"dateFormatItem-Ehms": "Eah:mm:ss",
	"dateFormatItem-EHms": "EHH:mm:ss",
	"dateFormatItem-Gy": "Gy年",
	"dateFormatItem-GyMMM": "Gy年M月",
	"dateFormatItem-GyMMMd": "Gy年M月d日",
	"dateFormatItem-GyMMMEd": "Gy年M月d日E",
	"dateFormatItem-h": "ah时",
	"dateFormatItem-H": "H时",
	"dateFormatItem-hm": "ah:mm",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-hms": "ah:mm:ss",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hmsv": "v ah:mm:ss",
	"dateFormatItem-Hmsv": "v HH:mm:ss",
	"dateFormatItem-hmv": "v ah:mm",
	"dateFormatItem-Hmv": "v HH:mm",
	"dateFormatItem-M": "M月",
	"dateFormatItem-Md": "M/d",
	"dateFormatItem-MEd": "M/dE",
	"dateFormatItem-MMdd": "MM/dd",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "M月d日",
	"dateFormatItem-MMMEd": "M月d日E",
	"dateFormatItem-MMMMd": "M月d日",
	"dateFormatItem-MMMMW": "MMM第W周",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y年",
	"dateFormatItem-yM": "y年M月",
	"dateFormatItem-yMd": "y/M/d",
	"dateFormatItem-yMEd": "y/M/dE",
	"dateFormatItem-yMM": "y年M月",
	"dateFormatItem-yMMM": "y年M月",
	"dateFormatItem-yMMMd": "y年M月d日",
	"dateFormatItem-yMMMEd": "y年M月d日E",
	"dateFormatItem-yMMMM": "y年M月",
	"dateFormatItem-yQQQ": "y年第Q季度",
	"dateFormatItem-yQQQQ": "y年第Q季度",
	"dateFormatItem-yw": "y年第w周",
	"dateTimeFormats-appendItem-Timezone": "{1}{0}",
	"field-era": "纪元",
	"field-year": "年",
	"field-year-relative+-1": "去年",
	"field-year-relative+0": "今年",
	"field-year-relative+1": "明年",
	"field-year-short": "年",
	"field-year-narrow": "年",
	"field-quarter": "季度",
	"field-quarter-relative+-1": "上季度",
	"field-quarter-relative+0": "本季度",
	"field-quarter-relative+1": "下季度",
	"field-quarter-short": "季",
	"field-quarter-narrow": "季",
	"field-month": "月",
	"field-month-relative+-1": "上个月",
	"field-month-relative+0": "本月",
	"field-month-relative+1": "下个月",
	"field-month-short": "月",
	"field-month-narrow": "月",
	"field-week": "周",
	"field-week-relative+-1": "上周",
	"field-week-relative+0": "本周",
	"field-week-relative+1": "下周",
	"field-week-short": "周",
	"field-week-narrow": "周",
	"field-day": "日",
	"field-day-relative+-2": "前天",
	"field-day-relative+-1": "昨天",
	"field-day-relative+0": "今天",
	"field-day-relative+1": "明天",
	"field-day-relative+2": "后天",
	"field-day-short": "日",
	"field-day-narrow": "日",
	"field-weekday": "工作日",
	"field-sun-relative+-1": "上周日",
	"field-sun-relative+0": "本周日",
	"field-sun-relative+1": "下周日",
	"field-sun-short-relative+-1": "上周日",
	"field-sun-short-relative+0": "本周日",
	"field-sun-short-relative+1": "下周日",
	"field-sun-narrow-relative+-1": "上周日",
	"field-sun-narrow-relative+0": "本周日",
	"field-sun-narrow-relative+1": "下周日",
	"field-mon-relative+-1": "上周一",
	"field-mon-relative+0": "本周一",
	"field-mon-relative+1": "下周一",
	"field-mon-short-relative+-1": "上周一",
	"field-mon-short-relative+0": "本周一",
	"field-mon-short-relative+1": "下周一",
	"field-mon-narrow-relative+-1": "上周一",
	"field-mon-narrow-relative+0": "本周一",
	"field-mon-narrow-relative+1": "下周一",
	"field-tue-relative+-1": "上周二",
	"field-tue-relative+0": "本周二",
	"field-tue-relative+1": "下周二",
	"field-tue-short-relative+-1": "上周二",
	"field-tue-short-relative+0": "本周二",
	"field-tue-short-relative+1": "下周二",
	"field-tue-narrow-relative+-1": "上周二",
	"field-tue-narrow-relative+0": "本周二",
	"field-tue-narrow-relative+1": "下周二",
	"field-wed-relative+-1": "上周三",
	"field-wed-relative+0": "本周三",
	"field-wed-relative+1": "下周三",
	"field-wed-short-relative+-1": "上周三",
	"field-wed-short-relative+0": "本周三",
	"field-wed-short-relative+1": "下周三",
	"field-wed-narrow-relative+-1": "上周三",
	"field-wed-narrow-relative+0": "本周三",
	"field-wed-narrow-relative+1": "下周三",
	"field-thu-relative+-1": "上周四",
	"field-thu-relative+0": "本周四",
	"field-thu-relative+1": "下周四",
	"field-thu-short-relative+-1": "上周四",
	"field-thu-short-relative+0": "本周四",
	"field-thu-short-relative+1": "下周四",
	"field-thu-narrow-relative+-1": "上周四",
	"field-thu-narrow-relative+0": "本周四",
	"field-thu-narrow-relative+1": "下周四",
	"field-fri-relative+-1": "上周五",
	"field-fri-relative+0": "本周五",
	"field-fri-relative+1": "下周五",
	"field-fri-short-relative+-1": "上周五",
	"field-fri-short-relative+0": "本周五",
	"field-fri-short-relative+1": "下周五",
	"field-fri-narrow-relative+-1": "上周五",
	"field-fri-narrow-relative+0": "本周五",
	"field-fri-narrow-relative+1": "下周五",
	"field-sat-relative+-1": "上周六",
	"field-sat-relative+0": "本周六",
	"field-sat-relative+1": "下周六",
	"field-sat-short-relative+-1": "上周六",
	"field-sat-short-relative+0": "本周六",
	"field-sat-short-relative+1": "下周六",
	"field-sat-narrow-relative+-1": "上周六",
	"field-sat-narrow-relative+0": "本周六",
	"field-sat-narrow-relative+1": "下周六",
	"field-dayperiod": "上午/下午",
	"field-hour": "小时",
	"field-hour-relative+0": "这一时间 / 此时",
	"field-hour-short": "小时",
	"field-hour-narrow": "小时",
	"field-minute": "分钟",
	"field-minute-relative+0": "此刻",
	"field-minute-short": "分",
	"field-minute-narrow": "分",
	"field-second": "秒",
	"field-second-relative+0": "现在",
	"field-second-short": "秒",
	"field-second-narrow": "秒",
	"field-zone": "时区"
}
//end v1.x content
);