define(
//begin v1.x content
{
	"months-format-abbr": [
		"gen",
		"feb",
		"mar",
		"apr",
		"mag",
		"giu",
		"lug",
		"ago",
		"set",
		"ott",
		"nov",
		"dic"
	],
	"months-format-narrow": [
		"G",
		"F",
		"M",
		"A",
		"M",
		"G",
		"L",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"months-format-wide": [
		"gennaio",
		"febbraio",
		"marzo",
		"aprile",
		"maggio",
		"giugno",
		"luglio",
		"agosto",
		"settembre",
		"ottobre",
		"novembre",
		"dicembre"
	],
	"months-standAlone-abbr": [
		"gen",
		"feb",
		"mar",
		"apr",
		"mag",
		"giu",
		"lug",
		"ago",
		"set",
		"ott",
		"nov",
		"dic"
	],
	"months-standAlone-narrow": [
		"G",
		"F",
		"M",
		"A",
		"M",
		"G",
		"L",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"months-standAlone-wide": [
		"gennaio",
		"febbraio",
		"marzo",
		"aprile",
		"maggio",
		"giugno",
		"luglio",
		"agosto",
		"settembre",
		"ottobre",
		"novembre",
		"dicembre"
	],
	"days-format-abbr": [
		"dom",
		"lun",
		"mar",
		"mer",
		"gio",
		"ven",
		"sab"
	],
	"days-format-narrow": [
		"D",
		"L",
		"M",
		"M",
		"G",
		"V",
		"S"
	],
	"days-format-short": [
		"dom",
		"lun",
		"mar",
		"mer",
		"gio",
		"ven",
		"sab"
	],
	"days-format-wide": [
		"domenica",
		"lunedì",
		"martedì",
		"mercoledì",
		"giovedì",
		"venerdì",
		"sabato"
	],
	"days-standAlone-abbr": [
		"dom",
		"lun",
		"mar",
		"mer",
		"gio",
		"ven",
		"sab"
	],
	"days-standAlone-narrow": [
		"D",
		"L",
		"M",
		"M",
		"G",
		"V",
		"S"
	],
	"days-standAlone-short": [
		"dom",
		"lun",
		"mar",
		"mer",
		"gio",
		"ven",
		"sab"
	],
	"days-standAlone-wide": [
		"domenica",
		"lunedì",
		"martedì",
		"mercoledì",
		"giovedì",
		"venerdì",
		"sabato"
	],
	"quarters-format-abbr": [
		"T1",
		"T2",
		"T3",
		"T4"
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"1º trimestre",
		"2º trimestre",
		"3º trimestre",
		"4º trimestre"
	],
	"quarters-standAlone-abbr": [
		"T1",
		"T2",
		"T3",
		"T4"
	],
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-standAlone-wide": [
		"1º trimestre",
		"2º trimestre",
		"3º trimestre",
		"4º trimestre"
	],
	"dayPeriods-format-abbr-midnight": "mezzanotte",
	"dayPeriods-format-abbr-am": "AM",
	"dayPeriods-format-abbr-noon": "mezzogiorno",
	"dayPeriods-format-abbr-pm": "PM",
	"dayPeriods-format-abbr-morning1": "di mattina",
	"dayPeriods-format-abbr-afternoon1": "del pomeriggio",
	"dayPeriods-format-abbr-evening1": "di sera",
	"dayPeriods-format-abbr-night1": "di notte",
	"dayPeriods-format-narrow-midnight": "mezzanotte",
	"dayPeriods-format-narrow-am": "m.",
	"dayPeriods-format-narrow-noon": "mezzogiorno",
	"dayPeriods-format-narrow-pm": "p.",
	"dayPeriods-format-narrow-morning1": "mattina",
	"dayPeriods-format-narrow-afternoon1": "pomeriggio",
	"dayPeriods-format-narrow-evening1": "sera",
	"dayPeriods-format-narrow-night1": "notte",
	"dayPeriods-format-wide-midnight": "mezzanotte",
	"dayPeriods-format-wide-am": "AM",
	"dayPeriods-format-wide-noon": "mezzogiorno",
	"dayPeriods-format-wide-pm": "PM",
	"dayPeriods-format-wide-morning1": "di mattina",
	"dayPeriods-format-wide-afternoon1": "del pomeriggio",
	"dayPeriods-format-wide-evening1": "di sera",
	"dayPeriods-format-wide-night1": "di notte",
	"dayPeriods-standAlone-abbr-midnight": "mezzanotte",
	"dayPeriods-standAlone-abbr-am": "AM",
	"dayPeriods-standAlone-abbr-noon": "mezzogiorno",
	"dayPeriods-standAlone-abbr-pm": "PM",
	"dayPeriods-standAlone-abbr-morning1": "mattina",
	"dayPeriods-standAlone-abbr-afternoon1": "pomeriggio",
	"dayPeriods-standAlone-abbr-evening1": "sera",
	"dayPeriods-standAlone-abbr-night1": "notte",
	"dayPeriods-standAlone-narrow-midnight": "mezzanotte",
	"dayPeriods-standAlone-narrow-am": "m.",
	"dayPeriods-standAlone-narrow-noon": "mezzogiorno",
	"dayPeriods-standAlone-narrow-pm": "p.",
	"dayPeriods-standAlone-narrow-morning1": "mattina",
	"dayPeriods-standAlone-narrow-afternoon1": "pomeriggio",
	"dayPeriods-standAlone-narrow-evening1": "sera",
	"dayPeriods-standAlone-narrow-night1": "notte",
	"dayPeriods-standAlone-wide-midnight": "mezzanotte",
	"dayPeriods-standAlone-wide-am": "AM",
	"dayPeriods-standAlone-wide-noon": "mezzogiorno",
	"dayPeriods-standAlone-wide-pm": "PM",
	"dayPeriods-standAlone-wide-morning1": "mattina",
	"dayPeriods-standAlone-wide-afternoon1": "pomeriggio",
	"dayPeriods-standAlone-wide-evening1": "sera",
	"dayPeriods-standAlone-wide-night1": "notte",
	"eraNames": [
		"avanti Cristo",
		"dopo Cristo"
	],
	"eraAbbr": [
		"a.C.",
		"d.C."
	],
	"eraNarrow": [
		"aC",
		"BCE",
		"dC",
		"CE"
	],
	"dateFormat-full": "EEEE d MMMM y",
	"dateFormat-long": "d MMMM y",
	"dateFormat-medium": "dd MMM y",
	"dateFormat-short": "dd/MM/yy",
	"timeFormat-full": "HH:mm:ss zzzz",
	"timeFormat-long": "HH:mm:ss z",
	"timeFormat-medium": "HH:mm:ss",
	"timeFormat-short": "HH:mm",
	"dateTimeFormat-full": "{1} {0}",
	"dateTimeFormat-long": "{1} {0}",
	"dateTimeFormat-medium": "{1}, {0}",
	"dateTimeFormat-short": "{1}, {0}",
	"dateFormatItem-d": "d",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-Ehm": "E h:mm a",
	"dateFormatItem-EHm": "E HH:mm",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "MMM y G",
	"dateFormatItem-GyMMMd": "d MMM y G",
	"dateFormatItem-GyMMMEd": "E d MMM y G",
	"dateFormatItem-h": "h a",
	"dateFormatItem-H": "HH",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hmsv": "h:mm:ss a v",
	"dateFormatItem-Hmsv": "HH:mm:ss v",
	"dateFormatItem-hmv": "h:mm a v",
	"dateFormatItem-Hmv": "HH:mm v",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MMMEd": "E d MMM",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-MMMMW": "'settimana' W 'di' MMM",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y",
	"dateFormatItem-yM": "M/y",
	"dateFormatItem-yMd": "d/M/y",
	"dateFormatItem-yMEd": "E d/M/y",
	"dateFormatItem-yMMM": "MMM y",
	"dateFormatItem-yMMMd": "d MMM y",
	"dateFormatItem-yMMMEd": "E d MMM y",
	"dateFormatItem-yMMMM": "MMMM y",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"dateFormatItem-yw": "'settimana' w 'del' y",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-era": "era",
	"field-year": "anno",
	"field-year-relative+-1": "anno scorso",
	"field-year-relative+0": "quest’anno",
	"field-year-relative+1": "anno prossimo",
	"field-year-short": "anno",
	"field-year-narrow": "anno",
	"field-quarter": "trimestre",
	"field-quarter-relative+-1": "trimestre scorso",
	"field-quarter-relative+0": "questo trimestre",
	"field-quarter-relative+1": "trimestre prossimo",
	"field-quarter-short": "trim.",
	"field-quarter-short-relative+-1": "trim. scorso",
	"field-quarter-short-relative+0": "questo trim.",
	"field-quarter-short-relative+1": "trim. prossimo",
	"field-quarter-narrow": "trim.",
	"field-quarter-narrow-relative+-1": "trim. scorso",
	"field-quarter-narrow-relative+0": "questo trim.",
	"field-quarter-narrow-relative+1": "trim. prossimo",
	"field-month": "mese",
	"field-month-relative+-1": "mese scorso",
	"field-month-relative+0": "questo mese",
	"field-month-relative+1": "mese prossimo",
	"field-month-short": "mese",
	"field-month-narrow": "mese",
	"field-week": "settimana",
	"field-week-relative+-1": "settimana scorsa",
	"field-week-relative+0": "questa settimana",
	"field-week-relative+1": "settimana prossima",
	"field-week-short": "sett.",
	"field-week-narrow": "sett.",
	"field-day": "giorno",
	"field-day-relative+-2": "l’altro ieri",
	"field-day-relative+-1": "ieri",
	"field-day-relative+0": "oggi",
	"field-day-relative+1": "domani",
	"field-day-relative+2": "dopodomani",
	"field-day-short": "g",
	"field-day-narrow": "g",
	"field-weekday": "giorno della settimana",
	"field-sun-relative+-1": "domenica scorsa",
	"field-sun-relative+0": "questa domenica",
	"field-sun-relative+1": "domenica prossima",
	"field-sun-short-relative+-1": "dom. scorsa",
	"field-sun-short-relative+0": "questa dom.",
	"field-sun-short-relative+1": "dom. prossima",
	"field-sun-narrow-relative+-1": "do scorsa",
	"field-sun-narrow-relative+0": "questa do",
	"field-sun-narrow-relative+1": "do prossima",
	"field-mon-relative+-1": "lunedì scorso",
	"field-mon-relative+0": "questo lunedì",
	"field-mon-relative+1": "lunedì prossimo",
	"field-mon-short-relative+-1": "lun. scorso",
	"field-mon-short-relative+0": "questo lun.",
	"field-mon-short-relative+1": "lun. prossimo",
	"field-mon-narrow-relative+-1": "lu scorso",
	"field-mon-narrow-relative+0": "questo lu",
	"field-mon-narrow-relative+1": "lu prossimo",
	"field-tue-relative+-1": "martedì scorso",
	"field-tue-relative+0": "questo martedì",
	"field-tue-relative+1": "martedì prossimo",
	"field-tue-short-relative+-1": "mar. scorso",
	"field-tue-short-relative+0": "questo mar.",
	"field-tue-short-relative+1": "mar. prossimo",
	"field-tue-narrow-relative+-1": "ma scorso",
	"field-tue-narrow-relative+0": "questo ma",
	"field-tue-narrow-relative+1": "ma prossimo",
	"field-wed-relative+-1": "mercoledì scorso",
	"field-wed-relative+0": "questo mercoledì",
	"field-wed-relative+1": "mercoledì prossimo",
	"field-wed-short-relative+-1": "mer. scorso",
	"field-wed-short-relative+0": "questo mer.",
	"field-wed-short-relative+1": "mer. prossimo",
	"field-wed-narrow-relative+-1": "me scorso",
	"field-wed-narrow-relative+0": "questo me",
	"field-wed-narrow-relative+1": "me prossimo",
	"field-thu-relative+-1": "giovedì scorso",
	"field-thu-relative+0": "questo giovedì",
	"field-thu-relative+1": "giovedì prossimo",
	"field-thu-short-relative+-1": "gio. scorso",
	"field-thu-short-relative+0": "questo gio.",
	"field-thu-short-relative+1": "gio. prossimo",
	"field-thu-narrow-relative+-1": "gi scorso",
	"field-thu-narrow-relative+0": "questo gi",
	"field-thu-narrow-relative+1": "gi prossimo",
	"field-fri-relative+-1": "venerdì scorso",
	"field-fri-relative+0": "questo venerdì",
	"field-fri-relative+1": "venerdì prossimo",
	"field-fri-short-relative+-1": "ven. scorso",
	"field-fri-short-relative+0": "questo ven.",
	"field-fri-short-relative+1": "ven. prossimo",
	"field-fri-narrow-relative+-1": "ve scorso",
	"field-fri-narrow-relative+0": "questo ve",
	"field-fri-narrow-relative+1": "ve prossimo",
	"field-sat-relative+-1": "sabato scorso",
	"field-sat-relative+0": "questo sabato",
	"field-sat-relative+1": "sabato prossimo",
	"field-sat-short-relative+-1": "sab. scorso",
	"field-sat-short-relative+0": "questo sab.",
	"field-sat-short-relative+1": "sab. prossimo",
	"field-sat-narrow-relative+-1": "sa scorso",
	"field-sat-narrow-relative+0": "questo sa",
	"field-sat-narrow-relative+1": "sa prossimo",
	"field-dayperiod": "AM/PM",
	"field-hour": "ora",
	"field-hour-relative+0": "quest’ora",
	"field-hour-short": "h.",
	"field-hour-narrow": "h",
	"field-minute": "minuto",
	"field-minute-relative+0": "questo minuto",
	"field-minute-short": "min.",
	"field-minute-narrow": "m",
	"field-second": "secondo",
	"field-second-relative+0": "ora",
	"field-second-short": "sec.",
	"field-second-narrow": "s",
	"field-zone": "fuso orario"
}
//end v1.x content
);