define(
//begin v1.x content
{
	"eraAbbr": [
		"Prima di R.O.C.",
		"Minguo"
	],
	"field-era": "era",
	"field-year": "anno",
	"field-year-relative+-1": "anno scorso",
	"field-year-relative+0": "quest’anno",
	"field-year-relative+1": "anno prossimo",
	"field-year-short": "anno",
	"field-year-narrow": "anno",
	"field-quarter": "trimestre",
	"field-quarter-relative+-1": "trimestre scorso",
	"field-quarter-relative+0": "questo trimestre",
	"field-quarter-relative+1": "trimestre prossimo",
	"field-quarter-short": "trim.",
	"field-quarter-short-relative+-1": "trim. scorso",
	"field-quarter-short-relative+0": "questo trim.",
	"field-quarter-short-relative+1": "trim. prossimo",
	"field-quarter-narrow": "trim.",
	"field-quarter-narrow-relative+-1": "trim. scorso",
	"field-quarter-narrow-relative+0": "questo trim.",
	"field-quarter-narrow-relative+1": "trim. prossimo",
	"field-month": "mese",
	"field-month-relative+-1": "mese scorso",
	"field-month-relative+0": "questo mese",
	"field-month-relative+1": "mese prossimo",
	"field-month-short": "mese",
	"field-month-narrow": "mese",
	"field-week": "settimana",
	"field-week-relative+-1": "settimana scorsa",
	"field-week-relative+0": "questa settimana",
	"field-week-relative+1": "settimana prossima",
	"field-week-short": "sett.",
	"field-week-narrow": "sett.",
	"field-day": "giorno",
	"field-day-relative+-2": "l’altro ieri",
	"field-day-relative+-1": "ieri",
	"field-day-relative+0": "oggi",
	"field-day-relative+1": "domani",
	"field-day-relative+2": "dopodomani",
	"field-day-short": "g",
	"field-day-narrow": "g",
	"field-weekday": "giorno della settimana",
	"field-sun-relative+-1": "domenica scorsa",
	"field-sun-relative+0": "questa domenica",
	"field-sun-relative+1": "domenica prossima",
	"field-sun-short-relative+-1": "dom. scorsa",
	"field-sun-short-relative+0": "questa dom.",
	"field-sun-short-relative+1": "dom. prossima",
	"field-sun-narrow-relative+-1": "do scorsa",
	"field-sun-narrow-relative+0": "questa do",
	"field-sun-narrow-relative+1": "do prossima",
	"field-mon-relative+-1": "lunedì scorso",
	"field-mon-relative+0": "questo lunedì",
	"field-mon-relative+1": "lunedì prossimo",
	"field-mon-short-relative+-1": "lun. scorso",
	"field-mon-short-relative+0": "questo lun.",
	"field-mon-short-relative+1": "lun. prossimo",
	"field-mon-narrow-relative+-1": "lu scorso",
	"field-mon-narrow-relative+0": "questo lu",
	"field-mon-narrow-relative+1": "lu prossimo",
	"field-tue-relative+-1": "martedì scorso",
	"field-tue-relative+0": "questo martedì",
	"field-tue-relative+1": "martedì prossimo",
	"field-tue-short-relative+-1": "mar. scorso",
	"field-tue-short-relative+0": "questo mar.",
	"field-tue-short-relative+1": "mar. prossimo",
	"field-tue-narrow-relative+-1": "ma scorso",
	"field-tue-narrow-relative+0": "questo ma",
	"field-tue-narrow-relative+1": "ma prossimo",
	"field-wed-relative+-1": "mercoledì scorso",
	"field-wed-relative+0": "questo mercoledì",
	"field-wed-relative+1": "mercoledì prossimo",
	"field-wed-short-relative+-1": "mer. scorso",
	"field-wed-short-relative+0": "questo mer.",
	"field-wed-short-relative+1": "mer. prossimo",
	"field-wed-narrow-relative+-1": "me scorso",
	"field-wed-narrow-relative+0": "questo me",
	"field-wed-narrow-relative+1": "me prossimo",
	"field-thu-relative+-1": "giovedì scorso",
	"field-thu-relative+0": "questo giovedì",
	"field-thu-relative+1": "giovedì prossimo",
	"field-thu-short-relative+-1": "gio. scorso",
	"field-thu-short-relative+0": "questo gio.",
	"field-thu-short-relative+1": "gio. prossimo",
	"field-thu-narrow-relative+-1": "gi scorso",
	"field-thu-narrow-relative+0": "questo gi",
	"field-thu-narrow-relative+1": "gi prossimo",
	"field-fri-relative+-1": "venerdì scorso",
	"field-fri-relative+0": "questo venerdì",
	"field-fri-relative+1": "venerdì prossimo",
	"field-fri-short-relative+-1": "ven. scorso",
	"field-fri-short-relative+0": "questo ven.",
	"field-fri-short-relative+1": "ven. prossimo",
	"field-fri-narrow-relative+-1": "ve scorso",
	"field-fri-narrow-relative+0": "questo ve",
	"field-fri-narrow-relative+1": "ve prossimo",
	"field-sat-relative+-1": "sabato scorso",
	"field-sat-relative+0": "questo sabato",
	"field-sat-relative+1": "sabato prossimo",
	"field-sat-short-relative+-1": "sab. scorso",
	"field-sat-short-relative+0": "questo sab.",
	"field-sat-short-relative+1": "sab. prossimo",
	"field-sat-narrow-relative+-1": "sa scorso",
	"field-sat-narrow-relative+0": "questo sa",
	"field-sat-narrow-relative+1": "sa prossimo",
	"field-dayperiod": "AM/PM",
	"field-hour": "ora",
	"field-hour-relative+0": "quest’ora",
	"field-hour-short": "h.",
	"field-hour-narrow": "h",
	"field-minute": "minuto",
	"field-minute-relative+0": "questo minuto",
	"field-minute-short": "min.",
	"field-minute-narrow": "m",
	"field-second": "secondo",
	"field-second-relative+0": "ora",
	"field-second-short": "sec.",
	"field-second-narrow": "s",
	"field-zone": "fuso orario"
}
//end v1.x content
);