define(
//begin v1.x content
{
	"months-format-abbr": [
		"jan",
		"feb",
		"mar",
		"apr",
		"maj",
		"jun",
		"jul",
		"avg",
		"sep",
		"okt",
		"nov",
		"dec"
	],
	"months-format-narrow": [
		"j",
		"f",
		"m",
		"a",
		"m",
		"j",
		"j",
		"a",
		"s",
		"o",
		"n",
		"d"
	],
	"months-format-wide": [
		"januar",
		"februar",
		"mart",
		"april",
		"maj",
		"juni",
		"juli",
		"avgust",
		"septembar",
		"oktobar",
		"novembar",
		"decembar"
	],
	"months-standAlone-abbr": [
		"jan",
		"feb",
		"mar",
		"apr",
		"maj",
		"jun",
		"jul",
		"avg",
		"sep",
		"okt",
		"nov",
		"dec"
	],
	"months-standAlone-narrow": [
		"j",
		"f",
		"m",
		"a",
		"m",
		"j",
		"j",
		"a",
		"s",
		"o",
		"n",
		"d"
	],
	"months-standAlone-wide": [
		"januar",
		"februar",
		"mart",
		"april",
		"maj",
		"juni",
		"juli",
		"avgust",
		"septembar",
		"oktobar",
		"novembar",
		"decembar"
	],
	"days-format-abbr": [
		"ned",
		"pon",
		"uto",
		"sri",
		"čet",
		"pet",
		"sub"
	],
	"days-format-narrow": [
		"N",
		"P",
		"U",
		"S",
		"Č",
		"P",
		"S"
	],
	"days-format-short": [
		"ned",
		"pon",
		"uto",
		"sri",
		"čet",
		"pet",
		"sub"
	],
	"days-format-wide": [
		"nedjelja",
		"ponedjeljak",
		"utorak",
		"srijeda",
		"četvrtak",
		"petak",
		"subota"
	],
	"days-standAlone-abbr": [
		"ned",
		"pon",
		"uto",
		"sri",
		"čet",
		"pet",
		"sub"
	],
	"days-standAlone-narrow": [
		"n",
		"p",
		"u",
		"s",
		"č",
		"p",
		"s"
	],
	"days-standAlone-short": [
		"ned",
		"pon",
		"uto",
		"sri",
		"čet",
		"pet",
		"sub"
	],
	"days-standAlone-wide": [
		"nedjelja",
		"ponedjeljak",
		"utorak",
		"srijeda",
		"četvrtak",
		"petak",
		"subota"
	],
	"quarters-format-abbr": [
		"K1",
		"K2",
		"K3",
		"K4"
	],
	"quarters-format-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"quarters-format-wide": [
		"Prvi kvartal",
		"Drugi kvartal",
		"Treći kvartal",
		"Četvrti kvartal"
	],
	"quarters-standAlone-abbr": [
		"K1",
		"K2",
		"K3",
		"K4"
	],
	"quarters-standAlone-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"quarters-standAlone-wide": [
		"Prvi kvartal",
		"Drugi kvartal",
		"Treći kvartal",
		"Četvrti kvartal"
	],
	"dayPeriods-format-abbr-midnight": "ponoć",
	"dayPeriods-format-abbr-am": "prijepodne",
	"dayPeriods-format-abbr-noon": "podne",
	"dayPeriods-format-abbr-pm": "popodne",
	"dayPeriods-format-abbr-morning1": "ujutro",
	"dayPeriods-format-abbr-afternoon1": "poslijepodne",
	"dayPeriods-format-abbr-evening1": "navečer",
	"dayPeriods-format-abbr-night1": "po noći",
	"dayPeriods-format-narrow-midnight": "ponoć",
	"dayPeriods-format-narrow-am": "prijepodne",
	"dayPeriods-format-narrow-noon": "podne",
	"dayPeriods-format-narrow-pm": "popodne",
	"dayPeriods-format-narrow-morning1": "ujutro",
	"dayPeriods-format-narrow-afternoon1": "poslijepodne",
	"dayPeriods-format-narrow-evening1": "navečer",
	"dayPeriods-format-narrow-night1": "po noći",
	"dayPeriods-format-wide-midnight": "ponoć",
	"dayPeriods-format-wide-am": "prijepodne",
	"dayPeriods-format-wide-noon": "podne",
	"dayPeriods-format-wide-pm": "popodne",
	"dayPeriods-format-wide-morning1": "ujutro",
	"dayPeriods-format-wide-afternoon1": "poslijepodne",
	"dayPeriods-format-wide-evening1": "navečer",
	"dayPeriods-format-wide-night1": "po noći",
	"dayPeriods-standAlone-abbr-midnight": "ponoć",
	"dayPeriods-standAlone-abbr-am": "prijepodne",
	"dayPeriods-standAlone-abbr-noon": "podne",
	"dayPeriods-standAlone-abbr-pm": "popodne",
	"dayPeriods-standAlone-abbr-morning1": "ujutro",
	"dayPeriods-standAlone-abbr-afternoon1": "poslijepodne",
	"dayPeriods-standAlone-abbr-evening1": "navečer",
	"dayPeriods-standAlone-abbr-night1": "po noći",
	"dayPeriods-standAlone-narrow-midnight": "ponoć",
	"dayPeriods-standAlone-narrow-am": "prijepodne",
	"dayPeriods-standAlone-narrow-noon": "podne",
	"dayPeriods-standAlone-narrow-pm": "popodne",
	"dayPeriods-standAlone-narrow-morning1": "ujutro",
	"dayPeriods-standAlone-narrow-afternoon1": "poslijepodne",
	"dayPeriods-standAlone-narrow-evening1": "navečer",
	"dayPeriods-standAlone-narrow-night1": "po noći",
	"dayPeriods-standAlone-wide-midnight": "ponoć",
	"dayPeriods-standAlone-wide-am": "prijepodne",
	"dayPeriods-standAlone-wide-noon": "podne",
	"dayPeriods-standAlone-wide-pm": "popodne",
	"dayPeriods-standAlone-wide-morning1": "ujutro",
	"dayPeriods-standAlone-wide-afternoon1": "poslijepodne",
	"dayPeriods-standAlone-wide-evening1": "navečer",
	"dayPeriods-standAlone-wide-night1": "po noći",
	"eraNames": [
		"prije nove ere",
		"nove ere"
	],
	"eraAbbr": [
		"p. n. e.",
		"n. e."
	],
	"dateFormat-full": "EEEE, d. MMMM y.",
	"dateFormat-long": "d. MMMM y.",
	"dateFormat-medium": "d. MMM. y.",
	"dateFormat-short": "d.M.yy.",
	"timeFormat-full": "HH:mm:ss zzzz",
	"timeFormat-long": "HH:mm:ss z",
	"timeFormat-medium": "HH:mm:ss",
	"timeFormat-short": "HH:mm",
	"dateTimeFormat-full": "{1} 'u' {0}",
	"dateTimeFormat-long": "{1} 'u' {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "d.",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E, d.",
	"dateFormatItem-Ehm": "E h:mm a",
	"dateFormatItem-EHm": "E HH:mm",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"dateFormatItem-EHms": "E HH:mm:ss",
	"dateFormatItem-Gy": "y. G",
	"dateFormatItem-GyMMM": "MMM y. G",
	"dateFormatItem-GyMMMd": "d. MMM y. G",
	"dateFormatItem-GyMMMEd": "E, d. MMM y. G",
	"dateFormatItem-h": "h a",
	"dateFormatItem-H": "HH",
	"dateFormatItem-hm": "hh:mm a",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-hms": "hh:mm:ss a",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hmsv": "h:mm:ss a (v)",
	"dateFormatItem-Hmsv": "HH:mm:ss (v)",
	"dateFormatItem-hmv": "h:mm a (v)",
	"dateFormatItem-Hmv": "HH:mm (v)",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-MEd": "E, d.M.",
	"dateFormatItem-MMdd": "d. M.",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-MMMMEd": "E, d. MMMM",
	"dateFormatItem-MMMMW": "W. 'sedmica' 'u' MMM",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y.",
	"dateFormatItem-yM": "MM/y",
	"dateFormatItem-yMd": "d.M.y.",
	"dateFormatItem-yMEd": "E, d.M.y.",
	"dateFormatItem-yMM": "M/y",
	"dateFormatItem-yMMM": "MMM y.",
	"dateFormatItem-yMMMd": "d. MMM y.",
	"dateFormatItem-yMMMEd": "E, d. MMM y.",
	"dateFormatItem-yMMMM": "LLLL y.",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"dateFormatItem-yw": "w. 'sedmica' 'u' y.",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-era": "era",
	"field-year": "godina",
	"field-year-relative+-1": "prošle godine",
	"field-year-relative+0": "ove godine",
	"field-year-relative+1": "sljedeće godine",
	"field-year-short": "god.",
	"field-year-narrow": "g.",
	"field-quarter": "kvartal",
	"field-quarter-relative+-1": "posljednji kvartal",
	"field-quarter-relative+0": "ovaj kvartal",
	"field-quarter-relative+1": "sljedeći kvartal",
	"field-quarter-short": "kv.",
	"field-quarter-narrow": "kv.",
	"field-month": "mjesec",
	"field-month-relative+-1": "prošli mjesec",
	"field-month-relative+0": "ovaj mjesec",
	"field-month-relative+1": "sljedeći mjesec",
	"field-month-short": "mj.",
	"field-month-narrow": "mj.",
	"field-week": "sedmica",
	"field-week-relative+-1": "prošle sedmice",
	"field-week-relative+0": "ove sedmice",
	"field-week-relative+1": "sljedeće sedmice",
	"field-week-short": "sed.",
	"field-week-narrow": "sed.",
	"field-day": "dan",
	"field-day-relative+-2": "prekjučer",
	"field-day-relative+-1": "jučer",
	"field-day-relative+0": "danas",
	"field-day-relative+1": "sutra",
	"field-day-relative+2": "prekosutra",
	"field-day-short": "dan",
	"field-day-narrow": "dan",
	"field-weekday": "dan u sedmici",
	"field-sun-relative+-1": "prošla nedjelja",
	"field-sun-relative+0": "ova nedjelja",
	"field-sun-relative+1": "sljedeća nedjelja",
	"field-sun-short-relative+-1": "prošla ned.",
	"field-sun-short-relative+0": "ova ned.",
	"field-sun-short-relative+1": "sljedeća ned.",
	"field-sun-narrow-relative+-1": "prošla ned.",
	"field-sun-narrow-relative+0": "ova ned.",
	"field-sun-narrow-relative+1": "sljedeća ned.",
	"field-mon-relative+-1": "prošli ponedjeljak",
	"field-mon-relative+0": "ovaj ponedjeljak",
	"field-mon-relative+1": "sljedeći ponedjeljak",
	"field-mon-short-relative+-1": "prošli pon.",
	"field-mon-short-relative+0": "ovaj pon.",
	"field-mon-short-relative+1": "sljedeći pon",
	"field-mon-narrow-relative+-1": "prošli pon.",
	"field-mon-narrow-relative+0": "ovaj pon.",
	"field-mon-narrow-relative+1": "sljedeći pon",
	"field-tue-relative+-1": "prošli utorak",
	"field-tue-relative+0": "ovaj utorak",
	"field-tue-relative+1": "sljedeći utorak",
	"field-tue-short-relative+-1": "prošli uto.",
	"field-tue-short-relative+0": "ovaj uto.",
	"field-tue-short-relative+1": "sljedeći uto.",
	"field-tue-narrow-relative+-1": "prošli uto.",
	"field-tue-narrow-relative+0": "ovaj uto.",
	"field-tue-narrow-relative+1": "sljedeći uto.",
	"field-wed-relative+-1": "prošla srijeda",
	"field-wed-relative+0": "ova srijeda",
	"field-wed-relative+1": "sljedeća srijeda",
	"field-wed-short-relative+-1": "prošla sri.",
	"field-wed-short-relative+0": "ova sri.",
	"field-wed-short-relative+1": "sljedeća sri.",
	"field-wed-narrow-relative+-1": "prošla sri.",
	"field-wed-narrow-relative+0": "ova sri.",
	"field-wed-narrow-relative+1": "sljedeća sri.",
	"field-thu-relative+-1": "prošli četvrtak",
	"field-thu-relative+0": "ovaj četvrtak",
	"field-thu-relative+1": "sljedeći četvrtak",
	"field-thu-short-relative+-1": "prošli čet.",
	"field-thu-short-relative+0": "ovaj čet.",
	"field-thu-short-relative+1": "sljedeći čet.",
	"field-thu-narrow-relative+-1": "prošli čet.",
	"field-thu-narrow-relative+0": "ovaj čet.",
	"field-thu-narrow-relative+1": "sljedeći čet.",
	"field-fri-relative+-1": "prošli petak",
	"field-fri-relative+0": "ovaj petak",
	"field-fri-relative+1": "sljedeći petak",
	"field-fri-short-relative+-1": "prošli pet.",
	"field-fri-short-relative+0": "ovaj pet.",
	"field-fri-short-relative+1": "sljedeći pet.",
	"field-fri-narrow-relative+-1": "prošli pet.",
	"field-fri-narrow-relative+0": "ovaj pet.",
	"field-fri-narrow-relative+1": "sljedeći pet.",
	"field-sat-relative+-1": "prošla subota",
	"field-sat-relative+0": "ova subota",
	"field-sat-relative+1": "sljedeća subota",
	"field-sat-short-relative+-1": "prošla sub.",
	"field-sat-short-relative+0": "ova sub.",
	"field-sat-short-relative+1": "sljedeća sub.",
	"field-sat-narrow-relative+-1": "prošla sub.",
	"field-sat-narrow-relative+0": "ova sub.",
	"field-sat-narrow-relative+1": "sljedeća sub.",
	"field-dayperiod": "prijepodne/poslijepodne",
	"field-hour": "sat",
	"field-hour-relative+0": "ovaj sat",
	"field-hour-short": "h",
	"field-hour-narrow": "h",
	"field-minute": "minuta",
	"field-minute-relative+0": "ova minuta",
	"field-minute-short": "min.",
	"field-minute-narrow": "min.",
	"field-second": "sekunda",
	"field-second-relative+0": "sada",
	"field-second-short": "sek.",
	"field-second-narrow": "s",
	"field-zone": "vremenska zona",
	"eraNarrow": [
		"p. n. e.",
		"n. e."
	]
}
//end v1.x content
);