define(
//begin v1.x content
{
	"months-format-abbr": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-standAlone-abbr": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-standAlone-wide": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"field-era": "eră",
	"field-year": "an",
	"field-year-relative+-1": "anul trecut",
	"field-year-relative+0": "anul acesta",
	"field-year-relative+1": "anul viitor",
	"field-year-short": "an",
	"field-year-narrow": "an",
	"field-quarter": "trimestru",
	"field-quarter-relative+-1": "trimestrul trecut",
	"field-quarter-relative+0": "trimestrul acesta",
	"field-quarter-relative+1": "trimestrul viitor",
	"field-quarter-short": "trim.",
	"field-quarter-short-relative+-1": "trim. trecut",
	"field-quarter-short-relative+0": "trim. acesta",
	"field-quarter-short-relative+1": "trim. viitor",
	"field-quarter-narrow": "trim.",
	"field-quarter-narrow-relative+-1": "trim. trecut",
	"field-quarter-narrow-relative+0": "trim. acesta",
	"field-quarter-narrow-relative+1": "trim. viitor",
	"field-month": "lună",
	"field-month-relative+-1": "luna trecută",
	"field-month-relative+0": "luna aceasta",
	"field-month-relative+1": "luna viitoare",
	"field-month-short": "lună",
	"field-month-narrow": "lună",
	"field-week": "săptămână",
	"field-week-relative+-1": "săptămâna trecută",
	"field-week-relative+0": "săptămâna aceasta",
	"field-week-relative+1": "săptămâna viitoare",
	"field-week-short": "săpt.",
	"field-week-narrow": "săpt.",
	"field-day": "zi",
	"field-day-relative+-2": "alaltăieri",
	"field-day-relative+-1": "ieri",
	"field-day-relative+0": "azi",
	"field-day-relative+1": "mâine",
	"field-day-relative+2": "poimâine",
	"field-day-short": "zi",
	"field-day-narrow": "zi",
	"field-weekday": "Zi a săptămânii",
	"field-sun-relative+-1": "duminica trecută",
	"field-sun-relative+0": "duminica aceasta",
	"field-sun-relative+1": "duminica viitoare",
	"field-sun-short-relative+-1": "dum. trecută",
	"field-sun-short-relative+0": "dum. aceasta",
	"field-sun-short-relative+1": "dum. viitoare",
	"field-sun-narrow-relative+-1": "du. trecută",
	"field-sun-narrow-relative+0": "du. aceasta",
	"field-sun-narrow-relative+1": "du. viitoare",
	"field-mon-relative+-1": "lunea trecută",
	"field-mon-relative+0": "lunea aceasta",
	"field-mon-relative+1": "lunea viitoare",
	"field-mon-short-relative+-1": "lun. trecută",
	"field-mon-short-relative+0": "lun. aceasta",
	"field-mon-short-relative+1": "lun. viitoare",
	"field-mon-narrow-relative+-1": "lu. trecută",
	"field-mon-narrow-relative+0": "lu. aceasta",
	"field-mon-narrow-relative+1": "lu. viitoare",
	"field-tue-relative+-1": "marțea trecută",
	"field-tue-relative+0": "marțea aceasta",
	"field-tue-relative+1": "marțea viitoare",
	"field-tue-short-relative+-1": "mar. trecută",
	"field-tue-short-relative+0": "mar. aceasta",
	"field-tue-short-relative+1": "mar. viitoare",
	"field-tue-narrow-relative+-1": "ma. trecută",
	"field-tue-narrow-relative+0": "ma. aceasta",
	"field-tue-narrow-relative+1": "ma. viitoare",
	"field-wed-relative+-1": "miercurea trecută",
	"field-wed-relative+0": "miercurea aceasta",
	"field-wed-relative+1": "miercurea viitoare",
	"field-wed-short-relative+-1": "mie. trecută",
	"field-wed-short-relative+0": "mie. aceasta",
	"field-wed-short-relative+1": "mie. viitoare",
	"field-wed-narrow-relative+-1": "mi. trecută",
	"field-wed-narrow-relative+0": "mi. aceasta",
	"field-wed-narrow-relative+1": "mi. viitoare",
	"field-thu-relative+-1": "joia trecută",
	"field-thu-relative+0": "joia aceasta",
	"field-thu-relative+1": "joia viitoare",
	"field-thu-short-relative+-1": "joi trecută",
	"field-thu-short-relative+0": "joi aceasta",
	"field-thu-short-relative+1": "joia viitoare",
	"field-thu-narrow-relative+-1": "jo. trecută",
	"field-thu-narrow-relative+0": "jo. aceasta",
	"field-thu-narrow-relative+1": "jo. viitoare",
	"field-fri-relative+-1": "vinerea trecută",
	"field-fri-relative+0": "vinerea aceasta",
	"field-fri-relative+1": "vinerea viitoare",
	"field-fri-short-relative+-1": "vin. trecută",
	"field-fri-short-relative+0": "vin. aceasta",
	"field-fri-short-relative+1": "vin. viitoare",
	"field-fri-narrow-relative+-1": "vi. trecută",
	"field-fri-narrow-relative+0": "vi. aceasta",
	"field-fri-narrow-relative+1": "vi. viitoare",
	"field-sat-relative+-1": "sâmbăta trecută",
	"field-sat-relative+0": "sâmbăta aceasta",
	"field-sat-relative+1": "sâmbăta viitoare",
	"field-sat-short-relative+-1": "sâm. trecută",
	"field-sat-short-relative+0": "sâm. aceasta",
	"field-sat-short-relative+1": "sâm. viitoare",
	"field-sat-narrow-relative+-1": "sâ. trecută",
	"field-sat-narrow-relative+0": "sâ. aceasta",
	"field-sat-narrow-relative+1": "sâ. viitoare",
	"field-dayperiod": "a.m/p.m.",
	"field-hour": "oră",
	"field-hour-relative+0": "ora aceasta",
	"field-hour-short": "h",
	"field-hour-narrow": "h",
	"field-minute": "minut",
	"field-minute-relative+0": "minutul acesta",
	"field-minute-short": "min.",
	"field-minute-narrow": "m",
	"field-second": "secundă",
	"field-second-relative+0": "acum",
	"field-second-short": "sec.",
	"field-second-narrow": "s",
	"field-zone": "fus orar"
}
//end v1.x content
);