define(
//begin v1.x content
{
	"months-format-abbr": [
		"ทิชรี",
		"เฮวาน",
		"กีสเลฟ",
		"เตเวต",
		"เชวัต",
		"อาดาร์ I",
		"อาดาร์",
		"นิสซาน",
		"อิยาร์",
		"สีวัน",
		"ตามูซ",
		"อัฟ",
		"เอลอุล"
	],
	"months-format-abbr-leap": "อาดาร์ II",
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12",
		"13"
	],
	"months-format-narrow-leap": "7",
	"months-format-wide": [
		"ทิชรี",
		"เฮวาน",
		"กีสเลฟ",
		"เตเวต",
		"เชวัต",
		"อาดาร์ I",
		"อาดาร์",
		"นิสซาน",
		"อิยาร์",
		"สีวัน",
		"ตามูซ",
		"อัฟ",
		"เอลอุล"
	],
	"months-format-wide-leap": "อาดาร์ II",
	"months-standAlone-abbr": [
		"ทิชรี",
		"เฮวาน",
		"กีสเลฟ",
		"เตเวต",
		"เชวัต",
		"อาดาร์ I",
		"อาดาร์",
		"นิสซาน",
		"อิยาร์",
		"สีวัน",
		"ตามูซ",
		"อัฟ",
		"เอลอุล"
	],
	"months-standAlone-abbr-leap": "อาดาร์ II",
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12",
		"13"
	],
	"months-standAlone-narrow-leap": "7",
	"months-standAlone-wide": [
		"ทิชรี",
		"เฮวาน",
		"กีสเลฟ",
		"เตเวต",
		"เชวัต",
		"อาดาร์ I",
		"อาดาร์",
		"นิสซาน",
		"อิยาร์",
		"สีวัน",
		"ตามูซ",
		"อัฟ",
		"เอลอุล"
	],
	"months-standAlone-wide-leap": "อาดาร์ II",
	"eraAbbr": [
		"ย.ศ."
	],
	"dateFormat-full": "EEEEที่ d MMMM G y",
	"dateFormat-long": "d MMMM G y",
	"dateFormat-medium": "d MMM G y",
	"dateFormat-short": "d/M/y G",
	"field-era": "สมัย",
	"field-year": "ปี",
	"field-year-relative+-1": "ปีที่แล้ว",
	"field-year-relative+0": "ปีนี้",
	"field-year-relative+1": "ปีหน้า",
	"field-year-short": "ปี",
	"field-year-short-relative+-1": "ปีที่แล้ว",
	"field-year-short-relative+0": "ปีนี้",
	"field-year-short-relative+1": "ปีหน้า",
	"field-year-narrow": "ปี",
	"field-year-narrow-relative+-1": "ปีที่แล้ว",
	"field-year-narrow-relative+0": "ปีนี้",
	"field-year-narrow-relative+1": "ปีหน้า",
	"field-quarter": "ไตรมาส",
	"field-quarter-relative+-1": "ไตรมาสที่แล้ว",
	"field-quarter-relative+0": "ไตรมาสนี้",
	"field-quarter-relative+1": "ไตรมาสหน้า",
	"field-quarter-short": "ไตรมาส",
	"field-quarter-narrow": "ไตรมาส",
	"field-month": "เดือน",
	"field-month-relative+-1": "เดือนที่แล้ว",
	"field-month-relative+0": "เดือนนี้",
	"field-month-relative+1": "เดือนหน้า",
	"field-month-short": "เดือน",
	"field-month-short-relative+-1": "เดือนที่แล้ว",
	"field-month-short-relative+0": "เดือนนี้",
	"field-month-short-relative+1": "เดือนหน้า",
	"field-month-narrow": "เดือน",
	"field-month-narrow-relative+-1": "เดือนที่แล้ว",
	"field-month-narrow-relative+0": "เดือนนี้",
	"field-month-narrow-relative+1": "เดือนหน้า",
	"field-week": "สัปดาห์",
	"field-week-relative+-1": "สัปดาห์ที่แล้ว",
	"field-week-relative+0": "สัปดาห์นี้",
	"field-week-relative+1": "สัปดาห์หน้า",
	"field-week-short": "สัปดาห์",
	"field-week-short-relative+-1": "สัปดาห์ที่แล้ว",
	"field-week-short-relative+0": "สัปดาห์นี้",
	"field-week-short-relative+1": "สัปดาห์หน้า",
	"field-week-narrow": "สัปดาห์",
	"field-week-narrow-relative+-1": "สัปดาห์ที่แล้ว",
	"field-week-narrow-relative+0": "สัปดาห์นี้",
	"field-week-narrow-relative+1": "สัปดาห์หน้า",
	"field-day": "วัน",
	"field-day-relative+-2": "เมื่อวานซืน",
	"field-day-relative+-1": "เมื่อวาน",
	"field-day-relative+0": "วันนี้",
	"field-day-relative+1": "พรุ่งนี้",
	"field-day-relative+2": "มะรืนนี้",
	"field-day-short": "วัน",
	"field-day-short-relative+-2": "เมื่อวานซืน",
	"field-day-short-relative+-1": "เมื่อวาน",
	"field-day-short-relative+0": "วันนี้",
	"field-day-short-relative+1": "พรุ่งนี้",
	"field-day-short-relative+2": "มะรืนนี้",
	"field-day-narrow": "วัน",
	"field-day-narrow-relative+-2": "เมื่อวานซืน",
	"field-day-narrow-relative+-1": "เมื่อวาน",
	"field-day-narrow-relative+0": "วันนี้",
	"field-day-narrow-relative+1": "พรุ่งนี้",
	"field-day-narrow-relative+2": "มะรืนนี้",
	"field-weekday": "วันในสัปดาห์",
	"field-sun-relative+-1": "วันอาทิตย์ที่แล้ว",
	"field-sun-relative+0": "วันอาทิตย์นี้",
	"field-sun-relative+1": "วันอาทิตย์หน้า",
	"field-sun-short-relative+-1": "วันอาทิตย์ที่แล้ว",
	"field-sun-short-relative+0": "วันอาทิตย์นี้",
	"field-sun-short-relative+1": "วันอาทิตย์หน้า",
	"field-sun-narrow-relative+-1": "วันอาทิตย์ที่แล้ว",
	"field-sun-narrow-relative+0": "วันอาทิตย์นี้",
	"field-sun-narrow-relative+1": "วันอาทิตย์หน้า",
	"field-mon-relative+-1": "จันทร์ที่แล้ว",
	"field-mon-relative+0": "จันทร์นี้",
	"field-mon-relative+1": "จันทร์หน้า",
	"field-mon-short-relative+-1": "จันทร์ที่แล้ว",
	"field-mon-short-relative+0": "จันทร์นี้",
	"field-mon-short-relative+1": "จันทร์หน้า",
	"field-mon-narrow-relative+-1": "จันทร์ที่ผ่านมา",
	"field-mon-narrow-relative+0": "จันทร์นี้",
	"field-mon-narrow-relative+1": "จันทร์หน้า",
	"field-tue-relative+-1": "อังคารที่แล้ว",
	"field-tue-relative+0": "อังคารนี้",
	"field-tue-relative+1": "อังคารหน้า",
	"field-tue-short-relative+-1": "อังคารที่แล้ว",
	"field-tue-short-relative+0": "อังคารนี้",
	"field-tue-short-relative+1": "อังคารหน้า",
	"field-tue-narrow-relative+-1": "อังคารที่ผ่านมา",
	"field-tue-narrow-relative+0": "อังคารนี้",
	"field-tue-narrow-relative+1": "อังคารหน้า",
	"field-wed-relative+-1": "พุธที่แล้ว",
	"field-wed-relative+0": "พุธนี้",
	"field-wed-relative+1": "พุธหน้า",
	"field-wed-short-relative+-1": "พุธที่แล้ว",
	"field-wed-short-relative+0": "พุธนี้",
	"field-wed-short-relative+1": "พุธหน้า",
	"field-wed-narrow-relative+-1": "พุธที่ผ่านมา",
	"field-wed-narrow-relative+0": "พุธนี้",
	"field-wed-narrow-relative+1": "พุธหน้า",
	"field-thu-relative+-1": "พฤหัสที่แล้ว",
	"field-thu-relative+0": "พฤหัสนี้",
	"field-thu-relative+1": "พฤหัสหน้า",
	"field-thu-short-relative+-1": "พฤหัสที่แล้ว",
	"field-thu-short-relative+0": "พฤหัสนี้",
	"field-thu-short-relative+1": "พฤหัสหน้า",
	"field-thu-narrow-relative+-1": "พฤหัสที่ผ่านมา",
	"field-thu-narrow-relative+0": "พฤหัสนี้",
	"field-thu-narrow-relative+1": "พฤหัสหน้า",
	"field-fri-relative+-1": "ศุกร์ที่แล้ว",
	"field-fri-relative+0": "ศุกร์นี้",
	"field-fri-relative+1": "ศุกร์หน้า",
	"field-fri-short-relative+-1": "ศุกร์ที่แล้ว",
	"field-fri-short-relative+0": "ศุกร์นี้",
	"field-fri-short-relative+1": "ศุกร์หน้า",
	"field-fri-narrow-relative+-1": "ศุกร์ที่ผ่านมา",
	"field-fri-narrow-relative+0": "ศุกร์นี้",
	"field-fri-narrow-relative+1": "ศุกร์หน้า",
	"field-sat-relative+-1": "เสาร์ที่แล้ว",
	"field-sat-relative+0": "เสาร์นี้",
	"field-sat-relative+1": "เสาร์หน้า",
	"field-sat-short-relative+-1": "เสาร์ที่แล้ว",
	"field-sat-short-relative+0": "เสาร์นี้",
	"field-sat-short-relative+1": "เสาร์หน้า",
	"field-sat-narrow-relative+-1": "เสาร์ที่ผ่านมา",
	"field-sat-narrow-relative+0": "เสาร์นี้",
	"field-sat-narrow-relative+1": "เสาร์หน้า",
	"field-dayperiod": "ช่วงวัน",
	"field-hour": "ชั่วโมง",
	"field-hour-relative+0": "ชั่วโมงนี้",
	"field-hour-short": "ชม.",
	"field-hour-narrow": "ชม.",
	"field-minute": "นาที",
	"field-minute-relative+0": "นาทีนี้",
	"field-minute-short": "น.",
	"field-minute-narrow": "น.",
	"field-second": "วินาที",
	"field-second-relative+0": "ขณะนี้",
	"field-second-short": "วิ",
	"field-second-narrow": "วิ",
	"field-zone": "เขตเวลา",
	"eraNames": [
		"ย.ศ."
	],
	"eraNarrow": [
		"ย.ศ."
	],
	"days-format-abbr": [
		"อา.",
		"จ.",
		"อ.",
		"พ.",
		"พฤ.",
		"ศ.",
		"ส."
	],
	"days-format-narrow": [
		"อา",
		"จ",
		"อ",
		"พ",
		"พฤ",
		"ศ",
		"ส"
	],
	"days-format-short": [
		"อา.",
		"จ.",
		"อ.",
		"พ.",
		"พฤ.",
		"ศ.",
		"ส."
	],
	"days-format-wide": [
		"วันอาทิตย์",
		"วันจันทร์",
		"วันอังคาร",
		"วันพุธ",
		"วันพฤหัสบดี",
		"วันศุกร์",
		"วันเสาร์"
	],
	"days-standAlone-abbr": [
		"อา.",
		"จ.",
		"อ.",
		"พ.",
		"พฤ.",
		"ศ.",
		"ส."
	],
	"days-standAlone-narrow": [
		"อา",
		"จ",
		"อ",
		"พ",
		"พฤ",
		"ศ",
		"ส"
	],
	"days-standAlone-short": [
		"อา.",
		"จ.",
		"อ.",
		"พ.",
		"พฤ.",
		"ศ.",
		"ส."
	],
	"days-standAlone-wide": [
		"วันอาทิตย์",
		"วันจันทร์",
		"วันอังคาร",
		"วันพุธ",
		"วันพฤหัสบดี",
		"วันศุกร์",
		"วันเสาร์"
	],
	"quarters-format-abbr": [
		"ไตรมาส 1",
		"ไตรมาส 2",
		"ไตรมาส 3",
		"ไตรมาส 4"
	],
	"quarters-format-wide": [
		"ไตรมาส 1",
		"ไตรมาส 2",
		"ไตรมาส 3",
		"ไตรมาส 4"
	],
	"quarters-standAlone-abbr": [
		"ไตรมาส 1",
		"ไตรมาส 2",
		"ไตรมาส 3",
		"ไตรมาส 4"
	],
	"quarters-standAlone-wide": [
		"ไตรมาส 1",
		"ไตรมาส 2",
		"ไตรมาส 3",
		"ไตรมาส 4"
	],
	"dayPeriods-format-abbr-am": "ก่อนเที่ยง",
	"dayPeriods-format-abbr-pm": "หลังเที่ยง",
	"dayPeriods-format-narrow-am": "a",
	"dayPeriods-format-narrow-pm": "p",
	"dayPeriods-format-wide-am": "ก่อนเที่ยง",
	"dayPeriods-format-wide-pm": "หลังเที่ยง",
	"dayPeriods-standAlone-abbr-am": "ก่อนเที่ยง",
	"dayPeriods-standAlone-abbr-pm": "หลังเที่ยง",
	"dayPeriods-standAlone-narrow-am": "ก่อนเที่ยง",
	"dayPeriods-standAlone-narrow-pm": "หลังเที่ยง",
	"dayPeriods-standAlone-wide-am": "ก่อนเที่ยง",
	"dayPeriods-standAlone-wide-pm": "หลังเที่ยง",
	"dateFormatItem-Ed": "E d",
	"dateFormatItem-GyMMM": "MMM G y",
	"dateFormatItem-GyMMMd": "d MMM G y",
	"dateFormatItem-GyMMMEd": "E d MMM G y",
	"dateFormatItem-Md": "d/M",
	"dateFormatItem-MEd": "E d/M",
	"dateFormatItem-MMMd": "d MMM",
	"dateFormatItem-MMMEd": "E d MMM",
	"dateFormatItem-MMMMd": "d MMMM",
	"dateFormatItem-yyyyM": "M/y G",
	"dateFormatItem-yyyyMd": "d/M/y GGGGG",
	"dateFormatItem-yyyyMEd": "E d/M/y GGGGG",
	"dateFormatItem-yyyyMMM": "MMM G y",
	"dateFormatItem-yyyyMMMd": "d MMM G y",
	"dateFormatItem-yyyyMMMEd": "E d MMM G y",
	"dateFormatItem-yyyyMMMM": "MMMM G y",
	"dateFormatItem-yyyyQQQ": "QQQ G y",
	"dateFormatItem-yyyyQQQQ": "QQQQ G y",
	"timeFormat-full": "H นาฬิกา mm นาที ss วินาที zzzz",
	"timeFormat-long": "H นาฬิกา mm นาที ss วินาที z"
}
//end v1.x content
);