define(
//begin v1.x content
{
	"months-format-abbr": [
		"led",
		"úno",
		"bře",
		"dub",
		"kvě",
		"čvn",
		"čvc",
		"srp",
		"zář",
		"říj",
		"lis",
		"pro"
	],
	"months-format-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-format-wide": [
		"ledna",
		"února",
		"března",
		"dubna",
		"května",
		"června",
		"července",
		"srpna",
		"září",
		"října",
		"listopadu",
		"prosince"
	],
	"months-standAlone-abbr": [
		"led",
		"úno",
		"bře",
		"dub",
		"kvě",
		"čvn",
		"čvc",
		"srp",
		"zář",
		"říj",
		"lis",
		"pro"
	],
	"months-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
		"10",
		"11",
		"12"
	],
	"months-standAlone-wide": [
		"leden",
		"únor",
		"březen",
		"duben",
		"květen",
		"červen",
		"červenec",
		"srpen",
		"září",
		"říjen",
		"listopad",
		"prosinec"
	],
	"days-format-abbr": [
		"ne",
		"po",
		"út",
		"st",
		"čt",
		"pá",
		"so"
	],
	"days-format-narrow": [
		"N",
		"P",
		"Ú",
		"S",
		"Č",
		"P",
		"S"
	],
	"days-format-short": [
		"ne",
		"po",
		"út",
		"st",
		"čt",
		"pá",
		"so"
	],
	"days-format-wide": [
		"neděle",
		"pondělí",
		"úterý",
		"středa",
		"čtvrtek",
		"pátek",
		"sobota"
	],
	"days-standAlone-abbr": [
		"ne",
		"po",
		"út",
		"st",
		"čt",
		"pá",
		"so"
	],
	"days-standAlone-narrow": [
		"N",
		"P",
		"Ú",
		"S",
		"Č",
		"P",
		"S"
	],
	"days-standAlone-short": [
		"ne",
		"po",
		"út",
		"st",
		"čt",
		"pá",
		"so"
	],
	"days-standAlone-wide": [
		"neděle",
		"pondělí",
		"úterý",
		"středa",
		"čtvrtek",
		"pátek",
		"sobota"
	],
	"quarters-format-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-format-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-format-wide": [
		"1. čtvrtletí",
		"2. čtvrtletí",
		"3. čtvrtletí",
		"4. čtvrtletí"
	],
	"quarters-standAlone-abbr": [
		"Q1",
		"Q2",
		"Q3",
		"Q4"
	],
	"quarters-standAlone-narrow": [
		"1",
		"2",
		"3",
		"4"
	],
	"quarters-standAlone-wide": [
		"1. čtvrtletí",
		"2. čtvrtletí",
		"3. čtvrtletí",
		"4. čtvrtletí"
	],
	"dayPeriods-format-abbr-midnight": "půln.",
	"dayPeriods-format-abbr-am": "dop.",
	"dayPeriods-format-abbr-noon": "pol.",
	"dayPeriods-format-abbr-pm": "odp.",
	"dayPeriods-format-abbr-morning1": "r.",
	"dayPeriods-format-abbr-morning2": "dop.",
	"dayPeriods-format-abbr-afternoon1": "odp.",
	"dayPeriods-format-abbr-evening1": "več.",
	"dayPeriods-format-abbr-night1": "v n.",
	"dayPeriods-format-narrow-midnight": "půl.",
	"dayPeriods-format-narrow-am": "dop.",
	"dayPeriods-format-narrow-noon": "pol.",
	"dayPeriods-format-narrow-pm": "odp.",
	"dayPeriods-format-narrow-morning1": "r.",
	"dayPeriods-format-narrow-morning2": "d.",
	"dayPeriods-format-narrow-afternoon1": "o.",
	"dayPeriods-format-narrow-evening1": "v.",
	"dayPeriods-format-narrow-night1": "n.",
	"dayPeriods-format-wide-midnight": "půlnoc",
	"dayPeriods-format-wide-am": "dop.",
	"dayPeriods-format-wide-noon": "poledne",
	"dayPeriods-format-wide-pm": "odp.",
	"dayPeriods-format-wide-morning1": "ráno",
	"dayPeriods-format-wide-morning2": "dopoledne",
	"dayPeriods-format-wide-afternoon1": "odpoledne",
	"dayPeriods-format-wide-evening1": "večer",
	"dayPeriods-format-wide-night1": "v noci",
	"dayPeriods-standAlone-abbr-midnight": "půlnoc",
	"dayPeriods-standAlone-abbr-am": "dop.",
	"dayPeriods-standAlone-abbr-noon": "poledne",
	"dayPeriods-standAlone-abbr-pm": "odp.",
	"dayPeriods-standAlone-abbr-morning1": "ráno",
	"dayPeriods-standAlone-abbr-morning2": "dopoledne",
	"dayPeriods-standAlone-abbr-afternoon1": "odpoledne",
	"dayPeriods-standAlone-abbr-evening1": "večer",
	"dayPeriods-standAlone-abbr-night1": "noc",
	"dayPeriods-standAlone-narrow-midnight": "půl.",
	"dayPeriods-standAlone-narrow-am": "dop.",
	"dayPeriods-standAlone-narrow-noon": "pol.",
	"dayPeriods-standAlone-narrow-pm": "odp.",
	"dayPeriods-standAlone-narrow-morning1": "ráno",
	"dayPeriods-standAlone-narrow-morning2": "dop.",
	"dayPeriods-standAlone-narrow-afternoon1": "odp.",
	"dayPeriods-standAlone-narrow-evening1": "več.",
	"dayPeriods-standAlone-narrow-night1": "noc",
	"dayPeriods-standAlone-wide-midnight": "půlnoc",
	"dayPeriods-standAlone-wide-am": "dop.",
	"dayPeriods-standAlone-wide-noon": "poledne",
	"dayPeriods-standAlone-wide-pm": "odp.",
	"dayPeriods-standAlone-wide-morning1": "ráno",
	"dayPeriods-standAlone-wide-morning2": "dopoledne",
	"dayPeriods-standAlone-wide-afternoon1": "odpoledne",
	"dayPeriods-standAlone-wide-evening1": "večer",
	"dayPeriods-standAlone-wide-night1": "noc",
	"eraNames": [
		"př. n. l.",
		"n. l."
	],
	"eraAbbr": [
		"př. n. l.",
		"n. l."
	],
	"eraNarrow": [
		"př.n.l.",
		"n.l."
	],
	"dateFormat-full": "EEEE d. MMMM y",
	"dateFormat-long": "d. MMMM y",
	"dateFormat-medium": "d. M. y",
	"dateFormat-short": "dd.MM.yy",
	"timeFormat-full": "H:mm:ss zzzz",
	"timeFormat-long": "H:mm:ss z",
	"timeFormat-medium": "H:mm:ss",
	"timeFormat-short": "H:mm",
	"dateTimeFormat-full": "{1} {0}",
	"dateTimeFormat-long": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "d.",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E d.",
	"dateFormatItem-Ehm": "E h:mm a",
	"dateFormatItem-EHm": "E H:mm",
	"dateFormatItem-Ehms": "E h:mm:ss a",
	"dateFormatItem-EHms": "E H:mm:ss",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "LLLL y G",
	"dateFormatItem-GyMMMd": "d. M. y G",
	"dateFormatItem-GyMMMEd": "E d. M. y G",
	"dateFormatItem-GyMMMMd": "d. MMMM y G",
	"dateFormatItem-GyMMMMEd": "E d. MMMM y G",
	"dateFormatItem-h": "h a",
	"dateFormatItem-H": "H",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Hm": "H:mm",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-Hms": "H:mm:ss",
	"dateFormatItem-hmsv": "h:mm:ss a v",
	"dateFormatItem-Hmsv": "H:mm:ss v",
	"dateFormatItem-hmv": "h:mm a v",
	"dateFormatItem-Hmv": "H:mm v",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "d. M.",
	"dateFormatItem-MEd": "E d. M.",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d. M.",
	"dateFormatItem-MMMEd": "E d. M.",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-MMMMEd": "E d. MMMM",
	"dateFormatItem-MMMMW": "W. 'týden' MMMM",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y",
	"dateFormatItem-yM": "M/y",
	"dateFormatItem-yMd": "d. M. y",
	"dateFormatItem-yMEd": "E d. M. y",
	"dateFormatItem-yMMM": "LLLL y",
	"dateFormatItem-yMMMd": "d. M. y",
	"dateFormatItem-yMMMEd": "E d. M. y",
	"dateFormatItem-yMMMM": "LLLL y",
	"dateFormatItem-yMMMMd": "d. MMMM y",
	"dateFormatItem-yMMMMEd": "E d. MMMM y",
	"dateFormatItem-yQQQ": "QQQ y",
	"dateFormatItem-yQQQQ": "QQQQ y",
	"dateFormatItem-yw": "w. 'týden' 'roku' y",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-era": "letopočet",
	"field-year": "rok",
	"field-year-relative+-1": "minulý rok",
	"field-year-relative+0": "tento rok",
	"field-year-relative+1": "příští rok",
	"field-year-short": "r.",
	"field-year-short-relative+-1": "minulý rok",
	"field-year-short-relative+0": "tento rok",
	"field-year-short-relative+1": "příští rok",
	"field-year-narrow": "r.",
	"field-year-narrow-relative+-1": "minulý rok",
	"field-year-narrow-relative+0": "tento rok",
	"field-year-narrow-relative+1": "příští rok",
	"field-quarter": "čtvrtletí",
	"field-quarter-relative+-1": "minulé čtvrtletí",
	"field-quarter-relative+0": "toto čtvrtletí",
	"field-quarter-relative+1": "příští čtvrtletí",
	"field-quarter-short": "Q",
	"field-quarter-narrow": "Q",
	"field-month": "měsíc",
	"field-month-relative+-1": "minulý měsíc",
	"field-month-relative+0": "tento měsíc",
	"field-month-relative+1": "příští měsíc",
	"field-month-short": "měs.",
	"field-month-narrow": "měs.",
	"field-week": "týden",
	"field-week-relative+-1": "minulý týden",
	"field-week-relative+0": "tento týden",
	"field-week-relative+1": "příští týden",
	"field-week-short": "týd.",
	"field-week-short-relative+-1": "minulý týd.",
	"field-week-short-relative+0": "tento týd.",
	"field-week-short-relative+1": "příští týd.",
	"field-week-narrow": "týd.",
	"field-week-narrow-relative+-1": "minulý týd.",
	"field-week-narrow-relative+0": "tento týd.",
	"field-week-narrow-relative+1": "příští týd.",
	"field-day": "den",
	"field-day-relative+-2": "předevčírem",
	"field-day-relative+-1": "včera",
	"field-day-relative+0": "dnes",
	"field-day-relative+1": "zítra",
	"field-day-relative+2": "pozítří",
	"field-day-short": "den",
	"field-day-short-relative+-2": "předevčírem",
	"field-day-short-relative+-1": "včera",
	"field-day-short-relative+0": "dnes",
	"field-day-short-relative+1": "zítra",
	"field-day-short-relative+2": "pozítří",
	"field-day-narrow": "den",
	"field-day-narrow-relative+-2": "předevčírem",
	"field-day-narrow-relative+-1": "včera",
	"field-day-narrow-relative+0": "dnes",
	"field-day-narrow-relative+1": "zítra",
	"field-day-narrow-relative+2": "pozítří",
	"field-weekday": "den v týdnu",
	"field-sun-relative+-1": "minulou neděli",
	"field-sun-relative+0": "tuto neděli",
	"field-sun-relative+1": "příští neděli",
	"field-sun-short-relative+-1": "minulou neděli",
	"field-sun-short-relative+0": "tuto neděli",
	"field-sun-short-relative+1": "příští neděli",
	"field-sun-narrow-relative+-1": "minulou neděli",
	"field-sun-narrow-relative+0": "tuto neděli",
	"field-sun-narrow-relative+1": "příští neděli",
	"field-mon-relative+-1": "minulé pondělí",
	"field-mon-relative+0": "toto pondělí",
	"field-mon-relative+1": "příští pondělí",
	"field-mon-short-relative+-1": "minulé pondělí",
	"field-mon-short-relative+0": "toto pondělí",
	"field-mon-short-relative+1": "příští pondělí",
	"field-mon-narrow-relative+-1": "minulé pondělí",
	"field-mon-narrow-relative+0": "toto pondělí",
	"field-mon-narrow-relative+1": "příští pondělí",
	"field-tue-relative+-1": "minulé úterý",
	"field-tue-relative+0": "toto úterý",
	"field-tue-relative+1": "příští úterý",
	"field-tue-short-relative+-1": "minulé úterý",
	"field-tue-short-relative+0": "toto úterý",
	"field-tue-short-relative+1": "příští úterý",
	"field-tue-narrow-relative+-1": "minulé úterý",
	"field-tue-narrow-relative+0": "toto úterý",
	"field-tue-narrow-relative+1": "příští úterý",
	"field-wed-relative+-1": "minulou středu",
	"field-wed-relative+0": "tuto středu",
	"field-wed-relative+1": "příští středu",
	"field-wed-short-relative+-1": "minulou středu",
	"field-wed-short-relative+0": "tuto středu",
	"field-wed-short-relative+1": "příští středu",
	"field-wed-narrow-relative+-1": "minulou středu",
	"field-wed-narrow-relative+0": "tuto středu",
	"field-wed-narrow-relative+1": "příští středu",
	"field-thu-relative+-1": "minulý čtvrtek",
	"field-thu-relative+0": "tento čtvrtek",
	"field-thu-relative+1": "příští čtvrtek",
	"field-thu-short-relative+-1": "minulý čtvrtek",
	"field-thu-short-relative+0": "tento čtvrtek",
	"field-thu-short-relative+1": "příští čtvrtek",
	"field-thu-narrow-relative+-1": "minulý čtvrtek",
	"field-thu-narrow-relative+0": "tento čtvrtek",
	"field-thu-narrow-relative+1": "příští čtvrtek",
	"field-fri-relative+-1": "minulý pátek",
	"field-fri-relative+0": "tento pátek",
	"field-fri-relative+1": "příští pátek",
	"field-fri-short-relative+-1": "minulý pátek",
	"field-fri-short-relative+0": "tento pátek",
	"field-fri-short-relative+1": "příští pátek",
	"field-fri-narrow-relative+-1": "minulý pátek",
	"field-fri-narrow-relative+0": "tento pátek",
	"field-fri-narrow-relative+1": "příští pátek",
	"field-sat-relative+-1": "minulou sobotu",
	"field-sat-relative+0": "tuto sobotu",
	"field-sat-relative+1": "příští sobotu",
	"field-sat-short-relative+-1": "minulou sobotu",
	"field-sat-short-relative+0": "tuto sobotu",
	"field-sat-short-relative+1": "příští sobotu",
	"field-sat-narrow-relative+-1": "minulou sobotu",
	"field-sat-narrow-relative+0": "tuto sobotu",
	"field-sat-narrow-relative+1": "příští sobotu",
	"field-dayperiod": "část dne",
	"field-hour": "hodina",
	"field-hour-relative+0": "tuto hodinu",
	"field-hour-short": "h",
	"field-hour-narrow": "h",
	"field-minute": "minuta",
	"field-minute-relative+0": "tuto minutu",
	"field-minute-short": "min",
	"field-minute-narrow": "min",
	"field-second": "sekunda",
	"field-second-relative+0": "nyní",
	"field-second-short": "s",
	"field-second-short-relative+0": "nyní",
	"field-second-narrow": "s",
	"field-second-narrow-relative+0": "nyní",
	"field-zone": "časové pásmo"
}
//end v1.x content
);