define(
//begin v1.x content
{
	"eraAbbr": [
		"BE"
	],
	"dateFormat-full": "cccc d. MMMM y G",
	"dateFormat-long": "d. MMMM y G",
	"dateFormat-medium": "d.M.y G",
	"dateFormat-short": "d.M.y GGGGG",
	"dateFormatItem-d": "d",
	"dateFormatItem-Ed": "E d.",
	"dateFormatItem-Gy": "y G",
	"dateFormatItem-GyMMM": "LLL y G",
	"dateFormatItem-GyMMMd": "d. MMM y G",
	"dateFormatItem-GyMMMEd": "E d. MMM y G",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "d.M.",
	"dateFormatItem-MEd": "E d.M.",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MMMEd": "ccc d. MMM",
	"dateFormatItem-y": "y G",
	"dateFormatItem-yyyy": "y G",
	"dateFormatItem-yyyyM": "L.y G",
	"dateFormatItem-yyyyMd": "d.M.y G",
	"dateFormatItem-yyyyMEd": "E d.M.y G",
	"dateFormatItem-yyyyMMM": "LLL y G",
	"dateFormatItem-yyyyMMMd": "d. MMM y G",
	"dateFormatItem-yyyyMMMEd": "E d. MMM y G",
	"dateFormatItem-yyyyMMMM": "LLLL y G",
	"dateFormatItem-yyyyQQQ": "QQQ y G",
	"dateFormatItem-yyyyQQQQ": "QQQQ y G",
	"field-era": "aikakausi",
	"field-year": "vuosi",
	"field-year-relative+-1": "viime vuonna",
	"field-year-relative+0": "tänä vuonna",
	"field-year-relative+1": "ensi vuonna",
	"field-year-short": "v",
	"field-year-short-relative+-1": "viime v",
	"field-year-short-relative+0": "tänä v",
	"field-year-short-relative+1": "ensi v",
	"field-year-narrow": "v",
	"field-year-narrow-relative+-1": "viime v",
	"field-year-narrow-relative+0": "tänä v",
	"field-year-narrow-relative+1": "ensi v",
	"field-quarter": "neljännesvuosi",
	"field-quarter-relative+-1": "viime neljännesvuonna",
	"field-quarter-relative+0": "tänä neljännesvuonna",
	"field-quarter-relative+1": "ensi neljännesvuonna",
	"field-quarter-short": "neljännes",
	"field-quarter-short-relative+-1": "viime neljänneksenä",
	"field-quarter-short-relative+0": "tänä neljänneksenä",
	"field-quarter-short-relative+1": "ensi neljänneksenä",
	"field-quarter-narrow": "nelj.",
	"field-quarter-narrow-relative+-1": "viime nelj.",
	"field-quarter-narrow-relative+0": "tänä nelj.",
	"field-quarter-narrow-relative+1": "ensi nelj.",
	"field-month": "kuukausi",
	"field-month-relative+-1": "viime kuussa",
	"field-month-relative+0": "tässä kuussa",
	"field-month-relative+1": "ensi kuussa",
	"field-month-short": "kk",
	"field-month-short-relative+-1": "viime kk",
	"field-month-short-relative+0": "tässä kk",
	"field-month-short-relative+1": "ensi kk",
	"field-month-narrow": "kk",
	"field-month-narrow-relative+-1": "viime kk",
	"field-month-narrow-relative+0": "tässä kk",
	"field-month-narrow-relative+1": "ensi kk",
	"field-week": "viikko",
	"field-week-relative+-1": "viime viikolla",
	"field-week-relative+0": "tällä viikolla",
	"field-week-relative+1": "ensi viikolla",
	"field-week-short": "vk",
	"field-week-short-relative+-1": "viime vk",
	"field-week-short-relative+0": "tällä vk",
	"field-week-short-relative+1": "ensi vk",
	"field-week-narrow": "vk",
	"field-week-narrow-relative+-1": "viime vk",
	"field-week-narrow-relative+0": "tällä vk",
	"field-week-narrow-relative+1": "ensi vk",
	"field-day": "päivä",
	"field-day-relative+-2": "toissa päivänä",
	"field-day-relative+-1": "eilen",
	"field-day-relative+0": "tänään",
	"field-day-relative+1": "huomenna",
	"field-day-relative+2": "ylihuomenna",
	"field-day-short": "pv",
	"field-day-short-relative+-2": "toissap.",
	"field-day-short-relative+-1": "eilen",
	"field-day-short-relative+0": "tänään",
	"field-day-short-relative+1": "huom.",
	"field-day-short-relative+2": "ylihuom.",
	"field-day-narrow": "pv",
	"field-day-narrow-relative+-2": "toissap.",
	"field-day-narrow-relative+-1": "eilen",
	"field-day-narrow-relative+0": "tänään",
	"field-day-narrow-relative+1": "huom.",
	"field-day-narrow-relative+2": "ylihuom.",
	"field-weekday": "viikonpäivä",
	"field-sun-relative+-1": "viime sunnuntaina",
	"field-sun-relative+0": "tänä sunnuntaina",
	"field-sun-relative+1": "ensi sunnuntaina",
	"field-sun-short-relative+-1": "viime su",
	"field-sun-short-relative+0": "tänä su",
	"field-sun-short-relative+1": "ensi su",
	"field-sun-narrow-relative+-1": "viime su",
	"field-sun-narrow-relative+0": "tänä su",
	"field-sun-narrow-relative+1": "ensi su",
	"field-mon-relative+-1": "viime maanantaina",
	"field-mon-relative+0": "tänä maanantaina",
	"field-mon-relative+1": "ensi maanantaina",
	"field-mon-short-relative+-1": "viime ma",
	"field-mon-short-relative+0": "tänä ma",
	"field-mon-short-relative+1": "ensi ma",
	"field-mon-narrow-relative+-1": "viime ma",
	"field-mon-narrow-relative+0": "tänä ma",
	"field-mon-narrow-relative+1": "ensi ma",
	"field-tue-relative+-1": "viime tiistaina",
	"field-tue-relative+0": "tänä tiistaina",
	"field-tue-relative+1": "ensi tiistaina",
	"field-tue-short-relative+-1": "viime ti",
	"field-tue-short-relative+0": "tänä ti",
	"field-tue-short-relative+1": "ensi ti",
	"field-tue-narrow-relative+-1": "viime ti",
	"field-tue-narrow-relative+0": "tänä ti",
	"field-tue-narrow-relative+1": "ensi ti",
	"field-wed-relative+-1": "viime keskiviikkona",
	"field-wed-relative+0": "tänä keskiviikkona",
	"field-wed-relative+1": "ensi keskiviikkona",
	"field-wed-short-relative+-1": "viime ke",
	"field-wed-short-relative+0": "tänä ke",
	"field-wed-short-relative+1": "ensi ke",
	"field-wed-narrow-relative+-1": "viime ke",
	"field-wed-narrow-relative+0": "tänä ke",
	"field-wed-narrow-relative+1": "ensi ke",
	"field-thu-relative+-1": "viime torstaina",
	"field-thu-relative+0": "tänä torstaina",
	"field-thu-relative+1": "ensi torstaina",
	"field-thu-short-relative+-1": "viime to",
	"field-thu-short-relative+0": "tänä to",
	"field-thu-short-relative+1": "ensi to",
	"field-thu-narrow-relative+-1": "viime to",
	"field-thu-narrow-relative+0": "tänä to",
	"field-thu-narrow-relative+1": "ensi to",
	"field-fri-relative+-1": "viime perjantaina",
	"field-fri-relative+0": "tänä perjantaina",
	"field-fri-relative+1": "ensi perjantaina",
	"field-fri-short-relative+-1": "viime pe",
	"field-fri-short-relative+0": "tänä pe",
	"field-fri-short-relative+1": "ensi pe",
	"field-fri-narrow-relative+-1": "viime pe",
	"field-fri-narrow-relative+0": "tänä pe",
	"field-fri-narrow-relative+1": "ensi pe",
	"field-sat-relative+-1": "viime lauantaina",
	"field-sat-relative+0": "tänä lauantaina",
	"field-sat-relative+1": "ensi lauantaina",
	"field-sat-short-relative+-1": "viime la",
	"field-sat-short-relative+0": "tänä la",
	"field-sat-short-relative+1": "ensi la",
	"field-sat-narrow-relative+-1": "viime la",
	"field-sat-narrow-relative+0": "tänä la",
	"field-sat-narrow-relative+1": "ensi la",
	"field-dayperiod": "vuorokaudenaika",
	"field-hour": "tunti",
	"field-hour-relative+0": "tämän tunnin aikana",
	"field-hour-short": "t",
	"field-hour-short-relative+0": "tunnin sisällä",
	"field-hour-narrow": "t",
	"field-hour-narrow-relative+0": "tunnin sisällä",
	"field-minute": "minuutti",
	"field-minute-relative+0": "tämän minuutin aikana",
	"field-minute-short": "min",
	"field-minute-short-relative+0": "minuutin sisällä",
	"field-minute-narrow": "min",
	"field-minute-narrow-relative+0": "minuutin sisällä",
	"field-second": "sekunti",
	"field-second-relative+0": "nyt",
	"field-second-short": "s",
	"field-second-short-relative+0": "nyt",
	"field-second-narrow": "s",
	"field-second-narrow-relative+0": "nyt",
	"field-zone": "aikavyöhyke",
	"days-format-abbr": [
		"su",
		"ma",
		"ti",
		"ke",
		"to",
		"pe",
		"la"
	],
	"days-format-narrow": [
		"S",
		"M",
		"T",
		"K",
		"T",
		"P",
		"L"
	],
	"days-format-short": [
		"su",
		"ma",
		"ti",
		"ke",
		"to",
		"pe",
		"la"
	],
	"days-format-wide": [
		"sunnuntaina",
		"maanantaina",
		"tiistaina",
		"keskiviikkona",
		"torstaina",
		"perjantaina",
		"lauantaina"
	],
	"days-standAlone-abbr": [
		"su",
		"ma",
		"ti",
		"ke",
		"to",
		"pe",
		"la"
	],
	"days-standAlone-narrow": [
		"S",
		"M",
		"T",
		"K",
		"T",
		"P",
		"L"
	],
	"days-standAlone-short": [
		"su",
		"ma",
		"ti",
		"ke",
		"to",
		"pe",
		"la"
	],
	"days-standAlone-wide": [
		"sunnuntai",
		"maanantai",
		"tiistai",
		"keskiviikko",
		"torstai",
		"perjantai",
		"lauantai"
	],
	"quarters-format-abbr": [
		"1. nelj.",
		"2. nelj.",
		"3. nelj.",
		"4. nelj."
	],
	"quarters-format-wide": [
		"1. neljännes",
		"2. neljännes",
		"3. neljännes",
		"4. neljännes"
	],
	"quarters-standAlone-abbr": [
		"1. nelj.",
		"2. nelj.",
		"3. nelj.",
		"4. nelj."
	],
	"quarters-standAlone-wide": [
		"1. neljännes",
		"2. neljännes",
		"3. neljännes",
		"4. neljännes"
	],
	"dayPeriods-format-abbr-am": "ap.",
	"dayPeriods-format-abbr-pm": "ip.",
	"dayPeriods-format-narrow-am": "ap.",
	"dayPeriods-format-narrow-pm": "ip.",
	"dayPeriods-format-wide-am": "ap.",
	"dayPeriods-format-wide-pm": "ip.",
	"dayPeriods-standAlone-abbr-am": "ap.",
	"dayPeriods-standAlone-abbr-pm": "ip.",
	"dayPeriods-standAlone-narrow-am": "ap.",
	"dayPeriods-standAlone-narrow-pm": "ip.",
	"dayPeriods-standAlone-wide-am": "ap.",
	"dayPeriods-standAlone-wide-pm": "ip.",
	"dateFormatItem-H": "H",
	"dateFormatItem-hm": "h.mm a",
	"dateFormatItem-Hm": "H.mm",
	"dateFormatItem-hms": "h.mm.ss a",
	"dateFormatItem-Hms": "H.mm.ss",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-ms": "mm.ss",
	"timeFormat-full": "H.mm.ss zzzz",
	"timeFormat-long": "H.mm.ss z",
	"timeFormat-medium": "H.mm.ss",
	"timeFormat-short": "H.mm",
	"dateTimeFormat-full": "{1} 'klo' {0}",
	"dateTimeFormat-long": "{1} 'klo' {0}",
	"dateTimeFormat-medium": "{1} 'klo' {0}",
	"months-format-abbr": [
		"tammik.",
		"helmik.",
		"maalisk.",
		"huhtik.",
		"toukok.",
		"kesäk.",
		"heinäk.",
		"elok.",
		"syysk.",
		"lokak.",
		"marrask.",
		"jouluk."
	],
	"months-format-narrow": [
		"T",
		"H",
		"M",
		"H",
		"T",
		"K",
		"H",
		"E",
		"S",
		"L",
		"M",
		"J"
	],
	"months-format-wide": [
		"tammikuuta",
		"helmikuuta",
		"maaliskuuta",
		"huhtikuuta",
		"toukokuuta",
		"kesäkuuta",
		"heinäkuuta",
		"elokuuta",
		"syyskuuta",
		"lokakuuta",
		"marraskuuta",
		"joulukuuta"
	],
	"months-standAlone-abbr": [
		"tammi",
		"helmi",
		"maalis",
		"huhti",
		"touko",
		"kesä",
		"heinä",
		"elo",
		"syys",
		"loka",
		"marras",
		"joulu"
	],
	"months-standAlone-narrow": [
		"T",
		"H",
		"M",
		"H",
		"T",
		"K",
		"H",
		"E",
		"S",
		"L",
		"M",
		"J"
	],
	"months-standAlone-wide": [
		"tammikuu",
		"helmikuu",
		"maaliskuu",
		"huhtikuu",
		"toukokuu",
		"kesäkuu",
		"heinäkuu",
		"elokuu",
		"syyskuu",
		"lokakuu",
		"marraskuu",
		"joulukuu"
	]
}
//end v1.x content
);