define(
//begin v1.x content
{
	"months-format-abbr": [
		"janv.",
		"febr.",
		"marts",
		"apr.",
		"maijs",
		"jūn.",
		"jūl.",
		"aug.",
		"sept.",
		"okt.",
		"nov.",
		"dec."
	],
	"months-format-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"months-format-wide": [
		"janvāris",
		"februāris",
		"marts",
		"aprīlis",
		"maijs",
		"jūnijs",
		"jūlijs",
		"augusts",
		"septembris",
		"oktobris",
		"novembris",
		"decembris"
	],
	"months-standAlone-abbr": [
		"janv.",
		"febr.",
		"marts",
		"apr.",
		"maijs",
		"jūn.",
		"jūl.",
		"aug.",
		"sept.",
		"okt.",
		"nov.",
		"dec."
	],
	"months-standAlone-narrow": [
		"J",
		"F",
		"M",
		"A",
		"M",
		"J",
		"J",
		"A",
		"S",
		"O",
		"N",
		"D"
	],
	"months-standAlone-wide": [
		"janvāris",
		"februāris",
		"marts",
		"aprīlis",
		"maijs",
		"jūnijs",
		"jūlijs",
		"augusts",
		"septembris",
		"oktobris",
		"novembris",
		"decembris"
	],
	"days-format-abbr": [
		"svētd.",
		"pirmd.",
		"otrd.",
		"trešd.",
		"ceturtd.",
		"piektd.",
		"sestd."
	],
	"days-format-narrow": [
		"S",
		"P",
		"O",
		"T",
		"C",
		"P",
		"S"
	],
	"days-format-short": [
		"Sv",
		"Pr",
		"Ot",
		"Tr",
		"Ce",
		"Pk",
		"Se"
	],
	"days-format-wide": [
		"svētdiena",
		"pirmdiena",
		"otrdiena",
		"trešdiena",
		"ceturtdiena",
		"piektdiena",
		"sestdiena"
	],
	"days-standAlone-abbr": [
		"Svētd.",
		"Pirmd.",
		"Otrd.",
		"Trešd.",
		"Ceturtd.",
		"Piektd.",
		"Sestd."
	],
	"days-standAlone-narrow": [
		"S",
		"P",
		"O",
		"T",
		"C",
		"P",
		"S"
	],
	"days-standAlone-short": [
		"Sv",
		"Pr",
		"Ot",
		"Tr",
		"Ce",
		"Pk",
		"Se"
	],
	"days-standAlone-wide": [
		"Svētdiena",
		"Pirmdiena",
		"Otrdiena",
		"Trešdiena",
		"Ceturtdiena",
		"Piektdiena",
		"Sestdiena"
	],
	"quarters-format-abbr": [
		"1. cet.",
		"2. cet.",
		"3. cet.",
		"4. cet."
	],
	"quarters-format-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"quarters-format-wide": [
		"1. ceturksnis",
		"2. ceturksnis",
		"3. ceturksnis",
		"4. ceturksnis"
	],
	"quarters-standAlone-abbr": [
		"1. cet.",
		"2. cet.",
		"3. cet.",
		"4. cet."
	],
	"quarters-standAlone-narrow": [
		"1.",
		"2.",
		"3.",
		"4."
	],
	"quarters-standAlone-wide": [
		"1. ceturksnis",
		"2. ceturksnis",
		"3. ceturksnis",
		"4. ceturksnis"
	],
	"dayPeriods-format-abbr-midnight": "pusnaktī",
	"dayPeriods-format-abbr-am": "priekšp.",
	"dayPeriods-format-abbr-noon": "pusd.",
	"dayPeriods-format-abbr-pm": "pēcp.",
	"dayPeriods-format-abbr-morning1": "no rīta",
	"dayPeriods-format-abbr-afternoon1": "pēcpusd.",
	"dayPeriods-format-abbr-evening1": "vakarā",
	"dayPeriods-format-abbr-night1": "naktī",
	"dayPeriods-format-narrow-midnight": "pusnaktī",
	"dayPeriods-format-narrow-am": "priekšp.",
	"dayPeriods-format-narrow-noon": "pusd.",
	"dayPeriods-format-narrow-pm": "pēcp.",
	"dayPeriods-format-narrow-morning1": "no rīta",
	"dayPeriods-format-narrow-afternoon1": "pēcpusdienā",
	"dayPeriods-format-narrow-evening1": "vakarā",
	"dayPeriods-format-narrow-night1": "naktī",
	"dayPeriods-format-wide-midnight": "pusnaktī",
	"dayPeriods-format-wide-am": "priekšpusdienā",
	"dayPeriods-format-wide-noon": "pusdienlaikā",
	"dayPeriods-format-wide-pm": "pēcpusdienā",
	"dayPeriods-format-wide-morning1": "no rīta",
	"dayPeriods-format-wide-afternoon1": "pēcpusdienā",
	"dayPeriods-format-wide-evening1": "vakarā",
	"dayPeriods-format-wide-night1": "naktī",
	"dayPeriods-standAlone-abbr-midnight": "pusnakts",
	"dayPeriods-standAlone-abbr-am": "priekšp.",
	"dayPeriods-standAlone-abbr-noon": "pusd.",
	"dayPeriods-standAlone-abbr-pm": "pēcpusd.",
	"dayPeriods-standAlone-abbr-morning1": "rīts",
	"dayPeriods-standAlone-abbr-afternoon1": "pēcpusdiena",
	"dayPeriods-standAlone-abbr-evening1": "vakars",
	"dayPeriods-standAlone-abbr-night1": "nakts",
	"dayPeriods-standAlone-narrow-midnight": "pusnakts",
	"dayPeriods-standAlone-narrow-am": "priekšp.",
	"dayPeriods-standAlone-narrow-noon": "pusd.",
	"dayPeriods-standAlone-narrow-pm": "pēcp.",
	"dayPeriods-standAlone-narrow-morning1": "rīts",
	"dayPeriods-standAlone-narrow-afternoon1": "pēcpusd.",
	"dayPeriods-standAlone-narrow-evening1": "vakars",
	"dayPeriods-standAlone-narrow-night1": "nakts",
	"dayPeriods-standAlone-wide-midnight": "pusnakts",
	"dayPeriods-standAlone-wide-am": "priekšpusdiena",
	"dayPeriods-standAlone-wide-noon": "pusdienlaiks",
	"dayPeriods-standAlone-wide-pm": "pēcpusdiena",
	"dayPeriods-standAlone-wide-morning1": "rīts",
	"dayPeriods-standAlone-wide-afternoon1": "pēcpusdiena",
	"dayPeriods-standAlone-wide-evening1": "vakars",
	"dayPeriods-standAlone-wide-night1": "nakts",
	"eraNames": [
		"pirms mūsu ēras",
		"mūsu ērā"
	],
	"eraAbbr": [
		"p.m.ē.",
		"m.ē."
	],
	"eraNarrow": [
		"p.m.ē.",
		"m.ē."
	],
	"dateFormat-full": "EEEE, y. 'gada' d. MMMM",
	"dateFormat-long": "y. 'gada' d. MMMM",
	"dateFormat-medium": "y. 'gada' d. MMM",
	"dateFormat-short": "dd.MM.yy",
	"timeFormat-full": "HH:mm:ss zzzz",
	"timeFormat-long": "HH:mm:ss z",
	"timeFormat-medium": "HH:mm:ss",
	"timeFormat-short": "HH:mm",
	"dateTimeFormat-full": "{1} {0}",
	"dateTimeFormat-long": "{1} {0}",
	"dateTimeFormat-medium": "{1} {0}",
	"dateTimeFormat-short": "{1} {0}",
	"dateFormatItem-d": "d",
	"dateFormatItem-E": "ccc",
	"dateFormatItem-Ed": "E, d.",
	"dateFormatItem-Ehm": "E, h:mm a",
	"dateFormatItem-EHm": "E, HH:mm",
	"dateFormatItem-Ehms": "E, h:mm:ss a",
	"dateFormatItem-EHms": "E, HH:mm:ss",
	"dateFormatItem-Gy": "G y. 'g'.",
	"dateFormatItem-GyMMM": "G y. 'g'. MMM",
	"dateFormatItem-GyMMMd": "G y. 'g'. d. MMM",
	"dateFormatItem-GyMMMEd": "E, G y. 'g'. d. MMM",
	"dateFormatItem-h": "h a",
	"dateFormatItem-H": "HH",
	"dateFormatItem-hm": "h:mm a",
	"dateFormatItem-Hm": "HH:mm",
	"dateFormatItem-hms": "h:mm:ss a",
	"dateFormatItem-Hms": "HH:mm:ss",
	"dateFormatItem-hmsv": "h:mm:ss a v",
	"dateFormatItem-Hmsv": "HH:mm:ss v",
	"dateFormatItem-hmv": "h:mm a v",
	"dateFormatItem-Hmv": "HH:mm v",
	"dateFormatItem-M": "L",
	"dateFormatItem-Md": "dd.MM.",
	"dateFormatItem-MEd": "E, dd.MM.",
	"dateFormatItem-MMM": "LLL",
	"dateFormatItem-MMMd": "d. MMM",
	"dateFormatItem-MMMEd": "E, d. MMM",
	"dateFormatItem-MMMMd": "d. MMMM",
	"dateFormatItem-MMMMEd": "E, d. MMMM",
	"dateFormatItem-MMMMW": "MMM W. 'nedēļa'",
	"dateFormatItem-mmss": "mm:ss",
	"dateFormatItem-ms": "mm:ss",
	"dateFormatItem-y": "y. 'g'.",
	"dateFormatItem-yM": "MM.y.",
	"dateFormatItem-yMd": "y.MM.d.",
	"dateFormatItem-yMEd": "E, d.M.y.",
	"dateFormatItem-yMMM": "y. 'g'. MMM",
	"dateFormatItem-yMMMd": "y. 'g'. d. MMM",
	"dateFormatItem-yMMMEd": "E, y. 'g'. d. MMM",
	"dateFormatItem-yMMMM": "y. 'g'. MMMM",
	"dateFormatItem-yQQQ": "y. 'g'. QQQ",
	"dateFormatItem-yQQQQ": "y. 'g'. QQQQ",
	"dateFormatItem-yw": "y. 'g'. w. 'nedēļa'",
	"dateTimeFormats-appendItem-Timezone": "{0} {1}",
	"field-era": "ēra",
	"field-year": "gads",
	"field-year-relative+-1": "pagājušajā gadā",
	"field-year-relative+0": "šajā gadā",
	"field-year-relative+1": "nākamajā gadā",
	"field-year-short": "g.",
	"field-year-narrow": "g.",
	"field-quarter": "ceturksnis",
	"field-quarter-relative+-1": "pēdējais ceturksnis",
	"field-quarter-relative+0": "šis ceturksnis",
	"field-quarter-relative+1": "nākamais ceturksnis",
	"field-quarter-short": "cet.",
	"field-quarter-narrow": "cet.",
	"field-month": "mēnesis",
	"field-month-relative+-1": "pagājušajā mēnesī",
	"field-month-relative+0": "šajā mēnesī",
	"field-month-relative+1": "nākamajā mēnesī",
	"field-month-short": "mēn.",
	"field-month-narrow": "mēn.",
	"field-week": "nedēļa",
	"field-week-relative+-1": "pagājušajā nedēļā",
	"field-week-relative+0": "šajā nedēļā",
	"field-week-relative+1": "nākamajā nedēļā",
	"field-week-short": "ned.",
	"field-week-narrow": "ned.",
	"field-day": "diena",
	"field-day-relative+-2": "aizvakar",
	"field-day-relative+-1": "vakar",
	"field-day-relative+0": "šodien",
	"field-day-relative+1": "rīt",
	"field-day-relative+2": "parīt",
	"field-day-short": "d.",
	"field-day-narrow": "d.",
	"field-weekday": "nedēļas diena",
	"field-sun-relative+-1": "pagājušajā svētdienā",
	"field-sun-relative+0": "šajā svētdienā",
	"field-sun-relative+1": "nākamajā svētdienā",
	"field-sun-short-relative+-1": "pag. svētd.",
	"field-sun-short-relative+0": "šajā svētd.",
	"field-sun-short-relative+1": "nāk. svētd.",
	"field-sun-narrow-relative+-1": "pag. svētd.",
	"field-sun-narrow-relative+0": "šajā svētd.",
	"field-sun-narrow-relative+1": "nāk. svētd.",
	"field-mon-relative+-1": "pagājušajā pirmdienā",
	"field-mon-relative+0": "šajā pirmdienā",
	"field-mon-relative+1": "nākamajā pirmdienā",
	"field-mon-short-relative+-1": "pag. pirmd.",
	"field-mon-short-relative+0": "šajā pirmd.",
	"field-mon-short-relative+1": "nāk. pirmd.",
	"field-mon-narrow-relative+-1": "pag. pirmd.",
	"field-mon-narrow-relative+0": "šajā pirmd.",
	"field-mon-narrow-relative+1": "nāk. pirmd.",
	"field-tue-relative+-1": "pagājušajā otrdienā",
	"field-tue-relative+0": "šajā otrdienā",
	"field-tue-relative+1": "nākamajā otrdienā",
	"field-tue-short-relative+-1": "pag. otrd.",
	"field-tue-short-relative+0": "šajā otrd.",
	"field-tue-short-relative+1": "nāk. otrd.",
	"field-tue-narrow-relative+-1": "pag. otrd.",
	"field-tue-narrow-relative+0": "šajā otrd.",
	"field-tue-narrow-relative+1": "nāk. otrd.",
	"field-wed-relative+-1": "pagājušajā trešdienā",
	"field-wed-relative+0": "šajā trešdienā",
	"field-wed-relative+1": "nākamajā trešdienā",
	"field-wed-short-relative+-1": "pag. trešd.",
	"field-wed-short-relative+0": "šajā trešd.",
	"field-wed-short-relative+1": "nāk. trešd.",
	"field-wed-narrow-relative+-1": "pag. trešd.",
	"field-wed-narrow-relative+0": "šajā trešd.",
	"field-wed-narrow-relative+1": "nāk. trešd.",
	"field-thu-relative+-1": "pagājušajā ceturtdienā",
	"field-thu-relative+0": "šajā ceturtdienā",
	"field-thu-relative+1": "nākamajā ceturtdienā",
	"field-thu-short-relative+-1": "pag. ceturtd.",
	"field-thu-short-relative+0": "šajā ceturtd.",
	"field-thu-short-relative+1": "nāk. ceturtd.",
	"field-thu-narrow-relative+-1": "pag. ceturtd.",
	"field-thu-narrow-relative+0": "šajā ceturtd.",
	"field-thu-narrow-relative+1": "nāk. ceturtd.",
	"field-fri-relative+-1": "pagājušajā piektdienā",
	"field-fri-relative+0": "šajā piektdienā",
	"field-fri-relative+1": "nākamajā piektdienā",
	"field-fri-short-relative+-1": "pag. piektd.",
	"field-fri-short-relative+0": "šajā piektd.",
	"field-fri-short-relative+1": "nāk. piektd.",
	"field-fri-narrow-relative+-1": "pag. piektd.",
	"field-fri-narrow-relative+0": "šajā piektd.",
	"field-fri-narrow-relative+1": "nāk. piektd.",
	"field-sat-relative+-1": "pagājušajā sestdienā",
	"field-sat-relative+0": "šajā sestdienā",
	"field-sat-relative+1": "nākamajā sestdienā",
	"field-sat-short-relative+-1": "pag. sestd.",
	"field-sat-short-relative+0": "šajā sestd.",
	"field-sat-short-relative+1": "nāk. sestd.",
	"field-sat-narrow-relative+-1": "pag. sestd.",
	"field-sat-narrow-relative+0": "šajā sestd.",
	"field-sat-narrow-relative+1": "nāk. sestd.",
	"field-dayperiod": "priekšpusdienā/pēcpusdienā",
	"field-hour": "stundas",
	"field-hour-relative+0": "šajā stundā",
	"field-hour-short": "st.",
	"field-hour-narrow": "h",
	"field-minute": "minūtes",
	"field-minute-relative+0": "šajā minūtē",
	"field-minute-short": "min.",
	"field-minute-narrow": "min",
	"field-second": "sekundes",
	"field-second-relative+0": "tagad",
	"field-second-short": "sek.",
	"field-second-narrow": "s",
	"field-zone": "laika josla"
}
//end v1.x content
);